<?php
$data = [
  'AFN' => 
  [
    'id' => 'AFN',
    'name' => 'Afghani',
    'number' => 971,
    'minor_units' => 2,
    'country_name' => 'AFGHANISTAN',
    'country_code' => '',
    'sign' => '؋',
    'active' => '0',
  ],
  'EUR' => 
  [
    'id' => 'EUR',
    'name' => 'Euro',
    'number' => 978,
    'minor_units' => 2,
    'country_name' => 'Vatican City State (HOLY SEE)',
    'country_code' => '',
    'sign' => '€',
    'active' => 1,
  ],
  'ALL' => 
  [
    'id' => 'ALL',
    'name' => 'Lek',
    'number' => 8,
    'minor_units' => 2,
    'country_name' => 'ALBANIA',
    'country_code' => '',
    'sign' => 'L',
    'active' => '0',
  ],
  'DZD' => 
  [
    'id' => 'DZD',
    'name' => 'Algerian Dinar',
    'number' => 12,
    'minor_units' => 2,
    'country_name' => 'ALGERIA',
    'country_code' => '',
    'sign' => 'د.ج',
    'active' => '0',
  ],
  'USD' => 
  [
    'id' => 'USD',
    'name' => 'US Dollar',
    'number' => 840,
    'minor_units' => 2,
    'country_name' => 'VIRGIN ISLANDS (US)',
    'country_code' => '',
    'sign' => '$',
    'active' => 1,
  ],
  'AOA' => 
  [
    'id' => 'AOA',
    'name' => 'Kwanza',
    'number' => 973,
    'minor_units' => 2,
    'country_name' => 'ANGOLA',
    'country_code' => '',
    'sign' => 'Kz',
    'active' => '0',
  ],
  'XCD' => 
  [
    'id' => 'XCD',
    'name' => 'East Caribbean Dollar',
    'number' => 951,
    'minor_units' => 2,
    'country_name' => 'SAINT VINCENT AND THE GRENADINES',
    'country_code' => '',
    'sign' => '$',
    'active' => '0',
  ],
  'ARS' => 
  [
    'id' => 'ARS',
    'name' => 'Argentine Peso',
    'number' => 32,
    'minor_units' => 2,
    'country_name' => 'ARGENTINA',
    'country_code' => '',
    'sign' => '$',
    'active' => '0',
  ],
  'AMD' => 
  [
    'id' => 'AMD',
    'name' => 'Armenian Dram',
    'number' => 51,
    'minor_units' => 2,
    'country_name' => 'ARMENIA',
    'country_code' => '',
    'sign' => 'դր.',
    'active' => '0',
  ],
  'AWG' => 
  [
    'id' => 'AWG',
    'name' => 'Aruban Florin',
    'number' => 533,
    'minor_units' => 2,
    'country_name' => 'ARUBA',
    'country_code' => '',
    'sign' => 'ƒ',
    'active' => '0',
  ],
  'AUD' => 
  [
    'id' => 'AUD',
    'name' => 'Australian Dollar',
    'number' => 36,
    'minor_units' => 2,
    'country_name' => 'TUVALU',
    'country_code' => '',
    'sign' => '$',
    'active' => '0',
  ],
  'AZN' => 
  [
    'id' => 'AZN',
    'name' => 'Azerbaijanian Manat',
    'number' => 944,
    'minor_units' => 2,
    'country_name' => 'AZERBAIJAN',
    'country_code' => '',
    'sign' => '',
    'active' => '0',
  ],
  'BSD' => 
  [
    'id' => 'BSD',
    'name' => 'Bahamian Dollar',
    'number' => 44,
    'minor_units' => 2,
    'country_name' => 'BAHAMAS',
    'country_code' => '',
    'sign' => '$',
    'active' => '0',
  ],
  'BHD' => 
  [
    'id' => 'BHD',
    'name' => 'Bahraini Dinar',
    'number' => 48,
    'minor_units' => 3,
    'country_name' => 'BAHRAIN',
    'country_code' => '',
    'sign' => '.د.ب',
    'active' => '0',
  ],
  'BDT' => 
  [
    'id' => 'BDT',
    'name' => 'Taka',
    'number' => 50,
    'minor_units' => 2,
    'country_name' => 'BANGLADESH',
    'country_code' => '',
    'sign' => '৳',
    'active' => '0',
  ],
  'BBD' => 
  [
    'id' => 'BBD',
    'name' => 'Barbados Dollar',
    'number' => 52,
    'minor_units' => 2,
    'country_name' => 'BARBADOS',
    'country_code' => '',
    'sign' => '$',
    'active' => '0',
  ],
  'BYR' => 
  [
    'id' => 'BYR',
    'name' => 'Belarussian Ruble',
    'number' => 974,
    'minor_units' => 0,
    'country_name' => 'BELARUS',
    'country_code' => '',
    'sign' => 'Br',
    'active' => '0',
  ],
  'BZD' => 
  [
    'id' => 'BZD',
    'name' => 'Belize Dollar',
    'number' => 84,
    'minor_units' => 2,
    'country_name' => 'BELIZE',
    'country_code' => '',
    'sign' => '$',
    'active' => '0',
  ],
  'XOF' => 
  [
    'id' => 'XOF',
    'name' => 'CFA Franc BCEAO',
    'number' => 952,
    'minor_units' => 0,
    'country_name' => 'TOGO',
    'country_code' => '',
    'sign' => 'Fr',
    'active' => '0',
  ],
  'BMD' => 
  [
    'id' => 'BMD',
    'name' => 'Bermudian Dollar',
    'number' => 60,
    'minor_units' => 2,
    'country_name' => 'BERMUDA',
    'country_code' => '',
    'sign' => '$',
    'active' => '0',
  ],
  'BTN' => 
  [
    'id' => 'BTN',
    'name' => 'Ngultrum',
    'number' => 64,
    'minor_units' => 2,
    'country_name' => 'BHUTAN',
    'country_code' => '',
    'sign' => 'Nu.',
    'active' => '0',
  ],
  'INR' => 
  [
    'id' => 'INR',
    'name' => 'Indian Rupee',
    'number' => 356,
    'minor_units' => 2,
    'country_name' => 'INDIA',
    'country_code' => '',
    'sign' => '',
    'active' => '0',
  ],
  'BOB' => 
  [
    'id' => 'BOB',
    'name' => 'Boliviano',
    'number' => 68,
    'minor_units' => 2,
    'country_name' => 'BOLIVIA, PLURINATIONAL STATE OF',
    'country_code' => '',
    'sign' => 'Bs.',
    'active' => '0',
  ],
  'BOV' => 
  [
    'id' => 'BOV',
    'name' => 'Mvdol',
    'number' => 984,
    'minor_units' => 2,
    'country_name' => 'BOLIVIA, PLURINATIONAL STATE OF',
    'country_code' => '',
    'sign' => '',
    'active' => '0',
  ],
  'BAM' => 
  [
    'id' => 'BAM',
    'name' => 'Convertible Mark',
    'number' => 977,
    'minor_units' => 2,
    'country_name' => 'BOSNIA AND HERZEGOVINA',
    'country_code' => '',
    'sign' => '',
    'active' => '0',
  ],
  'BWP' => 
  [
    'id' => 'BWP',
    'name' => 'Pula',
    'number' => 72,
    'minor_units' => 2,
    'country_name' => 'BOTSWANA',
    'country_code' => '',
    'sign' => 'P',
    'active' => '0',
  ],
  'NOK' => 
  [
    'id' => 'NOK',
    'name' => 'Norwegian Krone',
    'number' => 578,
    'minor_units' => 2,
    'country_name' => 'SVALBARD AND JAN MAYEN',
    'country_code' => '',
    'sign' => 'kr',
    'active' => '0',
  ],
  'BRL' => 
  [
    'id' => 'BRL',
    'name' => 'Brazilian Real',
    'number' => 986,
    'minor_units' => 2,
    'country_name' => 'BRAZIL',
    'country_code' => '',
    'sign' => 'R$',
    'active' => '0',
  ],
  'BND' => 
  [
    'id' => 'BND',
    'name' => 'Brunei Dollar',
    'number' => 96,
    'minor_units' => 2,
    'country_name' => 'BRUNEI DARUSSALAM',
    'country_code' => '',
    'sign' => '$',
    'active' => '0',
  ],
  'BGN' => 
  [
    'id' => 'BGN',
    'name' => 'Bulgarian Lev',
    'number' => 975,
    'minor_units' => 2,
    'country_name' => 'BULGARIA',
    'country_code' => '',
    'sign' => 'лв',
    'active' => '0',
  ],
  'BIF' => 
  [
    'id' => 'BIF',
    'name' => 'Burundi Franc',
    'number' => 108,
    'minor_units' => 0,
    'country_name' => 'BURUNDI',
    'country_code' => '',
    'sign' => 'Fr',
    'active' => '0',
  ],
  'KHR' => 
  [
    'id' => 'KHR',
    'name' => 'Riel',
    'number' => 116,
    'minor_units' => 2,
    'country_name' => 'CAMBODIA',
    'country_code' => '',
    'sign' => '៛',
    'active' => '0',
  ],
  'XAF' => 
  [
    'id' => 'XAF',
    'name' => 'CFA Franc BEAC',
    'number' => 950,
    'minor_units' => 0,
    'country_name' => 'GABON',
    'country_code' => '',
    'sign' => 'Fr',
    'active' => '0',
  ],
  'CAD' => 
  [
    'id' => 'CAD',
    'name' => 'Canadian Dollar',
    'number' => 124,
    'minor_units' => 2,
    'country_name' => 'CANADA',
    'country_code' => '',
    'sign' => '$',
    'active' => '0',
  ],
  'CVE' => 
  [
    'id' => 'CVE',
    'name' => 'Cape Verde Escudo',
    'number' => 132,
    'minor_units' => 2,
    'country_name' => 'CAPE VERDE',
    'country_code' => '',
    'sign' => '',
    'active' => '0',
  ],
  'KYD' => 
  [
    'id' => 'KYD',
    'name' => 'Cayman Islands Dollar',
    'number' => 136,
    'minor_units' => 2,
    'country_name' => 'CAYMAN ISLANDS',
    'country_code' => '',
    'sign' => '$',
    'active' => '0',
  ],
  'CLF' => 
  [
    'id' => 'CLF',
    'name' => 'Unidades de fomento',
    'number' => 990,
    'minor_units' => 0,
    'country_name' => 'CHILE',
    'country_code' => '',
    'sign' => '',
    'active' => '0',
  ],
  'CLP' => 
  [
    'id' => 'CLP',
    'name' => 'Chilean Peso',
    'number' => 152,
    'minor_units' => 0,
    'country_name' => 'CHILE',
    'country_code' => '',
    'sign' => '$',
    'active' => '0',
  ],
  'CNY' => 
  [
    'id' => 'CNY',
    'name' => 'Yuan Renminbi',
    'number' => 156,
    'minor_units' => 2,
    'country_name' => 'CHINA',
    'country_code' => '',
    'sign' => '',
    'active' => '0',
  ],
  'COP' => 
  [
    'id' => 'COP',
    'name' => 'Colombian Peso',
    'number' => 170,
    'minor_units' => 2,
    'country_name' => 'COLOMBIA',
    'country_code' => '',
    'sign' => '$',
    'active' => '0',
  ],
  'COU' => 
  [
    'id' => 'COU',
    'name' => 'Unidad de Valor Real',
    'number' => 970,
    'minor_units' => 2,
    'country_name' => 'COLOMBIA',
    'country_code' => '',
    'sign' => '',
    'active' => '0',
  ],
  'KMF' => 
  [
    'id' => 'KMF',
    'name' => 'Comoro Franc',
    'number' => 174,
    'minor_units' => 0,
    'country_name' => 'COMOROS',
    'country_code' => '',
    'sign' => 'Fr',
    'active' => '0',
  ],
  'CDF' => 
  [
    'id' => 'CDF',
    'name' => 'Congolese Franc',
    'number' => 976,
    'minor_units' => 2,
    'country_name' => 'CONGO, THE DEMOCRATIC REPUBLIC OF',
    'country_code' => '',
    'sign' => 'Fr',
    'active' => '0',
  ],
  'NZD' => 
  [
    'id' => 'NZD',
    'name' => 'New Zealand Dollar',
    'number' => 554,
    'minor_units' => 2,
    'country_name' => 'TOKELAU',
    'country_code' => '',
    'sign' => '$',
    'active' => '0',
  ],
  'CRC' => 
  [
    'id' => 'CRC',
    'name' => 'Costa Rican Colon',
    'number' => 188,
    'minor_units' => 2,
    'country_name' => 'COSTA RICA',
    'country_code' => '',
    'sign' => '₡',
    'active' => '0',
  ],
  'HRK' => 
  [
    'id' => 'HRK',
    'name' => 'Croatian Kuna',
    'number' => 191,
    'minor_units' => 2,
    'country_name' => 'CROATIA',
    'country_code' => '',
    'sign' => 'kn',
    'active' => '0',
  ],
  'CUC' => 
  [
    'id' => 'CUC',
    'name' => 'Peso Convertible',
    'number' => 931,
    'minor_units' => 2,
    'country_name' => 'CUBA',
    'country_code' => '',
    'sign' => '$',
    'active' => '0',
  ],
  'CUP' => 
  [
    'id' => 'CUP',
    'name' => 'Cuban Peso',
    'number' => 192,
    'minor_units' => 2,
    'country_name' => 'CUBA',
    'country_code' => '',
    'sign' => '$',
    'active' => '0',
  ],
  'ANG' => 
  [
    'id' => 'ANG',
    'name' => 'Netherlands Antillean Guilder',
    'number' => 532,
    'minor_units' => 2,
    'country_name' => 'SINT MAARTEN (DUTCH PART)',
    'country_code' => '',
    'sign' => 'ƒ',
    'active' => '0',
  ],
  'CZK' => 
  [
    'id' => 'CZK',
    'name' => 'Czech Koruna',
    'number' => 203,
    'minor_units' => 2,
    'country_name' => 'CZECH REPUBLIC',
    'country_code' => '',
    'sign' => 'Kč',
    'active' => '0',
  ],
  'DKK' => 
  [
    'id' => 'DKK',
    'name' => 'Danish Krone',
    'number' => 208,
    'minor_units' => 2,
    'country_name' => 'GREENLAND',
    'country_code' => '',
    'sign' => 'kr',
    'active' => '0',
  ],
  'DJF' => 
  [
    'id' => 'DJF',
    'name' => 'Djibouti Franc',
    'number' => 262,
    'minor_units' => 0,
    'country_name' => 'DJIBOUTI',
    'country_code' => '',
    'sign' => 'Fr',
    'active' => '0',
  ],
  'DOP' => 
  [
    'id' => 'DOP',
    'name' => 'Dominican Peso',
    'number' => 214,
    'minor_units' => 2,
    'country_name' => 'DOMINICAN REPUBLIC',
    'country_code' => '',
    'sign' => '$',
    'active' => '0',
  ],
  'EGP' => 
  [
    'id' => 'EGP',
    'name' => 'Egyptian Pound',
    'number' => 818,
    'minor_units' => 2,
    'country_name' => 'EGYPT',
    'country_code' => '',
    'sign' => '',
    'active' => '0',
  ],
  'SVC' => 
  [
    'id' => 'SVC',
    'name' => 'El Salvador Colon',
    'number' => 222,
    'minor_units' => 2,
    'country_name' => 'EL SALVADOR',
    'country_code' => '',
    'sign' => '₡',
    'active' => '0',
  ],
  'ERN' => 
  [
    'id' => 'ERN',
    'name' => 'Nakfa',
    'number' => 232,
    'minor_units' => 2,
    'country_name' => 'ERITREA',
    'country_code' => '',
    'sign' => 'Nfk',
    'active' => '0',
  ],
  'ETB' => 
  [
    'id' => 'ETB',
    'name' => 'Ethiopian Birr',
    'number' => 230,
    'minor_units' => 2,
    'country_name' => 'ETHIOPIA',
    'country_code' => '',
    'sign' => 'Br',
    'active' => '0',
  ],
  'FKP' => 
  [
    'id' => 'FKP',
    'name' => 'Falkland Islands Pound',
    'number' => 238,
    'minor_units' => 2,
    'country_name' => 'FALKLAND ISLANDS (MALVINAS)',
    'country_code' => '',
    'sign' => '£',
    'active' => '0',
  ],
  'FJD' => 
  [
    'id' => 'FJD',
    'name' => 'Fiji Dollar',
    'number' => 242,
    'minor_units' => 2,
    'country_name' => 'FIJI',
    'country_code' => '',
    'sign' => '$',
    'active' => '0',
  ],
  'XPF' => 
  [
    'id' => 'XPF',
    'name' => 'CFP Franc',
    'number' => 953,
    'minor_units' => 0,
    'country_name' => 'WALLIS AND FUTUNA',
    'country_code' => '',
    'sign' => 'Fr',
    'active' => '0',
  ],
  'GMD' => 
  [
    'id' => 'GMD',
    'name' => 'Dalasi',
    'number' => 270,
    'minor_units' => 2,
    'country_name' => 'GAMBIA',
    'country_code' => '',
    'sign' => 'D',
    'active' => '0',
  ],
  'GEL' => 
  [
    'id' => 'GEL',
    'name' => 'Lari',
    'number' => 981,
    'minor_units' => 2,
    'country_name' => 'GEORGIA',
    'country_code' => '',
    'sign' => 'ლ',
    'active' => '0',
  ],
  'GHS' => 
  [
    'id' => 'GHS',
    'name' => 'Ghana Cedi',
    'number' => 936,
    'minor_units' => 2,
    'country_name' => 'GHANA',
    'country_code' => '',
    'sign' => '₵',
    'active' => '0',
  ],
  'GIP' => 
  [
    'id' => 'GIP',
    'name' => 'Gibraltar Pound',
    'number' => 292,
    'minor_units' => 2,
    'country_name' => 'GIBRALTAR',
    'country_code' => '',
    'sign' => '£',
    'active' => '0',
  ],
  'GTQ' => 
  [
    'id' => 'GTQ',
    'name' => 'Quetzal',
    'number' => 320,
    'minor_units' => 2,
    'country_name' => 'GUATEMALA',
    'country_code' => '',
    'sign' => 'Q',
    'active' => '0',
  ],
  'GBP' => 
  [
    'id' => 'GBP',
    'name' => 'Pound Sterling',
    'number' => 826,
    'minor_units' => 2,
    'country_name' => 'UNITED KINGDOM',
    'country_code' => '',
    'sign' => '£',
    'active' => '0',
  ],
  'GNF' => 
  [
    'id' => 'GNF',
    'name' => 'Guinea Franc',
    'number' => 324,
    'minor_units' => 0,
    'country_name' => 'GUINEA',
    'country_code' => '',
    'sign' => 'Fr',
    'active' => '0',
  ],
  'GYD' => 
  [
    'id' => 'GYD',
    'name' => 'Guyana Dollar',
    'number' => 328,
    'minor_units' => 2,
    'country_name' => 'GUYANA',
    'country_code' => '',
    'sign' => '$',
    'active' => '0',
  ],
  'HTG' => 
  [
    'id' => 'HTG',
    'name' => 'Gourde',
    'number' => 332,
    'minor_units' => 2,
    'country_name' => 'HAITI',
    'country_code' => '',
    'sign' => 'G',
    'active' => '0',
  ],
  'HNL' => 
  [
    'id' => 'HNL',
    'name' => 'Lempira',
    'number' => 340,
    'minor_units' => 2,
    'country_name' => 'HONDURAS',
    'country_code' => '',
    'sign' => 'L',
    'active' => '0',
  ],
  'HKD' => 
  [
    'id' => 'HKD',
    'name' => 'Hong Kong Dollar',
    'number' => 344,
    'minor_units' => 2,
    'country_name' => 'HONG KONG',
    'country_code' => '',
    'sign' => '$',
    'active' => '0',
  ],
  'HUF' => 
  [
    'id' => 'HUF',
    'name' => 'Forint',
    'number' => 348,
    'minor_units' => 2,
    'country_name' => 'HUNGARY',
    'country_code' => '',
    'sign' => 'Ft',
    'active' => '0',
  ],
  'ISK' => 
  [
    'id' => 'ISK',
    'name' => 'Iceland Krona',
    'number' => 352,
    'minor_units' => 0,
    'country_name' => 'ICELAND',
    'country_code' => '',
    'sign' => 'kr',
    'active' => '0',
  ],
  'IDR' => 
  [
    'id' => 'IDR',
    'name' => 'Rupiah',
    'number' => 360,
    'minor_units' => 2,
    'country_name' => 'INDONESIA',
    'country_code' => '',
    'sign' => 'Rp',
    'active' => '0',
  ],
  'XDR' => 
  [
    'id' => 'XDR',
    'name' => 'SDR (Special Drawing Right)',
    'number' => 960,
    'minor_units' => 0,
    'country_name' => 'INTERNATIONAL MONETARY FUND (IMF) ',
    'country_code' => '',
    'sign' => '',
    'active' => '0',
  ],
  'IRR' => 
  [
    'id' => 'IRR',
    'name' => 'Iranian Rial',
    'number' => 364,
    'minor_units' => 2,
    'country_name' => 'IRAN, ISLAMIC REPUBLIC OF',
    'country_code' => '',
    'sign' => '﷼',
    'active' => '0',
  ],
  'IQD' => 
  [
    'id' => 'IQD',
    'name' => 'Iraqi Dinar',
    'number' => 368,
    'minor_units' => 3,
    'country_name' => 'IRAQ',
    'country_code' => '',
    'sign' => 'ع.د',
    'active' => '0',
  ],
  'ILS' => 
  [
    'id' => 'ILS',
    'name' => 'New Israeli Sheqel',
    'number' => 376,
    'minor_units' => 2,
    'country_name' => 'ISRAEL',
    'country_code' => '',
    'sign' => '₪',
    'active' => '0',
  ],
  'JMD' => 
  [
    'id' => 'JMD',
    'name' => 'Jamaican Dollar',
    'number' => 388,
    'minor_units' => 2,
    'country_name' => 'JAMAICA',
    'country_code' => '',
    'sign' => '$',
    'active' => '0',
  ],
  'JPY' => 
  [
    'id' => 'JPY',
    'name' => 'Yen',
    'number' => 392,
    'minor_units' => 0,
    'country_name' => 'JAPAN',
    'country_code' => '',
    'sign' => '¥',
    'active' => 1,
  ],
  'JOD' => 
  [
    'id' => 'JOD',
    'name' => 'Jordanian Dinar',
    'number' => 400,
    'minor_units' => 3,
    'country_name' => 'JORDAN',
    'country_code' => '',
    'sign' => 'د.ا',
    'active' => '0',
  ],
  'KZT' => 
  [
    'id' => 'KZT',
    'name' => 'Tenge',
    'number' => 398,
    'minor_units' => 2,
    'country_name' => 'KAZAKHSTAN',
    'country_code' => '',
    'sign' => '₸',
    'active' => '0',
  ],
  'KES' => 
  [
    'id' => 'KES',
    'name' => 'Kenyan Shilling',
    'number' => 404,
    'minor_units' => 2,
    'country_name' => 'KENYA',
    'country_code' => '',
    'sign' => 'Sh',
    'active' => '0',
  ],
  'KPW' => 
  [
    'id' => 'KPW',
    'name' => 'North Korean Won',
    'number' => 408,
    'minor_units' => 2,
    'country_name' => 'KOREA, DEMOCRATIC PEOPLE’S REPUBLIC OF',
    'country_code' => '',
    'sign' => '₩',
    'active' => '0',
  ],
  'KRW' => 
  [
    'id' => 'KRW',
    'name' => 'Won',
    'number' => 410,
    'minor_units' => 0,
    'country_name' => 'KOREA, REPUBLIC OF',
    'country_code' => '',
    'sign' => '₩',
    'active' => '0',
  ],
  'KWD' => 
  [
    'id' => 'KWD',
    'name' => 'Kuwaiti Dinar',
    'number' => 414,
    'minor_units' => 3,
    'country_name' => 'KUWAIT',
    'country_code' => '',
    'sign' => 'د.ك',
    'active' => '0',
  ],
  'KGS' => 
  [
    'id' => 'KGS',
    'name' => 'Som',
    'number' => 417,
    'minor_units' => 2,
    'country_name' => 'KYRGYZSTAN',
    'country_code' => '',
    'sign' => '',
    'active' => '0',
  ],
  'LAK' => 
  [
    'id' => 'LAK',
    'name' => 'Kip',
    'number' => 418,
    'minor_units' => 2,
    'country_name' => 'LAO PEOPLE’S DEMOCRATIC REPUBLIC',
    'country_code' => '',
    'sign' => '₭',
    'active' => '0',
  ],
  'LVL' => 
  [
    'id' => 'LVL',
    'name' => 'Latvian Lats',
    'number' => 428,
    'minor_units' => 2,
    'country_name' => 'LATVIA',
    'country_code' => '',
    'sign' => 'Ls',
    'active' => '0',
  ],
  'LBP' => 
  [
    'id' => 'LBP',
    'name' => 'Lebanese Pound',
    'number' => 422,
    'minor_units' => 2,
    'country_name' => 'LEBANON',
    'country_code' => '',
    'sign' => 'ل.ل',
    'active' => '0',
  ],
  'LSL' => 
  [
    'id' => 'LSL',
    'name' => 'Loti',
    'number' => 426,
    'minor_units' => 2,
    'country_name' => 'LESOTHO',
    'country_code' => '',
    'sign' => 'L',
    'active' => '0',
  ],
  'ZAR' => 
  [
    'id' => 'ZAR',
    'name' => 'Rand',
    'number' => 710,
    'minor_units' => 2,
    'country_name' => 'SOUTH AFRICA',
    'country_code' => '',
    'sign' => 'R',
    'active' => '0',
  ],
  'LRD' => 
  [
    'id' => 'LRD',
    'name' => 'Liberian Dollar',
    'number' => 430,
    'minor_units' => 2,
    'country_name' => 'LIBERIA',
    'country_code' => '',
    'sign' => '$',
    'active' => '0',
  ],
  'LYD' => 
  [
    'id' => 'LYD',
    'name' => 'Libyan Dinar',
    'number' => 434,
    'minor_units' => 3,
    'country_name' => 'LIBYA',
    'country_code' => '',
    'sign' => 'ل.د',
    'active' => '0',
  ],
  'CHF' => 
  [
    'id' => 'CHF',
    'name' => 'Swiss Franc',
    'number' => 756,
    'minor_units' => 2,
    'country_name' => 'SWITZERLAND',
    'country_code' => '',
    'sign' => 'Fr',
    'active' => 1,
  ],
  'LTL' => 
  [
    'id' => 'LTL',
    'name' => 'Lithuanian Litas',
    'number' => 440,
    'minor_units' => 2,
    'country_name' => 'LITHUANIA',
    'country_code' => '',
    'sign' => 'Lt',
    'active' => '0',
  ],
  'MOP' => 
  [
    'id' => 'MOP',
    'name' => 'Pataca',
    'number' => 446,
    'minor_units' => 2,
    'country_name' => 'MACAO',
    'country_code' => '',
    'sign' => 'P',
    'active' => '0',
  ],
  'MKD' => 
  [
    'id' => 'MKD',
    'name' => 'Denar',
    'number' => 807,
    'minor_units' => 2,
    'country_name' => 'MACEDONIA, THE FORMER YUGOSLAV REPUBLIC OF',
    'country_code' => '',
    'sign' => 'ден',
    'active' => '0',
  ],
  'MGA' => 
  [
    'id' => 'MGA',
    'name' => 'Malagasy Ariary',
    'number' => 969,
    'minor_units' => 2,
    'country_name' => 'MADAGASCAR',
    'country_code' => '',
    'sign' => 'Ar',
    'active' => '0',
  ],
  'MWK' => 
  [
    'id' => 'MWK',
    'name' => 'Kwacha',
    'number' => 454,
    'minor_units' => 2,
    'country_name' => 'MALAWI',
    'country_code' => '',
    'sign' => 'MK',
    'active' => '0',
  ],
  'MYR' => 
  [
    'id' => 'MYR',
    'name' => 'Malaysian Ringgit',
    'number' => 458,
    'minor_units' => 2,
    'country_name' => 'MALAYSIA',
    'country_code' => '',
    'sign' => 'RM',
    'active' => '0',
  ],
  'MVR' => 
  [
    'id' => 'MVR',
    'name' => 'Rufiyaa',
    'number' => 462,
    'minor_units' => 2,
    'country_name' => 'MALDIVES',
    'country_code' => '',
    'sign' => '.ރ',
    'active' => '0',
  ],
  'MRO' => 
  [
    'id' => 'MRO',
    'name' => 'Ouguiya',
    'number' => 478,
    'minor_units' => 2,
    'country_name' => 'MAURITANIA',
    'country_code' => '',
    'sign' => 'UM',
    'active' => '0',
  ],
  'MUR' => 
  [
    'id' => 'MUR',
    'name' => 'Mauritius Rupee',
    'number' => 480,
    'minor_units' => 2,
    'country_name' => 'MAURITIUS',
    'country_code' => '',
    'sign' => '₨',
    'active' => '0',
  ],
  'XUA' => 
  [
    'id' => 'XUA',
    'name' => 'ADB Unit of Account',
    'number' => 965,
    'minor_units' => 0,
    'country_name' => 'MEMBER COUNTRIES OF THE AFRICAN DEVELOPMENT BANK GROUP',
    'country_code' => '',
    'sign' => '',
    'active' => '0',
  ],
  'MXN' => 
  [
    'id' => 'MXN',
    'name' => 'Mexican Peso',
    'number' => 484,
    'minor_units' => 2,
    'country_name' => 'MEXICO',
    'country_code' => '',
    'sign' => '$',
    'active' => '0',
  ],
  'MXV' => 
  [
    'id' => 'MXV',
    'name' => 'Mexican Unidad de Inversion (UDI)',
    'number' => 979,
    'minor_units' => 2,
    'country_name' => 'MEXICO',
    'country_code' => '',
    'sign' => '',
    'active' => '0',
  ],
  'MDL' => 
  [
    'id' => 'MDL',
    'name' => 'Moldovan Leu',
    'number' => 498,
    'minor_units' => 2,
    'country_name' => 'MOLDOVA, REPUBLIC OF',
    'country_code' => '',
    'sign' => 'L',
    'active' => '0',
  ],
  'MNT' => 
  [
    'id' => 'MNT',
    'name' => 'Tugrik',
    'number' => 496,
    'minor_units' => 2,
    'country_name' => 'MONGOLIA',
    'country_code' => '',
    'sign' => '₮',
    'active' => '0',
  ],
  'MAD' => 
  [
    'id' => 'MAD',
    'name' => 'Moroccan Dirham',
    'number' => 504,
    'minor_units' => 2,
    'country_name' => 'WESTERN SAHARA',
    'country_code' => '',
    'sign' => 'د. م.',
    'active' => '0',
  ],
  'MZN' => 
  [
    'id' => 'MZN',
    'name' => 'Mozambique Metical',
    'number' => 943,
    'minor_units' => 2,
    'country_name' => 'MOZAMBIQUE',
    'country_code' => '',
    'sign' => 'MT',
    'active' => '0',
  ],
  'MMK' => 
  [
    'id' => 'MMK',
    'name' => 'Kyat',
    'number' => 104,
    'minor_units' => 2,
    'country_name' => 'MYANMAR',
    'country_code' => '',
    'sign' => 'Ks',
    'active' => '0',
  ],
  'NAD' => 
  [
    'id' => 'NAD',
    'name' => 'Namibia Dollar',
    'number' => 516,
    'minor_units' => 2,
    'country_name' => 'NAMIBIA',
    'country_code' => '',
    'sign' => '$',
    'active' => '0',
  ],
  'NPR' => 
  [
    'id' => 'NPR',
    'name' => 'Nepalese Rupee',
    'number' => 524,
    'minor_units' => 2,
    'country_name' => 'NEPAL',
    'country_code' => '',
    'sign' => '₨',
    'active' => '0',
  ],
  'NIO' => 
  [
    'id' => 'NIO',
    'name' => 'Cordoba Oro',
    'number' => 558,
    'minor_units' => 2,
    'country_name' => 'NICARAGUA',
    'country_code' => '',
    'sign' => 'C$',
    'active' => '0',
  ],
  'NGN' => 
  [
    'id' => 'NGN',
    'name' => 'Naira',
    'number' => 566,
    'minor_units' => 2,
    'country_name' => 'NIGERIA',
    'country_code' => '',
    'sign' => '₦',
    'active' => '0',
  ],
  'OMR' => 
  [
    'id' => 'OMR',
    'name' => 'Rial Omani',
    'number' => 512,
    'minor_units' => 3,
    'country_name' => 'OMAN',
    'country_code' => '',
    'sign' => 'ر.ع.',
    'active' => '0',
  ],
  'PKR' => 
  [
    'id' => 'PKR',
    'name' => 'Pakistan Rupee',
    'number' => 586,
    'minor_units' => 2,
    'country_name' => 'PAKISTAN',
    'country_code' => '',
    'sign' => '₨',
    'active' => '0',
  ],
  'PAB' => 
  [
    'id' => 'PAB',
    'name' => 'Balboa',
    'number' => 590,
    'minor_units' => 2,
    'country_name' => 'PANAMA',
    'country_code' => '',
    'sign' => 'B/.',
    'active' => '0',
  ],
  'PGK' => 
  [
    'id' => 'PGK',
    'name' => 'Kina',
    'number' => 598,
    'minor_units' => 2,
    'country_name' => 'PAPUA NEW GUINEA',
    'country_code' => '',
    'sign' => 'K',
    'active' => '0',
  ],
  'PYG' => 
  [
    'id' => 'PYG',
    'name' => 'Guarani',
    'number' => 600,
    'minor_units' => 0,
    'country_name' => 'PARAGUAY',
    'country_code' => '',
    'sign' => '₲',
    'active' => '0',
  ],
  'PEN' => 
  [
    'id' => 'PEN',
    'name' => 'Nuevo Sol',
    'number' => 604,
    'minor_units' => 2,
    'country_name' => 'PERU',
    'country_code' => '',
    'sign' => 'S/.',
    'active' => '0',
  ],
  'PHP' => 
  [
    'id' => 'PHP',
    'name' => 'Philippine Peso',
    'number' => 608,
    'minor_units' => 2,
    'country_name' => 'PHILIPPINES',
    'country_code' => '',
    'sign' => '₱',
    'active' => '0',
  ],
  'PLN' => 
  [
    'id' => 'PLN',
    'name' => 'Zloty',
    'number' => 985,
    'minor_units' => 2,
    'country_name' => 'POLAND',
    'country_code' => '',
    'sign' => 'zł',
    'active' => '0',
  ],
  'QAR' => 
  [
    'id' => 'QAR',
    'name' => 'Qatari Rial',
    'number' => 634,
    'minor_units' => 2,
    'country_name' => 'QATAR',
    'country_code' => '',
    'sign' => 'ر.ق',
    'active' => '0',
  ],
  'RON' => 
  [
    'id' => 'RON',
    'name' => 'New Romanian Leu',
    'number' => 946,
    'minor_units' => 2,
    'country_name' => 'ROMANIA',
    'country_code' => '',
    'sign' => 'L',
    'active' => '0',
  ],
  'RUB' => 
  [
    'id' => 'RUB',
    'name' => 'Russian Ruble',
    'number' => 643,
    'minor_units' => 2,
    'country_name' => 'RUSSIAN FEDERATION',
    'country_code' => '',
    'sign' => 'р.',
    'active' => 1,
  ],
  'RWF' => 
  [
    'id' => 'RWF',
    'name' => 'Rwanda Franc',
    'number' => 646,
    'minor_units' => 0,
    'country_name' => 'RWANDA',
    'country_code' => '',
    'sign' => 'Fr',
    'active' => '0',
  ],
  'SHP' => 
  [
    'id' => 'SHP',
    'name' => 'Saint Helena Pound',
    'number' => 654,
    'minor_units' => 2,
    'country_name' => 'SAINT HELENA, ASCENSION AND TRISTAN DA CUNHA',
    'country_code' => '',
    'sign' => '£',
    'active' => '0',
  ],
  'WST' => 
  [
    'id' => 'WST',
    'name' => 'Tala',
    'number' => 882,
    'minor_units' => 2,
    'country_name' => 'SAMOA',
    'country_code' => '',
    'sign' => 'T',
    'active' => '0',
  ],
  'STD' => 
  [
    'id' => 'STD',
    'name' => 'Dobra',
    'number' => 678,
    'minor_units' => 2,
    'country_name' => 'SAO TOME AND PRINCIPE',
    'country_code' => '',
    'sign' => 'Db',
    'active' => '0',
  ],
  'SAR' => 
  [
    'id' => 'SAR',
    'name' => 'Saudi Riyal',
    'number' => 682,
    'minor_units' => 2,
    'country_name' => 'SAUDI ARABIA',
    'country_code' => '',
    'sign' => 'ر.س',
    'active' => '0',
  ],
  'RSD' => 
  [
    'id' => 'RSD',
    'name' => 'Serbian Dinar',
    'number' => 941,
    'minor_units' => 2,
    'country_name' => 'SERBIA',
    'country_code' => '',
    'sign' => '',
    'active' => '0',
  ],
  'SCR' => 
  [
    'id' => 'SCR',
    'name' => 'Seychelles Rupee',
    'number' => 690,
    'minor_units' => 2,
    'country_name' => 'SEYCHELLES',
    'country_code' => '',
    'sign' => '₨',
    'active' => '0',
  ],
  'SLL' => 
  [
    'id' => 'SLL',
    'name' => 'Leone',
    'number' => 694,
    'minor_units' => 2,
    'country_name' => 'SIERRA LEONE',
    'country_code' => '',
    'sign' => 'Le',
    'active' => '0',
  ],
  'SGD' => 
  [
    'id' => 'SGD',
    'name' => 'Singapore Dollar',
    'number' => 702,
    'minor_units' => 2,
    'country_name' => 'SINGAPORE',
    'country_code' => '',
    'sign' => '$',
    'active' => '0',
  ],
  'XSU' => 
  [
    'id' => 'XSU',
    'name' => 'Sucre',
    'number' => 994,
    'minor_units' => 0,
    'country_name' => 'SISTEMA UNITARIO DE COMPENSACION REGIONAL DE PAGOS "SUCRE"',
    'country_code' => '',
    'sign' => '',
    'active' => '0',
  ],
  'SBD' => 
  [
    'id' => 'SBD',
    'name' => 'Solomon Islands Dollar',
    'number' => 90,
    'minor_units' => 2,
    'country_name' => 'SOLOMON ISLANDS',
    'country_code' => '',
    'sign' => '$',
    'active' => '0',
  ],
  'SOS' => 
  [
    'id' => 'SOS',
    'name' => 'Somali Shilling',
    'number' => 706,
    'minor_units' => 2,
    'country_name' => 'SOMALIA',
    'country_code' => '',
    'sign' => 'Sh',
    'active' => '0',
  ],
  'SSP' => 
  [
    'id' => 'SSP',
    'name' => 'South Sudanese Pound',
    'number' => 728,
    'minor_units' => 2,
    'country_name' => 'SOUTH SUDAN',
    'country_code' => '',
    'sign' => '£',
    'active' => '0',
  ],
  'LKR' => 
  [
    'id' => 'LKR',
    'name' => 'Sri Lanka Rupee',
    'number' => 144,
    'minor_units' => 2,
    'country_name' => 'SRI LANKA',
    'country_code' => '',
    'sign' => '',
    'active' => '0',
  ],
  'SDG' => 
  [
    'id' => 'SDG',
    'name' => 'Sudanese Pound',
    'number' => 938,
    'minor_units' => 2,
    'country_name' => 'SUDAN',
    'country_code' => '',
    'sign' => '£',
    'active' => '0',
  ],
  'SRD' => 
  [
    'id' => 'SRD',
    'name' => 'Surinam Dollar',
    'number' => 968,
    'minor_units' => 2,
    'country_name' => 'SURINAME',
    'country_code' => '',
    'sign' => '$',
    'active' => '0',
  ],
  'SZL' => 
  [
    'id' => 'SZL',
    'name' => 'Lilangeni',
    'number' => 748,
    'minor_units' => 2,
    'country_name' => 'SWAZILAND',
    'country_code' => '',
    'sign' => 'L',
    'active' => '0',
  ],
  'SEK' => 
  [
    'id' => 'SEK',
    'name' => 'Swedish Krona',
    'number' => 752,
    'minor_units' => 2,
    'country_name' => 'SWEDEN',
    'country_code' => '',
    'sign' => 'kr',
    'active' => '0',
  ],
  'CHE' => 
  [
    'id' => 'CHE',
    'name' => 'WIR Euro',
    'number' => 947,
    'minor_units' => 2,
    'country_name' => 'SWITZERLAND',
    'country_code' => '',
    'sign' => '',
    'active' => '0',
  ],
  'CHW' => 
  [
    'id' => 'CHW',
    'name' => 'WIR Franc',
    'number' => 948,
    'minor_units' => 2,
    'country_name' => 'SWITZERLAND',
    'country_code' => '',
    'sign' => '',
    'active' => '0',
  ],
  'SYP' => 
  [
    'id' => 'SYP',
    'name' => 'Syrian Pound',
    'number' => 760,
    'minor_units' => 2,
    'country_name' => 'SYRIAN ARAB REPUBLIC',
    'country_code' => '',
    'sign' => '',
    'active' => '0',
  ],
  'TWD' => 
  [
    'id' => 'TWD',
    'name' => 'New Taiwan Dollar',
    'number' => 901,
    'minor_units' => 2,
    'country_name' => 'TAIWAN, PROVINCE OF CHINA',
    'country_code' => '',
    'sign' => '$',
    'active' => '0',
  ],
  'TJS' => 
  [
    'id' => 'TJS',
    'name' => 'Somoni',
    'number' => 972,
    'minor_units' => 2,
    'country_name' => 'TAJIKISTAN',
    'country_code' => '',
    'sign' => 'ЅМ',
    'active' => '0',
  ],
  'TZS' => 
  [
    'id' => 'TZS',
    'name' => 'Tanzanian Shilling',
    'number' => 834,
    'minor_units' => 2,
    'country_name' => 'TANZANIA, UNITED REPUBLIC OF',
    'country_code' => '',
    'sign' => 'Sh',
    'active' => '0',
  ],
  'THB' => 
  [
    'id' => 'THB',
    'name' => 'Baht',
    'number' => 764,
    'minor_units' => 2,
    'country_name' => 'THAILAND',
    'country_code' => '',
    'sign' => '฿',
    'active' => '0',
  ],
  'TOP' => 
  [
    'id' => 'TOP',
    'name' => 'Pa’anga',
    'number' => 776,
    'minor_units' => 2,
    'country_name' => 'TONGA',
    'country_code' => '',
    'sign' => 'T$',
    'active' => '0',
  ],
  'TTD' => 
  [
    'id' => 'TTD',
    'name' => 'Trinidad and Tobago Dollar',
    'number' => 780,
    'minor_units' => 2,
    'country_name' => 'TRINIDAD AND TOBAGO',
    'country_code' => '',
    'sign' => '$',
    'active' => '0',
  ],
  'TND' => 
  [
    'id' => 'TND',
    'name' => 'Tunisian Dinar',
    'number' => 788,
    'minor_units' => 3,
    'country_name' => 'TUNISIA',
    'country_code' => '',
    'sign' => 'د.ت',
    'active' => '0',
  ],
  'TRY' => 
  [
    'id' => 'TRY',
    'name' => 'Turkish Lira',
    'number' => 949,
    'minor_units' => 2,
    'country_name' => 'TURKEY',
    'country_code' => '',
    'sign' => '',
    'active' => '0',
  ],
  'TMT' => 
  [
    'id' => 'TMT',
    'name' => 'Turkmenistan New Manat',
    'number' => 934,
    'minor_units' => 2,
    'country_name' => 'TURKMENISTAN',
    'country_code' => '',
    'sign' => 'm',
    'active' => '0',
  ],
  'UGX' => 
  [
    'id' => 'UGX',
    'name' => 'Uganda Shilling',
    'number' => 800,
    'minor_units' => 0,
    'country_name' => 'UGANDA',
    'country_code' => '',
    'sign' => 'Sh',
    'active' => '0',
  ],
  'UAH' => 
  [
    'id' => 'UAH',
    'name' => 'Hryvnia',
    'number' => 980,
    'minor_units' => 2,
    'country_name' => 'UKRAINE',
    'country_code' => '',
    'sign' => '₴',
    'active' => 1,
  ],
  'AED' => 
  [
    'id' => 'AED',
    'name' => 'UAE Dirham',
    'number' => 784,
    'minor_units' => 2,
    'country_name' => 'UNITED ARAB EMIRATES',
    'country_code' => '',
    'sign' => 'د.إ',
    'active' => '0',
  ],
  'USN' => 
  [
    'id' => 'USN',
    'name' => 'US Dollar (Next day)',
    'number' => 997,
    'minor_units' => 2,
    'country_name' => 'UNITED STATES',
    'country_code' => '',
    'sign' => '',
    'active' => '0',
  ],
  'USS' => 
  [
    'id' => 'USS',
    'name' => 'US Dollar (Same day)',
    'number' => 998,
    'minor_units' => 2,
    'country_name' => 'UNITED STATES',
    'country_code' => '',
    'sign' => '',
    'active' => '0',
  ],
  'UYI' => 
  [
    'id' => 'UYI',
    'name' => 'Uruguay Peso en Unidades Indexadas (URUIURUI)',
    'number' => 940,
    'minor_units' => 0,
    'country_name' => 'URUGUAY',
    'country_code' => '',
    'sign' => '',
    'active' => '0',
  ],
  'UYU' => 
  [
    'id' => 'UYU',
    'name' => 'Peso Uruguayo',
    'number' => 858,
    'minor_units' => 2,
    'country_name' => 'URUGUAY',
    'country_code' => '',
    'sign' => '$',
    'active' => '0',
  ],
  'UZS' => 
  [
    'id' => 'UZS',
    'name' => 'Uzbekistan Sum',
    'number' => 860,
    'minor_units' => 2,
    'country_name' => 'UZBEKISTAN',
    'country_code' => '',
    'sign' => '',
    'active' => '0',
  ],
  'VUV' => 
  [
    'id' => 'VUV',
    'name' => 'Vatu',
    'number' => 548,
    'minor_units' => 0,
    'country_name' => 'VANUATU',
    'country_code' => '',
    'sign' => 'Vt',
    'active' => '0',
  ],
  'VEF' => 
  [
    'id' => 'VEF',
    'name' => 'Bolivar',
    'number' => 937,
    'minor_units' => 2,
    'country_name' => 'VENEZUELA, BOLIVARIAN REPUBLIC OF',
    'country_code' => '',
    'sign' => 'Bs F',
    'active' => '0',
  ],
  'VND' => 
  [
    'id' => 'VND',
    'name' => 'Dong',
    'number' => 704,
    'minor_units' => 0,
    'country_name' => 'VIET NAM',
    'country_code' => '',
    'sign' => '₫',
    'active' => '0',
  ],
  'YER' => 
  [
    'id' => 'YER',
    'name' => 'Yemeni Rial',
    'number' => 886,
    'minor_units' => 2,
    'country_name' => 'YEMEN',
    'country_code' => '',
    'sign' => '﷼',
    'active' => '0',
  ],
  'ZMW' => 
  [
    'id' => 'ZMW',
    'name' => 'Zambian Kwacha',
    'number' => 967,
    'minor_units' => 2,
    'country_name' => 'ZAMBIA',
    'country_code' => '',
    'sign' => 'ZK',
    'active' => '0',
  ],
  'ZWL' => 
  [
    'id' => 'ZWL',
    'name' => 'Zimbabwe Dollar',
    'number' => 932,
    'minor_units' => 2,
    'country_name' => 'ZIMBABWE',
    'country_code' => '',
    'sign' => '$',
    'active' => '0',
  ],
  'XBA' => 
  [
    'id' => 'XBA',
    'name' => 'Bond Markets Unit European Composite Unit (EURCO)',
    'number' => 955,
    'minor_units' => 0,
    'country_name' => 'ZZ01_Bond Markets Unit European_EURCO',
    'country_code' => '',
    'sign' => '',
    'active' => '0',
  ],
  'XBB' => 
  [
    'id' => 'XBB',
    'name' => 'Bond Markets Unit European Monetary Unit (E.M.U.-6)',
    'number' => 956,
    'minor_units' => 0,
    'country_name' => 'ZZ02_Bond Markets Unit European_EMU-6',
    'country_code' => '',
    'sign' => '',
    'active' => '0',
  ],
  'XBC' => 
  [
    'id' => 'XBC',
    'name' => 'Bond Markets Unit European Unit of Account 9 (E.U.A.-9)',
    'number' => 957,
    'minor_units' => 0,
    'country_name' => 'ZZ03_Bond Markets Unit European_EUA-9',
    'country_code' => '',
    'sign' => '',
    'active' => '0',
  ],
  'XBD' => 
  [
    'id' => 'XBD',
    'name' => 'Bond Markets Unit European Unit of Account 17 (E.U.A.-17)',
    'number' => 958,
    'minor_units' => 0,
    'country_name' => 'ZZ04_Bond Markets Unit European_EUA-17',
    'country_code' => '',
    'sign' => '',
    'active' => '0',
  ],
  'XFU' => 
  [
    'id' => 'XFU',
    'name' => 'UIC-Franc',
    'number' => 0,
    'minor_units' => 0,
    'country_name' => 'ZZ05_UIC-Franc',
    'country_code' => '',
    'sign' => '',
    'active' => '0',
  ],
  'XTS' => 
  [
    'id' => 'XTS',
    'name' => 'Codes specifically reserved for testing purposes',
    'number' => 963,
    'minor_units' => 0,
    'country_name' => 'ZZ06_Testing_Code',
    'country_code' => '',
    'sign' => '',
    'active' => '0',
  ],
  'XXX' => 
  [
    'id' => 'XXX',
    'name' => 'The codes assigned for transactions where no currency is involved',
    'number' => 999,
    'minor_units' => 0,
    'country_name' => 'ZZ07_No_Currency',
    'country_code' => '',
    'sign' => '',
    'active' => '0',
  ],
  'XAU' => 
  [
    'id' => 'XAU',
    'name' => 'Gold',
    'number' => 959,
    'minor_units' => 0,
    'country_name' => 'ZZ08_Gold',
    'country_code' => '',
    'sign' => '',
    'active' => '0',
  ],
  'XPD' => 
  [
    'id' => 'XPD',
    'name' => 'Palladium',
    'number' => 964,
    'minor_units' => 0,
    'country_name' => 'ZZ09_Palladium',
    'country_code' => '',
    'sign' => '',
    'active' => '0',
  ],
  'XPT' => 
  [
    'id' => 'XPT',
    'name' => 'Platinum',
    'number' => 962,
    'minor_units' => 0,
    'country_name' => 'ZZ10_Platinum',
    'country_code' => '',
    'sign' => '',
    'active' => '0',
  ],
  'XAG' => 
  [
    'id' => 'XAG',
    'name' => 'Silver',
    'number' => 961,
    'minor_units' => 0,
    'country_name' => 'ZZ11_Silver',
    'country_code' => '',
    'sign' => '',
    'active' => '0',
  ],
];