<?php
return array (
  8 => 
  array (
    'id' => '8',
    'object_name' => 'articles',
    'object_id' => '11',
    'parent_id' => '0',
    'user_id' => '1',
    'user_name' => '',
    'user_email' => '',
    'add_date' => '1208948307',
    'text' => '[COLOR=green]дуже цікава історія[/COLOR]',
    'ip' => '192.168.1.25',
    'active' => '1',
    'activity' => '0',
  ),
  9 => 
  array (
    'id' => '9',
    'object_name' => 'blog',
    'object_id' => '8',
    'parent_id' => '0',
    'user_id' => '6',
    'user_name' => '',
    'user_email' => '',
    'add_date' => '1208948524',
    'text' => 'треба буде якось туди завітати',
    'ip' => '192.168.1.25',
    'active' => '1',
    'activity' => '0',
  ),
  10 => 
  array (
    'id' => '10',
    'object_name' => 'news',
    'object_id' => '5',
    'parent_id' => '0',
    'user_id' => '6',
    'user_name' => '',
    'user_email' => '',
    'add_date' => '1208948707',
    'text' => 'дуже занятно...',
    'ip' => '192.168.1.25',
    'active' => '1',
    'activity' => '0',
  ),
  11 => 
  array (
    'id' => '11',
    'object_name' => 'blog',
    'object_id' => '9',
    'parent_id' => '0',
    'user_id' => '1',
    'user_name' => '',
    'user_email' => '',
    'add_date' => '1208954635',
    'text' => 'На декоде також заходив, в себе про нього відпишуся',
    'ip' => '192.168.1.25',
    'active' => '1',
    'activity' => '0',
  ),
  12 => 
  array (
    'id' => '12',
    'object_name' => 'blog',
    'object_id' => '8',
    'parent_id' => '9',
    'user_id' => '1',
    'user_name' => '',
    'user_email' => '',
    'add_date' => '1208956866',
    'text' => 'так тебе туди і пустять:))',
    'ip' => '192.168.1.25',
    'active' => '1',
    'activity' => '0',
  ),
);