<?php
$data = array (
  7 => 
  array (
    'id' => '7',
    'parent' => '2',
    'forum' => '0',
    'topic' => '0',
    'user_id' => '7',
    'user_name' => 'xchaotic',
    'created' => '1208944628',
    'status' => 'a',
    'subject' => '9',
    'text' => '3',
    'new_topic' => '22',
    'edit_name' => '25',
    'edit_time' => '4',
    'show_edit_by' => '0',
    'use_sig' => '255',
    'use_emo' => '0',
    'icon_id' => '0',
    'poster_ip' => '',
    'language' => '1',
    'activity' => '0',
  ),
  8 => 
  array (
    'id' => '8',
    'parent' => '2',
    'forum' => '0',
    'topic' => '0',
    'user_id' => '1',
    'user_name' => 'test',
    'created' => '1208947652',
    'status' => 'a',
    'subject' => '11',
    'text' => '3',
    'new_topic' => '26',
    'edit_name' => '29',
    'edit_time' => '1',
    'show_edit_by' => '0',
    'use_sig' => '255',
    'use_emo' => '0',
    'icon_id' => '0',
    'poster_ip' => '',
    'language' => '1',
    'activity' => '0',
  ),
  9 => 
  array (
    'id' => '9',
    'parent' => '2',
    'forum' => '0',
    'topic' => '0',
    'user_id' => '7',
    'user_name' => 'xchaotic',
    'created' => '1208950009',
    'status' => 'a',
    'subject' => '8',
    'text' => '0',
    'new_topic' => '30',
    'edit_name' => '30',
    'edit_time' => '7',
    'show_edit_by' => '0',
    'use_sig' => '255',
    'use_emo' => '0',
    'icon_id' => '0',
    'poster_ip' => '',
    'language' => '1',
    'activity' => '0',
  ),
  10 => 
  array (
    'id' => '10',
    'parent' => '2',
    'forum' => '0',
    'topic' => '0',
    'user_id' => '4',
    'user_name' => 'serega',
    'created' => '1208958665',
    'status' => 'a',
    'subject' => '12',
    'text' => '1',
    'new_topic' => '31',
    'edit_name' => '32',
    'edit_time' => '1',
    'show_edit_by' => '0',
    'use_sig' => '255',
    'use_emo' => '0',
    'icon_id' => '0',
    'poster_ip' => '',
    'language' => '1',
    'activity' => '0',
  ),
);