<?php
$data = array (
  7 => 
  array (
    'id' => '7',
    'forum' => '2',
    'name' => 'Seagate Barracuda 7200.7 IDE',
    'desc' => 'Seagate Barracuda 7200.7 IDE, Сломался хард,помогите',
    'user_id' => '5',
    'user_name' => 'odlman',
    'created' => '1208252476',
    'status' => 'a',
    'num_views' => '11',
    'num_posts' => '4',
    'first_post_id' => '22',
    'last_post_id' => '26',
    'last_poster_id' => '5',
    'last_poster_name' => 'odlman',
    'last_post_date' => '1208253034',
    'icon_id' => '0',
    'pinned' => '0',
    'moved_to' => '',
    'approved' => '1',
    'language' => '0',
  ),
  8 => 
  array (
    'id' => '8',
    'forum' => '2',
    'name' => 'цифровой дом',
    'desc' => 'Цифровой Дом (Digital Home) Видеонаблюдение за машиной ночью',
    'user_id' => '1',
    'user_name' => 'test',
    'created' => '1208257853',
    'status' => 'a',
    'num_views' => '13',
    'num_posts' => '6',
    'first_post_id' => '27',
    'last_post_id' => '33',
    'last_poster_id' => '1',
    'last_poster_name' => 'test',
    'last_post_date' => '1208258390',
    'icon_id' => '0',
    'pinned' => '0',
    'moved_to' => '',
    'approved' => '1',
    'language' => '0',
  ),
);