<?php
$data = '
	`id` int(10) unsigned NOT NULL auto_increment,
	`id2` int(10) unsigned NOT NULL,
	`user_name` varchar(255) NOT NULL default \'\',
	`user_id` int(10) unsigned NOT NULL default \'0\',
	`poster_id` int(11) unsigned NOT NULL default \'0\',
	`cat_id` smallint(5) unsigned NOT NULL default \'0\',
	`title` varchar(255) NOT NULL default \'\',
	`text` text NOT NULL,
	`add_date` int(10) unsigned NOT NULL default \'0\',
	`edit_date` int(10) unsigned NOT NULL,
	`ip` varchar(15) NOT NULL default \'\',
	`num_reads` int(10) unsigned NOT NULL default \'0\',
	`attach_image` varchar(255) NOT NULL default \'\',
	`disable_comments` enum(\'0\',\'1\') NOT NULL default \'0\',
	`mode_type` tinyint(3) unsigned NOT NULL default \'0\',
	`mode_text` varchar(255) NOT NULL default \'\',
	`mood` varchar(255) NOT NULL default \'\',
	`privacy` tinyint(3) unsigned NOT NULL default \'0\',
	`allow_comments` tinyint(3) unsigned NOT NULL,
	`active` tinyint(1) unsigned NOT NULL default \'0\',
	`custom_cat_id` smallint(5) unsigned NOT NULL,
	`activity` int(10) unsigned NOT NULL default \'0\',
	`old_id` int(10) unsigned NOT NULL,
	`mask` int(10) unsigned NOT NULL,
	PRIMARY KEY  (`id`),
	KEY `user_id` (`user_id`),
	KEY `id2` (`id2`)
';