<?php
$data = '
	`id` int(10) unsigned NOT NULL AUTO_INCREMENT,
	`name` varchar(255) CHARACTER SET utf8 NOT NULL DEFAULT \'\',
	`url` varchar(255) CHARACTER SET utf8 NOT NULL DEFAULT \'\',
	`image` enum(\'0\',\'1\') CHARACTER SET utf8 NOT NULL DEFAULT \'0\',
	`description` text CHARACTER SET utf8 NOT NULL,
	`meta_keywords` text CHARACTER SET utf8 NOT NULL,
	`meta_desc` text CHARACTER SET utf8 NOT NULL,
	`external_url` varchar(255) CHARACTER SET utf8 NOT NULL DEFAULT \'\',
	`cat_id` text CHARACTER SET utf8 NOT NULL,
	`model` varchar(64) CHARACTER SET utf8 NOT NULL,
	`sku` varchar(64) CHARACTER SET utf8 NOT NULL,
	`quantity` int(10) NOT NULL DEFAULT \'0\',
	`stock_status_id` int(10) NOT NULL DEFAULT \'0\',
	`manufacturer_id` int(10) NOT NULL DEFAULT \'0\',
	`supplier_id` int(10) NOT NULL DEFAULT \'0\',
	`price` decimal(8,2) NOT NULL DEFAULT \'0.00\',
	`price_promo` decimal(8,2) NOT NULL DEFAULT \'0.00\',
	`price_partner` decimal(8,2) NOT NULL DEFAULT \'0.00\',
	`price_raw` decimal(8,2) NOT NULL DEFAULT \'0.00\',
	`old_price` decimal(8,2) NOT NULL DEFAULT \'0.00\',
	`currency` tinyint(3) unsigned NOT NULL DEFAULT \'0\',
	`add_date` int(10) unsigned NOT NULL DEFAULT \'0\',
	`update_date` int(10) unsigned NOT NULL DEFAULT \'0\',
	`last_viewed_date` int(10) NOT NULL DEFAULT \'0\',
	`featured` enum(\'0\',\'1\') CHARACTER SET utf8 NOT NULL DEFAULT \'0\',
	`active` enum(\'0\',\'1\') CHARACTER SET utf8 NOT NULL DEFAULT \'0\',
	`viewed` int(10) NOT NULL DEFAULT \'0\',
	PRIMARY KEY (`id`)
';