<?php

return [
  0 => [
    'c' => 'AD',
    'n' => 'Andorra',
    'f' => '0',
    'cont' => 'E',
    'call_code' => '',
  ],
  1 => [
    'c' => 'AE',
    'n' => 'United Arab Emirates',
    'f' => '0',
    'cont' => 'A',
    'call_code' => '',
  ],
  2 => [
    'c' => 'AF',
    'n' => 'Afghanistan',
    'f' => '0',
    'cont' => 'A',
    'call_code' => '',
  ],
  3 => [
    'c' => 'AG',
    'n' => 'Antigua and Barbuda',
    'f' => '0',
    'cont' => 'N',
    'call_code' => '',
  ],
  4 => [
    'c' => 'AI',
    'n' => 'Anguilla',
    'f' => '0',
    'cont' => 'N',
    'call_code' => '',
  ],
  5 => [
    'c' => 'AL',
    'n' => 'Albania',
    'f' => '0',
    'cont' => 'E',
    'call_code' => '',
  ],
  6 => [
    'c' => 'AM',
    'n' => 'Armenia',
    'f' => '0',
    'cont' => 'A',
    'call_code' => '',
  ],
  7 => [
    'c' => 'AN',
    'n' => 'Netherlands Antilles',
    'f' => '0',
    'cont' => 'N',
    'call_code' => '',
  ],
  8 => [
    'c' => 'AO',
    'n' => 'Angola',
    'f' => '0',
    'cont' => 'F',
    'call_code' => '',
  ],
  9 => [
    'c' => 'AQ',
    'n' => 'Antarctica',
    'f' => '0',
    'cont' => 'Q',
    'call_code' => '',
  ],
  10 => [
    'c' => 'AR',
    'n' => 'Argentina',
    'f' => '0',
    'cont' => 'S',
    'call_code' => '',
  ],
  11 => [
    'c' => 'AS',
    'n' => 'American Samoa',
    'f' => '0',
    'cont' => 'U',
    'call_code' => '',
  ],
  12 => [
    'c' => 'AT',
    'n' => 'Austria',
    'f' => '0',
    'cont' => 'E',
    'call_code' => '',
  ],
  13 => [
    'c' => 'AU',
    'n' => 'Australia',
    'f' => '0',
    'cont' => 'U',
    'call_code' => '',
  ],
  14 => [
    'c' => 'AW',
    'n' => 'Aruba',
    'f' => '0',
    'cont' => 'N',
    'call_code' => '',
  ],
  15 => [
    'c' => 'AX',
    'n' => 'Aland Islands',
    'f' => '0',
    'cont' => 'E',
    'call_code' => '',
  ],
  16 => [
    'c' => 'AZ',
    'n' => 'Azerbaijan',
    'f' => '0',
    'cont' => 'A',
    'call_code' => '',
  ],
  17 => [
    'c' => 'BA',
    'n' => 'Bosnia and Herzegovina',
    'f' => '0',
    'cont' => 'E',
    'call_code' => '',
  ],
  18 => [
    'c' => 'BB',
    'n' => 'Barbados',
    'f' => '0',
    'cont' => 'N',
    'call_code' => '',
  ],
  19 => [
    'c' => 'BD',
    'n' => 'Bangladesh',
    'f' => '0',
    'cont' => 'A',
    'call_code' => '',
  ],
  20 => [
    'c' => 'BE',
    'n' => 'Belgium',
    'f' => '0',
    'cont' => 'E',
    'call_code' => '',
  ],
  21 => [
    'c' => 'BF',
    'n' => 'Burkina Faso',
    'f' => '0',
    'cont' => 'F',
    'call_code' => '',
  ],
  22 => [
    'c' => 'BG',
    'n' => 'Bulgaria',
    'f' => '0',
    'cont' => 'E',
    'call_code' => '',
  ],
  23 => [
    'c' => 'BH',
    'n' => 'Bahrain',
    'f' => '0',
    'cont' => 'A',
    'call_code' => '',
  ],
  24 => [
    'c' => 'BI',
    'n' => 'Burundi',
    'f' => '0',
    'cont' => 'F',
    'call_code' => '',
  ],
  25 => [
    'c' => 'BJ',
    'n' => 'Benin',
    'f' => '0',
    'cont' => 'F',
    'call_code' => '',
  ],
  26 => [
    'c' => 'BM',
    'n' => 'Bermuda',
    'f' => '0',
    'cont' => 'N',
    'call_code' => '',
  ],
  27 => [
    'c' => 'BN',
    'n' => 'Brunei Darussalam',
    'f' => '0',
    'cont' => 'A',
    'call_code' => '',
  ],
  28 => [
    'c' => 'BO',
    'n' => 'Bolivia',
    'f' => '0',
    'cont' => 'S',
    'call_code' => '',
  ],
  29 => [
    'c' => 'BR',
    'n' => 'Brazil',
    'f' => '0',
    'cont' => 'S',
    'call_code' => '',
  ],
  30 => [
    'c' => 'BS',
    'n' => 'Bahamas',
    'f' => '0',
    'cont' => 'N',
    'call_code' => '',
  ],
  31 => [
    'c' => 'BT',
    'n' => 'Bhutan',
    'f' => '0',
    'cont' => 'A',
    'call_code' => '',
  ],
  32 => [
    'c' => 'BV',
    'n' => 'Bouvet Island',
    'f' => '0',
    'cont' => 'Q',
    'call_code' => '',
  ],
  33 => [
    'c' => 'BW',
    'n' => 'Botswana',
    'f' => '0',
    'cont' => 'F',
    'call_code' => '',
  ],
  34 => [
    'c' => 'BY',
    'n' => 'Belarus',
    'f' => '0',
    'cont' => 'E',
    'call_code' => '',
  ],
  35 => [
    'c' => 'BZ',
    'n' => 'Belize',
    'f' => '0',
    'cont' => 'N',
    'call_code' => '',
  ],
  36 => [
    'c' => 'CA',
    'n' => 'Canada',
    'f' => '1',
    'cont' => 'N',
    'call_code' => '',
  ],
  37 => [
    'c' => 'CC',
    'n' => 'Cocos (Keeling) Islands',
    'f' => '0',
    'cont' => 'A',
    'call_code' => '',
  ],
  38 => [
    'c' => 'CD',
    'n' => 'Congo, Democratic Republic of the',
    'f' => '0',
    'cont' => 'F',
    'call_code' => '',
  ],
  39 => [
    'c' => 'CF',
    'n' => 'Central African Republic',
    'f' => '0',
    'cont' => 'F',
    'call_code' => '',
  ],
  40 => [
    'c' => 'CG',
    'n' => 'Congo',
    'f' => '0',
    'cont' => 'F',
    'call_code' => '',
  ],
  41 => [
    'c' => 'CH',
    'n' => 'Switzerland',
    'f' => '0',
    'cont' => 'E',
    'call_code' => '',
  ],
  42 => [
    'c' => 'CI',
    'n' => 'Cote d\'Ivoire',
    'f' => '0',
    'cont' => 'F',
    'call_code' => '',
  ],
  43 => [
    'c' => 'CK',
    'n' => 'Cook Islands',
    'f' => '0',
    'cont' => 'U',
    'call_code' => '',
  ],
  44 => [
    'c' => 'CL',
    'n' => 'Chile',
    'f' => '0',
    'cont' => 'S',
    'call_code' => '',
  ],
  45 => [
    'c' => 'CM',
    'n' => 'Cameroon',
    'f' => '0',
    'cont' => 'F',
    'call_code' => '',
  ],
  46 => [
    'c' => 'CN',
    'n' => 'China',
    'f' => '0',
    'cont' => 'A',
    'call_code' => '',
  ],
  47 => [
    'c' => 'CO',
    'n' => 'Colombia',
    'f' => '0',
    'cont' => 'S',
    'call_code' => '',
  ],
  48 => [
    'c' => 'CR',
    'n' => 'Costa Rica',
    'f' => '0',
    'cont' => 'N',
    'call_code' => '',
  ],
  49 => [
    'c' => 'CU',
    'n' => 'Cuba',
    'f' => '0',
    'cont' => 'N',
    'call_code' => '',
  ],
  50 => [
    'c' => 'CV',
    'n' => 'Cape Verde',
    'f' => '0',
    'cont' => 'F',
    'call_code' => '',
  ],
  51 => [
    'c' => 'CX',
    'n' => 'Christmas Island',
    'f' => '0',
    'cont' => 'A',
    'call_code' => '',
  ],
  52 => [
    'c' => 'CY',
    'n' => 'Cyprus',
    'f' => '0',
    'cont' => 'A',
    'call_code' => '',
  ],
  53 => [
    'c' => 'CZ',
    'n' => 'Czech Republic',
    'f' => '0',
    'cont' => 'E',
    'call_code' => '',
  ],
  54 => [
    'c' => 'DE',
    'n' => 'Germany',
    'f' => '0',
    'cont' => 'E',
    'call_code' => '',
  ],
  55 => [
    'c' => 'DJ',
    'n' => 'Djibouti',
    'f' => '0',
    'cont' => 'F',
    'call_code' => '',
  ],
  56 => [
    'c' => 'DK',
    'n' => 'Denmark',
    'f' => '0',
    'cont' => 'E',
    'call_code' => '',
  ],
  57 => [
    'c' => 'DM',
    'n' => 'Dominica',
    'f' => '0',
    'cont' => 'N',
    'call_code' => '',
  ],
  58 => [
    'c' => 'DO',
    'n' => 'Dominican Republic',
    'f' => '0',
    'cont' => 'N',
    'call_code' => '',
  ],
  59 => [
    'c' => 'DZ',
    'n' => 'Algeria',
    'f' => '0',
    'cont' => 'F',
    'call_code' => '',
  ],
  60 => [
    'c' => 'EC',
    'n' => 'Ecuador',
    'f' => '0',
    'cont' => 'S',
    'call_code' => '',
  ],
  61 => [
    'c' => 'EE',
    'n' => 'Estonia',
    'f' => '0',
    'cont' => 'E',
    'call_code' => '',
  ],
  62 => [
    'c' => 'EG',
    'n' => 'Egypt',
    'f' => '0',
    'cont' => 'F',
    'call_code' => '',
  ],
  63 => [
    'c' => 'EH',
    'n' => 'Western Sahara',
    'f' => '0',
    'cont' => 'F',
    'call_code' => '',
  ],
  64 => [
    'c' => 'ER',
    'n' => 'Eritrea',
    'f' => '0',
    'cont' => 'F',
    'call_code' => '',
  ],
  65 => [
    'c' => 'ES',
    'n' => 'Spain',
    'f' => '0',
    'cont' => 'E',
    'call_code' => '',
  ],
  66 => [
    'c' => 'ET',
    'n' => 'Ethiopia',
    'f' => '0',
    'cont' => 'F',
    'call_code' => '',
  ],
  67 => [
    'c' => 'FI',
    'n' => 'Finland',
    'f' => '0',
    'cont' => 'E',
    'call_code' => '',
  ],
  68 => [
    'c' => 'FJ',
    'n' => 'Fiji',
    'f' => '0',
    'cont' => 'U',
    'call_code' => '',
  ],
  69 => [
    'c' => 'FK',
    'n' => 'Falkland Islands',
    'f' => '0',
    'cont' => 'S',
    'call_code' => '',
  ],
  70 => [
    'c' => 'FM',
    'n' => 'Federated States of Micronesia',
    'f' => '0',
    'cont' => 'U',
    'call_code' => '',
  ],
  71 => [
    'c' => 'FO',
    'n' => 'Faroe Islands',
    'f' => '0',
    'cont' => 'E',
    'call_code' => '',
  ],
  72 => [
    'c' => 'FR',
    'n' => 'France',
    'f' => '0',
    'cont' => 'N',
    'call_code' => '',
  ],
  73 => [
    'c' => 'GA',
    'n' => 'Gabon',
    'f' => '0',
    'cont' => 'F',
    'call_code' => '',
  ],
  74 => [
    'c' => 'GB',
    'n' => 'United Kingdom',
    'f' => '1',
    'cont' => 'E',
    'call_code' => '',
  ],
  75 => [
    'c' => 'GD',
    'n' => 'Grenada',
    'f' => '0',
    'cont' => 'N',
    'call_code' => '',
  ],
  76 => [
    'c' => 'GE',
    'n' => 'Georgia',
    'f' => '0',
    'cont' => 'A',
    'call_code' => '',
  ],
  77 => [
    'c' => 'GF',
    'n' => 'French Guiana',
    'f' => '0',
    'cont' => 'S',
    'call_code' => '',
  ],
  78 => [
    'c' => 'GG',
    'n' => 'Guernsey',
    'f' => '0',
    'cont' => 'E',
    'call_code' => '',
  ],
  79 => [
    'c' => 'GH',
    'n' => 'Ghana',
    'f' => '0',
    'cont' => 'F',
    'call_code' => '',
  ],
  80 => [
    'c' => 'GI',
    'n' => 'Gibraltar',
    'f' => '0',
    'cont' => 'E',
    'call_code' => '',
  ],
  81 => [
    'c' => 'GL',
    'n' => 'Greenland',
    'f' => '0',
    'cont' => 'N',
    'call_code' => '',
  ],
  82 => [
    'c' => 'GM',
    'n' => 'Gambia',
    'f' => '0',
    'cont' => 'F',
    'call_code' => '',
  ],
  83 => [
    'c' => 'GN',
    'n' => 'Guinea',
    'f' => '0',
    'cont' => 'F',
    'call_code' => '',
  ],
  84 => [
    'c' => 'GP',
    'n' => 'Guadeloupe',
    'f' => '0',
    'cont' => 'N',
    'call_code' => '',
  ],
  85 => [
    'c' => 'GQ',
    'n' => 'Equatorial Guinea',
    'f' => '0',
    'cont' => 'F',
    'call_code' => '',
  ],
  86 => [
    'c' => 'GR',
    'n' => 'Greece',
    'f' => '0',
    'cont' => 'E',
    'call_code' => '',
  ],
  87 => [
    'c' => 'GS',
    'n' => 'South Georgia and Sandwich Islands',
    'f' => '0',
    'cont' => 'Q',
    'call_code' => '',
  ],
  88 => [
    'c' => 'GT',
    'n' => 'Guatemala',
    'f' => '0',
    'cont' => 'N',
    'call_code' => '',
  ],
  89 => [
    'c' => 'GU',
    'n' => 'Guam',
    'f' => '0',
    'cont' => 'U',
    'call_code' => '',
  ],
  90 => [
    'c' => 'GW',
    'n' => 'Guinea-Bissau',
    'f' => '0',
    'cont' => 'F',
    'call_code' => '',
  ],
  91 => [
    'c' => 'GY',
    'n' => 'Guyana',
    'f' => '0',
    'cont' => 'S',
    'call_code' => '',
  ],
  92 => [
    'c' => 'HK',
    'n' => 'Hong Kong',
    'f' => '0',
    'cont' => 'A',
    'call_code' => '',
  ],
  93 => [
    'c' => 'HM',
    'n' => 'Heard Island and McDonald Islands',
    'f' => '0',
    'cont' => 'Q',
    'call_code' => '',
  ],
  94 => [
    'c' => 'HN',
    'n' => 'Honduras',
    'f' => '0',
    'cont' => 'N',
    'call_code' => '',
  ],
  95 => [
    'c' => 'HR',
    'n' => 'Croatia',
    'f' => '0',
    'cont' => 'E',
    'call_code' => '',
  ],
  96 => [
    'c' => 'HT',
    'n' => 'Haiti',
    'f' => '0',
    'cont' => 'N',
    'call_code' => '',
  ],
  97 => [
    'c' => 'HU',
    'n' => 'Hungary',
    'f' => '0',
    'cont' => 'E',
    'call_code' => '',
  ],
  98 => [
    'c' => 'ID',
    'n' => 'Indonesia',
    'f' => '0',
    'cont' => 'A',
    'call_code' => '',
  ],
  99 => [
    'c' => 'IE',
    'n' => 'Ireland',
    'f' => '0',
    'cont' => 'E',
    'call_code' => '',
  ],
  100 => [
    'c' => 'IL',
    'n' => 'Israel',
    'f' => '0',
    'cont' => 'A',
    'call_code' => '',
  ],
  101 => [
    'c' => 'IM',
    'n' => 'Isle of Man',
    'f' => '0',
    'cont' => 'E',
    'call_code' => '',
  ],
  102 => [
    'c' => 'IN',
    'n' => 'India',
    'f' => '0',
    'cont' => 'A',
    'call_code' => '',
  ],
  103 => [
    'c' => 'IO',
    'n' => 'British Indian Ocean Territory',
    'f' => '0',
    'cont' => 'A',
    'call_code' => '',
  ],
  104 => [
    'c' => 'IQ',
    'n' => 'Iraq',
    'f' => '0',
    'cont' => 'A',
    'call_code' => '',
  ],
  105 => [
    'c' => 'IR',
    'n' => 'Iran',
    'f' => '0',
    'cont' => 'A',
    'call_code' => '',
  ],
  106 => [
    'c' => 'IS',
    'n' => 'Iceland',
    'f' => '0',
    'cont' => 'E',
    'call_code' => '',
  ],
  107 => [
    'c' => 'IT',
    'n' => 'Italy',
    'f' => '0',
    'cont' => 'E',
    'call_code' => '',
  ],
  108 => [
    'c' => 'JE',
    'n' => 'Jersey',
    'f' => '0',
    'cont' => 'E',
    'call_code' => '',
  ],
  109 => [
    'c' => 'JM',
    'n' => 'Jamaica',
    'f' => '0',
    'cont' => 'N',
    'call_code' => '',
  ],
  110 => [
    'c' => 'JO',
    'n' => 'Jordan',
    'f' => '0',
    'cont' => 'A',
    'call_code' => '',
  ],
  111 => [
    'c' => 'JP',
    'n' => 'Japan',
    'f' => '0',
    'cont' => 'A',
    'call_code' => '',
  ],
  112 => [
    'c' => 'KE',
    'n' => 'Kenya',
    'f' => '0',
    'cont' => 'F',
    'call_code' => '',
  ],
  113 => [
    'c' => 'KG',
    'n' => 'Kyrgyzstan',
    'f' => '0',
    'cont' => 'A',
    'call_code' => '',
  ],
  114 => [
    'c' => 'KH',
    'n' => 'Cambodia',
    'f' => '0',
    'cont' => 'A',
    'call_code' => '',
  ],
  115 => [
    'c' => 'KI',
    'n' => 'Kiribati',
    'f' => '0',
    'cont' => 'U',
    'call_code' => '',
  ],
  116 => [
    'c' => 'KM',
    'n' => 'Comoros',
    'f' => '0',
    'cont' => 'F',
    'call_code' => '',
  ],
  117 => [
    'c' => 'KN',
    'n' => 'Saint Kitts and Nevis',
    'f' => '0',
    'cont' => 'N',
    'call_code' => '',
  ],
  118 => [
    'c' => 'KP',
    'n' => 'North Korea',
    'f' => '0',
    'cont' => 'A',
    'call_code' => '',
  ],
  119 => [
    'c' => 'KR',
    'n' => 'South Korea',
    'f' => '0',
    'cont' => 'A',
    'call_code' => '',
  ],
  120 => [
    'c' => 'KW',
    'n' => 'Kuwait',
    'f' => '0',
    'cont' => 'A',
    'call_code' => '',
  ],
  121 => [
    'c' => 'KY',
    'n' => 'Cayman Islands',
    'f' => '0',
    'cont' => 'N',
    'call_code' => '',
  ],
  122 => [
    'c' => 'KZ',
    'n' => 'Kazakhstan',
    'f' => '0',
    'cont' => 'A',
    'call_code' => '',
  ],
  123 => [
    'c' => 'LA',
    'n' => 'Laos',
    'f' => '0',
    'cont' => 'A',
    'call_code' => '',
  ],
  124 => [
    'c' => 'LB',
    'n' => 'Lebanon',
    'f' => '0',
    'cont' => 'A',
    'call_code' => '',
  ],
  125 => [
    'c' => 'LC',
    'n' => 'Saint Lucia',
    'f' => '0',
    'cont' => 'N',
    'call_code' => '',
  ],
  126 => [
    'c' => 'LI',
    'n' => 'Liechtenstein',
    'f' => '0',
    'cont' => 'E',
    'call_code' => '',
  ],
  127 => [
    'c' => 'LK',
    'n' => 'Sri Lanka',
    'f' => '0',
    'cont' => 'A',
    'call_code' => '',
  ],
  128 => [
    'c' => 'LR',
    'n' => 'Liberia',
    'f' => '0',
    'cont' => 'F',
    'call_code' => '',
  ],
  129 => [
    'c' => 'LS',
    'n' => 'Lesotho',
    'f' => '0',
    'cont' => 'F',
    'call_code' => '',
  ],
  130 => [
    'c' => 'LT',
    'n' => 'Lithuania',
    'f' => '0',
    'cont' => 'E',
    'call_code' => '',
  ],
  131 => [
    'c' => 'LU',
    'n' => 'Luxembourg',
    'f' => '0',
    'cont' => 'E',
    'call_code' => '',
  ],
  132 => [
    'c' => 'LV',
    'n' => 'Latvia',
    'f' => '0',
    'cont' => 'E',
    'call_code' => '',
  ],
  133 => [
    'c' => 'LY',
    'n' => 'Libya',
    'f' => '0',
    'cont' => 'F',
    'call_code' => '',
  ],
  134 => [
    'c' => 'MA',
    'n' => 'Morocco',
    'f' => '0',
    'cont' => 'F',
    'call_code' => '',
  ],
  135 => [
    'c' => 'MC',
    'n' => 'Monaco',
    'f' => '0',
    'cont' => 'E',
    'call_code' => '',
  ],
  136 => [
    'c' => 'MD',
    'n' => 'Moldova',
    'f' => '0',
    'cont' => 'E',
    'call_code' => '',
  ],
  137 => [
    'c' => 'ME',
    'n' => 'Montenegro',
    'f' => '0',
    'cont' => 'E',
    'call_code' => '',
  ],
  138 => [
    'c' => 'MG',
    'n' => 'Madagascar',
    'f' => '0',
    'cont' => 'F',
    'call_code' => '',
  ],
  139 => [
    'c' => 'MH',
    'n' => 'Marshall Islands',
    'f' => '0',
    'cont' => 'U',
    'call_code' => '',
  ],
  140 => [
    'c' => 'MK',
    'n' => 'Macedonia',
    'f' => '0',
    'cont' => 'E',
    'call_code' => '',
  ],
  141 => [
    'c' => 'ML',
    'n' => 'Mali',
    'f' => '0',
    'cont' => 'F',
    'call_code' => '',
  ],
  142 => [
    'c' => 'MM',
    'n' => 'Myanmar',
    'f' => '0',
    'cont' => 'A',
    'call_code' => '',
  ],
  143 => [
    'c' => 'MN',
    'n' => 'Mongolia',
    'f' => '0',
    'cont' => 'A',
    'call_code' => '',
  ],
  144 => [
    'c' => 'MO',
    'n' => 'Macao',
    'f' => '0',
    'cont' => 'A',
    'call_code' => '',
  ],
  145 => [
    'c' => 'MP',
    'n' => 'Northern Mariana Islands',
    'f' => '0',
    'cont' => 'U',
    'call_code' => '',
  ],
  146 => [
    'c' => 'MQ',
    'n' => 'Martinique',
    'f' => '0',
    'cont' => 'N',
    'call_code' => '',
  ],
  147 => [
    'c' => 'MR',
    'n' => 'Mauritania',
    'f' => '0',
    'cont' => 'F',
    'call_code' => '',
  ],
  148 => [
    'c' => 'MS',
    'n' => 'Montserrat',
    'f' => '0',
    'cont' => 'N',
    'call_code' => '',
  ],
  149 => [
    'c' => 'MT',
    'n' => 'Malta',
    'f' => '0',
    'cont' => 'E',
    'call_code' => '',
  ],
  150 => [
    'c' => 'MU',
    'n' => 'Mauritius',
    'f' => '0',
    'cont' => 'F',
    'call_code' => '',
  ],
  151 => [
    'c' => 'MV',
    'n' => 'Maldives',
    'f' => '0',
    'cont' => 'A',
    'call_code' => '',
  ],
  152 => [
    'c' => 'MW',
    'n' => 'Malawi',
    'f' => '0',
    'cont' => 'F',
    'call_code' => '',
  ],
  153 => [
    'c' => 'MX',
    'n' => 'Mexico',
    'f' => '0',
    'cont' => 'N',
    'call_code' => '',
  ],
  154 => [
    'c' => 'MY',
    'n' => 'Malaysia',
    'f' => '0',
    'cont' => 'A',
    'call_code' => '',
  ],
  155 => [
    'c' => 'MZ',
    'n' => 'Mozambique',
    'f' => '0',
    'cont' => 'F',
    'call_code' => '',
  ],
  156 => [
    'c' => 'NA',
    'n' => 'Namibia',
    'f' => '0',
    'cont' => 'F',
    'call_code' => '',
  ],
  157 => [
    'c' => 'NC',
    'n' => 'New Caledonia',
    'f' => '0',
    'cont' => 'U',
    'call_code' => '',
  ],
  158 => [
    'c' => 'NE',
    'n' => 'Niger',
    'f' => '0',
    'cont' => 'F',
    'call_code' => '',
  ],
  159 => [
    'c' => 'NF',
    'n' => 'Norfolk Island',
    'f' => '0',
    'cont' => 'U',
    'call_code' => '',
  ],
  160 => [
    'c' => 'NG',
    'n' => 'Nigeria',
    'f' => '0',
    'cont' => 'F',
    'call_code' => '',
  ],
  161 => [
    'c' => 'NI',
    'n' => 'Nicaragua',
    'f' => '0',
    'cont' => 'N',
    'call_code' => '',
  ],
  162 => [
    'c' => 'NL',
    'n' => 'Netherlands',
    'f' => '0',
    'cont' => 'E',
    'call_code' => '',
  ],
  163 => [
    'c' => 'NO',
    'n' => 'Norway',
    'f' => '0',
    'cont' => 'E',
    'call_code' => '',
  ],
  164 => [
    'c' => 'NP',
    'n' => 'Nepal',
    'f' => '0',
    'cont' => 'A',
    'call_code' => '',
  ],
  165 => [
    'c' => 'NR',
    'n' => 'Nauru',
    'f' => '0',
    'cont' => 'U',
    'call_code' => '',
  ],
  166 => [
    'c' => 'NU',
    'n' => 'Niue',
    'f' => '0',
    'cont' => 'U',
    'call_code' => '',
  ],
  167 => [
    'c' => 'NZ',
    'n' => 'New Zealand',
    'f' => '0',
    'cont' => 'U',
    'call_code' => '',
  ],
  168 => [
    'c' => 'OM',
    'n' => 'Oman',
    'f' => '0',
    'cont' => 'A',
    'call_code' => '',
  ],
  169 => [
    'c' => 'PA',
    'n' => 'Panama',
    'f' => '0',
    'cont' => 'N',
    'call_code' => '',
  ],
  170 => [
    'c' => 'PE',
    'n' => 'Peru',
    'f' => '0',
    'cont' => 'S',
    'call_code' => '',
  ],
  171 => [
    'c' => 'PF',
    'n' => 'French Polynesia',
    'f' => '0',
    'cont' => 'U',
    'call_code' => '',
  ],
  172 => [
    'c' => 'PG',
    'n' => 'Papua New Guinea',
    'f' => '0',
    'cont' => 'U',
    'call_code' => '',
  ],
  173 => [
    'c' => 'PH',
    'n' => 'Philippines',
    'f' => '0',
    'cont' => 'A',
    'call_code' => '',
  ],
  174 => [
    'c' => 'PK',
    'n' => 'Pakistan',
    'f' => '0',
    'cont' => 'A',
    'call_code' => '',
  ],
  175 => [
    'c' => 'PL',
    'n' => 'Poland',
    'f' => '0',
    'cont' => 'E',
    'call_code' => '',
  ],
  176 => [
    'c' => 'PM',
    'n' => 'Saint Pierre and Miquelon',
    'f' => '0',
    'cont' => 'N',
    'call_code' => '',
  ],
  177 => [
    'c' => 'PN',
    'n' => 'Pitcairn',
    'f' => '0',
    'cont' => 'U',
    'call_code' => '',
  ],
  178 => [
    'c' => 'PR',
    'n' => 'Puerto Rico',
    'f' => '0',
    'cont' => 'N',
    'call_code' => '',
  ],
  179 => [
    'c' => 'PS',
    'n' => 'Palestinian territories',
    'f' => '0',
    'cont' => 'A',
    'call_code' => '',
  ],
  180 => [
    'c' => 'PT',
    'n' => 'Portugal',
    'f' => '0',
    'cont' => 'E',
    'call_code' => '',
  ],
  181 => [
    'c' => 'PW',
    'n' => 'Palau',
    'f' => '0',
    'cont' => 'U',
    'call_code' => '',
  ],
  182 => [
    'c' => 'PY',
    'n' => 'Paraguay',
    'f' => '0',
    'cont' => 'S',
    'call_code' => '',
  ],
  183 => [
    'c' => 'QA',
    'n' => 'Qatar',
    'f' => '0',
    'cont' => 'A',
    'call_code' => '',
  ],
  184 => [
    'c' => 'RE',
    'n' => 'Reunion',
    'f' => '0',
    'cont' => 'F',
    'call_code' => '',
  ],
  185 => [
    'c' => 'RO',
    'n' => 'Romania',
    'f' => '0',
    'cont' => 'E',
    'call_code' => '',
  ],
  186 => [
    'c' => 'RS',
    'n' => 'Serbia',
    'f' => '0',
    'cont' => 'E',
    'call_code' => '',
  ],
  187 => [
    'c' => 'RU',
    'n' => 'Russian Federation',
    'f' => '0',
    'cont' => 'E',
    'call_code' => '',
  ],
  188 => [
    'c' => 'RW',
    'n' => 'Rwanda',
    'f' => '0',
    'cont' => 'F',
    'call_code' => '',
  ],
  189 => [
    'c' => 'SA',
    'n' => 'Saudi Arabia',
    'f' => '0',
    'cont' => 'A',
    'call_code' => '',
  ],
  190 => [
    'c' => 'SB',
    'n' => 'Solomon Islands',
    'f' => '0',
    'cont' => 'U',
    'call_code' => '',
  ],
  191 => [
    'c' => 'SC',
    'n' => 'Seychelles',
    'f' => '0',
    'cont' => 'F',
    'call_code' => '',
  ],
  192 => [
    'c' => 'SD',
    'n' => 'Sudan',
    'f' => '0',
    'cont' => 'F',
    'call_code' => '',
  ],
  193 => [
    'c' => 'SE',
    'n' => 'Sweden',
    'f' => '0',
    'cont' => 'E',
    'call_code' => '',
  ],
  194 => [
    'c' => 'SG',
    'n' => 'Singapore',
    'f' => '0',
    'cont' => 'A',
    'call_code' => '',
  ],
  195 => [
    'c' => 'SH',
    'n' => 'Saint Helena',
    'f' => '0',
    'cont' => 'F',
    'call_code' => '',
  ],
  196 => [
    'c' => 'SI',
    'n' => 'Slovenia',
    'f' => '0',
    'cont' => 'E',
    'call_code' => '',
  ],
  197 => [
    'c' => 'SJ',
    'n' => 'Svalbard and Jan Mayen',
    'f' => '0',
    'cont' => 'E',
    'call_code' => '',
  ],
  198 => [
    'c' => 'SK',
    'n' => 'Slovakia',
    'f' => '0',
    'cont' => 'E',
    'call_code' => '',
  ],
  199 => [
    'c' => 'SL',
    'n' => 'Sierra Leone',
    'f' => '0',
    'cont' => 'F',
    'call_code' => '',
  ],
  200 => [
    'c' => 'SM',
    'n' => 'San Marino',
    'f' => '0',
    'cont' => 'E',
    'call_code' => '',
  ],
  201 => [
    'c' => 'SN',
    'n' => 'Senegal',
    'f' => '0',
    'cont' => 'F',
    'call_code' => '',
  ],
  202 => [
    'c' => 'SO',
    'n' => 'Somalia',
    'f' => '0',
    'cont' => 'F',
    'call_code' => '',
  ],
  203 => [
    'c' => 'SR',
    'n' => 'Suriname',
    'f' => '0',
    'cont' => 'S',
    'call_code' => '',
  ],
  204 => [
    'c' => 'ST',
    'n' => 'Sao Tome and Principe',
    'f' => '0',
    'cont' => 'F',
    'call_code' => '',
  ],
  205 => [
    'c' => 'SV',
    'n' => 'El Salvador',
    'f' => '0',
    'cont' => 'N',
    'call_code' => '',
  ],
  206 => [
    'c' => 'SY',
    'n' => 'Syria',
    'f' => '0',
    'cont' => 'A',
    'call_code' => '',
  ],
  207 => [
    'c' => 'SZ',
    'n' => 'Swaziland',
    'f' => '0',
    'cont' => 'F',
    'call_code' => '',
  ],
  208 => [
    'c' => 'TC',
    'n' => 'Turks and Caicos Islands',
    'f' => '0',
    'cont' => 'N',
    'call_code' => '',
  ],
  209 => [
    'c' => 'TD',
    'n' => 'Chad',
    'f' => '0',
    'cont' => 'F',
    'call_code' => '',
  ],
  210 => [
    'c' => 'TF',
    'n' => 'French Southern Territories',
    'f' => '0',
    'cont' => 'Q',
    'call_code' => '',
  ],
  211 => [
    'c' => 'TG',
    'n' => 'Togo',
    'f' => '0',
    'cont' => 'F',
    'call_code' => '',
  ],
  212 => [
    'c' => 'TH',
    'n' => 'Thailand',
    'f' => '0',
    'cont' => 'A',
    'call_code' => '',
  ],
  213 => [
    'c' => 'TJ',
    'n' => 'Tajikistan',
    'f' => '0',
    'cont' => 'A',
    'call_code' => '',
  ],
  214 => [
    'c' => 'TK',
    'n' => 'Tokelau',
    'f' => '0',
    'cont' => 'U',
    'call_code' => '',
  ],
  215 => [
    'c' => 'TL',
    'n' => 'Timor-Leste',
    'f' => '0',
    'cont' => 'A',
    'call_code' => '',
  ],
  216 => [
    'c' => 'TM',
    'n' => 'Turkmenistan',
    'f' => '0',
    'cont' => 'A',
    'call_code' => '',
  ],
  217 => [
    'c' => 'TN',
    'n' => 'Tunisia',
    'f' => '0',
    'cont' => 'F',
    'call_code' => '',
  ],
  218 => [
    'c' => 'TO',
    'n' => 'Tonga',
    'f' => '0',
    'cont' => 'U',
    'call_code' => '',
  ],
  219 => [
    'c' => 'TR',
    'n' => 'Turkey',
    'f' => '0',
    'cont' => 'A',
    'call_code' => '',
  ],
  220 => [
    'c' => 'TT',
    'n' => 'Trinidad and Tobago',
    'f' => '0',
    'cont' => 'N',
    'call_code' => '',
  ],
  221 => [
    'c' => 'TV',
    'n' => 'Tuvalu',
    'f' => '0',
    'cont' => 'U',
    'call_code' => '',
  ],
  222 => [
    'c' => 'TW',
    'n' => 'Taiwan',
    'f' => '0',
    'cont' => 'A',
    'call_code' => '',
  ],
  223 => [
    'c' => 'TZ',
    'n' => 'Tanzania',
    'f' => '0',
    'cont' => 'F',
    'call_code' => '',
  ],
  224 => [
    'c' => 'UA',
    'n' => 'Ukraine',
    'f' => '0',
    'cont' => 'E',
    'call_code' => '',
  ],
  225 => [
    'c' => 'UG',
    'n' => 'Uganda',
    'f' => '0',
    'cont' => 'F',
    'call_code' => '',
  ],
  226 => [
    'c' => 'UM',
    'n' => 'United States Minor Outlying Islands',
    'f' => '0',
    'cont' => 'U',
    'call_code' => '',
  ],
  227 => [
    'c' => 'US',
    'n' => 'United States',
    'f' => '1',
    'cont' => 'N',
    'call_code' => '',
  ],
  228 => [
    'c' => 'UY',
    'n' => 'Uruguay',
    'f' => '0',
    'cont' => 'S',
    'call_code' => '',
  ],
  229 => [
    'c' => 'UZ',
    'n' => 'Uzbekistan',
    'f' => '0',
    'cont' => 'A',
    'call_code' => '',
  ],
  230 => [
    'c' => 'VA',
    'n' => 'Vatican City',
    'f' => '0',
    'cont' => 'E',
    'call_code' => '',
  ],
  231 => [
    'c' => 'VC',
    'n' => 'Saint Vincent and the Grenadines',
    'f' => '0',
    'cont' => 'N',
    'call_code' => '',
  ],
  232 => [
    'c' => 'VE',
    'n' => 'Venezuela',
    'f' => '0',
    'cont' => 'S',
    'call_code' => '',
  ],
  233 => [
    'c' => 'VG',
    'n' => 'British Virgin Islands',
    'f' => '0',
    'cont' => 'N',
    'call_code' => '',
  ],
  234 => [
    'c' => 'VI',
    'n' => 'United States Virgin Islands',
    'f' => '0',
    'cont' => 'N',
    'call_code' => '',
  ],
  235 => [
    'c' => 'VN',
    'n' => 'Viet Nam',
    'f' => '0',
    'cont' => 'A',
    'call_code' => '',
  ],
  236 => [
    'c' => 'VU',
    'n' => 'Vanuatu',
    'f' => '0',
    'cont' => 'U',
    'call_code' => '',
  ],
  237 => [
    'c' => 'WF',
    'n' => 'Wallis and Futuna',
    'f' => '0',
    'cont' => 'U',
    'call_code' => '',
  ],
  238 => [
    'c' => 'WS',
    'n' => 'Samoa',
    'f' => '0',
    'cont' => 'U',
    'call_code' => '',
  ],
  239 => [
    'c' => 'YE',
    'n' => 'Yemen',
    'f' => '0',
    'cont' => 'A',
    'call_code' => '',
  ],
  240 => [
    'c' => 'YT',
    'n' => 'Mayotte',
    'f' => '0',
    'cont' => 'F',
    'call_code' => '',
  ],
  241 => [
    'c' => 'ZA',
    'n' => 'South Africa',
    'f' => '0',
    'cont' => 'F',
    'call_code' => '',
  ],
  242 => [
    'c' => 'ZM',
    'n' => 'Zambia',
    'f' => '0',
    'cont' => 'F',
    'call_code' => '',
  ],
  243 => [
    'c' => 'ZW',
    'n' => 'Zimbabwe',
    'f' => '0',
    'cont' => 'F',
    'call_code' => '',
  ],
];
