<?php

return [
  1 => [
    'id' => '1',
    'status' => 'a',
    'name' => '',
    'pswd' => '',
    'user_lastvisit' => '0',
    'user_regdate' => '1207920949',
    'group' => '1',
    'user_posts' => '0',
    'user_timezone' => '0',
    'user_dateformat' => 'd M Y H:i',
    'user_rank' => null,
    'user_avatar' => null,
    'user_email' => null,
    'user_icq' => null,
    'user_website' => null,
    'user_from' => null,
    'user_sig' => null,
    'user_aim' => null,
    'user_yim' => null,
    'user_msnm' => null,
    'user_occ' => null,
    'user_interests' => null,
    'user_birth' => '0000-00-00',
    'view_sig' => '1',
    'view_images' => '1',
    'view_avatars' => '1',
    'posts_per_page' => '0',
    'topics_per_page' => '0',
    'dst_status' => '0',
    'language' => '0',
  ],
];
