<?php

return [
  1 => [
    'id' => '1',
    'cat_id' => '0',
    'name' => 'about',
    'text' => 'Page about us',
    'page_title' => '',
    'page_heading' => '',
    'meta_keywords' => '',
    'meta_desc' => '',
    'locale' => '0',
    'active' => '1',
  ],
  2 => [
    'id' => '2',
    'cat_id' => '0',
    'name' => 'faq',
    'text' => 'FAQ page',
    'page_title' => '',
    'page_heading' => '',
    'meta_keywords' => '',
    'meta_desc' => '',
    'locale' => '0',
    'active' => '1',
  ],
  3 => [
    'id' => '3',
    'cat_id' => '0',
    'name' => 'terms',
    'text' => 'Terms page',
    'page_title' => '',
    'page_heading' => '',
    'meta_keywords' => '',
    'meta_desc' => '',
    'locale' => '0',
    'active' => '1',
  ],
  4 => [
    'id' => '4',
    'cat_id' => '0',
    'name' => 'privacy',
    'text' => 'Privacy page',
    'page_title' => '',
    'page_heading' => '',
    'meta_keywords' => '',
    'meta_desc' => '',
    'locale' => '0',
    'active' => '1',
  ],
];
