<?php

return [
  2 => [
    'id' => '2',
    'name' => 'admin',
    'description' => '',
    'version' => '',
    'author' => '',
    'active' => '1',
  ],
  3 => [
    'id' => '3',
    'name' => 'admin_groups',
    'description' => '',
    'version' => '',
    'author' => '',
    'active' => '1',
  ],
  4 => [
    'id' => '4',
    'name' => 'admin_home',
    'description' => '',
    'version' => '',
    'author' => '',
    'active' => '1',
  ],
  5 => [
    'id' => '5',
    'name' => 'admin_messages',
    'description' => '',
    'version' => '',
    'author' => '',
    'active' => '1',
  ],
  6 => [
    'id' => '6',
    'name' => 'admin_modules',
    'description' => '',
    'version' => '',
    'author' => '',
    'active' => '1',
  ],
  7 => [
    'id' => '7',
    'name' => 'backup_manager',
    'description' => '',
    'version' => '',
    'author' => '',
    'active' => '1',
  ],
  8 => [
    'id' => '8',
    'name' => 'blocks',
    'description' => '',
    'version' => '',
    'author' => '',
    'active' => '1',
  ],
  9 => [
    'id' => '9',
    'name' => 'category_editor',
    'description' => '',
    'version' => '',
    'author' => '',
    'active' => '1',
  ],
  10 => [
    'id' => '10',
    'name' => 'check_multi_accounts',
    'description' => '',
    'version' => '',
    'author' => '',
    'active' => '1',
  ],
  11 => [
    'id' => '11',
    'name' => 'conf_editor',
    'description' => '',
    'version' => '',
    'author' => '',
    'active' => '1',
  ],
  13 => [
    'id' => '13',
    'name' => 'custom_bbcode_editor',
    'description' => '',
    'version' => '',
    'author' => '',
    'active' => '1',
  ],
  14 => [
    'id' => '14',
    'name' => 'custom_replace',
    'description' => '',
    'version' => '',
    'author' => '',
    'active' => '1',
  ],
  15 => [
    'id' => '15',
    'name' => 'db_manager',
    'description' => '',
    'version' => '',
    'author' => '',
    'active' => '1',
  ],
  19 => [
    'id' => '19',
    'name' => 'file_manager',
    'description' => '',
    'version' => '',
    'author' => '',
    'active' => '1',
  ],
  23 => [
    'id' => '23',
    'name' => 'locale_editor',
    'description' => '',
    'version' => '',
    'author' => '',
    'active' => '1',
  ],
  26 => [
    'id' => '26',
    'name' => 'log_core_errors_viewer',
    'description' => '',
    'version' => '',
    'author' => '',
    'active' => '0',
  ],
  28 => [
    'id' => '28',
    'name' => 'log_exec_analyser',
    'description' => '',
    'version' => '',
    'author' => '',
    'active' => '0',
  ],
  30 => [
    'id' => '30',
    'name' => 'log_user_errors_viewer',
    'description' => '',
    'version' => '',
    'author' => '',
    'active' => '0',
  ],
  38 => [
    'id' => '38',
    'name' => 'members',
    'description' => '',
    'version' => '',
    'author' => '',
    'active' => '1',
  ],
  39 => [
    'id' => '39',
    'name' => 'menus_editor',
    'description' => '',
    'version' => '',
    'author' => '',
    'active' => '1',
  ],
  40 => [
    'id' => '40',
    'name' => 'online_users_manager',
    'description' => '',
    'version' => '',
    'author' => '',
    'active' => '1',
  ],
  44 => [
    'id' => '44',
    'name' => 'revisions_manager',
    'description' => '',
    'version' => '',
    'author' => '',
    'active' => '1',
  ],
  46 => [
    'id' => '46',
    'name' => 'settings',
    'description' => '',
    'version' => '',
    'author' => '',
    'active' => '1',
  ],
  48 => [
    'id' => '48',
    'name' => 'site_nav_bar',
    'description' => '',
    'version' => '',
    'author' => '',
    'active' => '1',
  ],
  49 => [
    'id' => '49',
    'name' => 'static_pages',
    'description' => '',
    'version' => '',
    'author' => '',
    'active' => '1',
  ],
  51 => [
    'id' => '51',
    'name' => 'template_editor',
    'description' => '',
    'version' => '',
    'author' => '',
    'active' => '1',
  ],
  52 => [
    'id' => '52',
    'name' => 'user_dynamic_info',
    'description' => '',
    'version' => '',
    'author' => '',
    'active' => '1',
  ],
  53 => [
    'id' => '53',
    'name' => 'user_groups',
    'description' => '',
    'version' => '',
    'author' => '',
    'active' => '1',
  ],
  55 => [
    'id' => '55',
    'name' => 'user_modules',
    'description' => '',
    'version' => '',
    'author' => '',
    'active' => '1',
  ],
  58 => [
    'id' => '58',
    'name' => 'analyze_admin_exec_log',
    'description' => '',
    'version' => '',
    'author' => '',
    'active' => '0',
  ],
  59 => [
    'id' => '59',
    'name' => 'analyze_engine_log',
    'description' => '',
    'version' => '',
    'author' => '',
    'active' => '0',
  ],
  60 => [
    'id' => '60',
    'name' => 'analyze_error_log',
    'description' => '',
    'version' => '',
    'author' => '',
    'active' => '0',
  ],
  61 => [
    'id' => '61',
    'name' => 'ban_editor',
    'description' => '',
    'version' => '',
    'author' => '',
    'active' => '0',
  ],
  65 => [
    'id' => '65',
    'name' => 'log_admin_exec',
    'description' => '',
    'version' => '',
    'author' => '',
    'active' => '0',
  ],
  67 => [
    'id' => '67',
    'name' => 'log_ssh_viewer',
    'description' => '',
    'version' => '',
    'author' => '',
    'active' => '0',
  ],
  68 => [
    'id' => '68',
    'name' => 'log_webshell_actions_viewer',
    'description' => '',
    'version' => '',
    'author' => '',
    'active' => '0',
  ],
  69 => [
    'id' => '69',
    'name' => 'manage_auto_ban',
    'description' => '',
    'version' => '',
    'author' => '',
    'active' => '0',
  ],
  70 => [
    'id' => '70',
    'name' => 'manage_dynamic_attributes',
    'description' => '',
    'version' => '',
    'author' => '',
    'active' => '0',
  ],
  72 => [
    'id' => '72',
    'name' => 'manage_shop',
    'description' => '',
    'version' => '',
    'author' => '',
    'active' => '1',
  ],
  73 => [
    'id' => '73',
    'name' => 'manage_sphinx',
    'description' => '',
    'version' => '',
    'author' => '',
    'active' => '0',
  ],
  76 => [
    'id' => '76',
    'name' => 'manage_conf',
    'description' => '',
    'version' => '',
    'author' => '',
    'active' => '1',
  ],
  77 => [
    'id' => '77',
    'name' => 'manage_servers',
    'description' => '',
    'version' => '',
    'author' => '',
    'active' => '0',
  ],
  78 => [
    'id' => '78',
    'name' => 'manage_sites',
    'description' => '',
    'version' => '',
    'author' => '',
    'active' => '0',
  ],
  79 => [
    'id' => '79',
    'name' => 'manage_advertising',
    'description' => '',
    'version' => '',
    'author' => '',
    'active' => '0',
  ],
  80 => [
    'id' => '80',
    'name' => 'manage_dashboards',
    'description' => '',
    'version' => '',
    'author' => '',
    'active' => '1',
  ],
  81 => [
    'id' => '81',
    'name' => 'manage_tips',
    'description' => '',
    'version' => '',
    'author' => '',
    'active' => '1',
  ],
  82 => [
    'id' => '82',
    'name' => 'admin_wall',
    'description' => '',
    'version' => '',
    'author' => '',
    'active' => '1',
  ],
  83 => [
    'id' => '83',
    'name' => 'manage_widgets',
    'description' => '',
    'version' => '',
    'author' => '',
    'active' => '0',
  ],
  84 => [
    'id' => '84',
    'name' => 'shop_supplier_panel',
    'description' => '',
    'version' => '',
    'author' => '',
    'active' => '1',
  ],
  85 => [
    'id' => '85',
    'name' => 'admin_account',
    'description' => '',
    'version' => '',
    'author' => '',
    'active' => '1',
  ],
  86 => [
    'id' => '86',
    'name' => 'manage_users',
    'description' => '',
    'version' => '',
    'author' => '',
    'active' => '0',
  ],
  87 => [
    'id' => '87',
    'name' => 'manage_countries',
    'description' => '',
    'version' => '',
    'author' => '',
    'active' => '0',
  ],
  88 => [
    'id' => '88',
    'name' => 'manage_currencies',
    'description' => '',
    'version' => '',
    'author' => '',
    'active' => '0',
  ],
  89 => [
    'id' => '89',
    'name' => 'manage_icons',
    'description' => '',
    'version' => '',
    'author' => '',
    'active' => '0',
  ],
  90 => [
    'id' => '90',
    'name' => 'manage_languages',
    'description' => '',
    'version' => '',
    'author' => '',
    'active' => '0',
  ],
  91 => [
    'id' => '91',
    'name' => 'manage_regions',
    'description' => '',
    'version' => '',
    'author' => '',
    'active' => '0',
  ],
  92 => [
    'id' => '92',
    'name' => 'manage_timezones',
    'description' => '',
    'version' => '',
    'author' => '',
    'active' => '0',
  ],
  93 => [
    'id' => '93',
    'name' => 'shop_contentm_panel',
    'description' => '',
    'version' => '',
    'author' => '',
    'active' => '1',
  ],
  94 => [
    'id' => '94',
    'name' => 'manage_cities',
    'description' => '',
    'version' => '',
    'author' => '',
    'active' => '0',
  ],
  95 => [
    'id' => '95',
    'name' => 'activity_viewer',
    'description' => '',
    'version' => '',
    'author' => '',
    'active' => '0',
  ],
  96 => [
    'id' => '96',
    'name' => 'dev',
    'description' => '',
    'version' => '',
    'author' => '',
    'active' => '0',
  ],
  97 => [
    'id' => '97',
    'name' => 'help_tickets',
    'description' => '',
    'version' => '',
    'author' => '',
    'active' => '0',
  ],
  98 => [
    'id' => '98',
    'name' => 'manage_articles',
    'description' => '',
    'version' => '',
    'author' => '',
    'active' => '0',
  ],
  99 => [
    'id' => '99',
    'name' => 'manage_blogs',
    'description' => '',
    'version' => '',
    'author' => '',
    'active' => '0',
  ],
  100 => [
    'id' => '100',
    'name' => 'manage_comments',
    'description' => '',
    'version' => '',
    'author' => '',
    'active' => '1',
  ],
  101 => [
    'id' => '101',
    'name' => 'manage_faq',
    'description' => '',
    'version' => '',
    'author' => '',
    'active' => '0',
  ],
  102 => [
    'id' => '102',
    'name' => 'manage_forum',
    'description' => '',
    'version' => '',
    'author' => '',
    'active' => '0',
  ],
  103 => [
    'id' => '103',
    'name' => 'manage_news',
    'description' => '',
    'version' => '',
    'author' => '',
    'active' => '1',
  ],
  104 => [
    'id' => '104',
    'name' => 'manage_reput',
    'description' => '',
    'version' => '',
    'author' => '',
    'active' => '0',
  ],
  105 => [
    'id' => '105',
    'name' => 'polls_manager',
    'description' => '',
    'version' => '',
    'author' => '',
    'active' => '0',
  ],
  106 => [
    'id' => '106',
    'name' => 'se_keywords_manager',
    'description' => '',
    'version' => '',
    'author' => '',
    'active' => '0',
  ],
  107 => [
    'id' => '107',
    'name' => 'merge_products',
    'description' => '',
    'version' => '',
    'author' => '',
    'active' => '1',
  ],
  108 => [
    'id' => '108',
    'name' => 'parse_ambar_site',
    'description' => '',
    'version' => '',
    'author' => '',
    'active' => '1',
  ],
  109 => [
    'id' => '109',
    'name' => 'parse_eda_lg_site',
    'description' => '',
    'version' => '',
    'author' => '',
    'active' => '1',
  ],
  110 => [
    'id' => '110',
    'name' => 'parse_vseprodam_site',
    'description' => '',
    'version' => '',
    'author' => '',
    'active' => '1',
  ],
  111 => [
    'id' => '111',
    'name' => 'parse_zakaz_site',
    'description' => '',
    'version' => '',
    'author' => '',
    'active' => '1',
  ],
  112 => [
    'id' => '112',
    'name' => 'invoice',
    'description' => '',
    'version' => '',
    'author' => '',
    'active' => '1',
  ],
  113 => [
    'id' => '113',
    'name' => 'log_admin_auth',
    'description' => '',
    'version' => '',
    'author' => '',
    'active' => '0',
  ],
  114 => [
    'id' => '114',
    'name' => 'log_admin_auth_fails',
    'description' => '',
    'version' => '',
    'author' => '',
    'active' => '0',
  ],
  115 => [
    'id' => '115',
    'name' => 'log_user_auth',
    'description' => '',
    'version' => '',
    'author' => '',
    'active' => '0',
  ],
  116 => [
    'id' => '116',
    'name' => 'log_user_auth_fails',
    'description' => '',
    'version' => '',
    'author' => '',
    'active' => '0',
  ],
  117 => [
    'id' => '117',
    'name' => 'manage_shop_promo',
    'description' => '',
    'version' => '',
    'author' => '',
    'active' => '1',
  ],
];
