DROP TABLE IF EXISTS `sexy_log_maxmind_phone_verify`;
CREATE TABLE `sexy_log_maxmind_phone_verify` (
  `id` int(10) unsigned NOT NULL auto_increment,
  `owner_id` int(11) unsigned NOT NULL,
  `check_type` enum('i','v') NOT NULL,
  `phone_num` varchar(32) NOT NULL,
  `phone_type` tinyint(3) unsigned NOT NULL,
  `verify_code` varchar(4) NOT NULL,
  `ref_id` varchar(32) NOT NULL,
  `success` enum('0','1') NOT NULL,
  `date` int(10) unsigned NOT NULL,
  `process_time` int(10) unsigned NOT NULL,
  `error_text` text NOT NULL,
  `site_id` tinyint(3) unsigned NOT NULL,
  `user_id` int(10) unsigned NOT NULL,
  `user_group` tinyint(3) unsigned NOT NULL,
  `is_admin` enum('0','1') NOT NULL,
  `ip` varchar(32) NOT NULL,
  `query_string` text NOT NULL,
  `user_agent` varchar(255) NOT NULL,
  `referer` varchar(255) NOT NULL,
  `request_uri` varchar(255) NOT NULL,
  `object` varchar(255) NOT NULL,
  `action` varchar(255) NOT NULL,
  `server_answer` varchar(255) NOT NULL,
  PRIMARY KEY  (`id`)
);


DROP TABLE IF EXISTS `sexy_countries`;
CREATE TABLE `sexy_countries` (
  `c` char(2) NOT NULL default '',
  `n` varchar(64) NOT NULL default '',
  `f` enum('0','1') NOT NULL default '0',
  `cont` char(1) NOT NULL default '',
  `call_code` char(4) NOT NULL default '',
  PRIMARY KEY  (`c`)
) ENGINE=MyISAM DEFAULT CHARSET=latin1;

INSERT INTO `sexy_countries` (`c`, `n`, `f`, `cont`, `call_code`) 
VALUES 
('AD', 'Andorra', '0', 'E', '376'),
('AE', 'United Arab Emirates', '0', 'A', '971'),
('AF', 'Afghanistan', '0', 'A', '93'),
('AG', 'Antigua and Barbuda', '0', 'N', '1268'),
('AI', 'Anguilla', '0', 'N', '1264'),
('AL', 'Albania', '0', 'E', '355'),
('AM', 'Armenia', '0', 'A', '374'),
('AN', 'Netherlands Antilles', '0', 'N', '599'),
('AO', 'Angola', '0', 'F', '244'),
('AQ', 'Antarctica', '0', 'Q', ''),
('AR', 'Argentina', '0', 'S', '54'),
('AS', 'American Samoa', '0', 'U', '1684'),
('AT', 'Austria', '0', 'E', '43'),
('AU', 'Australia', '0', 'U', '61'),
('AW', 'Aruba', '0', 'N', '297'),
('AX', 'Aland Islands', '0', 'E', ''),
('AZ', 'Azerbaijan', '0', 'A', '994'),
('BA', 'Bosnia and Herzegovina', '0', 'E', '387'),
('BB', 'Barbados', '0', 'N', '1246'),
('BD', 'Bangladesh', '0', 'A', '880'),
('BE', 'Belgium', '0', 'E', '32'),
('BF', 'Burkina Faso', '0', 'F', '226'),
('BG', 'Bulgaria', '0', 'E', '359'),
('BH', 'Bahrain', '0', 'A', '973'),
('BI', 'Burundi', '0', 'F', '257'),
('BJ', 'Benin', '0', 'F', '229'),
('BM', 'Bermuda', '0', 'N', '1441'),
('BN', 'Brunei Darussalam', '0', 'A', '673'),
('BO', 'Bolivia', '0', 'S', '591'),
('BR', 'Brazil', '0', 'S', '55'),
('BS', 'Bahamas', '0', 'N', '1242'),
('BT', 'Bhutan', '0', 'A', '975'),
('BV', 'Bouvet Island', '0', 'Q', ''),
('BW', 'Botswana', '0', 'F', '267'),
('BY', 'Belarus', '0', 'E', '375'),
('BZ', 'Belize', '0', 'N', '501'),
('CA', 'Canada', '1', 'N', '1'),
('CC', 'Cocos (Keeling) Islands', '0', 'A', ''),
('CD', 'Congo, Democratic Republic of the', '0', 'F', '243'),
('CF', 'Central African Republic', '0', 'F', '236'),
('CG', 'Congo', '0', 'F', '242'),
('CH', 'Switzerland', '0', 'E', '41'),
('CI', 'Cote d''Ivoire', '0', 'F', '225'),
('CK', 'Cook Islands', '0', 'U', '682'),
('CL', 'Chile', '0', 'S', '56'),
('CM', 'Cameroon', '0', 'F', '237'),
('CN', 'China', '0', 'A', '86'),
('CO', 'Colombia', '0', 'S', '57'),
('CR', 'Costa Rica', '0', 'N', '506'),
('CU', 'Cuba', '0', 'N', '53'),
('CV', 'Cape Verde', '0', 'F', '238'),
('CX', 'Christmas Island', '0', 'A', ''),
('CY', 'Cyprus', '0', 'A', '357'),
('CZ', 'Czech Republic', '0', 'E', '420'),
('DE', 'Germany', '0', 'E', '49'),
('DJ', 'Djibouti', '0', 'F', '253'),
('DK', 'Denmark', '0', 'E', '45'),
('DM', 'Dominica', '0', 'N', '1767'),
('DO', 'Dominican Republic', '0', 'N', '1809'),
('DZ', 'Algeria', '0', 'F', '213'),
('EC', 'Ecuador', '0', 'S', '593'),
('EE', 'Estonia', '0', 'E', '372'),
('EG', 'Egypt', '0', 'F', '20'),
('EH', 'Western Sahara', '0', 'F', ''),
('ER', 'Eritrea', '0', 'F', '291'),
('ES', 'Spain', '0', 'E', '34'),
('ET', 'Ethiopia', '0', 'F', '251'),
('FI', 'Finland', '0', 'E', '358'),
('FJ', 'Fiji', '0', 'U', '679'),
('FK', 'Falkland Islands', '0', 'S', '500'),
('FM', 'Federated States of Micronesia', '0', 'U', '691'),
('FO', 'Faroe Islands', '0', 'E', '298'),
('FR', 'France', '0', 'N', '33'),
('GA', 'Gabon', '0', 'F', '241'),
('GB', 'United Kingdom', '1', 'E', '44'),
('GD', 'Grenada', '0', 'N', '1473'),
('GE', 'Georgia', '0', 'A', '995'),
('GF', 'French Guiana', '0', 'S', '594'),
('GG', 'Guernsey', '0', 'E', ''),
('GH', 'Ghana', '0', 'F', '233'),
('GI', 'Gibraltar', '0', 'E', '350'),
('GL', 'Greenland', '0', 'N', '299'),
('GM', 'Gambia', '0', 'F', '220'),
('GN', 'Guinea', '0', 'F', '224'),
('GP', 'Guadeloupe', '0', 'N', '590'),
('GQ', 'Equatorial Guinea', '0', 'F', '240'),
('GR', 'Greece', '0', 'E', '30'),
('GS', 'South Georgia and Sandwich Islands', '0', 'Q', ''),
('GT', 'Guatemala', '0', 'N', '502'),
('GU', 'Guam', '0', 'U', '1671'),
('GW', 'Guinea-Bissau', '0', 'F', '245'),
('GY', 'Guyana', '0', 'S', '592'),
('HK', 'Hong Kong', '0', 'A', '852'),
('HM', 'Heard Island and McDonald Islands', '0', 'Q', ''),
('HN', 'Honduras', '0', 'N', '504'),
('HR', 'Croatia', '0', 'E', '385'),
('HT', 'Haiti', '0', 'N', '509'),
('HU', 'Hungary', '0', 'E', '36'),
('ID', 'Indonesia', '0', 'A', '62'),
('IE', 'Ireland', '0', 'E', '353'),
('IL', 'Israel', '0', 'A', '972'),
('IM', 'Isle of Man', '0', 'E', ''),
('IN', 'India', '0', 'A', '91'),
('IO', 'British Indian Ocean Territory', '0', 'A', ''),
('IQ', 'Iraq', '0', 'A', '964'),
('IR', 'Iran', '0', 'A', '98'),
('IS', 'Iceland', '0', 'E', '354'),
('IT', 'Italy', '0', 'E', '39'),
('JE', 'Jersey', '0', 'E', ''),
('JM', 'Jamaica', '0', 'N', '1876'),
('JO', 'Jordan', '0', 'A', '962'),
('JP', 'Japan', '0', 'A', '81'),
('KE', 'Kenya', '0', 'F', '254'),
('KG', 'Kyrgyzstan', '0', 'A', '996'),
('KH', 'Cambodia', '0', 'A', '855'),
('KI', 'Kiribati', '0', 'U', '686'),
('KM', 'Comoros', '0', 'F', '269'),
('KN', 'Saint Kitts and Nevis', '0', 'N', '1869'),
('KP', 'North Korea', '0', 'A', '850'),
('KR', 'South Korea', '0', 'A', '82'),
('KW', 'Kuwait', '0', 'A', '965'),
('KY', 'Cayman Islands', '0', 'N', '1345'),
('KZ', 'Kazakhstan', '0', 'A', '7'),
('LA', 'Laos', '0', 'A', '856'),
('LB', 'Lebanon', '0', 'A', '961'),
('LC', 'Saint Lucia', '0', 'N', '1758'),
('LI', 'Liechtenstein', '0', 'E', '423'),
('LK', 'Sri Lanka', '0', 'A', '94'),
('LR', 'Liberia', '0', 'F', '231'),
('LS', 'Lesotho', '0', 'F', '266'),
('LT', 'Lithuania', '0', 'E', '370'),
('LU', 'Luxembourg', '0', 'E', '352'),
('LV', 'Latvia', '0', 'E', '371'),
('LY', 'Libya', '0', 'F', '218'),
('MA', 'Morocco', '0', 'F', '212'),
('MC', 'Monaco', '0', 'E', '377'),
('MD', 'Moldova', '0', 'E', '373'),
('ME', 'Montenegro', '0', 'E', '382'),
('MG', 'Madagascar', '0', 'F', '261'),
('MH', 'Marshall Islands', '0', 'U', '692'),
('MK', 'Macedonia', '0', 'E', '389'),
('ML', 'Mali', '0', 'F', '223'),
('MM', 'Myanmar', '0', 'A', '95'),
('MN', 'Mongolia', '0', 'A', '976'),
('MO', 'Macao', '0', 'A', ''),
('MP', 'Northern Mariana Islands', '0', 'U', '1670'),
('MQ', 'Martinique', '0', 'N', '596'),
('MR', 'Mauritania', '0', 'F', '222'),
('MS', 'Montserrat', '0', 'N', '1664'),
('MT', 'Malta', '0', 'E', '356'),
('MU', 'Mauritius', '0', 'F', '230'),
('MV', 'Maldives', '0', 'A', '960'),
('MW', 'Malawi', '0', 'F', '265'),
('MX', 'Mexico', '0', 'N', '52'),
('MY', 'Malaysia', '0', 'A', '60'),
('MZ', 'Mozambique', '0', 'F', '258'),
('NA', 'Namibia', '0', 'F', '264'),
('NC', 'New Caledonia', '0', 'U', '687'),
('NE', 'Niger', '0', 'F', '227'),
('NF', 'Norfolk Island', '0', 'U', ''),
('NG', 'Nigeria', '0', 'F', '234'),
('NI', 'Nicaragua', '0', 'N', '505'),
('NL', 'Netherlands', '0', 'E', '31'),
('NO', 'Norway', '0', 'E', '47'),
('NP', 'Nepal', '0', 'A', '977'),
('NR', 'Nauru', '0', 'U', '674'),
('NU', 'Niue', '0', 'U', '683'),
('NZ', 'New Zealand', '0', 'U', '64'),
('OM', 'Oman', '0', 'A', '968'),
('PA', 'Panama', '0', 'N', '507'),
('PE', 'Peru', '0', 'S', '51'),
('PF', 'French Polynesia', '0', 'U', '689'),
('PG', 'Papua New Guinea', '0', 'U', '675'),
('PH', 'Philippines', '0', 'A', '63'),
('PK', 'Pakistan', '0', 'A', '92'),
('PL', 'Poland', '0', 'E', '48'),
('PM', 'Saint Pierre and Miquelon', '0', 'N', ''),
('PN', 'Pitcairn', '0', 'U', ''),
('PR', 'Puerto Rico', '0', 'N', '1787'),
('PS', 'Palestinian territories', '0', 'A', ''),
('PT', 'Portugal', '0', 'E', '351'),
('PW', 'Palau', '0', 'U', '680'),
('PY', 'Paraguay', '0', 'S', '595'),
('QA', 'Qatar', '0', 'A', '974'),
('RE', 'Reunion', '0', 'F', ''),
('RO', 'Romania', '0', 'E', '40'),
('RS', 'Serbia', '0', 'E', '381'),
('RU', 'Russian Federation', '0', 'E', '7'),
('RW', 'Rwanda', '0', 'F', '250'),
('SA', 'Saudi Arabia', '0', 'A', '966'),
('SB', 'Solomon Islands', '0', 'U', '677'),
('SC', 'Seychelles', '0', 'F', '248'),
('SD', 'Sudan', '0', 'F', '249'),
('SE', 'Sweden', '0', 'E', '46'),
('SG', 'Singapore', '0', 'A', '65'),
('SH', 'Saint Helena', '0', 'F', ''),
('SI', 'Slovenia', '0', 'E', '386'),
('SJ', 'Svalbard and Jan Mayen', '0', 'E', ''),
('SK', 'Slovakia', '0', 'E', '421'),
('SL', 'Sierra Leone', '0', 'F', '232'),
('SM', 'San Marino', '0', 'E', '378'),
('SN', 'Senegal', '0', 'F', '221'),
('SO', 'Somalia', '0', 'F', '252'),
('SR', 'Suriname', '0', 'S', '597'),
('ST', 'Sao Tome and Principe', '0', 'F', '239'),
('SV', 'El Salvador', '0', 'N', '503'),
('SY', 'Syria', '0', 'A', '963'),
('SZ', 'Swaziland', '0', 'F', '268'),
('TC', 'Turks and Caicos Islands', '0', 'N', '1649'),
('TD', 'Chad', '0', 'F', '235'),
('TF', 'French Southern Territories', '0', 'Q', ''),
('TG', 'Togo', '0', 'F', '228'),
('TH', 'Thailand', '0', 'A', '66'),
('TJ', 'Tajikistan', '0', 'A', '992'),
('TK', 'Tokelau', '0', 'U', '690'),
('TL', 'Timor-Leste', '0', 'A', ''),
('TM', 'Turkmenistan', '0', 'A', '993'),
('TN', 'Tunisia', '0', 'F', '216'),
('TO', 'Tonga', '0', 'U', '676'),
('TR', 'Turkey', '0', 'A', '90'),
('TT', 'Trinidad and Tobago', '0', 'N', '1868'),
('TV', 'Tuvalu', '0', 'U', '688'),
('TW', 'Taiwan', '0', 'A', '886'),
('TZ', 'Tanzania', '0', 'F', '255'),
('UA', 'Ukraine', '0', 'E', '380'),
('UG', 'Uganda', '0', 'F', '256'),
('UM', 'United States Minor Outlying Islands', '0', 'U', ''),
('US', 'United States', '1', 'N', '1'),
('UY', 'Uruguay', '0', 'S', '598'),
('UZ', 'Uzbekistan', '0', 'A', '998'),
('VA', 'Vatican City', '0', 'E', '39'),
('VC', 'Saint Vincent and the Grenadines', '0', 'N', '1784'),
('VE', 'Venezuela', '0', 'S', '58'),
('VG', 'British Virgin Islands', '0', 'N', '1284'),
('VI', 'United States Virgin Islands', '0', 'N', '1340'),
('VN', 'Viet Nam', '0', 'A', '84'),
('VU', 'Vanuatu', '0', 'U', '678'),
('WF', 'Wallis and Futuna', '0', 'U', '681'),
('WS', 'Samoa', '0', 'U', '685'),
('YE', 'Yemen', '0', 'A', '967'),
('YT', 'Mayotte', '0', 'F', '262'),
('ZA', 'South Africa', '0', 'F', '27'),
('ZM', 'Zambia', '0', 'F', '260'),
('ZW', 'Zimbabwe', '0', 'F', '263');

INSERT INTO `sexy_sys_menu_items` (`menu_id`, `type_id`, `parent_id`, `name`, `location`, `icon`, `user_groups`, `order`, `active`) VALUES ('5', '1', '113', 'Maxmind Phone Verify Service Log Viewer', 'object=log_maxmind_phone_verify', '', '', '107', '1' );