<?php

return PhpCsFixer\Config::create()
    ->setRiskyAllowed(true)
    ->setRules([
        'align_multiline_comment' => true,
        'array_syntax' => ['syntax' => 'short'],
		'backtick_to_shell_exec' => true,
#		'binary_operator_spaces' => ['align', 'align_single_space', 'align_single_space_minimal', 'single_space'],
		'blank_line_after_namespace' => true,
		'blank_line_after_opening_tag' => true,
#        'blank_line_before_statement' => ['statements' => ['break', 'continue', 'declare', 'return', 'throw', 'try']],
#		'braces' => ['allow_single_line_closure' => false, 'position_after_anonymous_constructs' => ['same'], 'position_after_control_structures' => ['same'], 'position_after_functions_and_oop_constructs' => ['same']],
#		'cast_spaces' => ['space' => ['single']],
		'class_attributes_separation' => ['elements' => ['const', 'method', 'property']],
#		'class_definition' => ['multiLineExtendsEachSingleLine' => false, 'singleItemSingleLine' => false, 'singleLine' => false],
		'class_keyword_remove' => true,
        'combine_consecutive_issets' => true,
        'combine_consecutive_unsets' => true,
        'compact_nullable_typehint' => true,
		'concat_space' => ['spacing' => 'none'],
		'declare_equal_normalize' => ['space' => 'single'],
		'dir_constant' => true,
        'escape_implicit_backslashes' => true,
		'elseif' => true,
        'explicit_indirect_variable' => true,
        'explicit_string_variable' => true,
        'final_internal_class' => true,
		'full_opening_tag' => false,
		'function_declaration' => ['closure_function_spacing' => 'one'],
		'function_to_constant' => ['functions' => ['get_class', 'php_sapi_name', 'phpversion', 'pi']],
		'function_typehint_space' => true,
#        'header_comment' => ['header' => $header],
        'heredoc_to_nowdoc' => true,
        'list_syntax' => ['syntax' => 'long'],
        'method_chaining_indentation' => true,
        'method_argument_space' => ['ensure_fully_multiline' => true],
        'multiline_comment_opening_closing' => true,
#        'no_extra_blank_lines' => ['tokens' => ['break', 'continue', 'extra', 'return', 'throw', 'use', 'parenthesis_brace_block', 'square_brace_block', 'curly_brace_block']],
        'no_null_property_initialization' => true,
        'no_short_echo_tag' => true,
        'no_superfluous_elseif' => true,
        'no_unneeded_curly_braces' => true,
        'no_unneeded_final_method' => true,
#        'no_unreachable_default_argument_value' => true,
        'no_useless_else' => true,
        'no_useless_return' => true,
        'ordered_class_elements' => true,
        'ordered_imports' => true,
        'php_unit_strict' => true,
#        'php_unit_test_annotation' => true,
#        'php_unit_test_class_requires_covers' => true,
#        'phpdoc_add_missing_param_annotation' => true,
        'phpdoc_order' => true,
        'phpdoc_types_order' => true,
        'semicolon_after_instruction' => true,
        'single_line_comment_style' => ['comment_types' => ['asterisk', 'hash']],
        'strict_comparison' => true,
        'strict_param' => true,
        'yoda_style' => false,
    ])
    ->setFinder(
        PhpCsFixer\Finder::create()
        ->files()
#        ->in(__DIR__ . '/classes')
        ->name('*.php')
    );
