#dist: trusty
#sudo: false

language: php

php:
  - 5.6
  - 7.0
  - hhvm
#  - nightly

services:
  - memcached
  - redis-server

env:
  - YF_DB_PSWD=

before_script:
  - env | sort
  - composer self-update
  - composer require --prefer-source --no-interaction jakub-onderka/php-parallel-lint

script: export YF_DB_PSWD=""; cd ./.dev/tests/bin/ && ./php_parallel_lint_all.sh && ./phpunit_run_all.sh

matrix:
  fast_finish: true

notifications:
  slack: yfix:g116ToSWgVpzNUZoXSJipxsB
#  webhooks:
#    urls:
#      - https://webhooks.gitter.im/e/011c4351cc1d01e7874b
#    on_success: change  # options: [always|never|change] default: always
#    on_failure: always  # options: [always|never|change] default: always
