language: php

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - hhvm

services:
  - memcached
  - redis-server
  - rabbitmq
  - mongodb

#env:
#  - YF_DB_PSWD=

before_script:
#  - if [ -n "$(hhvm --version | grep -i hiphop)" ]; then phpenv config-add .dev/tests/travis_php.ini; fi 
  - mysql -e 'create database yf_for_unit_tests;'
#  - composer self-update
#  - (cd ./libs/ && COMPOSER=../.dev/scripts/assets/composer.json composer install --prefer-source --no-interaction --dev)

script: export YF_DB_PSWD=""; cd ./.dev/tests/bin/ && ./phpunit_run_all.sh

matrix:
#  allow_failures:
#    - php: 5.6
#    - php: hhvm
  fast_finish: true

#after_script:
#  - php ./bin/coveralls -v

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/011c4351cc1d01e7874b
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
#    on_start: false     # default: false
