<?php
return '
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `id2` int(10) unsigned NOT NULL,
  `user_id` int(10) unsigned NOT NULL DEFAULT \'0\',
  `cat_id` int(10) unsigned NOT NULL DEFAULT \'0\',
  `folder_id` int(10) unsigned NOT NULL,
  `img_name` varchar(255) NOT NULL DEFAULT \'\',
  `name` varchar(255) NOT NULL DEFAULT \'\',
  `desc` text NOT NULL,
  `show_in_ads` enum(\'0\',\'1\') NOT NULL DEFAULT \'0\',
  `diplay_order` int(10) unsigned NOT NULL DEFAULT \'0\',
  `general_sort_id` int(10) unsigned NOT NULL DEFAULT \'0\',
  `folder_sort_id` int(10) unsigned NOT NULL DEFAULT \'0\',
  `add_date` int(10) unsigned NOT NULL DEFAULT \'0\',
  `other_info` text NOT NULL,
  `active` enum(\'1\',\'0\') NOT NULL DEFAULT \'1\',
  `is_public` enum(\'0\',\'1\') NOT NULL DEFAULT \'0\',
  `is_featured` enum(\'0\',\'1\') NOT NULL DEFAULT \'0\',
  `geo_cc` char(2) NOT NULL,
  `geo_rc` char(2) NOT NULL,
  `priority` int(11) NOT NULL DEFAULT \'0\',
  `allow_rate` enum(\'1\',\'0\') NOT NULL,
  `rating` float NOT NULL,
  `num_votes` int(10) unsigned NOT NULL,
  `votes_sum` int(11) NOT NULL,
  `last_vote_date` int(10) unsigned NOT NULL,
  `allow_tagging` enum(\'0\',\'1\') NOT NULL,
  PRIMARY KEY (`id`),
  KEY `user_id` (`user_id`),
  KEY `add_date` (`add_date`),
  KEY `folder_id` (`folder_id`),
  KEY `is_public` (`is_public`),
  KEY `geo_cc` (`geo_cc`),
  KEY `geo_rc` (`geo_rc`),
  KEY `rating` (`rating`),
  KEY `id2` (`id2`)
  /** ENGINE=INNODB **/
';
