<?php
return array (
  1 => 
  array (
    'id' => '1',
    'object_name' => 'blog',
    'object_id' => '1',
    'parent_id' => '0',
    'user_id' => '4',
    'user_name' => '',
    'user_email' => '',
    'add_date' => '1207834186',
    'text' => 'very interesting tems, i\'ll be watch to this post',
    'ip' => '192.168.1.25',
    'active' => '1',
    'activity' => '0',
  ),
  2 => 
  array (
    'id' => '2',
    'object_name' => 'gallery',
    'object_id' => '1',
    'parent_id' => '0',
    'user_id' => '5',
    'user_name' => '',
    'user_email' => '',
    'add_date' => '1207834752',
    'text' => '[SIZE=14]hmm... mabe japanes at [B]huanhe[/B][/SIZE][COLOR=green][/COLOR]',
    'ip' => '192.168.1.25',
    'active' => '1',
    'activity' => '0',
  ),
  3 => 
  array (
    'id' => '3',
    'object_name' => 'news',
    'object_id' => '2',
    'parent_id' => '0',
    'user_id' => '5',
    'user_name' => '',
    'user_email' => '',
    'add_date' => '1207837877',
    'text' => '[B]that was not a news today[/B]',
    'ip' => '192.168.1.25',
    'active' => '1',
    'activity' => '0',
  ),
  4 => 
  array (
    'id' => '4',
    'object_name' => 'gallery',
    'object_id' => '1',
    'parent_id' => '0',
    'user_id' => '6',
    'user_name' => '',
    'user_email' => '',
    'add_date' => '1207838899',
    'text' => '[I]that\'s right[/I]',
    'ip' => '192.168.1.25',
    'active' => '1',
    'activity' => '0',
  ),
  5 => 
  array (
    'id' => '5',
    'object_name' => 'blog',
    'object_id' => '3',
    'parent_id' => '0',
    'user_id' => '4',
    'user_name' => '',
    'user_email' => '',
    'add_date' => '1207905214',
    'text' => '[COLOR=blue]Firefox is similar & free...[/COLOR]',
    'ip' => '192.168.1.25',
    'active' => '1',
    'activity' => '0',
  ),
  6 => 
  array (
    'id' => '6',
    'object_name' => 'news',
    'object_id' => '3',
    'parent_id' => '0',
    'user_id' => '4',
    'user_name' => '',
    'user_email' => '',
    'add_date' => '1207905567',
    'text' => '[COLOR=red][SIZE=14][B]Hmm.. zimbabwe - not interesting[/B][/SIZE][/COLOR]',
    'ip' => '192.168.1.25',
    'active' => '1',
    'activity' => '0',
  ),
  7 => 
  array (
    'id' => '7',
    'object_name' => 'articles',
    'object_id' => '3',
    'parent_id' => '0',
    'user_id' => '4',
    'user_name' => '',
    'user_email' => '',
    'add_date' => '1207908606',
    'text' => 'tomcats - that\'s historical aircraft, but I like li & yak aircrafts',
    'ip' => '192.168.1.25',
    'active' => '1',
    'activity' => '0',
  ),
);