<?php
return '
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `group` tinyint(3) unsigned NOT NULL DEFAULT \'0\',
  `name` varchar(255) NOT NULL DEFAULT \'\',
  `nick` varchar(64) NOT NULL DEFAULT \'\',
  `login` varchar(64) NOT NULL DEFAULT \'\',
  `email` varchar(50) NOT NULL DEFAULT \'\',
  `password` varchar(32) NOT NULL DEFAULT \'\',
  `phone` varchar(40) NOT NULL DEFAULT \'\',
  `city` varchar(40) NOT NULL DEFAULT \'\',
  `state` varchar(20) NOT NULL DEFAULT \'\',
  `country` varchar(30) NOT NULL DEFAULT \'USA\',
  `zip_code` varchar(16) NOT NULL DEFAULT \'\',
  `address` varchar(255) NOT NULL DEFAULT \'\',
  `sex` enum(\'Female\',\'Male\') NOT NULL DEFAULT \'Female\',
  `age` smallint(2) unsigned NOT NULL DEFAULT \'0\',
  `birth_date` date NOT NULL DEFAULT \'0000-00-00\',
  `visits` smallint(6) unsigned NOT NULL DEFAULT \'0\',
  `active` tinyint(1) unsigned NOT NULL DEFAULT \'1\',
  `add_date` int(10) unsigned NOT NULL DEFAULT \'0\',
  `last_update` int(10) unsigned NOT NULL DEFAULT \'0\',
  `last_login` int(10) unsigned NOT NULL DEFAULT \'0\',
  `num_logins` smallint(6) unsigned NOT NULL DEFAULT \'0\',
  `last_view` int(10) unsigned NOT NULL DEFAULT \'0\',
  `num_views` int(10) unsigned NOT NULL DEFAULT \'0\',
  `verify_code` varchar(32) NOT NULL DEFAULT \'\',
  `profile_url` varchar(64) NOT NULL,
  `admin_comments` text NOT NULL,
  `ip` varchar(15) NOT NULL DEFAULT \'\',
  `photo_verified` enum(\'0\',\'1\') NOT NULL,
  `avatar` varchar(255) NOT NULL DEFAULT \'\',
  `priority` int(11) NOT NULL DEFAULT \'0\',
  `lon` decimal(8,4) NOT NULL DEFAULT \'0.0000\',
  `lat` decimal(8,4) NOT NULL DEFAULT \'0.0000\',
  `has_avatar` enum(\'0\',\'1\') NOT NULL DEFAULT \'0\',
  `contact_by_email` enum(\'1\',\'0\') NOT NULL,
  `emails` smallint(6) unsigned NOT NULL DEFAULT \'0\',
  `emailssent` smallint(6) unsigned NOT NULL DEFAULT \'0\',
  `go_after_login` varchar(255) NOT NULL DEFAULT \'\',
  PRIMARY KEY (`id`),
  KEY `login` (`login`),
  KEY `nick` (`nick`),
  KEY `active` (`active`),
  KEY `group` (`group`),
  KEY `email` (`email`),
  KEY `has_avatar` (`has_avatar`),
  KEY `priority` (`priority`),
  KEY `country` (`country`)
  /** ENGINE=InnoDB DEFAULT CHARSET=utf8 **/
';
