<?php
/** @var Other common used tables required data */
$data = my_array_merge((array)$data, array(
"moods"	=> array(
	99999 => array("name" => ''),
	array("name" => 'None, or other'),
	array("name" => 'accomplished'),
	array("name" => 'aggravated'),
	array("name" => 'amused'),
	array("name" => 'angry'),
	array("name" => 'annoyed'),
	array("name" => 'anxious'),
	array("name" => 'apathetic'),
	array("name" => 'artistic'),
	array("name" => 'awake'),
	array("name" => 'bitchy'),
	array("name" => 'blah'),
	array("name" => 'blank'),
	array("name" => 'bored'),
	array("name" => 'bouncy'),
	array("name" => 'busy'),
	array("name" => 'calm'),
	array("name" => 'cheerful'),
	array("name" => 'chipper'),
	array("name" => 'cold'),
	array("name" => 'complacent'),
	array("name" => 'confused'),
	array("name" => 'contemplative'),
	array("name" => 'content'),
	array("name" => 'cranky'),
	array("name" => 'crappy'),
	array("name" => 'crazy'),
	array("name" => 'creative'),
	array("name" => 'crushed'),
	array("name" => 'curious'),
	array("name" => 'cynical'),
	array("name" => 'depressed'),
	array("name" => 'determined'),
	array("name" => 'devious'),
	array("name" => 'dirty'),
	array("name" => 'disappointed'),
	array("name" => 'discontent'),
	array("name" => 'distressed'),
	array("name" => 'ditzy'),
	array("name" => 'dorky'),
	array("name" => 'drained'),
	array("name" => 'drunk'),
	array("name" => 'ecstatic'),
	array("name" => 'embarrassed'),
	array("name" => 'energetic'),
	array("name" => 'enraged'),
	array("name" => 'enthralled'),
	array("name" => 'envious'),
	array("name" => 'exanimate'),
	array("name" => 'excited'),
	array("name" => 'exhausted'),
	array("name" => 'flirty'),
	array("name" => 'frustrated'),
	array("name" => 'full'),
	array("name" => 'geeky'),
	array("name" => 'giddy'),
	array("name" => 'giggly'),
	array("name" => 'gloomy'),
	array("name" => 'good'),
	array("name" => 'grateful'),
	array("name" => 'groggy'),
	array("name" => 'grumpy'),
	array("name" => 'guilty'),
	array("name" => 'happy'),
	array("name" => 'high'),
	array("name" => 'hopeful'),
	array("name" => 'horny'),
	array("name" => 'hot'),
	array("name" => 'hungry'),
	array("name" => 'hyper'),
	array("name" => 'impressed'),
	array("name" => 'indescribable'),
	array("name" => 'indifferent'),
	array("name" => 'infuriated'),
	array("name" => 'intimidated'),
	array("name" => 'irate'),
	array("name" => 'irritated'),
	array("name" => 'jealous'),
	array("name" => 'jubilant'),
	array("name" => 'lazy'),
	array("name" => 'lethargic'),
	array("name" => 'listless'),
	array("name" => 'lonely'),
	array("name" => 'loved'),
	array("name" => 'melancholy'),
	array("name" => 'mellow'),
	array("name" => 'mischievous'),
	array("name" => 'moody'),
	array("name" => 'morose'),
	array("name" => 'naughty'),
	array("name" => 'nauseated'),
	array("name" => 'nerdy'),
	array("name" => 'nervous'),
	array("name" => 'nostalgic'),
	array("name" => 'numb'),
	array("name" => 'okay'),
	array("name" => 'optimistic'),
	array("name" => 'peaceful'),
	array("name" => 'pensive'),
	array("name" => 'pessimistic'),
	array("name" => 'pissed off'),
	array("name" => 'pleased'),
	array("name" => 'predatory'),
	array("name" => 'productive'),
	array("name" => 'quixotic'),
	array("name" => 'recumbent'),
	array("name" => 'refreshed'),
	array("name" => 'rejected'),
	array("name" => 'rejuvenated'),
	array("name" => 'relaxed'),
	array("name" => 'relieved'),
	array("name" => 'restless'),
	array("name" => 'rushed'),
	array("name" => 'sad'),
	array("name" => 'satisfied'),
	array("name" => 'scared'),
	array("name" => 'shocked'),
	array("name" => 'sick'),
	array("name" => 'silly'),
	array("name" => 'sleepy'),
	array("name" => 'sore'),
	array("name" => 'stressed'),
	array("name" => 'surprised'),
	array("name" => 'sympathetic'),
	array("name" => 'thankful'),
	array("name" => 'thirsty'),
	array("name" => 'thoughtful'),
	array("name" => 'tired'),
	array("name" => 'touched'),
	array("name" => 'uncomfortable'),
	array("name" => 'weird'),
	array("name" => 'working'),
	array("name" => 'worried'),
),
"search_engines"	=> array(
	99999 => array(
		"name"			=> "Google",
		"search_url"	=> "www.google.com",
		"q_s_word"		=> "q",
		"q_s_word2"		=> "as_q",
		"q_s_charset"	=> "",
		"def_charset"	=> "UTF-8",
		"active"		=> "1",
	),
	array(
		"name"			=> "MSN",
		"search_url"	=> "search.msn.com",
		"q_s_word"		=> "q",
		"q_s_word2"		=> "",
		"q_s_charset"	=> "",
		"def_charset"	=> "UTF-8",
		"active"		=> "1",
	),
	array(
		"name"			=> "Yahoo",
		"search_url"	=> "search.yahoo.com",
		"q_s_word"		=> "p",
		"q_s_word2"		=> "",
		"q_s_charset"	=> "ei",
		"def_charset"	=> "UTF-8",
		"active"		=> "1",
	),
	array(
		"name"			=> "Yandex",
		"search_url"	=> "www.yandex.ru",
		"q_s_word"		=> "text",
		"q_s_word2"		=> "",
		"q_s_charset"	=> "",
		"def_charset"	=> "cp1251",
		"active"		=> "1",
	),
	array(
		"name"			=> "Rambler",
		"search_url"	=> "search.rambler.ru",
		"q_s_word"		=> "words",
		"q_s_word2"		=> "",
		"q_s_charset"	=> "",
		"def_charset"	=> "cp1251",
		"active"		=> "1",
	),
	array(
		"name"			=> "Aport",
		"search_url"	=> "sm.aport.ru",
		"q_s_word"		=> "r",
		"q_s_word2"		=> "",
		"q_s_charset"	=> "",
		"def_charset"	=> "cp1251",
		"active"		=> "1",
	),
),
));
$forum_tables_datas_file = dirname(__FILE__)."/installer_forum_tables_datas.php";
if (file_exists($forum_tables_datas_file)) {
	include_once($forum_tables_datas_file);
}
$shop_tables_datas_file = dirname(__FILE__)."/installer_shop_tables_datas.php";
if (file_exists($shop_tables_datas_file)) {
	include_once($shop_tables_datas_file);
}
?>
