<?php

return [
    'fields' => [
        'id' => [
            'name' => 'id',
            'type' => 'int',
            'length' => 10,
            'decimals' => null,
            'unsigned' => false,
            'nullable' => false,
            'default' => null,
            'charset' => null,
            'collate' => null,
            'auto_inc' => true,
            'primary' => true,
            'unique' => false,
            'values' => null,
        ],
        'title' => [
            'name' => 'title',
            'type' => 'varchar',
            'length' => 255,
            'decimals' => null,
            'unsigned' => null,
            'nullable' => false,
            'default' => '',
            'charset' => null,
            'collate' => null,
            'auto_inc' => false,
            'primary' => false,
            'unique' => false,
            'values' => null,
        ],
        'file' => [
            'name' => 'file',
            'type' => 'varchar',
            'length' => 255,
            'decimals' => null,
            'unsigned' => null,
            'nullable' => false,
            'default' => '',
            'charset' => null,
            'collate' => null,
            'auto_inc' => false,
            'primary' => false,
            'unique' => false,
            'values' => null,
        ],
        'php_code' => [
            'name' => 'php_code',
            'type' => 'text',
            'length' => null,
            'decimals' => null,
            'unsigned' => null,
            'nullable' => false,
            'default' => '',
            'charset' => null,
            'collate' => null,
            'auto_inc' => false,
            'primary' => false,
            'unique' => false,
            'values' => null,
        ],
        'next_run' => [
            'name' => 'next_run',
            'type' => 'int',
            'length' => 10,
            'decimals' => null,
            'unsigned' => false,
            'nullable' => false,
            'default' => '0',
            'charset' => null,
            'collate' => null,
            'auto_inc' => false,
            'primary' => false,
            'unique' => false,
            'values' => null,
        ],
        'week_day' => [
            'name' => 'week_day',
            'type' => 'tinyint',
            'length' => 1,
            'decimals' => null,
            'unsigned' => false,
            'nullable' => false,
            'default' => '-1',
            'charset' => null,
            'collate' => null,
            'auto_inc' => false,
            'primary' => false,
            'unique' => false,
            'values' => null,
        ],
        'month_day' => [
            'name' => 'month_day',
            'type' => 'smallint',
            'length' => 2,
            'decimals' => null,
            'unsigned' => false,
            'nullable' => false,
            'default' => '-1',
            'charset' => null,
            'collate' => null,
            'auto_inc' => false,
            'primary' => false,
            'unique' => false,
            'values' => null,
        ],
        'hour' => [
            'name' => 'hour',
            'type' => 'smallint',
            'length' => 2,
            'decimals' => null,
            'unsigned' => false,
            'nullable' => false,
            'default' => '-1',
            'charset' => null,
            'collate' => null,
            'auto_inc' => false,
            'primary' => false,
            'unique' => false,
            'values' => null,
        ],
        'minute' => [
            'name' => 'minute',
            'type' => 'smallint',
            'length' => 2,
            'decimals' => null,
            'unsigned' => false,
            'nullable' => false,
            'default' => '-1',
            'charset' => null,
            'collate' => null,
            'auto_inc' => false,
            'primary' => false,
            'unique' => false,
            'values' => null,
        ],
        'cronkey' => [
            'name' => 'cronkey',
            'type' => 'varchar',
            'length' => 32,
            'decimals' => null,
            'unsigned' => null,
            'nullable' => false,
            'default' => '',
            'charset' => null,
            'collate' => null,
            'auto_inc' => false,
            'primary' => false,
            'unique' => false,
            'values' => null,
        ],
        'log' => [
            'name' => 'log',
            'type' => 'tinyint',
            'length' => 1,
            'decimals' => null,
            'unsigned' => false,
            'nullable' => false,
            'default' => '0',
            'charset' => null,
            'collate' => null,
            'auto_inc' => false,
            'primary' => false,
            'unique' => false,
            'values' => null,
        ],
        'description' => [
            'name' => 'description',
            'type' => 'text',
            'length' => null,
            'decimals' => null,
            'unsigned' => null,
            'nullable' => false,
            'default' => null,
            'charset' => null,
            'collate' => null,
            'auto_inc' => false,
            'primary' => false,
            'unique' => false,
            'values' => null,
        ],
        'enabled' => [
            'name' => 'enabled',
            'type' => 'tinyint',
            'length' => 1,
            'decimals' => null,
            'unsigned' => false,
            'nullable' => false,
            'default' => '1',
            'charset' => null,
            'collate' => null,
            'auto_inc' => false,
            'primary' => false,
            'unique' => false,
            'values' => null,
        ],
        'key' => [
            'name' => 'key',
            'type' => 'varchar',
            'length' => 30,
            'decimals' => null,
            'unsigned' => null,
            'nullable' => false,
            'default' => '',
            'charset' => null,
            'collate' => null,
            'auto_inc' => false,
            'primary' => false,
            'unique' => false,
            'values' => null,
        ],
        'safemode' => [
            'name' => 'safemode',
            'type' => 'tinyint',
            'length' => 1,
            'decimals' => null,
            'unsigned' => false,
            'nullable' => false,
            'default' => '0',
            'charset' => null,
            'collate' => null,
            'auto_inc' => false,
            'primary' => false,
            'unique' => false,
            'values' => null,
        ],
    ],
    'indexes' => [
        'PRIMARY' => [
            'name' => 'PRIMARY',
            'type' => 'primary',
            'columns' => [
                'id' => 'id',
            ],
        ],
        'task_next_run' => [
            'name' => 'task_next_run',
            'type' => 'index',
            'columns' => [
                'next_run' => 'next_run',
            ],
        ],
    ],
    'foreign_keys' => [
    ],
    'options' => [
    ],
];
