<?php

return [
    'fields' => [
        'id' => [
            'name' => 'id',
            'type' => 'smallint',
            'length' => 5,
            'decimals' => null,
            'unsigned' => true,
            'nullable' => false,
            'default' => null,
            'charset' => null,
            'collate' => null,
            'auto_inc' => true,
            'primary' => true,
            'unique' => false,
            'values' => null,
        ],
        'code' => [
            'name' => 'code',
            'type' => 'varchar',
            'length' => 50,
            'decimals' => null,
            'unsigned' => null,
            'nullable' => true,
            'default' => 'NULL',
            'charset' => null,
            'collate' => null,
            'auto_inc' => false,
            'primary' => false,
            'unique' => false,
            'values' => null,
        ],
        'url' => [
            'name' => 'url',
            'type' => 'varchar',
            'length' => 100,
            'decimals' => null,
            'unsigned' => null,
            'nullable' => true,
            'default' => 'NULL',
            'charset' => null,
            'collate' => null,
            'auto_inc' => false,
            'primary' => false,
            'unique' => false,
            'values' => null,
        ],
        'emoticon' => [
            'name' => 'emoticon',
            'type' => 'varchar',
            'length' => 75,
            'decimals' => null,
            'unsigned' => null,
            'nullable' => true,
            'default' => 'NULL',
            'charset' => null,
            'collate' => null,
            'auto_inc' => false,
            'primary' => false,
            'unique' => false,
            'values' => null,
        ],
        'emo_set' => [
            'name' => 'emo_set',
            'type' => 'tinyint',
            'length' => 3,
            'decimals' => null,
            'unsigned' => true,
            'nullable' => false,
            'default' => '1',
            'charset' => null,
            'collate' => null,
            'auto_inc' => false,
            'primary' => false,
            'unique' => false,
            'values' => null,
        ],
    ],
    'indexes' => [
        'PRIMARY' => [
            'name' => 'PRIMARY',
            'type' => 'primary',
            'columns' => [
                'id' => 'id',
            ],
        ],
    ],
    'foreign_keys' => [
    ],
    'options' => [
    ],
];
