<?php

return [
    'fields' => [
        'id' => [
            'name' => 'id',
            'type' => 'int',
            'length' => 10,
            'decimals' => null,
            'unsigned' => true,
            'nullable' => false,
            'default' => null,
            'charset' => null,
            'collate' => null,
            'auto_inc' => true,
            'primary' => true,
            'unique' => false,
            'values' => null,
        ],
        'banner_id' => [
            'name' => 'banner_id',
            'type' => 'int',
            'length' => 10,
            'decimals' => null,
            'unsigned' => true,
            'nullable' => false,
            'default' => '0',
            'charset' => null,
            'collate' => null,
            'auto_inc' => false,
            'primary' => false,
            'unique' => false,
            'values' => null,
        ],
        'date' => [
            'name' => 'date',
            'type' => 'int',
            'length' => 10,
            'decimals' => null,
            'unsigned' => true,
            'nullable' => false,
            'default' => '0',
            'charset' => null,
            'collate' => null,
            'auto_inc' => false,
            'primary' => false,
            'unique' => false,
            'values' => null,
        ],
        'action' => [
            'name' => 'action',
            'type' => 'varchar',
            'length' => 16,
            'decimals' => null,
            'unsigned' => null,
            'nullable' => false,
            'default' => null,
            'charset' => null,
            'collate' => null,
            'auto_inc' => false,
            'primary' => false,
            'unique' => false,
            'values' => null,
        ],
        'session_id' => [
            'name' => 'session_id',
            'type' => 'varchar',
            'length' => 32,
            'decimals' => null,
            'unsigned' => null,
            'nullable' => false,
            'default' => '',
            'charset' => null,
            'collate' => null,
            'auto_inc' => false,
            'primary' => false,
            'unique' => false,
            'values' => null,
        ],
        'ip' => [
            'name' => 'ip',
            'type' => 'varchar',
            'length' => 16,
            'decimals' => null,
            'unsigned' => null,
            'nullable' => false,
            'default' => '',
            'charset' => null,
            'collate' => null,
            'auto_inc' => false,
            'primary' => false,
            'unique' => false,
            'values' => null,
        ],
        'user_agent' => [
            'name' => 'user_agent',
            'type' => 'varchar',
            'length' => 255,
            'decimals' => null,
            'unsigned' => null,
            'nullable' => false,
            'default' => '',
            'charset' => null,
            'collate' => null,
            'auto_inc' => false,
            'primary' => false,
            'unique' => false,
            'values' => null,
        ],
    ],
    'indexes' => [
        'PRIMARY' => [
            'name' => 'PRIMARY',
            'type' => 'primary',
            'columns' => [
                'id' => 'id',
            ],
        ],
        'ip' => [
            'name' => 'ip',
            'type' => 'index',
            'columns' => [
                'ip' => 'ip',
            ],
        ],
        'banner_id' => [
            'name' => 'banner_id',
            'type' => 'index',
            'columns' => [
                'banner_id' => 'banner_id',
            ],
        ],
        'date' => [
            'name' => 'date',
            'type' => 'index',
            'columns' => [
                'date' => 'date',
            ],
        ],
    ],
    'foreign_keys' => [
    ],
    'options' => [
        'engine' => 'InnoDB',
        'charset' => 'utf8',
    ],
];
