<?php
#autogenerated by unicode_blocks_txt2php() PHP function at 2008-12-22 11:05:27, 171 blocks total
#charset ANSI
$unicode_blocks = array(
  'Basic Latin' => 
  array(
	0 => 0x0000,
	1 => 0x007F,
	2 => 0,
  ),
  'Latin-1 Supplement' => 
  array(
	0 => 0x0080,
	1 => 0x00FF,
	2 => 1,
  ),
  'Latin Extended-A' => 
  array(
	0 => 0x0100,
	1 => 0x017F,
	2 => 2,
  ),
  'Latin Extended-B' => 
  array(
	0 => 0x0180,
	1 => 0x024F,
	2 => 3,
  ),
  'IPA Extensions' => 
  array(
	0 => 0x0250,
	1 => 0x02AF,
	2 => 4,
  ),
  'Spacing Modifier Letters' => 
  array(
	0 => 0x02B0,
	1 => 0x02FF,
	2 => 5,
  ),
  'Combining Diacritical Marks' => 
  array(
	0 => 0x0300,
	1 => 0x036F,
	2 => 6,
  ),
  'Greek and Coptic' => 
  array(
	0 => 0x0370,
	1 => 0x03FF,
	2 => 7,
  ),
  'Cyrillic' => 
  array(
	0 => 0x0400,
	1 => 0x04FF,
	2 => 8,
  ),
  'Cyrillic Supplement' => 
  array(
	0 => 0x0500,
	1 => 0x052F,
	2 => 9,
  ),
  'Armenian' => 
  array(
	0 => 0x0530,
	1 => 0x058F,
	2 => 10,
  ),
  'Hebrew' => 
  array(
	0 => 0x0590,
	1 => 0x05FF,
	2 => 11,
  ),
  'Arabic' => 
  array(
	0 => 0x0600,
	1 => 0x06FF,
	2 => 12,
  ),
  'Syriac' => 
  array(
	0 => 0x0700,
	1 => 0x074F,
	2 => 13,
  ),
  'Arabic Supplement' => 
  array(
	0 => 0x0750,
	1 => 0x077F,
	2 => 14,
  ),
  'Thaana' => 
  array(
	0 => 0x0780,
	1 => 0x07BF,
	2 => 15,
  ),
  'NKo' => 
  array(
	0 => 0x07C0,
	1 => 0x07FF,
	2 => 16,
  ),
  'Devanagari' => 
  array(
	0 => 0x0900,
	1 => 0x097F,
	2 => 17,
  ),
  'Bengali' => 
  array(
	0 => 0x0980,
	1 => 0x09FF,
	2 => 18,
  ),
  'Gurmukhi' => 
  array(
	0 => 0x0A00,
	1 => 0x0A7F,
	2 => 19,
  ),
  'Gujarati' => 
  array(
	0 => 0x0A80,
	1 => 0x0AFF,
	2 => 20,
  ),
  'Oriya' => 
  array(
	0 => 0x0B00,
	1 => 0x0B7F,
	2 => 21,
  ),
  'Tamil' => 
  array(
	0 => 0x0B80,
	1 => 0x0BFF,
	2 => 22,
  ),
  'Telugu' => 
  array(
	0 => 0x0C00,
	1 => 0x0C7F,
	2 => 23,
  ),
  'Kannada' => 
  array(
	0 => 0x0C80,
	1 => 0x0CFF,
	2 => 24,
  ),
  'Malayalam' => 
  array(
	0 => 0x0D00,
	1 => 0x0D7F,
	2 => 25,
  ),
  'Sinhala' => 
  array(
	0 => 0x0D80,
	1 => 0x0DFF,
	2 => 26,
  ),
  'Thai' => 
  array(
	0 => 0x0E00,
	1 => 0x0E7F,
	2 => 27,
  ),
  'Lao' => 
  array(
	0 => 0x0E80,
	1 => 0x0EFF,
	2 => 28,
  ),
  'Tibetan' => 
  array(
	0 => 0x0F00,
	1 => 0x0FFF,
	2 => 29,
  ),
  'Myanmar' => 
  array(
	0 => 0x1000,
	1 => 0x109F,
	2 => 30,
  ),
  'Georgian' => 
  array(
	0 => 0x10A0,
	1 => 0x10FF,
	2 => 31,
  ),
  'Hangul Jamo' => 
  array(
	0 => 0x1100,
	1 => 0x11FF,
	2 => 32,
  ),
  'Ethiopic' => 
  array(
	0 => 0x1200,
	1 => 0x137F,
	2 => 33,
  ),
  'Ethiopic Supplement' => 
  array(
	0 => 0x1380,
	1 => 0x139F,
	2 => 34,
  ),
  'Cherokee' => 
  array(
	0 => 0x13A0,
	1 => 0x13FF,
	2 => 35,
  ),
  'Unified Canadian Aboriginal Syllabics' => 
  array(
	0 => 0x1400,
	1 => 0x167F,
	2 => 36,
  ),
  'Ogham' => 
  array(
	0 => 0x1680,
	1 => 0x169F,
	2 => 37,
  ),
  'Runic' => 
  array(
	0 => 0x16A0,
	1 => 0x16FF,
	2 => 38,
  ),
  'Tagalog' => 
  array(
	0 => 0x1700,
	1 => 0x171F,
	2 => 39,
  ),
  'Hanunoo' => 
  array(
	0 => 0x1720,
	1 => 0x173F,
	2 => 40,
  ),
  'Buhid' => 
  array(
	0 => 0x1740,
	1 => 0x175F,
	2 => 41,
  ),
  'Tagbanwa' => 
  array(
	0 => 0x1760,
	1 => 0x177F,
	2 => 42,
  ),
  'Khmer' => 
  array(
	0 => 0x1780,
	1 => 0x17FF,
	2 => 43,
  ),
  'Mongolian' => 
  array(
	0 => 0x1800,
	1 => 0x18AF,
	2 => 44,
  ),
  'Limbu' => 
  array(
	0 => 0x1900,
	1 => 0x194F,
	2 => 45,
  ),
  'Tai Le' => 
  array(
	0 => 0x1950,
	1 => 0x197F,
	2 => 46,
  ),
  'New Tai Lue' => 
  array(
	0 => 0x1980,
	1 => 0x19DF,
	2 => 47,
  ),
  'Khmer Symbols' => 
  array(
	0 => 0x19E0,
	1 => 0x19FF,
	2 => 48,
  ),
  'Buginese' => 
  array(
	0 => 0x1A00,
	1 => 0x1A1F,
	2 => 49,
  ),
  'Balinese' => 
  array(
	0 => 0x1B00,
	1 => 0x1B7F,
	2 => 50,
  ),
  'Sundanese' => 
  array(
	0 => 0x1B80,
	1 => 0x1BBF,
	2 => 51,
  ),
  'Lepcha' => 
  array(
	0 => 0x1C00,
	1 => 0x1C4F,
	2 => 52,
  ),
  'Ol Chiki' => 
  array(
	0 => 0x1C50,
	1 => 0x1C7F,
	2 => 53,
  ),
  'Phonetic Extensions' => 
  array(
	0 => 0x1D00,
	1 => 0x1D7F,
	2 => 54,
  ),
  'Phonetic Extensions Supplement' => 
  array(
	0 => 0x1D80,
	1 => 0x1DBF,
	2 => 55,
  ),
  'Combining Diacritical Marks Supplement' => 
  array(
	0 => 0x1DC0,
	1 => 0x1DFF,
	2 => 56,
  ),
  'Latin Extended Additional' => 
  array(
	0 => 0x1E00,
	1 => 0x1EFF,
	2 => 57,
  ),
  'Greek Extended' => 
  array(
	0 => 0x1F00,
	1 => 0x1FFF,
	2 => 58,
  ),
  'General Punctuation' => 
  array(
	0 => 0x2000,
	1 => 0x206F,
	2 => 59,
  ),
  'Superscripts and Subscripts' => 
  array(
	0 => 0x2070,
	1 => 0x209F,
	2 => 60,
  ),
  'Currency Symbols' => 
  array(
	0 => 0x20A0,
	1 => 0x20CF,
	2 => 61,
  ),
  'Combining Diacritical Marks for Symbols' => 
  array(
	0 => 0x20D0,
	1 => 0x20FF,
	2 => 62,
  ),
  'Letterlike Symbols' => 
  array(
	0 => 0x2100,
	1 => 0x214F,
	2 => 63,
  ),
  'Number Forms' => 
  array(
	0 => 0x2150,
	1 => 0x218F,
	2 => 64,
  ),
  'Arrows' => 
  array(
	0 => 0x2190,
	1 => 0x21FF,
	2 => 65,
  ),
  'Mathematical Operators' => 
  array(
	0 => 0x2200,
	1 => 0x22FF,
	2 => 66,
  ),
  'Miscellaneous Technical' => 
  array(
	0 => 0x2300,
	1 => 0x23FF,
	2 => 67,
  ),
  'Control Pictures' => 
  array(
	0 => 0x2400,
	1 => 0x243F,
	2 => 68,
  ),
  'Optical Character Recognition' => 
  array(
	0 => 0x2440,
	1 => 0x245F,
	2 => 69,
  ),
  'Enclosed Alphanumerics' => 
  array(
	0 => 0x2460,
	1 => 0x24FF,
	2 => 70,
  ),
  'Box Drawing' => 
  array(
	0 => 0x2500,
	1 => 0x257F,
	2 => 71,
  ),
  'Block Elements' => 
  array(
	0 => 0x2580,
	1 => 0x259F,
	2 => 72,
  ),
  'Geometric Shapes' => 
  array(
	0 => 0x25A0,
	1 => 0x25FF,
	2 => 73,
  ),
  'Miscellaneous Symbols' => 
  array(
	0 => 0x2600,
	1 => 0x26FF,
	2 => 74,
  ),
  'Dingbats' => 
  array(
	0 => 0x2700,
	1 => 0x27BF,
	2 => 75,
  ),
  'Miscellaneous Mathematical Symbols-A' => 
  array(
	0 => 0x27C0,
	1 => 0x27EF,
	2 => 76,
  ),
  'Supplemental Arrows-A' => 
  array(
	0 => 0x27F0,
	1 => 0x27FF,
	2 => 77,
  ),
  'Braille Patterns' => 
  array(
	0 => 0x2800,
	1 => 0x28FF,
	2 => 78,
  ),
  'Supplemental Arrows-B' => 
  array(
	0 => 0x2900,
	1 => 0x297F,
	2 => 79,
  ),
  'Miscellaneous Mathematical Symbols-B' => 
  array(
	0 => 0x2980,
	1 => 0x29FF,
	2 => 80,
  ),
  'Supplemental Mathematical Operators' => 
  array(
	0 => 0x2A00,
	1 => 0x2AFF,
	2 => 81,
  ),
  'Miscellaneous Symbols and Arrows' => 
  array(
	0 => 0x2B00,
	1 => 0x2BFF,
	2 => 82,
  ),
  'Glagolitic' => 
  array(
	0 => 0x2C00,
	1 => 0x2C5F,
	2 => 83,
  ),
  'Latin Extended-C' => 
  array(
	0 => 0x2C60,
	1 => 0x2C7F,
	2 => 84,
  ),
  'Coptic' => 
  array(
	0 => 0x2C80,
	1 => 0x2CFF,
	2 => 85,
  ),
  'Georgian Supplement' => 
  array(
	0 => 0x2D00,
	1 => 0x2D2F,
	2 => 86,
  ),
  'Tifinagh' => 
  array(
	0 => 0x2D30,
	1 => 0x2D7F,
	2 => 87,
  ),
  'Ethiopic Extended' => 
  array(
	0 => 0x2D80,
	1 => 0x2DDF,
	2 => 88,
  ),
  'Cyrillic Extended-A' => 
  array(
	0 => 0x2DE0,
	1 => 0x2DFF,
	2 => 89,
  ),
  'Supplemental Punctuation' => 
  array(
	0 => 0x2E00,
	1 => 0x2E7F,
	2 => 90,
  ),
  'CJK Radicals Supplement' => 
  array(
	0 => 0x2E80,
	1 => 0x2EFF,
	2 => 91,
  ),
  'Kangxi Radicals' => 
  array(
	0 => 0x2F00,
	1 => 0x2FDF,
	2 => 92,
  ),
  'Ideographic Description Characters' => 
  array(
	0 => 0x2FF0,
	1 => 0x2FFF,
	2 => 93,
  ),
  'CJK Symbols and Punctuation' => 
  array(
	0 => 0x3000,
	1 => 0x303F,
	2 => 94,
  ),
  'Hiragana' => 
  array(
	0 => 0x3040,
	1 => 0x309F,
	2 => 95,
  ),
  'Katakana' => 
  array(
	0 => 0x30A0,
	1 => 0x30FF,
	2 => 96,
  ),
  'Bopomofo' => 
  array(
	0 => 0x3100,
	1 => 0x312F,
	2 => 97,
  ),
  'Hangul Compatibility Jamo' => 
  array(
	0 => 0x3130,
	1 => 0x318F,
	2 => 98,
  ),
  'Kanbun' => 
  array(
	0 => 0x3190,
	1 => 0x319F,
	2 => 99,
  ),
  'Bopomofo Extended' => 
  array(
	0 => 0x31A0,
	1 => 0x31BF,
	2 => 100,
  ),
  'CJK Strokes' => 
  array(
	0 => 0x31C0,
	1 => 0x31EF,
	2 => 101,
  ),
  'Katakana Phonetic Extensions' => 
  array(
	0 => 0x31F0,
	1 => 0x31FF,
	2 => 102,
  ),
  'Enclosed CJK Letters and Months' => 
  array(
	0 => 0x3200,
	1 => 0x32FF,
	2 => 103,
  ),
  'CJK Compatibility' => 
  array(
	0 => 0x3300,
	1 => 0x33FF,
	2 => 104,
  ),
  'CJK Unified Ideographs Extension A' => 
  array(
	0 => 0x3400,
	1 => 0x4DBF,
	2 => 105,
  ),
  'Yijing Hexagram Symbols' => 
  array(
	0 => 0x4DC0,
	1 => 0x4DFF,
	2 => 106,
  ),
  'CJK Unified Ideographs' => 
  array(
	0 => 0x4E00,
	1 => 0x9FFF,
	2 => 107,
  ),
  'Yi Syllables' => 
  array(
	0 => 0xA000,
	1 => 0xA48F,
	2 => 108,
  ),
  'Yi Radicals' => 
  array(
	0 => 0xA490,
	1 => 0xA4CF,
	2 => 109,
  ),
  'Vai' => 
  array(
	0 => 0xA500,
	1 => 0xA63F,
	2 => 110,
  ),
  'Cyrillic Extended-B' => 
  array(
	0 => 0xA640,
	1 => 0xA69F,
	2 => 111,
  ),
  'Modifier Tone Letters' => 
  array(
	0 => 0xA700,
	1 => 0xA71F,
	2 => 112,
  ),
  'Latin Extended-D' => 
  array(
	0 => 0xA720,
	1 => 0xA7FF,
	2 => 113,
  ),
  'Syloti Nagri' => 
  array(
	0 => 0xA800,
	1 => 0xA82F,
	2 => 114,
  ),
  'Phags-pa' => 
  array(
	0 => 0xA840,
	1 => 0xA87F,
	2 => 115,
  ),
  'Saurashtra' => 
  array(
	0 => 0xA880,
	1 => 0xA8DF,
	2 => 116,
  ),
  'Kayah Li' => 
  array(
	0 => 0xA900,
	1 => 0xA92F,
	2 => 117,
  ),
  'Rejang' => 
  array(
	0 => 0xA930,
	1 => 0xA95F,
	2 => 118,
  ),
  'Cham' => 
  array(
	0 => 0xAA00,
	1 => 0xAA5F,
	2 => 119,
  ),
  'Hangul Syllables' => 
  array(
	0 => 0xAC00,
	1 => 0xD7AF,
	2 => 120,
  ),
  'High Surrogates' => 
  array(
	0 => 0xD800,
	1 => 0xDB7F,
	2 => 121,
  ),
  'High Private Use Surrogates' => 
  array(
	0 => 0xDB80,
	1 => 0xDBFF,
	2 => 122,
  ),
  'Low Surrogates' => 
  array(
	0 => 0xDC00,
	1 => 0xDFFF,
	2 => 123,
  ),
  'Private Use Area' => 
  array(
	0 => 0xE000,
	1 => 0xF8FF,
	2 => 124,
  ),
  'CJK Compatibility Ideographs' => 
  array(
	0 => 0xF900,
	1 => 0xFAFF,
	2 => 125,
  ),
  'Alphabetic Presentation Forms' => 
  array(
	0 => 0xFB00,
	1 => 0xFB4F,
	2 => 126,
  ),
  'Arabic Presentation Forms-A' => 
  array(
	0 => 0xFB50,
	1 => 0xFDFF,
	2 => 127,
  ),
  'Variation Selectors' => 
  array(
	0 => 0xFE00,
	1 => 0xFE0F,
	2 => 128,
  ),
  'Vertical Forms' => 
  array(
	0 => 0xFE10,
	1 => 0xFE1F,
	2 => 129,
  ),
  'Combining Half Marks' => 
  array(
	0 => 0xFE20,
	1 => 0xFE2F,
	2 => 130,
  ),
  'CJK Compatibility Forms' => 
  array(
	0 => 0xFE30,
	1 => 0xFE4F,
	2 => 131,
  ),
  'Small Form Variants' => 
  array(
	0 => 0xFE50,
	1 => 0xFE6F,
	2 => 132,
  ),
  'Arabic Presentation Forms-B' => 
  array(
	0 => 0xFE70,
	1 => 0xFEFF,
	2 => 133,
  ),
  'Halfwidth and Fullwidth Forms' => 
  array(
	0 => 0xFF00,
	1 => 0xFFEF,
	2 => 134,
  ),
  'Specials' => 
  array(
	0 => 0xFFF0,
	1 => 0xFFFF,
	2 => 135,
  ),
  'Linear B Syllabary' => 
  array(
	0 => 0x10000,
	1 => 0x1007F,
	2 => 136,
  ),
  'Linear B Ideograms' => 
  array(
	0 => 0x10080,
	1 => 0x100FF,
	2 => 137,
  ),
  'Aegean Numbers' => 
  array(
	0 => 0x10100,
	1 => 0x1013F,
	2 => 138,
  ),
  'Ancient Greek Numbers' => 
  array(
	0 => 0x10140,
	1 => 0x1018F,
	2 => 139,
  ),
  'Ancient Symbols' => 
  array(
	0 => 0x10190,
	1 => 0x101CF,
	2 => 140,
  ),
  'Phaistos Disc' => 
  array(
	0 => 0x101D0,
	1 => 0x101FF,
	2 => 141,
  ),
  'Lycian' => 
  array(
	0 => 0x10280,
	1 => 0x1029F,
	2 => 142,
  ),
  'Carian' => 
  array(
	0 => 0x102A0,
	1 => 0x102DF,
	2 => 143,
  ),
  'Old Italic' => 
  array(
	0 => 0x10300,
	1 => 0x1032F,
	2 => 144,
  ),
  'Gothic' => 
  array(
	0 => 0x10330,
	1 => 0x1034F,
	2 => 145,
  ),
  'Ugaritic' => 
  array(
	0 => 0x10380,
	1 => 0x1039F,
	2 => 146,
  ),
  'Old Persian' => 
  array(
	0 => 0x103A0,
	1 => 0x103DF,
	2 => 147,
  ),
  'Deseret' => 
  array(
	0 => 0x10400,
	1 => 0x1044F,
	2 => 148,
  ),
  'Shavian' => 
  array(
	0 => 0x10450,
	1 => 0x1047F,
	2 => 149,
  ),
  'Osmanya' => 
  array(
	0 => 0x10480,
	1 => 0x104AF,
	2 => 150,
  ),
  'Cypriot Syllabary' => 
  array(
	0 => 0x10800,
	1 => 0x1083F,
	2 => 151,
  ),
  'Phoenician' => 
  array(
	0 => 0x10900,
	1 => 0x1091F,
	2 => 152,
  ),
  'Lydian' => 
  array(
	0 => 0x10920,
	1 => 0x1093F,
	2 => 153,
  ),
  'Kharoshthi' => 
  array(
	0 => 0x10A00,
	1 => 0x10A5F,
	2 => 154,
  ),
  'Cuneiform' => 
  array(
	0 => 0x12000,
	1 => 0x123FF,
	2 => 155,
  ),
  'Cuneiform Numbers and Punctuation' => 
  array(
	0 => 0x12400,
	1 => 0x1247F,
	2 => 156,
  ),
  'Byzantine Musical Symbols' => 
  array(
	0 => 0x1D000,
	1 => 0x1D0FF,
	2 => 157,
  ),
  'Musical Symbols' => 
  array(
	0 => 0x1D100,
	1 => 0x1D1FF,
	2 => 158,
  ),
  'Ancient Greek Musical Notation' => 
  array(
	0 => 0x1D200,
	1 => 0x1D24F,
	2 => 159,
  ),
  'Tai Xuan Jing Symbols' => 
  array(
	0 => 0x1D300,
	1 => 0x1D35F,
	2 => 160,
  ),
  'Counting Rod Numerals' => 
  array(
	0 => 0x1D360,
	1 => 0x1D37F,
	2 => 161,
  ),
  'Mathematical Alphanumeric Symbols' => 
  array(
	0 => 0x1D400,
	1 => 0x1D7FF,
	2 => 162,
  ),
  'Mahjong Tiles' => 
  array(
	0 => 0x1F000,
	1 => 0x1F02F,
	2 => 163,
  ),
  'Domino Tiles' => 
  array(
	0 => 0x1F030,
	1 => 0x1F09F,
	2 => 164,
  ),
  'CJK Unified Ideographs Extension B' => 
  array(
	0 => 0x20000,
	1 => 0x2A6DF,
	2 => 165,
  ),
  'CJK Compatibility Ideographs Supplement' => 
  array(
	0 => 0x2F800,
	1 => 0x2FA1F,
	2 => 166,
  ),
  'Tags' => 
  array(
	0 => 0xE0000,
	1 => 0xE007F,
	2 => 167,
  ),
  'Variation Selectors Supplement' => 
  array(
	0 => 0xE0100,
	1 => 0xE01EF,
	2 => 168,
  ),
  'Supplementary Private Use Area-A' => 
  array(
	0 => 0xF0000,
	1 => 0xFFFFF,
	2 => 169,
  ),
  'Supplementary Private Use Area-B' => 
  array(
	0 => 0x100000,
	1 => 0x10FFFF,
	2 => 170,
  ),
);
?>