<?php

$data = array(
  'form_validate_required'				=> 'The %field field is required.',
  'form_validate_isset'					=> 'The %field field must have a value.',
  'form_validate_valid_email'			=> 'The %field field must contain a valid email address.',
  'form_validate_valid_emails'			=> 'The %field field must contain all valid email addresses.',
  'form_validate_valid_url'				=> 'The %field field must contain a valid URL.',
  'form_validate_valid_ip'				=> 'The %field field must contain a valid IP.',
  'form_validate_min_length'			=> 'The %field field must be at least %param characters in length.',
  'form_validate_max_length'			=> 'The %field field cannot exceed %param characters in length.',
  'form_validate_exact_length'			=> 'The %field field must be exactly %param characters in length.',
  'form_validate_alpha'					=> 'The %field field may only contain alphabetical characters.',
  'form_validate_alpha_numeric'			=> 'The %field field may only contain alpha-numeric characters.',
  'form_validate_alpha_numeric_spaces'	=> 'The %field field may only contain alpha-numeric characters and spaces.',
  'form_validate_alpha_dash'			=> 'The %field field may only contain alpha-numeric characters, underscores, and dashes.',
  'form_validate_numeric'				=> 'The %field field must contain only numbers.',
  'form_validate_is_numeric'			=> 'The %field field must contain only numeric characters.',
  'form_validate_integer'				=> 'The %field field must contain an integer.',
  'form_validate_regex_match'			=> 'The %field field is not in the correct format.',
  'form_validate_matches'				=> 'The %field field does not match the %param field.',
  'form_validate_differs'				=> 'The %field field must differ from the %param field.',
  'form_validate_is_unique' 			=> 'The %field field must contain a unique value.',
  'form_validate_is_natural'			=> 'The %field field must only contain digits.',
  'form_validate_is_natural_no_zero'	=> 'The %field field must only contain digits and must be greater than zero.',
  'form_validate_decimal'				=> 'The %field field must contain a decimal number.',
  'form_validate_less_than'				=> 'The %field field must contain a number less than %param.',
  'form_validate_less_than_equal_to'	=> 'The %field field must contain a number less than or equal to %param.',
  'form_validate_greater_than'			=> 'The %field field must contain a number greater than %param.',
  'form_validate_greater_than_equal_to'	=> 'The %field field must contain a number greater than or equal to %param.',
);