<?php

$data = array(
  'form_validate_required'              => 'Заполните поле %field.',
  'form_validate_isset'                 => 'Поле %field не может быть пустым.',
  'form_validate_valid_email'           => 'Поле %field должно содержать действующий Email.',
  'form_validate_valid_emails'          => 'Все Email адреса в поле %field должны быть действительными.',
  'form_validate_valid_url'             => 'Поле %field должно содержать действующий URL.',
  'form_validate_valid_ip'              => 'Поле %field должно содержать действующий IP.',
  'form_validate_min_length'            => 'Длина поля %field должна быть не менеее %param символов.',
  'form_validate_max_length'            => 'Длина поля %field не должна превышать %param символов.',
  'form_validate_exact_length'          => 'Длина поля %field должна равняться %param символам.',
  'form_validate_alpha'                 => 'Поле %field должно содержать только латинские буквенные символы.',
  'form_validate_alpha_numeric'         => 'Поле %field должно содержать только латинские буквы и числа.',
  'form_validate_alpha_numeric_spaces'  => 'Поле %field должно содержать только латинские буквы, числа и пробелы.',
  'form_validate_alpha_dash'            => 'Поле %field должно содержать только латинские буквы, числа, подчеркивания и тире.',
  'form_validate_numeric'               => 'Поле %field должно содержать только цифры.',
  'form_validate_is_numeric'            => 'Поле %field должно содержать только цифровые символы.',
  'form_validate_integer'               => 'Поле %field должно содержать значения типа integer.',
  'form_validate_regex_match'           => 'Поле %field содержит некорректный формат данных.',
  'form_validate_matches'               => 'Поле %field не соответствует полю %param.',
  'form_validate_differs'               => 'Поле %field должно отличаться от поля %param.',
  'form_validate_is_unique'             => 'Поле %field должно содержать уникальное значение.',
  'form_validate_is_natural'            => 'Поле %field должно содержать только цифры',
  'form_validate_is_natural_no_zero'    => 'Поле %field должно содержать только цифры и больше нуля.',
  'form_validate_decimal'               => 'Поле %field должно содержать только десятичные числа.',
  'form_validate_less_than'             => 'Поле %field должно содержать число меньше %param.',
  'form_validate_less_than_equal_to'    => 'Поле %field должно содержать число меньше или равно %param.',
  'form_validate_greater_than'          => 'Поле %field должно содержать число больше %param.',
  'form_validate_greater_than_equal_to' => 'Поле %field должно содержать число больше или равно %param.',
  'form_validate_captcha'               => 'Поле %field неверно.',
);
