<?php
return '
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `name` varchar(255) NOT NULL CHARACTER SET utf8 COLLATE utf8_unicode_ci DEFAULT \'\',
  `url` varchar(255) NOT NULL CHARACTER SET utf8 COLLATE utf8_unicode_ci DEFAULT \'\',
  `image` tinyint(1) NOT NULL DEFAULT \'0\',
  `description` text NOT NULL CHARACTER SET utf8 COLLATE utf8_unicode_ci,
  `features` text NOT NULL CHARACTER SET utf8 COLLATE utf8_unicode_ci,
  `meta_keywords` text NOT NULL CHARACTER SET utf8 COLLATE utf8_unicode_ci,
  `meta_desc` text NOT NULL CHARACTER SET utf8 COLLATE utf8_unicode_ci,
  `external_url` varchar(255) NOT NULL CHARACTER SET utf8 COLLATE utf8_unicode_ci DEFAULT \'\',
  `cat_id` int(11) NOT NULL,
  `model` varchar(64) NOT NULL CHARACTER SET utf8 COLLATE utf8_unicode_ci,
  `sku` varchar(64) NOT NULL CHARACTER SET utf8 COLLATE utf8_unicode_ci,
  `quantity` int(10) NOT NULL DEFAULT \'100\',
  `stock_status_id` int(10) NOT NULL DEFAULT \'0\',
  `manufacturer_id` int(10) NOT NULL DEFAULT \'0\',
  `supplier_id` int(10) NOT NULL DEFAULT \'0\',
  `price` decimal(8,2) NOT NULL DEFAULT \'0.00\',
  `price_promo` decimal(8,2) NOT NULL DEFAULT \'0.00\',
  `price_partner` decimal(8,2) NOT NULL DEFAULT \'0.00\',
  `price_raw` decimal(8,2) NOT NULL DEFAULT \'0.00\',
  `old_price` decimal(8,2) NOT NULL DEFAULT \'0.00\',
  `currency` tinyint(3) unsigned NOT NULL DEFAULT \'0\',
  `add_date` int(10) unsigned NOT NULL DEFAULT \'0\',
  `update_date` int(10) unsigned NOT NULL DEFAULT \'0\',
  `last_viewed_date` int(10) NOT NULL DEFAULT \'0\',
  `featured` tinyint(1) NOT NULL DEFAULT \'0\',
  `active` tinyint(1) NOT NULL DEFAULT \'0\',
  `viewed` int(10) NOT NULL DEFAULT \'0\',
  `sold` int(10) NOT NULL DEFAULT \'0\',
  `status` int(10) NOT NULL DEFAULT \'0\',
  `articul` varchar(32) NOT NULL DEFAULT \'\',
  `origin_url` varchar(255) NOT NULL,
  `source` varchar(255) NOT NULL,
  PRIMARY KEY (`id`),
  KEY `cat_id` (`cat_id`),
  KEY `active` (`active`),
  KEY `viewed` (`viewed`),
  KEY `sold` (`sold`),
  KEY `active_cat_id` (`active`,`cat_id`),
  KEY `add_date` (`add_date`),
  KEY `update_date` (`update_date`),
  KEY `manufacturer_id` (`manufacturer_id`),
  KEY `supplier_id` (`supplier_id`)
';
