<?php

$GLOBALS['INSTALL']["data_menu_items"] = array(
	// Next menu block start here (menu_id=2)
	array(
		"id"			=> 20,
		"menu_id"		=> 2,
		"parent_id"		=> 0,
		"name"			=> 'Forum',
		"location"		=> 'object=forum',
		"type_id"		=> 1,
		"order"			=> 2,
		"active"		=> 0,
	),
	array(
		"id"			=> 21,
		"menu_id"		=> 2,
		"parent_id"		=> 0,
		"name"			=> 'Home',
		"location"		=> 'object=home_page',
		"type_id"		=> 1,
		"order"			=> 0,
		"active"		=> 0,
	),
	array(
		"id"			=> 22,
		"menu_id"		=> 2,
		"parent_id"		=> 0,
		"name"			=> 'FAQ',
		"location"		=> 'object=static_pages&action=show&id=faq',
		"type_id"		=> 1,
		"order"			=> 8,
		"active"		=> 0,
	),
	array(
		"id"			=> 23,
		"menu_id"		=> 2,
		"parent_id"		=> 0,
		"name"			=> 'About',
		"location"		=> 'object=static_pages&action=show&id=about',
		"type_id"		=> 1,
		"order"			=> 9,
		"active"		=> 0,
	),
	array(
		"id"			=> 24,
		"menu_id"		=> 2,
		"parent_id"		=> 0,
		"name"			=> 'Terms',
		"location"		=> 'object=static_pages&action=show&id=terms',
		"type_id"		=> 1,
		"order"			=> 6,
		"active"		=> 0,
	),
	array(
		"id"			=> 25,
		"menu_id"		=> 2,
		"parent_id"		=> 0,
		"name"			=> 'Privacy',
		"location"		=> 'object=static_pages&action=show&id=privacy',
		"type_id"		=> 1,
		"order"			=> 7,
		"active"		=> 0,
	),
	array(
		"id"			=> 28,
		"menu_id"		=> 2,
		"parent_id"		=> 0,
		"name"			=> 'Interests',
		"location"		=> 'object=interests',
		"type_id"		=> 1,
		"order"			=> 5,
		"active"		=> 0,
	),
	array(
		"id"			=> 29,
		"menu_id"		=> 2,
		"parent_id"		=> 0,
		"name"			=> 'Blog',
		"location"		=> 'object=blog',
		"type_id"		=> 1,
		"order"			=> 3,
		"active"		=> 0,
	),
	array(
		"id"			=> 31,
		"menu_id"		=> 2,
		"parent_id"		=> 0,
		"name"			=> 'Gallery',
		"location"		=> 'object=gallery',
		"type_id"		=> 1,
		"order"			=> 4,
		"active"		=> 0,
	),
	array(
		"id"			=> 32,
		"menu_id"		=> 2,
		"parent_id"		=> 0,
		"name"			=> 'Contact Us',
		"location"		=> 'object=help&action=email_form',
		"type_id"		=> 1,
		"order"			=> 10,
		"active"		=> 0,
	),
	array(
		"id"			=> 34,
		"menu_id"		=> 2,
		"parent_id"		=> 0,
		"name"			=> 'News',
		"location"		=> 'object=news',
		"type_id"		=> 1,
		"order"			=> 1,
		"active"		=> 0,
	),
	array(
		"id"			=> 35,
		"menu_id"		=> 2,
		"parent_id"		=> 0,
		"name"			=> 'Articles',
		"location"		=> 'object=articles',
		"type_id"		=> 1,
		"order"			=> 2,
		"active"		=> 0,
	),
	array(
		"id"			=> 36,
		"menu_id"		=> 2,
		"parent_id"		=> 0,
		"name"			=> 'Community',
		"location"		=> 'object=community',
		"type_id"		=> 1,
		"order"			=> 6,
		"active"		=> 0,
	),
	array(
		"id"					=> 37,
		"menu_id"		=> 2,
		"parent_id"		=> 0,
		"name"			=> 'Shop',
		"location"		=> 'object=shop',
		"type_id"			=> 1,
		"order"			=> 1,
		"active"			=> 0,
	),
	// Next menu block start here (menu_id=4)
	array(
		"id"			=> 1,
		"menu_id"		=> 4,
		"parent_id"		=> 0,
		"name"			=> 'Account',
		"location"		=> 'object=account',
		"type_id"		=> 1,
		"order"			=> 1,
		"active"		=> 1,
	),
	array(
		"id"			=> 2,
		"menu_id"		=> 4,
		"parent_id"		=> 0,
		"name"			=> 'Edit profile',
		"location"		=> 'object=user_info',
		"type_id"		=> 1,
		"order"			=> 2,
		"active"		=> 1,
	),
	array(
		"id"			=> 3,
		"menu_id"		=> 4,
		"parent_id"		=> 0,
		"name"			=> 'View profile',
		"location"		=> 'object=user_profile&action=show&id={eval_code($GLOBALS[\'main\']->USER_ID)}',
		"type_id"		=> 1,
		"order"			=> 3,
		"active"		=> 1,
	),
	array(
		"id"			=> 4,
		"menu_id"		=> 4,
		"parent_id"		=> 0,
		"name"			=> 'Email',
		"location"		=> 'object=email&action=inbox',
		"type_id"		=> 1,
		"order"			=> 4,
		"active"		=> 1,
	),
	array(
		"id"			=> 5,
		"menu_id"		=> 4,
		"parent_id"		=> 0,
		"name"			=> 'My blog',
		"location"		=> 'object=blog&action=show_posts',
		"type_id"		=> 1,
		"order"			=> 6,
		"active"		=> 1,
	),
	array(
		"id"			=> 6,
		"menu_id"		=> 4,
		"parent_id"		=> 0,
		"name"			=> 'My gallery',
		"location"		=> 'object=gallery&action=show_gallery',
		"type_id"		=> 1,
		"order"			=> 7,
		"active"		=> 1,
	),
	array(
		"id"			=> 7,
		"menu_id"		=> 4,
		"parent_id"		=> 0,
		"name"			=> 'My interests',
		"location"		=> 'object=interests&action=manage',
		"type_id"		=> 1,
		"order"			=> 8,
		"active"		=> 1,
	),
	array(
		"id"			=> 8,
		"menu_id"		=> 4,
		"parent_id"		=> 0,
		"name"			=> 'Favorite Users',
		"location"		=> 'object=account&action=edit_favorites',
		"type_id"		=> 1,
		"order"			=> 9,
		"active"		=> 1,
	),
	array(
		"id"			=> 9,
		"menu_id"		=> 4,
		"parent_id"		=> 0,
		"name"			=> 'Ignored Users',
		"location"		=> 'object=account&action=edit_ignored',
		"type_id"		=> 1,
		"order"			=> 10,
		"active"		=> 1,
	),
	array(
		"id"			=> 10,
		"menu_id"		=> 4,
		"parent_id"		=> 0,
		"name"			=> 'Friends',
		"location"		=> 'object=friends&action=view_all_friends',
		"type_id"		=> 1,
		"order"			=> 11,
		"active"		=> 1,
	),
	array(
		"id"			=> 11,
		"menu_id"		=> 4,
		"parent_id"		=> 0,
		"name"			=> 'Friend Of',
		"location"		=> 'object=friends&action=view_all_friend_of',
		"type_id"		=> 1,
		"order"			=> 12,
		"active"		=> 1,
	),
	array(
		"id"			=> 12,
		"menu_id"		=> 4,
		"parent_id"		=> 0,
		"name"			=> 'Logout',
		"location"		=> 'task=logout',
		"type_id"		=> 1,
		"order"			=> 14,
		"active"		=> 1,
	),
	array(
		"id"			=> 13,
		"menu_id"		=> 4,
		"parent_id"		=> 0,
		"name"			=> 'My articles',
		"location"		=> 'object=articles&action=manage',
		"type_id"		=> 1,
		"order"			=> 5,
		"active"		=> 1,
	),
	array(
		"id"			=> 14,
		"menu_id"		=> 4,
		"parent_id"		=> 0,
		"name"			=> 'Tags',
		"location"		=> 'object=tags',
		"type_id"		=> 1,
		"order"			=> 13,
		"active"		=> 1,
	),
);

?>