<?php

class yf_core_css {

	private $content_added = array();
	private $content_md5 = array();

	function _init() {
	}

	function add($content, $is_file = true, $params = array()) {
		// input: string/array
		// todo: auto detection of css/link
		if (!is_array($content)) {
			$content = array(0 => $content);
		}
		foreach ((array)$content as $v) {
			$v = trim($v);
			if (!strlen($v)) {
				continue;
			}
			if ($is_file) {
				$v = '<link href="'.htmlspecialchars($v, ENT_QUOTES).'" rel="stylesheet">';
			}
			$md5 = md5($v);
			if (empty($this->content_md5[$md5])) {
				$this->content_md5[$md5] = $md5;
				$this->content_added[] = $v;
			}
		}
	}

	function show_css($params = array()) {
		$content = tpl()->parse_if_exists('style_css');
		$content = trim($content);
		if (strpos($content,"\n") === false && strlen($content)) {
			// single string = automatically generated by compass
			$content = '<link href="'.htmlspecialchars(WEB_PATH. tpl()->TPL_PATH. $content, ENT_QUOTES).'" rel="stylesheet">';
		}
		foreach ((array)$this->content_added as $v) {
			$content .= $v;
		}
		return $content;
	}

	function _find_module_css($module = '') {
// TODO: connect this
		if (!$module) {
			$module = $_GET['object'];
		}
		$stpl_path = $module.'/'.$module.'.css';
		$paths = array(
			MAIN_TYPE_ADMIN ? YF_PATH. 'templates/admin/'.$stpl_path : '',
			YF_PATH. 'templates/user/'.$stpl_path,
			MAIN_TYPE_ADMIN ? YF_PATH. 'plugins/'.$module.'/templates/admin/'.$stpl_path : '',
			YF_PATH. 'plugins/'.$module.'/templates/user/'.$stpl_path,
			MAIN_TYPE_ADMIN ? PROJECT_PATH. 'templates/admin/'.$stpl_path : '',
			PROJECT_PATH. 'templates/user/'.$stpl_path,
			SITE_PATH != PROJECT_PATH ? SITE_PATH. 'templates/user/'.$stpl_path : '',
		);
		$found = '';
		foreach (array_reverse($paths, true) as $path) {
			if (file_exists($path)) {
				$found = $path;
				break;
			}
		}
		return $found;
	}
}
