<?php

class yf_core_js {
	function _init() {
		$this->content_added = array();
		$this->content_md5 = array();
	}
	
	function add($content,$is_file = true) {
		// input: string/array		
		// todo: auto detection of script/link
		if (!is_array($content)) $content = array(0 => $content);
		foreach ($content as $v) {
			if ($is_file) $v = "<script src=\"".$v."\"></script>";
			$md5 = md5($v);
			if (empty($this->content_md5[$md5])) {
				$this->content_md5[$md5] = $md5;
				$this->content_added[] = $v;
			}
		}
	}
	
	function show_js() {
		$content = tpl()->parse('script_js');
		if (strpos($content,"\n") == 0) {
			// single string = automatically generated by compass
			$content = "<script src=\"".WEB_PATH.tpl()->TPL_PATH.$content."\"></script>";
		} 
		foreach ($this->content_added as $v) {
			$content .= $v;
		}
		return $content;
	}
}