<?php

class yf_core_css {

// TODO: auto-caching into web-accessible dir with locking (to avoid duplicate cache entry attempts)

	public $content = array();
	/** @array List of pre-defined assets */
	public $assets = array(
		'jquery-ui'	=> '//cdnjs.cloudflare.com/ajax/libs/jqueryui/1.10.4/css/jquery-ui.min.css',
		'angular-ui'=> '//cdnjs.cloudflare.com/ajax/libs/angular-ui/0.4.0/angular-ui.min.css',
		'bs2'		=> '//netdna.bootstrapcdn.com/twitter-bootstrap/2.3.2/css/bootstrap-combined.min.css',
		'bs3'		=> '//netdna.bootstrapcdn.com/bootstrap/3.1.0/css/bootstrap.min.css',
	);

	/**
	* Catch missing method call
	*/
	function __call($name, $args) {
		return main()->extend_call($this, $name, $args);
	}

	/**
	*/
	public function _init() {
		// Main CSS from theme stpl
		$main_style_css = trim(tpl()->parse_if_exists('style_css'));
		// single string = automatically generated by compass
		if (strpos($main_style_css, "\n") === false && strlen($main_style_css) && preg_match('~^css/style.css\?[0-9]{10}$~ims', $main_style_css)) {
			$this->add_url(WEB_PATH. tpl()->TPL_PATH. $main_style_css);
		} else {
			$this->add_raw($main_style_css);
		}
	}

	/**
	* Main method to display overall CSS. Can be called from main
	* like this: {execute_shutdown(core_css,show)} or {execute_shutdown(graphics,show_css)}
	*/
	public function show($params = array()) {
		// CSS from current module
		$module_css_path = $this->_find_module_css($_GET['object']);
		if ($module_css_path) {
			$this->add_file($module_css_path);
		}
		if ($params['packed']) {
			$packed = $this->_show_packed_content($params);
			// Degrade gracefully
			if (strlen($packed)) {
				return $packed;
			}
		}
		$out = array();
		// Process previously added content, depending on its type
		foreach ((array)$this->content as $md5 => $v) {
			$type = $v['type'];
			$text = $v['text'];
			$_params = (array)$v['params'] + (array)$params;
			$css_class = $_params['class'] ? ' class="'.$_params['class'].'"' : '';
			if ($type == 'url') {
				if ($params['min'] && !DEBUG_MODE && strpos($text, '.min.') === false) {
					$text = substr($text, 0, -strlen('.css')).'.min.css';
				}
// TODO: add optional _prepare_html() for $url
				$out[$md5] = '<link href="'.$text.'" rel="stylesheet"'.$css_class.' />';
			} elseif ($type == 'file') {
				$out[$md5] = '<style type="text/css"'.$css_class.'>'. PHP_EOL. file_get_contents($text). PHP_EOL. '</style>';
			} elseif ($type == 'inline') {
				$text = $this->_strip_style_tags($text);
				$out[$md5] = '<style type="text/css"'.$css_class.'>'. PHP_EOL. $text. PHP_EOL. '</style>';
			} elseif ($type == 'raw') {
				$out[$md5] = $text;
			}
		}
		$this->content = array();
		return implode(PHP_EOL, $out);
	}

	/**
	*/
	public function _show_packed_content($params = array()) {
		$packed_file = $this->_pack_content($params);
		if (!$packed_file || !file_exists($packed_file)) {
			return false;
		}
		$css_class = $params['class'] ? ' class="'.$params['class'].'"' : '';
		return '<link href="'.$packed_file.'" rel="stylesheet"'.$css_class.' />';
	}

	/**
	*/
	public function _pack_content($params = array()) {
// TODO: add tpl for auto-generated hash file name, using: %host, %project, %include_path, %yf_path, %date, %is_user, %is_admin ...
// TODO: add ability to pass callback for auto-generated hash file name
// TODO: support for .min, using some of console minifier (yahoo, google, jsmin ...)
		$packed_file = INCLUDE_PATH. 'uploads/css/packed_'.md5($_SERVER['HTTP_HOST']).'.css';
		if (file_exists($packed_file) && filemtime($packed_file) > (time() - 3600)) {
			return $packed_file;
		}
		$packed_dir = dirname($packed_file);
		if (!file_exists($packed_dir)) {
			mkdir($packed_dir, 0755, true);
		}
		$out = array();
		foreach ((array)$this->content as $md5 => $v) {
			$type = $v['type'];
			$text = $v['text'];
			if ($type == 'url') {
				$out[$md5] = file_get_contents($text);
			} elseif ($type == 'file') {
				$out[$md5] = file_get_contents($text);
			} elseif ($type == 'inline') {
				$text = $this->_strip_style_tags($text);
				$out[$md5] = $text;
			} elseif ($type == 'raw') {
				$out[$md5] = $text;
			}
		}
// TODO: in DEBUG_MODE add comments into generated file and change its name to not overlap with production one
		file_put_contents($packed_file, implode(PHP_EOL, $out));
		return $packed_file;
	}

	/**
	* Alias
	*/
	public function show_css($params = array()) {
		return $this->show($params);
	}

	/**
	* $content: string/array
	* $type: = auto|asset|url|file|inline|raw
	*/
	public function add($content, $force_type = 'auto', $params = array()) {
		if (DEBUG_MODE) {
			$trace = main()->trace_string();
		}
		if (!is_array($content)) {
			$content = array($content);
		}
		if (is_array($force_type)) {
			$params = (array)$params + $force_type;
			$force_type = '';
		}
		foreach ($content as $_content) {
			$_content = trim($_content);
			if (!strlen($_content)) {
				continue;
			}
			$type = '';
			if (in_array($force_type, array('url','file','inline','raw','asset'))) {
				$type = $force_type;
			} else {
				$type = $this->_detect_content($_content);
			}
			$md5 = md5($_content);
			if ($type == 'url') {
				$this->content[$md5] = array(
					'type'	=> 'url',
					'text'	=> $_content,
					'params'=> $params,
				);
			} elseif ($type == 'file') {
				if (file_exists($_content)) {
					$text = file_get_contents($_content);
					if (strlen($text)) {
						$this->content[$md5] = array(
							'type'	=> 'file',
							'text'	=> $_content,
							'params'=> $params,
						);
					}
				}
			} elseif ($type == 'inline') {
				$this->content[$md5] = array(
					'type'	=> 'inline',
					'text'	=> $_content,
					'params'=> $params,
				);
			} elseif ($type == 'raw') {
				$this->content[$md5] = array(
					'type'	=> 'raw',
					'text'	=> $_content,
					'params'=> $params,
				);
			} elseif ($type == 'asset') {
				$info = $this->assets[$_content];
				if (is_array($url)) {
					$url = $info['url'];
					if ($info['require']) {
						$this->add($info['require'], 'asset');
					}
				} else {
					$url = $info;
				}
				$md5 = md5($url);
				$this->content[$md5] = array(
					'type'	=> 'url',
					'text'	=> $url,
					'params'=> $params,
				);
			}
			if (DEBUG_MODE) {
				debug('core_css[]', array(
					'type'		=> $type,
					'md5'		=> $md5,
					'content'	=> $_content,
					'is_added'	=> isset($this->content[$md5]),
					'params'	=> $params,
					'trace'		=> $trace,
				));
			}
		}
	}

	/**
	*/
	public function add_url($content, $params = array()) {
		return $this->add($content, 'url', $params);
	}

	/**
	*/
	public function add_file($content, $params = array()) {
		return $this->add($content, 'file', $params);
	}

	/**
	*/
	public function add_inline($content, $params = array()) {
		return $this->add($content, 'inline', $params);
	}

	/**
	*/
	public function add_raw($content, $params = array()) {
		return $this->add($content, 'raw', $params);
	}

	/**
	*/
	public function _find_module_css($module = '') {
		if (!$module) {
			$module = $_GET['object'];
		}
		$stpl_path = $module.'/'.$module.'.css';
		$paths = array(
			MAIN_TYPE_ADMIN ? YF_PATH. 'templates/admin/'.$stpl_path : '',
			YF_PATH. 'templates/user/'.$stpl_path,
			MAIN_TYPE_ADMIN ? YF_PATH. 'plugins/'.$module.'/templates/admin/'.$stpl_path : '',
			YF_PATH. 'plugins/'.$module.'/templates/user/'.$stpl_path,
			MAIN_TYPE_ADMIN ? PROJECT_PATH. 'templates/admin/'.$stpl_path : '',
			PROJECT_PATH. 'templates/user/'.$stpl_path,
			SITE_PATH != PROJECT_PATH ? SITE_PATH. 'templates/user/'.$stpl_path : '',
		);
		$found = '';
		foreach (array_reverse($paths, true) as $path) {
			if (!strlen($path)) {
				continue;
			}
			if (file_exists($path)) {
				$found = $path;
				break;
			}
		}
		return $found;
	}

	/**
	*/
	public function _detect_content($content = '') {
		$content = trim($content);
		$type = false;
		if (isset($this->assets[$content])) {
			$type = 'asset';
		} elseif (preg_match('~^(http://|https://|//)[a-z0-9]+~ims', $content)) {
			$type = 'url';
		} elseif (preg_match('~^/[a-z0-9\./_-]+\.css$~ims', $content) && file_exists($content)) {
			$type = 'file';
		} elseif (preg_match('~^(<style|[$;#\.@/\*])~ims', $content) || strpos($content, PHP_EOL) !== false) {
			$type = 'inline';
		}
		return $type;
	}

	/**
	*/
	public function _strip_style_tags ($text) {
/*
// TODO: add support for extracting url from <link rel="stylesheet" href="path.to/style.css">
//		preg_replace_callback('~<link[\s\t]+rel="stylesheet"[\s\t]+href="([^"]+)"[\s\t]*[/]?>~ims', function($m) use (&$text) {
//			return $m[1];
//		});
*/
		for ($i = 0; $i < 10; $i++) {
			if (strpos($text, 'style') === false) {
				break;
			}
			$text = preg_replace('~^<style[^>]*?>~ims', '', $text);
			$text = preg_replace('~</style>$~ims', '', $text);
		}
		return $text;
	}
}
