<?php

class yf_core_css {

	/**
	* Catch missing method call
	*/
	function __call($name, $args) {
		return main()->extend_call($this, $name, $args);
	}

	/**
	* Direct call to object as to string is not allowed, return empty string instead
	*/
	function __toString() {
		return '';
	}

	/**
	*/
	public function _init() {
		// Main CSS from theme stpl
		$main_style_css = trim(tpl()->parse_if_exists('style_css'));
		// single string = automatically generated by compass
		if (strpos($main_style_css, "\n") === false && strlen($main_style_css) && preg_match('~^css/style.css\?[0-9]{10}$~ims', $main_style_css)) {
			$this->add_url(WEB_PATH. tpl()->TPL_PATH. $main_style_css);
		} else {
			$this->add_raw($main_style_css);
		}
	}

	/**
	*/
	public function add($content, $content_type_hint = 'auto', $params = array()) {
		return _class('assets')->add($content, 'css', $content_type_hint, $params);
	}

	/**
	*/
	public function add_url($content, $params = array()) {
		return $this->add($content, 'url', $params);
	}

	/**
	*/
	public function add_file($content, $params = array()) {
		return $this->add($content, 'file', $params);
	}

	/**
	*/
	public function add_inline($content, $params = array()) {
		return $this->add($content, 'inline', $params);
	}

	/**
	*/
	public function add_raw($content, $params = array()) {
		return $this->add($content, 'raw', $params);
	}

	/**
	*/
	public function add_asset($content, $params = array()) {
		return $this->add($content, 'asset', $params);
	}

	/**
	* Output CSS content
	*/
	public function show($params = array()) {
		return _class('assets')->show_css($params);
	}

	/**
	* Alias
	*/
	public function show_css($params = array()) {
		return $this->show($params);
	}
}
