<?php

class yf_core_js {

	private $content = array();
	
	/**
	* Main method to display overall JS. Can be called from main like this: {execute_shutdown(core_js,show_js)} or {execute_shutdown(graphics,show_js)}
	*/
	public function show_js($params = array()) {
		$content = tpl()->parse_if_exists('script_js');
		$content = trim($content);
		if (strpos($content,"\n") === false && strlen($content)) {
			// single string = automatically generated by compass
			$content = '<script src="'.htmlspecialchars(WEB_PATH. tpl()->TPL_PATH. $content).'" type="text/javascript"></script>';
		} 
		foreach ((array)$this->content as $md5 => $info) {
			$content .= $info['text'];
		}
		$module_js_path = $this->_find_module_js($_GET['object']);
		if ($module_js_path) {
			$content .= PHP_EOL. '<script type="text/javascript">'.file_get_contents($module_js_path).'</style>'. PHP_EOL;
		}
		return $content;
	}
	
	/**
	*/
	public function add_url($urls, $params = array()) {
		if (!is_array($urls)) {
			$urls = array($urls);
		}
		foreach ((array)$urls as $url) {
			$path = trim($url);
			if (!strlen($url)) {
				continue;
			}
			$md5 = md5($url);
			$this->content[$md5] = array(
				'type'	=> 'url',
				'text'	=> $url,
			);
		}
	}
	
	/**
	*/
	public function add_file($paths, $params = array()) {
		if (!is_array($paths)) {
			$paths = array($paths);
		}
		foreach ((array)$paths as $path) {
			$path = trim($path);
			if (!strlen($path)) {
				continue;
			}
#			if (!file_exists($path)) {
#				continue;
#			}
			$text = file_get_contents($path);
			if (!strlen($text)) {
				continue;
			}
			$md5 = md5($path);
			$this->content[$md5] = array(
				'type'	=> 'file',
				'text'	=> $text,
			);
		}
	}
	
	/**
	*/
	public function add_inline($texts, $params = array()) {
		if (!is_array($texts)) {
			$texts = array($texts);
		}
		foreach ((array)$texts as $text) {
			if (!strlen($text)) {
				continue;
			}
			$md5 = md5($text);
			$this->content[$md5] = array(
				'type'	=> 'inline',
				'text'	=> $text,
			);
		}
	}
	
	/**
	*/
	public function add($content, $is_file = true, $params = array()) {
// TODO: replace $is_file with string type: url|file|inline
		// input: string/array
		if (!is_array($content)) {
			$content = array(0 => $content);
		}
		foreach ($content as $v) {
			$v = trim($v);
			if (!strlen($v)) {
				continue;
			}
			if ($is_file) {
				$v = '<script src="'.htmlspecialchars($v, ENT_QUOTES).'" type="text/javascript"></script>';
			}
			$md5 = md5($v);
			if (!isset($this->content[$md5])) {
				$this->content[$md5] = array(
					'type'	=> $is_file ? 'file' : 'url',
					'text'	=> $v,
				);
			}
		}
	}

	/**
	* Search for JS for current module in several places, where it can be stored.
	*/
	private function _find_module_js($module = '') {
		if (!$module) {
			$module = $_GET['object'];
		}
		$js_path = $module.'/'.$module.'.js';
		$paths = array(
			MAIN_TYPE_ADMIN ? YF_PATH. 'templates/admin/'.$js_path : '',
			YF_PATH. 'templates/user/'.$js_path,
			MAIN_TYPE_ADMIN ? YF_PATH. 'plugins/'.$module.'/templates/admin/'.$js_path : '',
			YF_PATH. 'plugins/'.$module.'/templates/user/'.$js_path,
			MAIN_TYPE_ADMIN ? PROJECT_PATH. 'templates/admin/'.$js_path : '',
			PROJECT_PATH. 'templates/user/'.$js_path,
			SITE_PATH != PROJECT_PATH ? SITE_PATH. 'templates/user/'.$js_path : '',
		);
		$found = '';
		foreach (array_reverse($paths, true) as $path) {
			if (!strlen($path)) {
				continue;
			}
			if (file_exists($path)) {
				$found = $path;
				break;
			}
		}
		return $found;
	}

	/**
	*/
	private function _content_is_url($content) {
		if (!_class('validate')->valid_url($content)) {
			return false;
		}
// TODO: //domain.com/script.js
// TODO: http://domain.com/script.js
// TODO: https://domain.com/script.js
// TODO: domain.com/script.js
// TODO: /script.js
// TODO: script.js
// TODO: explode by newlines into several items 
	}

	/**
	*/
	private function _content_is_file($content) {
// TODO: file_exists and not starts with (http:// | https:// | //)
// TODO: file allowed to begin with PROJECT_PATH, SITE_PATH or YF_PATH
	}

	/**
	*/
	private function _content_is_inline($content) {
// TODO: can contain one line, but not like url
// TODO: can be without <script> inside
// TODO: trim <script[^>]+>(?P<content>.+?)</script>
	}

// todo: auto detection of script/link
}