<?php
return array(
	'fields' => array(
		'time' => array(
			'name' => 'time',
			'type' => 'decimal',
			'length' => '13',
			'decimals' => '3',
			'unsigned' => true,
			'nullable' => false,
			'default' => '0.000',
			'auto_inc' => false,
			'primary' => false,
			'unique' => false,
			'values' => NULL,
		),
		'ip' => array(
			'name' => 'ip',
			'type' => 'varchar',
			'length' => '16',
			'decimals' => NULL,
			'unsigned' => NULL,
			'nullable' => false,
			'default' => '',
			'auto_inc' => false,
			'primary' => false,
			'unique' => false,
			'values' => NULL,
		),
		'login' => array(
			'name' => 'login',
			'type' => 'varchar',
			'length' => '64',
			'decimals' => NULL,
			'unsigned' => NULL,
			'nullable' => false,
			'default' => '',
			'auto_inc' => false,
			'primary' => false,
			'unique' => false,
			'values' => NULL,
		),
		'pswd' => array(
			'name' => 'pswd',
			'type' => 'varchar',
			'length' => '64',
			'decimals' => NULL,
			'unsigned' => NULL,
			'nullable' => false,
			'default' => '',
			'auto_inc' => false,
			'primary' => false,
			'unique' => false,
			'values' => NULL,
		),
		'reason' => array(
			'name' => 'reason',
			'type' => 'char',
			'length' => '1',
			'decimals' => NULL,
			'unsigned' => NULL,
			'nullable' => false,
			'default' => 'w',
			'auto_inc' => false,
			'primary' => false,
			'unique' => false,
			'values' => NULL,
		),
		'site_id' => array(
			'name' => 'site_id',
			'type' => 'tinyint',
			'length' => '3',
			'decimals' => NULL,
			'unsigned' => true,
			'nullable' => false,
			'default' => '0',
			'auto_inc' => false,
			'primary' => false,
			'unique' => false,
			'values' => NULL,
		),
		'server_id' => array(
			'name' => 'server_id',
			'type' => 'tinyint',
			'length' => '3',
			'decimals' => NULL,
			'unsigned' => true,
			'nullable' => false,
			'default' => '0',
			'auto_inc' => false,
			'primary' => false,
			'unique' => false,
			'values' => NULL,
		),
	),
	'indexes' => array(
		'PRIMARY' => array(
			'name' => 'PRIMARY',
			'type' => 'primary',
			'columns' => array(
				'time' => 'time',
			),
		),
	),
	'foreign_keys' => array(
	),
	'options' => array(
	),
);
