<?php

return [
    'fields' => [
        'country' => [
            'name' => 'country',
            'type' => 'char',
            'length' => 2,
            'decimals' => null,
            'unsigned' => null,
            'nullable' => false,
            'default' => null,
            'charset' => null,
            'collate' => null,
            'auto_inc' => false,
            'primary' => false,
            'unique' => false,
            'values' => null,
        ],
        'city' => [
            'name' => 'city',
            'type' => 'varchar',
            'length' => 32,
            'decimals' => null,
            'unsigned' => null,
            'nullable' => false,
            'default' => null,
            'charset' => null,
            'collate' => null,
            'auto_inc' => false,
            'primary' => false,
            'unique' => false,
            'values' => null,
        ],
        'region' => [
            'name' => 'region',
            'type' => 'char',
            'length' => 3,
            'decimals' => null,
            'unsigned' => null,
            'nullable' => false,
            'default' => null,
            'charset' => null,
            'collate' => null,
            'auto_inc' => false,
            'primary' => false,
            'unique' => false,
            'values' => null,
        ],
        'population' => [
            'name' => 'population',
            'type' => 'int',
            'length' => 8,
            'decimals' => null,
            'unsigned' => false,
            'nullable' => false,
            'default' => '0',
            'charset' => null,
            'collate' => null,
            'auto_inc' => false,
            'primary' => false,
            'unique' => false,
            'values' => null,
        ],
        'latitude' => [
            'name' => 'latitude',
            'type' => 'float',
            'length' => null,
            'decimals' => null,
            'unsigned' => false,
            'nullable' => false,
            'default' => null,
            'charset' => null,
            'collate' => null,
            'auto_inc' => false,
            'primary' => false,
            'unique' => false,
            'values' => null,
        ],
        'longitude' => [
            'name' => 'longitude',
            'type' => 'float',
            'length' => null,
            'decimals' => null,
            'unsigned' => false,
            'nullable' => false,
            'default' => null,
            'charset' => null,
            'collate' => null,
            'auto_inc' => false,
            'primary' => false,
            'unique' => false,
            'values' => null,
        ],
    ],
    'indexes' => [
        'country' => [
            'name' => 'country',
            'type' => 'index',
            'columns' => [
                'country' => 'country',
            ],
        ],
        'population' => [
            'name' => 'population',
            'type' => 'index',
            'columns' => [
                'population' => 'population',
            ],
        ],
    ],
    'foreign_keys' => [
    ],
    'options' => [
    ],
];
