<?php
return array (
  2 => 
  array (
    'id' => '2',
    'cat_id' => '28',
    'user_id' => '1',
    'is_own_article' => '0',
    'author_name' => 'test',
    'title' => 'Aviation Flight Control Instruments Developed Before World War II',
    'summary' => 'The Triumph of Instrument Flight',
    'full_text' => 'Most of the pages in this flying story are devoted to actual experiences from all sectors of aviation. I bring readers into the cockpit. I hope they will enjoy adventure and a learning experience. This is not a "how to" book. In the few instances where technology is pivotal, I try to keep it simple. 

Another aviator\'s book is used as a reference for the birth of his airline. He is Robert Mudge and he is still living in Massachusetts. 

The "retrospective" word in the title for this book is an indication that U.S. aviation history was reexamined. For the first time, we can now see that two principal threads in flying, each beginning within a few years of the other, came together and set the stage for the aviation industry that we know today. I will leave to readers to discover what that juncture was and how an essential threshold was then crossed. That portion of the published book, in terms of word volume in comparison with the adventure experiences mentioned above is small, but crucial. 

Instrument flight is flying with no earth horizon as a reference. Why is that important? Without the ability to control the flight of an aircraft, from takeoff to landing, despite clouds, haze, smoke, snow and other obscurations to earth and particularly earth\'s horizon reference, the progress of aviation, strong in its first three decades, would have been completely stunted. In 1929, the newly formed airlines\' planes took off in the morning when the weather permitted. They would land in the afternoon and put passengers on a train for the night. The competition was rail. 

The sight of the Conductor leaning out of a passenger car, Hamilton watch in one hand and lantern in the other, signaling the Engineer to leave the station, has been repeated millions of times, with almost never a delay for the weather. Air travel needed a way to "leave on time." Some solution to clouds and rain and snow and fog had to be found. 

The Wright brothers built and flew the first successful powered airplane in December 1903. In all essential aspects, the Wrights had it right. They needed lift from the wings. To obtain lift they needed a motor to create forward thrust. Just as important, they needed flight control and they got it from flight control surfaces. As pilots, the Wrights exercised intelligent flight control by visual observation of the earth beneath them. Their elevator and their rudder were their flight control surfaces. 

Glenn Curtiss came along just a few years after the Wright brothers. The Wrights had developed mechanical expertise in the bicycle business. Curtiss had been building motorcycle engines. Curtiss was able to add power to the airplane engine. Curtiss and the Wrights became competitors. 

Early flight control surfaces are visible on Glenn Curtiss\' "June Bug" pictured in the story. Upfront is the elevator and behind the pilot was the rudder. Curtiss was later persuaded to put the elevator back with the rudder. 

The Wright brothers knew they needed a flight control to counteract the tendency of their airframe to roll to one side or the other. This was accomplished by whichever brother was flying the plane, who as pilot was lying prone on a bottom wing which could flex. Aided by moving his own weight, the pilot could literally warp the lower wing to help control the tendency of the craft to roll from side to side. They had designed their wing to achieve a crude form of aileron control. 

Just a few short years after the Wrights\' first flight in 1903, Glenn Curtiss improved on wing warping by providing the triangular sections at the end of the wing of his "June Bug," the early "aileron." After the Wright\'s "elevator" and "rudder," this "aileron" became the third discrete flight control surface. Curtiss moved the aileron by leaning his shoulders left or right to move an actuating cord that stretched beside him in his pilot seat. 

The French completed the basic flight controls by giving the pilot foot pedals to control the rudder, and a "stick" to control elevator and aileron. In the meantime, Curtiss had added not just power but also reliability to the engine. 

Most important for this flying story, aircraft now had three flight control surfaces and the means to move them. In clear weather, pilots used their visual sight reference to move the flight controls for safely conducted flight. 

The retrospective then moves to World War I, then flying the mail using light beacons, and ultimately the third decade of the 20th century, particularly the years 1927-1931. Lindbergh flew the Atlantic to Paris in 1927. He kept awake for 33 hours. Just as important, his radial air-cooled engine kept humming for those 33 hours. Some speculated that the flight was a fluke. All accorded it as a hugely popular event. 

In early sections of the book, the reader gets a brief glimpse of the author\'s first introductions to aircraft, up close. A Curtiss Jenny story is followed by a Stinson Detroiter experience. 

The author\'s 1929 ride in a Detroiter leads to a follow-on appreciation for a very early and very successful corporate aviation experience. 

The Lindbergh feat certainly gave a boost to the efforts of a group of aviation enthusiasts, some daring, some cautious, some who blended daring and caution in the right mixture. Month by month in the years 1929-1931, pilots shattered endurance records, one week in the air, two weeks in the air, and more. Other pilots, men and women, month by month, set new point to point speed records. 

Consider the National Air Races at Cleveland in 1931. Lowell Bayles of Springfield beat out Jimmy Doolittle for the coveted Thompson Trophy. Bayles was flying the GeeBee, designed and built by the Granville brothers. 

St. Louis, Los Angeles and Texas provide stories of early success. Tokyo and Wenatchee, Washington share a story of achievement. Lindbergh makes another important and revealing flight, this time with his wife, Anne. The years 1929-31 provided a plethora of record-making and record-breaking flight events. 

For the progress of aviation, the speed and endurance feats were much more important than winning the race or setting a record. Designers and pilots were establishing the aircraft as a reliable, high performance device. All were making history, though in the acclaim of records, some may not have realized the impact. 

Collectively, these men and women proved that aviation was here to stay. It would change the history of the world in many ways. The subject of instrument flying would never have become relevant if aircraft had not achieved reliability, and flying them more than a novelty. 

While the Wrights and Glenn Curtiss and Igor Sikorsky and the Granvilles and those who flew their aircraft were moving the chalks, so to speak, from novelty to practicality, two brothers and their father had been working in a Long Island laboratory, and with demonstration aircraft, on their vision of an autopilot for aircraft. Their contribution would have the potential to lead to published schedules for air transport departure times, and then, despite clouds, rain and even fog, getting aircraft off at published departure times. 

One crucial step remained after the autopilot was demonstrated. 

The ultimate blind landing anticipated by Lawrence Sperry in 1914 was still 80 years in the future. It came into being in the last decade of the 20th century in the Boeing 757-767-777 series of transport aircraft and in military aircraft. 

When new instruments came to the pilot\'s panel, and ground/air radio aids to navigation replaced light beacons, instrument flying became the foundation for much of aviation\'s experience.',
    'status' => 'active',
    'credentials' => '',
    'add_date' => '1207139843',
    'edit_date' => '0',
    'views' => '0',
    'short_url' => 'aviation_flight_control_instruments_developed_before_world_war_i',
    'activity' => '0',
  ),
  3 => 
  array (
    'id' => '3',
    'cat_id' => '28',
    'user_id' => '1',
    'is_own_article' => '0',
    'author_name' => 'test',
    'title' => 'Tomcats and Boeing 777s - Combat Missions with Airborne Refueling',
    'summary' => 'The Triumph of Instrument Flight',
    'full_text' => 'We have about fifty years to cover here, from 1950 to 2000. It took almost all of those fifty years for skill and technology, and the confidence that these had fully matured, to move commercial aviation to accept instrument landings with passengers aboard, under full instrument control. Hands Off! Fifty years for that last fifty feet may be an overstatement, but the final triumph of a fully blind landing can hardly be overstated. A number of achievments had to fall in place first. 

My "hands-on" activity as PPC in the pilot\'s seat of a Navy patrol aircraft came to an end in 1962. From that year on, my understanding of both commercial and military aviation has come from reading, from flying as a passenger, and from discussions with those who have been direct participants in aviation progress in the United States. 

Before the defeat of Germany in World War II, the Luftwaffe had introduced both jet fighters and rocket plane interceptors into combat. Too late to change the outcome of the war in Europe, Germany nevertheless pioneered the operational jet age. England was not far behind with the U.S. a close third. Both the United States and Great Britain had test versions of jet aircraft well along in development programs by V-E day. 

My own first recollection of jets in the U.S. was the Lockheed Shooting Star, a single-seat jet fighter plane. The squadron I reported to in 1951 received a two-seat trainer version (TV-2) of this aircraft to begin checking out our "middle-aged" (anyone over 30) pilots. At this time, the real Navy fighter "jocks," with their new steam catapaults and canted flight decks (both of which were British ideas) became operational on carriers then supporting both propeller and jet aircraft. In the multi-engine sector, I can recall USAAF pilots at Long Beach airport making touch-and-go landings about 1950 in a twin jet bomber about the size of the World War II B-25 Mitchell. Those early twin-jets took a lot of runway for takeoff and had to stay pretty close to an airport. Fuel consumption rates were high and fuel capacities were low to keep weight down so that these planes of limited takeoff thrust could get off the ground. JATO, for Jet Assisted Take Off was an early application of jets in a supporting role. Afterburners were developed to give take-off thrust assists in the launch of practical military jet aircraft. I can recall successive afterburner "booms" emanating from Westover Field, Massachusetts, near my home, when a squadron of F-102 or F-106 aircraft would be scrambled. Those reminders of the Cold War took place before Westover lost its fighters and its B-52 bombers and became a reserve base with C-5 transport aircraft. In the early days of operational jet squadrons in the military, "tail pipe temperature" was a required part of the jet powered aircraft check off list. If it was too high, engine thrust could be lowered and takeoff distance lengthened. More importantly, the hot metal could develop an unsafe condition that could work its way forward toward the heart of the powerplant. So, flights would be rescheduled for hours when the tail pipe temperature readings would be lower. 

One of my memories of early commercial jet flight was a United Airlines Boeing 707, a "short version," making its maiden flight about 1956 or 1957 from San Francisco to San Diego. This plane landed into a beautiful Lindbergh Field sunset, letting down very carefully over the El Cortez Hotel. In the 1950s, the Air Force introduced the B-47, a range-starved nuclear delivery platform, quickly superseded, I am sure to an Air Force pilot\'s great pleasure, by the B-52 of enduring operational life. British aviation gave us the four-jet Comet. After a number of incidents and fatal accidents, this aircraft was quickly retired from service. Travelers connecting through O\'Hare recall one parked there, abandoned in effect, too costly to fix and fly to a decent burial in England. Her four jets were faired into the wings, as were the Navy\'s P-6, an ill-fated four jet seaplane built by Martin in Baltimore. Both of the XP-6s crashed and the effort to create a military seaplane with jet power ended forever. 

The Navy tried twin-jet aircraft to deliver fat nuclear warheads from aircraft carriers, with the AJ being an aircraft of short operational life and quickly forgettable capabilities. Douglas got the Navy successfully into multi-engine jets for carrier-based nuclear delivery requirements. The Navy added two jets to the two Wright 3350 propeller engines on the P2V to create the P2V-5F series that extended the useful life of that successful patrol aircraft. In my own flights in that aircraft, we always used the two jets to shorten our takeoff runs. Jet-prop aircraft also came into the inventory. For civil aviation and for short haul airlines these have maintained some performance advantages. But, by and large the "pure-jet" has won the day. 

Power plant development for aircraft propulsion is a dramatic story. The liquid cooled in-line engines gave way to the air-cooled radial engines. Then came turbines, in both the pure jet version and the prop-jet. 

The jet engine, as first as used in the military fighter aircraft, forced the domestic air traffic control system to incorporate important improvements in instrument flight procedures. The early jets were fuel-limited. The fuel per mile efficiencies eventually became very good but the U.S. Air Force made in flight refueling a standard practice for longer flights and the Navy followed suit. All-weather performance for jet fighters became a requirement, not something a pilot needed only when he got caught in instrument flight conditions. So, the military developers of air traffic control procedures, with the assistance of expertise in the ranks of civil air traffic control operators, pioneered faster penetration of destination weather systems, with steeper, straight in approaches of shorter duration, all contributing to simpler and safer instrument landings. 

I do not want Illustration 4 with its Grumman fighter planes to lead the reader to believe that I was a part of any "new age" of flight. That photo actually represents the last utility for World War II high performance fighter aircraft. These were fast prop planes. They had good flight control instrumentation but had limited radio receiver options. I was flying them in support of drone missions to give the USS Mississippi\'s Terrier missile batteries some operational target experience. The F6F-5K, a modified Hellcat, had a Bendix autopilot and receivers for remote commands so that it could be controlled from takeoff through landing from chase planes or ground control. We also readied the Hellcat to be flown off carriers with heavy bomb loads into the shore hugging railroad tunnels of North Korea. 

Many of the World War II fighter planes were not instrument-qualified, mainly because they had no second option in case of primary radio failure and no backup flight systems. I flew some of these aircraft under instrument conditions only when I unexpectedly encountered instrument conditions. In some ferry flights, to move a plane to another base, I went around weather and in one northern Florida weather front near Jacksonville, practically flat hatted (flew lower than allowed Visual Flight Rule minimums) to avoid clouds in order to reach NAS Sanford, Florida. The climb out at Niagara Falls when returning an F8F from a hurricane evacuation involved a solid 10,000 feet of overcast. I did not fear it, knowing from my aerology briefing and from an incoming pilot that the "tops" were clearly marked at about 10,000 feet. 

The jet fighter pilots that matriculated with the new technology into the era of all-weather fighter aircraft marked a new breed of military pilots. These men and women made contributions not only to execute missions requiring penetration into instrument weather, but their new destination-airport weather penetration techniques, with time-abbreviated approach and letdown procedures, have benefited all aviation. 

I hope to have made it clear that a central theme of this story is that the U.S. has set a notable mark in civil aviation. Technology has been an important factor, though I have hardly addressed that subject. (From response to an earlier book of mine, I also realize that some will feel that this story contains far too much technology.) The instructor personnel involved at the thousands of civilian airfields, and the training they give and promote, the young pilots they have graduated and the Aircraft and Engineering (A&E) licenses that have been earned, have made a variety of aviation careers attractive and challenging. The flight simulators used by the airlines have made an enormous contribution. These systems are a huge advance from the Link Trainers we used in the 1940s. I salute the Fixed Base Operators (FBOs), many of whom struggle to make ends meet and keep a facility going. They deserve recognition. 

I recognize and salute commercial airlines. I am proud that I am now in a modest way, a member of an airline family. One of my sons has made American Airlines his career, not as a pilot, but as reservations agent, ticket counter agent, ramp agent, and baggage agent. His wife, now a teacher, has been an American overseas boarding agent, and with her gift of the Spanish language, was chosen to help open several South American terminals for her airline. Another son has a wife who is a stewardess on American Airlines\' business-building South American runs. She finds time to be mother to two children. Another son\'s wife has just retired from more than 30 years of flying as a stewardess for Delta Airlines. Her recognition of the value of Robert Mudge\'s story of Northeast Airlines got me launched on this story. 

I have learned from my considerable experience as a passenger, and from all of these next-generation family alliances, these loving alliances, that the success of an airline in 2002 is built on employee tension, from the cockpit to the tarmac. 

Airlines work hard to get out on time, as carefully loaded as possible and as full as possible of law-abiding, paying, passengers that can be attracted to its services. I have learned from my own ability to see what is happening in the scenes and behind the scenes when I have been an airline passenger, for one period a frequent passenger, that every employee of a scheduled airline in this new millennium is a Lifeguard at Shark Beach. In today\'s global environment, it would not work any other way. There is no easy job in the airline business. We passengers expect a lot and we get a lot. Safety must take precedence and we enjoy unprecedented safety in flight. The folks I have written about in the 1920s, 30s and 40s set us on the safety course and we need to recall them with gratitude. But, there are people who do not like us. Tension produces performance and our society has demanded performance. Still, I have reflected on this and worry about it and do not have any idea how we might relieve that tension and still achieve the results we demand. 

I am proud of my ACA-170 certificate No. ITL 1352261, dated 09/25/56. It was issued by The Department of Commerce, Civil Aeronautics Administration, signed by the Director Office of Aviation Safety, and it indicates that I have been found to be properly qualified to exercise the privileges of "COMMERCIAL PILOT" with Ratings and Limitations of "AIRPLANE MULTIENGINE LAND INSTRUMENT." 

Reading the back of the certificate, I learn that I am in violation of the provision that I notify CAA of a change of address within 30 days. Just now, as I examine that rule, I realize that I have changed addresses more than 20 times since the address I submitted when the application was approved. That address was a fine home out on beautiful East Avenue in Rochester, New York in the Brighton section. My mother had a small apartment at that address. I frequently used it because as a Navy itinerant, my own family lacked a permanent address. That Rochester address has been chewed up into what Rochestarians call, "The Can of Worms," a highway interchange. Progress, you old devil you! 

When I was leaving for World War II from the U.S. Naval Academy (USNA, the "trade" school, many called it), my mother and father wrote me letters with small talk about family life back home. I recall specifically, the stories about my (younger) sister, who had begun dating. My parents wrote of the noise of the motorcycle arriving and bringing a young male date to our front door. Those letters often featured an extra paragraph to tell me about the noise of a Harley-Davidson leaving our front door on Faraday Street in 1942 in Rochester, New York, well past the neighbors\' evening bedtimes. One of those young men ended up in a P-47 flying out of Britain for the U.S. Army Air Corps in World War II. (Sadly, he did not make it back.) I developed this mental connection between motorcycles in peace, and fighter aircraft in war. 

I have not held the "yoke" or the "stick" of an aircraft since the mid-60s. When I was a child growing up near the New York Central railroad tracks in western New York State, I could hear the big freight going through every night about 2 a.m. Its steam whistle was a thrill. When the snow got too high even for a utility steam engine\'s plow during our harsh winters, I would wake up because I did not hear a whistle that night. For the past twenty years, a twin engine plane has come over my home every morning in the 4 a.m. darkness. Those are surely two radial engines, like the twin Beech of yore, and I can hear the pilot "synch-ing" his engines some mornings. In occasional bad weather, I have missed him or her though that plane\'s on-schedule reliability has been so good that I am sure it made it to Hartford later in the morning. Where did it originate? I had pretty good binaural hearing up to five years ago so I tracked that plane from Portland, Maine. Even on clear nights, it was obviously on the Bradley Field (Hartford, CT) approach that takes most instrument flights over my house. Why was that little plane making the trip so regularly, weekdays and weekends? Well, I can speculate that it was bringing fresh lobster to the elite of Hartford. My pilot friend has been missing for nearly five months now. I miss that plane. It was my last active connection with aviation. Just as with the steam engine pulling that midnight freight, another cycle of my life is complete. 

Today, young ladies are fully involved in all aspects of U.S. aviation. I see those confident young girls driving by my home, some now on motorcycles and many sitting high in their SUVs. I am seeing the well spring for a source of future pilots. We will be better off, and they will be better off, when they trade that cell phone for a good pair of earphones embedded in a hard hat. 

I worried that I did not have fresh anecdotal material to emphasize these final thoughts. Three e-mails have saved me. 

"28 October 2001 

Hi Folks, 

Had a mission tonight that went really well. Sweaty (our girl pilot) was on my wing and she hung in there really well. We went out to the tanker (the first of three times) and it went ok, but three and a half hours later, after the moon had set, it was so friggin dark. We all have our lights off so the bad guys can\'t see us. To tank we have to take our night vision goggles off, and it takes 20 minutes for your eyes to get used to the dark again. So I came off the goggles and tanked immediately. All I could see was the dark mass of an L10-11 and the basket of the drouge we plug into. The air was a little bumpy and there was no horizon. I tried to stare at the basket and fly formation off of that, but I started to get Vertigo. I was in a turn with the tanker but I did not perceive it. I was bouncing around and getting dizzy. It is the hardest thing I have done in a while. 

The combat stuff is going well. Our four ship, of two Tomcats and two hornets (I will never capitalize the plastic plane!) was going after stuff...and coming off target we started getting anti aircraft artillery coming up at us. They could hear our jets and were shooting at me. It looked Roman candle balls coming up in streams. I saw on the mountain where it was coming from and rolled in on the site. We got a designation, and I came off and felt a thump under my bird. Now I was pissed. We had good engine readings and the hydraulic system was good, so I was not too worried about the jet. We watched that spot on the ground with our system and when they shot again, we were able to pinpoint where it came from. Next pass they got a thousand pounds of love riding a laser beam shining on their heads. It is strange to say that killing people could be satisfying, but I wanted to cheer. "Oh, so you want to shoot at ME?" The jet was fine for the trip home, and we landed uneventfully, if a night carrier landing with no moon at all can be called uneventful. 

I took some pictures the other day, and some from a night strike through my goggles...they are awesome, I just wish they did not limit the field of view so severely. It is like looking through two toilet paper tubes. The countryside is so barren. Nothing but rocks and dirt, and more sand than you can imagine. Who would live there? The river valleys have some agricultural development, but as you go further North it is Grand Canyon like. I would love to go raging around in all the terrain, but it is too dangerous below a certain altitude. We don\'t go below it. 

I don\'t have much to tell you about except work. Have not been working out so much, and movies are right out. We have our first "Beer Day" coming in about a week. If we are at sea for more than 45 days straight, they give everybody two beers. Somehow, people manage to get more. I might be doing some scrounging. 

Trying to take some video of stuff, just to keep records of all the things we do. Ready room antics are alive and well, and the pranks are starting. We took Jay\'s springs out of his bed and hid them in another room. This after he tried for weeks to get them in the first place. He was only getting a couple hours of sleep a night because the bars under his mattress made it terribly uncomfortable. Last week he found an unused set in another room and took them. The S-5 guy in charge of beds said he needed them back, and Jay refused. A couple days later some worker bees came in and tried to take them. Jay flipped and kicked them out. So he came in yesterday from a 9 hour mission at like noon and found his springs missing. I thought he was going to have a stroke. He called the S-5 Lt(jg) who had threatened to take them back because he needed them for some visitors coming out to the boat. Jay assumed that this poor guy had taken them back. He was dressing him down with a vengeance, making him say sir every other word. The S-5 guy went and cried to the XO of the ship and our XO had to apologize. (our XO was in on it all along) Jay took it well. I will never forget him coming in and ranting to himself, "They took my springs...I have no springs...hrmph." I think we should start some trouble with the hornet Bubbas...but they don\'t joke so well. A year ago when we stole the hornet squadron\'s table that said "single seat forever" and took it to Fallon and put in on the Bombing range. (and shacked it of course) , their Skipper called NCIS (FBI of the Navy). He threatened to press charges...no sense of humor, so we are hesitant to go there again. There really is nothing like being in a tightly knit organization. Even more so when you are living day to day, trying to make the most of a bad situation. 

Hope you are taking care. I am looking forward to getting home and saying hello in person. Chad" 

"02 November 2001 

Subject: A Quick Note 

Chad: We wanted to say hello and tell you that we saw your ship on Channel 1 news. We saw some of your shipmates. We were able to get an idea of how you live. We watch Channel 1 news daily. Channel 1 is a news program produced for students and teachers. The reporter on the ship was Seth Doane. He reported that the ship is on an inverted schedule. Are you on the schedule eating breakfast at 6:00 a.m.? He interviewed Tim Parker- he was a flight deck person, Jason Cusak and Scott Sally as seaman, Dustin Osborne as the chef and Jerelle Harthy who recycles all the trash. 

We feel sorry for you because we saw how small your bunk is. We hope that you be careful when you get out of bed and hit your head. We also saw one of your gyms where you work out. Lindsay wants to know if you have a curfew? We saw a night landing and the cable you have to snag when you stop. It was cool to see. Leeza wants to know if the quick stop jerks you forward? Alisha would like to know if it\'s a quick trip to your target? 

Do you have a maximum time to fly? Adam wants to know what you do if you have to go to the bathroom while you are flying? We wanted to say HAPPY HALLOWEEN and tell you the world series is tied 2-2 Yankees to Diamondbacks." 

"Re: A Quick Note 

Hi guys, 

Things have been very busy as the operations have stepped up. Our flights are lasting over 7 hours. Imagine strapping yourself to a (hard) seat, one that sits you straight up, for that long. Getting out of the jet after landing yesterday, I almost fell off the ladder my legs were so stiff. It made me wish I was 14 again. I had loosened my lap belts to stretch out a bit and did not tighten them back up. When we came in and snagged the wire, I was thrown forward into the instrument panel. I smacked both my knees on the gauges...OUCH! We have been taking off around midnight, then flying through Pakistan to the airborne tanker where we get gas. Our plane has a probe that we can extend. The tanker has a basket that is shaped like a badminton birdee. It is attached to a hose coming out the back of the tanker, and we fly up behind it and carefully plug our probe into the basket. Then they turn on the pumps and we can take fuel from the big tankers. We tank twice going in and twice coming out of Afghanistan. 

If we are flying too much, the Skipper has to give us a waiver to allow us to fly more. The limit is 65 hours in a month. I have gotten 45 hours in the last two weeks, so I will need one. With the long missions going to the bathroom has become an issue. We carry a specially made ziplock bag. It has a powder in it, and we use those to go. It is hard to take care of that and fly at the same time, but sometimes you HAVE to go. 

Our squadron is split between Yankees fans and Diamondback fans. Since we are called the Diamondbacks too, I have been rooting for them, but I don\'t really care who wins. I wish I could send the videos of the strikes we have been doing, but they are still secret. I will put a bunch of clips that I have taken together, and send it to you when I get a chance. Thanks for the support, and Hope your Halloween was fun. 

Take care, 

Chad" 

I have endeavored in the early chapters of this story to present a theme that military aviation and civilian aviation have been very important to each other, almost co-dependent, during the formative days of U.S. aviation in the early part of the 20th century. Gradually, during the last 50 years of the 20th century, the bond has loosened. Each of these components of aviation is now quite self-sufficient. Yes, the civil airlines are still happy to see a healthy cadre of trained military pilots knocking at their doors for openings in pilot ranks. But we are not likely to again see contract civilian pilots manning military planes to establish new air routes needed for military requirements. Nor is it likely that civil and commercial pilots would be needed again to man hundreds of new military pilot training bases sprouting up all over our country. 

The later chapters have centered on events in which I have in some way participated. The contributions to our country of civil airline pilots, Navy pilots and pilots in the Army Air Corps defy measure. It was never a challenge in the writing of this story to make any special effort to look for examples to relate. In telling the story that I wanted to tell, I came upon example after example of the valor, the ingenuity, and the pioneering that both civil aviation and the military air services mean to this country. Watch a Coast Guard helicopter crew on TV as it makes a rescue at sea. That takes proficiency way up the scale. 

The comparison between Instrument Landing System-ILS instrument approaches to a landing and the use of Ground Controlled Approaches-GCA for that same purpose illustrates one of the earlier preference differences between civil and military aviation. In the employment of either of these instrument landing aids, the pilot has his hands on the flight controls and is using his gyro horizon and his gyro compass to furnish the essential information needed to keep to a pre-defined flight path. In the GCA approach, a pilot is coached back onto the correct flight path by a human voice stationed near the runway on the ground. With ILS, the pilot is coached back to the correct flight path by reference to another instrument on his panel that combines information on the plane\'s deviation in azimuth and elevation from the correct flight path. 

Let me go back to the Aleutian flying I did in 1946-48 to illustrate the value of GCA to military pilots at airfields before ILS existed. The two principal airfields for Navy pilots were at Kodiak, Alaska and at Adak, Alaska. Both had low frequency radio range letdowns with approaches coming from the sea. Their main instrument runways headed into steep mountains. When making low frequency radio range approaches at either field, mandatory pullups were required well short of the designated instrument runway if the pilot had not gained visual contact with the airfield during the approach. Both fields had GCA units and thank God for that. On a GCA approach, the pilot turns control of his aircraft heading and altitude over to the short interval vocal commands given by a ground operator (the GCA controller) who can see the plane on special radarscopes. The polished vocal practice, a result of much training, of the ground controller included a requirement that he or she never be silent for any sustained period. The pilot followed the directions of the controller in flying his plane right down to touchdown. The skill of both pilot and GCA controller was to never let the aircraft get very far from the desired position so that corrections were always small. A safe touchdown resulted from a collaborative effort. 

About the middle of my Aleutian tour, in May of 1947, our Privateer aircraft were outfitted with new electronic equipment bearing the designation, SCS-51. Many of the airfields we used were just being equipped with the ground electronics installation necessary for the SCS-51 equipment to work. Known as ILS, for Instrument Landing System, in the commercial airline world, the SCS-51 system provided the pilot with constant glide path and azimuth information in graphic presentations in an instrument display right on his instrument panel. The pilot actually "sees" whether he is high or low from the correct glidepath and right or left of the correct glidepath. It is a very good system and it is used today (2002) in more advanced versions. 

The pilot\'s gyro horizon and gyro compass indicators were vital to the "small correction" concept of a GCA approach. And were just as vital to the "small correction" concept of the ILS approach. 

First use of ILS in commercial aviation is credited to Braniff Airways in 1947. Commercial airline, air freight, and corporate aircraft pilots would almost always choose to use the ILS system over GCA, when both were available, because the pilot stays in complete control. When the pilot reaches minimums and cannot see the runway, he or she can execute a "missed approach procedure" and take the plane back to altitude. Commercial pilots believed in their abilities and wanted hands-on control of their aircraft during takeoffs and landings. Commercial pilots, many of whom are ex-military or military reserve pilots, did not minimize the value of GCA and would certainly have used it if required, but their choice was ILS. 

World War II military pilots welcomed GCA because it gave them a chance to get back on the ground safely when a low frequency radio range approach or an Automatic Direction Finder (ADF) approach would still leave them up in the clouds. GCA was a life-saving solution that came during the war to some military bases. There was no SCS-51 in those war years, military or civilian. A GCA endearment was the intimacy of the attention given by a ground controller during the critical period of a pilot\'s descent to the ground under instrument conditions. 

ILS still shares much of the load for instrument weather situations involving low ceiling and low visibility approaches and landings in the United States. ILS is passive, and not only in the sense that the pilot keeps control of the aircraft. With ILS, there is no personnel crew on the ground to be paid and trained and on watch 24 hours a day. For the most part, ILS and related methods have become the standard. 

For those readers interested in pursuing further knowledge on how low ceiling, low visibility instrument approaches and landings are handled in 2001a little web searching is a good first step. First, the acronym "GCA" will now fetch such groups as the Green Communities Alliance, Gun Control Alliance and Global Coalition for Africa. One must insert the full "Ground Control Approach" terminology to discover that two full GCA systems are archived at the Wright Patterson Air Force Base Museum. 

At their website, www.wpafb.mil/museum , one discovers that the final resting place for two complete GCA sets, one from Keesler AFB, in Mississippi and the other that had been in service at Wright Patterson Field, is the U.S. Air Force Museum at Wright Patterson Field.. The Keesler unit remained in service until 1980 and the WPAFB unit until 1978. As improved, after World War II, these units consisted of a search radar system with a 45-mile search radius, a two-way voice radio system, and a precision radar system for use during the final 11-mile final approach to the runway. Those web pages include a brief statement on how this equipment was used. For example, " It-the precision radar-alternately scans in both the vertical and horizontal planes to track the approaching aircraft\'s line of descent and course. The controller advises the pilot by radio of any changes in glidepath or course needed to accomplish a safe landing." One interesting paragraph cites the Berlin Airlift in 1948-49, in which hundreds of lives were at risk in the air and on the ground, as an indication of GCA\'s effectiveness, and persuasiveness, while in use. 

The insertion of "ILS" into a web search engine leads to that acronym\'s use by many organizations that are not remotely connected with instrument flight. One result, however, was "Instrument Landing System" and a very helpful website, home.sprynet/~jayschnell/Ils1.htm 

This website is copyrighted by Mr. Jerome Gerald Schnedorf III. In a page headed, "Instrument Landing System," Mr. Schnedorf visualizes a precision instrument approach as a child\'s "slide at the park." He likens the non-precision approach to "a series of steps on a staircase." For the non-precision approach-he cites nine real-world examples from which a pilot might choose - a directional system such as a passive Localizer, or an active system such as an Airport Surveillance Radar - to aid him in bringing his aircraft toward the instrument runway in use on the correct runway heading. During this type of non-precision approach, the pilot lets his aircraft down, say in 500 foot steps, until arriving at some previously defined minimum altitude in the immediate environs of the field. The precision approach systems that Mr. Schnedorf defines are the Instrument Landing System (ILS), the Precision Approach Radar (PAR) and the Microwave Landing System (MLS). 

As a direct consequence of putting a draft version of this story on our publisher\'s website (www.daileyint.com) in November 2001, I was privileged to enter into dialogues with two recently retired airline pilots in early 2002. The results follow: 

With his words, "We\'ve come a long way; baby," 

Retired (1997) Delta Airlines Captain Robert E. Mitchell brought retired Navy Captain Franklyn E. Dailey Jr. up to date on "hands-off" landings under Instrument Flight Rules (IFR) conditions. In an early chapter, I had written (and have now removed for reasons that will become obvious), "Commercial aviation is not ready in 2002 for this mode of operation." The lines that follow were the summary response of Captain Mitchell on 02/12/2002 to my out-of-date sentence. 

"In fact the present generation of aircraft (typified by B-757/767/777) are equipped for just that, and the crews so trained. It is common practice and approved procedure to engage the autopilot/flight director and RNAV (horizontal) and VNAV (vertical) at 1000 feet agl (1000 feet above ground level) after takeoff and not touch anything (including the brakes) until you reverse the engines on roll-out. Normal minimums for these aircraft going into a large airport that is Category III equipped, is just 600 feet runway visual range (no ceiling requirement at all). In essence, you don\'t see anything except the green centerline lights as you roll out!" 

Here is Captain Mitchell\'s 02/13/2002 follow-up to his summary paragraph: 

"Well, that is pretty much what computers have done for instrument flight and approaches in the last 20 years or so. I found as an instructor that getting a student (maybe with as much as 15 - 20 thousand flight hours and no previous experience in the \'glass cockpit airliners\') to grasp the concept was no small challenge. You must realize that a lot has probably changed in the years since my (1999) retirement. 

"The auto-flight system and controls in the B-757/767/777 aircraft are almost identical. In fact, the FAA issues an ATR rating (Airline Transport Rating) that is common to all three aircraft. My ticket shows "Airline Transport Pilot: DC-9, B-757, B-767 (the 777 came just after I retired). The system is comprised of the autopilot, autothrottles, autobrakes, flight director, RNAV and VNAV. All of these components are part of a larger bundle of \'magic\' called the Flight Management System. 

"The autopilot is pretty much the same as it has always been, just refined and refined. However, there are three separate autopilot systems that automatically engage in the approach mode to give redundancy. The autopilot may be used without any of the other autoflight components (and are the same as in a DC-6 or DC-9 plus or minus some details). The only restriction is that it cannot be used by itself without these other components below 1000 feet agl. 

"The auto throttle system is used most all of the time and is turned on/off by a switch on the glareshield. It sets the power for takeoff, will maintain a selected airspeed or mach number and is somehow (magic again) connected to the Flight Management System so that it will maintain a cruise airspeed/mach number that is the most efficient for that flight segment. The autobrakes must be used for takeoff (procedure) and are selected by a switch. They will apply maximum braking to all wheels if the throttles are manually retarded to idle for a rejected or aborted takeoff. They may be used for any landing, visual or instrument, but must be used for a Category III approach/landing. The flight director (2 separate units, one for the captain and one for the first officer) is a standard dual-cue system (orange bars superimposed on the attitude gyro called the ADI or Attitude Directional Indicator) which may be used alone (hand flying) or coupled with the autopilot. It can be controlled manually by entering the desired heading and vertical command (altitude hold, selected vertical speed or go-around mode). It can be used in conjunction with the autopilot and/or the RNAVand VNAV. 

"RNAV is the horizontal navigation system which is based on position information automatically gained from the DME (Distance Measuring Equipment), from two separate VORs (omnirange), and is backed up by three INS units (which become primary when out of range of VOR i.e., ocean crossing). This information is displayed in the cockpit on the HSI (Horizontal Situation Indicator)." (Author\'s Note. I am guessing that INS stands for Inertial Navigation System.) 

"Flight plan information for RNAV and VNAV (and the Flight Management System) is entered by the crew into the CDU (cockpit display system) which is a very small computer screen and keyboard located on the center console between the pilots. There are two of these units; one for the captain and one for the first officer. If memory serves me correctly, this system even has the capability to download all this flight plan data via an inter-link with the company\'s flight control (dispatchers), thus not requiring a manual entry by the crew." (This paragraph is condensed from a clarification dated 02/18/2002 by Robert E. Mitchell.) 

"The Flight Management System recognizes airways, ATC charted fixes, airports, etc. When engaged, it will provide heading information to the autopilot and flight directors, and fly the entire flight from the departure point (including any published instrument departure) to the initial approach fix at your destination. You can program it to fly direct from fix to fix or fly an entire airway route, ie: J22 to DCA, J14 JFK direct BOS. (Author\'s Note: From memory, DCA is Washington National, now Reagan, JFK is Kennedy, formerly Idlewild, and BOS is Boston, for Logan Airport.) You can change anything enroute at any time if you so desire. RNAV does not know anything about altitude. If you only engage RNAV, then altitude management is strictly the pilots\' responsibility." 

"VNAV (vertical navigation) is the altitude portion of the system. You must enter the desired cruise altitude and the altitude at which you want to be at the initial approach fix (it even has the capability to put you over the runway threshold at 50\'...but that isn\'t used). When programmed, VNAV is usually engaged at 1000 feet agl. Along with the autoflight system it will climb the aircraft to the selected cruise altitude, level off, and retard the throttles to the selected cruise power setting. At the descent point (computed from the altitude at which you wish to cross a specified point) it will again retard the throttles and begin the descent, keeping you informed all along as to how the descent profile is coming along. There are however, safeguards to ensure that you do not climb or descend without proper clearance." 

"In the approach mode, the autoflight system uses ground based ILS systems just as it has for years. In very bad weather conditions however things change a lot. All major airports now have instrument runways which have been designated as Category III runways. These ILS units and runways must meet a much higher standard and must have a lot of additional components." 

"Category III is further broken down into Cat IIIa and IIIb and the above rules likewise apply. In both Cat IIIa and b, ceiling is of no concern, only runway visual range RVR (as measured along side the runway) is controlling and in the case of IIIb it can be as low as 300 feet! The crew and aircraft must be qualified for Cat III and the aircraft must be coupled to the autopilot, flight directors, autothrottle and autobrakes. It is a completely hands-off approach and landing. The only physical movements the pilot must make is to properly program the approach, lower the gear and flaps, arm the auto spoilers and reverse the engines after touch down. There is no requirement to see anything! You just hope and pray that all those little electrodes are getting the right signals and when you stop you\'re on the runway and not off in the grass somewhere. The aircraft will flare, touchdown, throttles retard to idle, the nose wheel settles on the runway, the brakes apply and centerline guidance rolls the aircraft to a stop! As I mentioned, the pilot may see a few of the green centerline light as the aircraft rolls out, but that is not a requirement. The hard part now is taxiing to the terminal. I must admit that it took quite awhile to completely trust the system and even then it was not a very comfortable situation. One other requirement: max crosswind component to initiate a Cat III approach is 10 knots." 

"I realize that this is a quick, down and dirty description and I hope it helps. You would not believe the problems we had in training with 50+ year old 727 captains who had not been trained on a new aircraft in 10 - 15 years and the word computer scared them to death! It was a giant step! The young guys who had seen all this magic in the military in some form or another had no problem at all. Would you believe that the Navy now has full autoland to come aboard the carriers! 

"As for me, I entered pre-flight in the fall of 1958 and spent 8 years in the Navy flying S-2s and A4s. My last year I was an instructor in an instrument flight training unit. I went with Delta in August 1966 and retired in 1997. I flew the DC-6/7, Convair 880, DC-9, DC-8, B-727, B-757 and 767 and the767ER. I spent 5 years (1986-1991) as an instructor in the Flight Training Department on the 757/767which was treated as one aircraft. My last year there I was a senior instructor charged with training new instructors. The last six years were on the ER flying to Europe. I was based in Atlanta all 31years. 

Robert E. Mitchell 

15450 Thorntree Run 

Alpharetta, GA 30004" ',
    'status' => 'active',
    'credentials' => '',
    'add_date' => '1207140125',
    'edit_date' => '0',
    'views' => '4',
    'short_url' => 'tomcats_and_boeing_777s__combat_missions_with_airborne_refuelin',
    'activity' => '0',
  ),
  4 => 
  array (
    'id' => '4',
    'cat_id' => '28',
    'user_id' => '1',
    'is_own_article' => '0',
    'author_name' => 'test',
    'title' => 'U.S. Military Draft and Pearl Harbor',
    'summary' => 'World War I Led to World War II',
    'full_text' => 'Men and Machinery 

The coin of the realm in WW II was called "materiel", favoring the less ambiguous variant derived from the French of the word "material". It was materiel, authorized in the U.S. Lend/Lease programs of WW II, when it arrived at U.S. seaports and was loaded into and onto freighters, which were then formed, ship behind ship in six, eight or ten columns, in convoys stretched across the sea. Steam locomotives and aircraft were lashed to the main decks of many freighters. On arrival at an overseas port, these were just one or two maintenance steps away from service and combat. The U.S. literally drowned its adversaries in materiel. Getting it there was a major effort and will be discussed in important episodes in this story. 

The machinery at the heart of this story was called materiel when it was on its way, much of it on railroad flat cars, to the shipbuilding yards of the U.S.. After shaping, assembly and welding, this materiel became ship\'s hull and machinery. A warship was then launched and commissioned. 

(Next, a photo and explanation for its 2008 insertion into our 1998 story of pre-World War II events in the United States.
Above, the USS Edison, DD-439, slides \'down the ways\' from Federal Shipbuilding and Drydock, Kearny N.J. in Nov. 1940. Note the number on her bow, and count the stars in the flag. 

Claud M. "Mickey" Mick III, son of Claud M. Mick Jr., a USS Edison DD-439 shipmate of mine in 1944, [I am Franklyn E. Dailey Jr. author of these website pages and author of the book that resulted from them] contacted me after viewing a TV broadcast segment, labeled Segment 4, of the Military Channel TV series "Quest for Sunken Ships." The picture above is from a clip that appeared in Segment 4, which dealt with events in the life of the U.S. Navy\'s World War II destroyer, the USS Murphy, DD-603. During the broadcast, Mick\'s attention became riveted on the launch scene in the film, and realized the ship being launched was not the Murphy, but his Dad\'s ship, the Edison. Mick contacted me by e-mail (franklyn21@earthlink.net) and also contacted the TV producers, who obligingly supplied him a DVD of the Segment 4 broadcast, containing the Edison launch. In his first contact with me, Mickey Mick sent along a digital snapshot of the scene above by stopping his TIVO-stored TV broadcast and shooting the picture on his TV. Later, with the DVD in hand, he sent along this better shot from the same clip. 

The Edison photos must have been taken from Navy file footage of her launch at the Federal Shipbuilding and Drydock Co. in Kearny NJ. (Murphy was built by Bethlehem on Staten Island.) TV viewers in late 2007 or early 2008 would have found the series in local TV schedules. The Military Channel is related to the Discovery Channel.) 

We resume here our 1998 draft narrative of events of late 1940 and early 1941. 

Next for the ship and its machinery came an underway "shake down" cruise. Those reservists, draftees and the relatively small cadre of regulars who were aboard for the launch, the commissioning (the commissioning "detail"), and the shakedown could all claim to be called "plank owners". From the time the keel was laid until addition of the ship\'s armament after commissioning, the ship\'s personnel complement expanded daily toward full war strength. This small flood of nameless men from \'anytown U.S.A.\' became ship\'s crew. Before their names became known, their identities emerged first as deck seamen, or below decks machinists, water tenders and firemen, or radiomen and radarmen, signalmen and quartermasters, or sonar men or shipfitters, or torpedomen and other members of the ordnance gang including firecontrolmen who had main deck, above deck and below deck stations. The construction of a ship from base metal is a remarkable creation. The evolution of a crew, the bringing together of the right ratings in several disciplines, is an even greater transformation. The whole is greater than the sum of its parts. For the Edison crew of WW II, and for all who went overseas, word from home and to home meant V-mail, not E-mail. 

Air and Sea 

Air and sea define continuums, joined at the water\'s edge by the elements, nature\'s condition. The elements extend no a priori favors; they have no friend or foe. A new ship has just one formally defined shakedown cruise. The elements conduct repeated shakedowns of the men and their machinery. 

A Reluctant Nation 

The human condition is beset with conflict. Thirty minutes of media news briefs might convince the just-arrived alien that conflict is the only human condition. After World War I, much of the world went to sleep with the League of Nations, convinced (or wanting to believe) that the killing fields, both on land and at sea in WW I, could never happen again. A strong vein of isolationism held sway in the heartland of the U.S. The country has been re- made periodically from waves of immigrants. The sympathies of those who come are at first rooted in their forbears; these sympathies did not naturally align to present a single counter force to isolationists in the decades following WW I. (My personal feeling after WW II was that no one could get me angry enough to go to war again. I must admit that a number of persons, forces or events since WW II has put me to war-thinking anew.) And so it was on August 12, 1941, 25 years after the U.S. entry into World War I, and by a margin of just one vote, the U.S. House of Representatives extended a hastily revived draft. 

Considering the scale of the conflict which came to be known as World War II, the U.S .was even less prepared than it had been for World War I. The War in the Atlantic in 1939, which U.S. leaders wrapped in the term, Neutrality Patrol, began almost as a repeat of the Great War 25 years before. At sea, England and Germany took up where they left off. A re-armed Germany had also developed new capacities for active prosecution of war. Japan sided with the Allies in WW I but between the wars its military had convinced its industrious, unquestioning citizens that Japan\'s expansion objectives were valid and that these demanded different alliances. After its foray into China, Japan concentrated its WW II efforts on the defeat of Britain and the U.S. Pearl Harbor was a new twist that vaulted the U.S. beyond a Neutrality Patrol. 

Wartime Leaders 

Politically, most of the nations of the world , including the U.S., had learned little from World War I. A few U.S. individuals who had experienced service in WW I were a small exception. Those who were called upon to serve again in WW II brought valuable experience forward. This was especially true in shipping and shipping protection in the Atlantic. Two men who led the war effort in their respective nations deserve special note in this respect. Both came from naval backgrounds. The two were U.S. President Franklin D. Roosevelt and British Prime Minister Winston Churchill. The U.S. military draft and this residual leadership experience from World War I were critical factors in Germany\'s eventual defeat. 

The Protagonists in Focus 

\'Your men and your machinery\' against \'their men and their machinery\'? Not always. Sometimes it is your men and machinery against the air and sea. This author was a participant, but this is a first-hand account only of the men and machinery he sailed with and fought with. The enemy is known only through the actions they forced and the losses they inflicted. No first hand account of the enemy will be found here. That, too, is pretty much the case with the elements brewed by the air and sea. Meteorologists often provided early warning, but when weather arrived, the ferocity of the elements at the air and sea boundary always presented a new challenge. When the ship\'s inclinometer showed a roll of 58 degrees, a young watch officer became transfixed by the reading on that instrument. A more experienced skipper, for his part, kept a stop watch in his hand. The key was that the time duration of the roll was more important than the angle of heel. A roll too slow was the danger signal that she might really go over. 

The focus here will be on seamen and machinery. It will be largely a one-sided view. Timewise, any reflections on the precise identity of the "enemy" came most often during the extensive daily photo slide training ritual run by the Recognition Officer. In these daily sessions, a ship or plane pictured in the fraction of a second set for the shutter action on the projector, reached your consciousness first as "friend" or "foe" even before a specific national identity flashed into your mind. Except for these sessions and occasional broadcasts from the BBC, acute awareness of an "enemy" came in fast paced action episodes. There was no shouting from trench to trench as in land warfare. The Captain might try to get into the enemy\'s mind but everyone else fought based on the \'situation-at-hand\'. Getting performance out of men and machinery was the task. Chance controlled the rest. 

So in a sequence of episodes, this story will be about putting U.S. men and their machinery, in this case a U.S. destroyer, against challenges to their survival. The intentional threats came from Germany, Italy, and briefly, the Vichy French. The elements took a heavy toll, but differed from the others in that weather\'s respites could be accepted with less suspicion. 

A Backgrounder on Time and Decision (sometimes, indecision) 

Hitler began his rise to power in 1933. The abject failure of Neville Chamberlain\'s diplomacy is encapsulated for all time in the word "Munich". Even that word does not begin to express the loss of the opportunity France and Britain had presented to them for a "Triple Alliance" with Russia before Russia made its deal with Germany in 1939. Winston Churchill, who was not in the British government during the period, later capsuled his country\'s leadership in one sentence: "Britain\'s ruling class takes it weekend in the country while Hitler takes his countries in the weekends." 

So that this narrative might move more directly to a series of destroyer episodes in 1942-44, I will employ some tabulations. The three tables which follow reflect the inconclusiveness of WW I, which ended with the Armistice of November 11, 1918 followed by the Treaty of Versailles. A latent instability between wars, and a man historians and diplomats would never evaluate, finally swept millions of men and women into the inferno of WW II. Indeed, Adolph Hitler was an early puzzle to the German people, although they could see earlier than the rest of the world that he was capable of complete ruthlessness in the pursuit of his objectives. 

The first table, Prelude To War, covers the period 1935-1939, and ends with the beginning of armed hostilities, when Germany, led by Adolph Hitler, invaded Poland. Where specific dates are given in these tables, they are U.S. dates.
After all Polish military resistance ended, and Germany and Russia took their agreed-upon spoils, a period of nervous waiting ensued during which Hitler prepared his next moves. From his observations of the Chamberlain government of Britain in earlier diplomatic action, Hitler had concluded, incorrectly, that Britain would not act militarily when Germany invaded Poland. 

Some revision of Germany\'s expansion plans had to be made when Britain and France declared war. The relatively ineffective military actions taken by Britain and France in an interregnum of nearly eight months gave Hitler and his generals time to make the necessary revisions. 

The next table provides some key events in the period from the first actual hostilities of World War II in 1939 to the announcement of the Tripartite Pact in September 1940. The U.S., whose policies had been greatly influenced by isolationists in the Congress, was in its "waking up" phase.
In the shadow of this defeat, the armada of "anything that would sail" that took the defeated British Army off the beaches at Dunquerque and back to England was a near-miracle. It was the pilot light that stayed lighted after the main burners had been extinguished. Not just the scale and make-up of this small boat "spit kit" fleet, but its result, the salvage of thousands of important soldiers for the isle of Britain in its next two years of dogged resistance, turned out to be essential to the final, successful result in 1945. 

In addition to the defeat of its land forces, Britain suffered another sobering immediate consequence of Dunkerque. The rescue of forces cost the loss of 10 destroyers sunk and 75 disabled. 

Churchill\'s return to government as Prime Minister and as Minister of Defence on May 10, 1940 meant that the evacuation at Dunquerque and the impending fall of France were unparalleled crises greeting his return to government. Though he had protested most of the decisions of the Chamberlain and Baldwin governments that preceded him, he and Britain were left to deal with the consequences. While Dunquerque was a defeat for Britain and for Churchill, the fight that the British showed in military defeat set the tone for the next two years. The first result was survival and the second was victory. But, a war was still to be fought.
The third in this series of event-positioning tables establishes U.S. responsibility areas in the Western Atlantic in 1941 and ends with Japan\'s attack on Pearl Harbor. In the "short of war" period, the U.S. could escort British ships in its neutrality "zone" and would hand them over to British/Canadian escorts at transit from this new marker of the " Western Hemisphere".
The "Axis powers" became a full reality just after President Roosevelt\'s "day that will live in infamy", the day of Japan\'s surprise attack on Pearl Harbor, Dec. 7., 1941. By December 8, the U.S. had declared war on Japan and on December 11, Germany and Italy declared war on the U.S.. Japan, Germany, and Italy were now at war with the Britain, the U.S., the free French and the Polish units which had escaped the Nazi net in Europe. By November 1941, the U.S. Army had 1.5 million men, in uniform, but not yet adequately armed. The U.S. Navy shipbuilding effort was beginning to show results, particularly in modern destroyers. 

The air Battle of Britain had been over almost two years when the first action episode of this story unfolded in August 1942. The Pilotless Bombardment of Britain, as Winston Churchill called it, which became intense in the summer of 1944, was still two years in the future. For the British, it was a very long war. In the preface to Volume 1 of his history of U.S. Naval Operations in World War II covering the period September 1939-May 1943, Samuel Eliot Morison stated, "Thus the Battle of the Atlantic was second to none in its influence on the outcome of the war. Yet the history of it is exceedingly difficult to relate in an acceptable literary form." 

In three tables, we have tried to show the interweave of events and the challenges of playing two hands of poker as if they were one against powerful cards in the hands of men who would lead with death, until death. 

Hitler was a late convert to the U-Boat, favoring investments in air power and his land armies. Entreaties from then Commodore Doenitz, and Britain\'s entry into the active war persuaded Hitler to raise U-Boat production in 1939 from just over three per month to 25 per month. The U-Boat fleet swelled from 45 boats in 1939 to 300 boats at sea in 1941 with 800 targeted for 1943. [/I]',
    'status' => 'active',
    'credentials' => '',
    'add_date' => '1207140349',
    'edit_date' => '0',
    'views' => '0',
    'short_url' => 'u_s_military_draft_and_pearl_harbor',
    'activity' => '0',
  ),
  5 => 
  array (
    'id' => '5',
    'cat_id' => '54',
    'user_id' => '1',
    'is_own_article' => '0',
    'author_name' => 'test',
    'title' => 'Troubleshooting Laptop Wireless Connections',
    'summary' => 'This is the first draft of what I hope will grow into a collection of laptop troubleshooting flowcharts. I\'m currently planning pages for battery charging/life troubleshooting, display failure, drive failure, and wireless/modem/networking problems.',
    'full_text' => 'Note that these steps correspond with decision points on the flowchart and are reached directly by clicking on the diamond symbols. The text below cannot be read sequentially. 

See wireless network? Does the laptop operating system software see the wireless network you are trying to connect to? Many notebooks come equipped with a special manufacturer\'s configuration utility, such as Toshiba\'s ConfigFree, in addition to standard OS connectivity software, like the "View Available Wireless Networks" option in modern Windows versions. In addition, there should be a little wireless icon in the system tray, which may flash a small bubble announcement when it connects or fails to connect. Floating the mouse pointer over the wireless icon in the system tray on a Windows desktop should show the name of the wireless connection (often a HEX address that looks like alphabet soup if not changed from the default), the speed (54 Mbps for 802.11G), the signal strength, and whether a connection to a router has been established. Note that a connection to a router does not imply a connection to the internet. 

Manufacturer provided software can provide a much more accurate picture of relative router distances and signal strength. In some circumstances, especially public networks at hotels, campuses and coffee shops, your laptop may consistently choose to connect to a weak router or access point when stronger signals are available. The manufacturer software usually shows this much clearer than the five green signal strength bars of "View Available Wireless Networks." 

Return to Diagnostic Chart 

Switch on, enabled? When a laptop won\'t connect to a wireless network, more often than not it\'s because the wireless adapter is switched off or disabled in software. As with volume controls for computer speakers, wireless networking can be disabled both manually and through software, and in more than one place. Most modern laptops come equipped with an manual slide switch on the front or side of the laptop that turns the wireless adapter on or off. There is is usually an LED associated with the switch that will be lit only when the laptop\'s wireless capability is on. However, the LED will remain lit even if the wireless has been disabled in software, it is a status indicator for the hardware switch only. The switch can easily be turned off by accident when picking up the laptop or even by a book or other table clutter coming into contact with the side of the notebook, so it\'s a very common problem. 

The easiest place to tell if the laptop wireless adapter has been disabled through software is in Device Manager. One sure sign the adapter is disabled in software (or not operating properly) is if it doesn\'t appear in the system tray. If your laptop wireless adapter is discrete, a USB or PC card (PCMCIA) plug-in, shut down, make sure it\'s plugged in firmly, and reboot. Even if the wireless device is designed to be hot-swappable (plugged in while the laptop is turned on) it\'s better to shut down and do it, since this will give the operating system a chance to reset. 

Return to Diagnostic Chart 

Router active, in range? If there isn\'t a wireless network in range, the notebook certainly can\'t connect to it. It doesn\'t matter is somebody else\'s laptop once connected to a network from the spot you are trying to connect, the question is whether or not there\'s an active signal your laptop should be picking up now. The most obvious reason for the wireless router to be invisible to your laptop is if the router is turned off or out of range. Next comes the wireless function of the router being disabled, or the antenna being damaged or missing. The best way to start troubleshooting wireless problems is to take your laptop and plunk it down right next to the router you are trying to connect to. If the wireless activity LED on the router isn\'t on and active, either wireless has been disabled on the router or the router is faulty. 

Return to Diagnostic Chart 

Home network? Wireless networks in the home often use the exact same equipment as those in Internet cafes and small businesses, but corporate and campus networks often use more sophisticated routers. One of the feature some network administrators of large businesses take advantage of is to hide their network from casual encounters with the outside world simply by instructing the routers not to announce their presence with an "I\'m here" beacon. This is one step beyond enabling security, which would normally be done as well. If the router beacon is turned off, you\'ll need to get the exact network setting from the network admin or another computer on the network in order to set up the wireless connection. 

Return to Diagnostic Chart 

See known good network? This is the easiest, if not always the most convenient troubleshooting step. If you take the laptop to your neighbor\'s house or to the local cafe with free internet access, does the laptop at least see the existence of a known good network through either the OS view or the manufacturer\'s add-on software? If the laptop can\'t see a known good network with the wireless adapter turned on and enabled, the problem is with the laptop and not with the router. Try disabling and enabling the wireless adapter, going through a full OS restart after each change. Try reinstalling the driver for the wireless adapter, and check the Internet for the most recent version of the driver available. The wireless adapter may have failed, but it\'s more likely a software problem. Don\'t rush into downloading a the latest BIOS update for the notebook, especially if the wireless adapter is built in. 

Return to Diagnostic Chart 

Works security off? The inability to connect to a secured wireless network is usually do to the security working properly, as opposed to the way you thought it would work. If the first time you go to connect, the dialog box gets hung up on "Acquiring Network Address" you probably got the encryption key wrong. The first troubleshooting step for failure to connect to a secured wireless network in the home should always be turning off security on the router, rebooting, and seeing if the connection now works. There are several different levels of security available on most wireless routers, some of which aren\'t really though of as security because they don\'t include encryption, such as MAC (Media Access Control) addressing. MAC filters allow you to establish a sort of a white list for network connections, the router won\'t make a connection to any wireless device that doesn\'t know it\'s MAC address (usually included on the router label) , but it will allow any laptop that has the MAC address typed in to connect without further ado. 

WPA (Wi-Fi Protected Access) uses real encryption to encrypt data on the wireless network, making it difficult to nearly impossible for outsiders to decode network traffic without the key, often listed as the WEP (Wired Equivalent Privacy) key. WPA is an improved version of WEP that replaces it, but the terms are sometimes used interchangeably, especially when talking about the key. A lot of confusion arises from the length of the WEP key and the MAC addresses which are often typed improperly on the laptop if in use. It\'s also possible to create an unique encryption key for the router, which the router uses to create keys for your computers. 

While most newer notebooks using Windows XP or Vista allow windows to handle the wireless networking, some earlier laptops with Windows 2000 or previous versions installed may have the wireless networking managed by the software that shipped with the wireless adapter, even if it\'s built in. Some of these third party drivers do not automatically prompt for the password on a security enabled network. You have to go into the properties for the adapter, choose the security type (usually WEP on non-corporate networks), choose the key length (generally 64 bit) and type in the password. For home networks, the default password is usually printed on a label on the bottom of the router. Businesses and more advanced users will usually choose a non-random password to give out, like the name of the establishment or a word in English that can be easily typed by users. In all cases, the software should associate the password with that router and never ask again. Some further confusion may arise if generic router names, like NETGEAR are used to identify the network. The software should still differentiate between them based on the hardware address, but it can make things hard on the user (you). 

Return to Diagnostic Chart 

Works on ethernet port? Can the laptop access the Internet if you connect it directly to the router with an Ethernet cable? This is normally a yellow 100BaseT cable with RJ-45 connectors provided with the router. If you have trouble accessing the router to create or change settings, plugging directly in through an ethernet port or USB (if so equipped) is recommended.The router may come with setup software, but it\'s also common to access the onboard setup software directly through your browser, which doesn\'t require a live Internet connection. You just type the IP address of your router into the address bar, and provide the default password, assuming you haven\'t changed it.
Return to Diagnostic Chart 

Firewall, security blocked? One good reason for a laptop to refuse to see the Internet, even when it\'s plugged directly into the router, is that the security settings on the laptop prevent it from getting onto the web. The variations on what can go wrong here are far too in depth for a hardware troubleshooting flowchart, the best test is to disable all security software, reboot and try to connect. Unfortunately, disabling all security software, including firewalls, isn\'t always easy to do, and may require talking to tech support at the security software company. If this is a laptop that belongs to your employer and has been set up to run on a corporate network, you should talk to your network administrator before taking any radical steps that may make it work at home but prevent it from connecting to the network at work. 

Return to Diagnostic Chart 

Live Internet at router? It\'s not unusual for new DSL subscribers to try to set-up their network as soon as the kit arrives from the phone company, before the phone company has actually set the line up for DSL. It won\'t work. There\'s just no way your laptop can connect to the Internet through your router, wireless or not, if there\'s no connection between the router and the Internet. Most routers come equipped with a status light for the Internet connection. If you cycle the power on the router (if there\'s no switch, you can pull the plug) you should see activity on the Internet LED as the router negotiates for and gains an Internet connection. That doesn\'t absolutely guarantee that the connection is good or that the router is functioning properly, but it probably points to a problem with software settings on your notebooks. 

If LED doesn\'t show an Internet connection, get on the phone with the ISP (usually the telco or cable company), the fault could be with them, it could be with the router, or it could with the land lines. While a land line problem is the responsibility of the ISP, at least, outside your house, it doesn\'t hurt to walk outside and see if there\'s an obvious tree branch lying on the line or something, just so you\'ll know for sure what the problem is. In the case of DSL, if the telephone still works, the line should be OK. With a cable modem, if the TV works, the cable is fine. The ISP should be able to tell from their end whether or not there\'s a problem with their signal without coming to your house. If you\'re a new DSL customer and you live too far from the telephone company switching gear, it\'s possible that DSL won\'t work in your location, even though they delivered the equipment and turned on the service. 

Return to Diagnostic Chart 

Default settings at router? Don\'t trust your memory, restore the router settings to default through the router console accessed by the IP address or accompanying software. Unplugging the router does not reset the defaults, which are stored in non volatile memory. If restoring the router defaults, cycling the power and rebooting the laptop doesn\'t allow you to connect, just go back one step and continue, answering "Yes" to default settings at router.. 

Return to Diagnostic Chart 

Intermittent connection? One of the most frustrating problems to troubleshoot on wireless networks are intermittent connections. Logic seems to dictate that if it works sometimes, it should work all the time, but mismatched hardware or protocols can result in intermittent operation, just like interference, failing hardware, or a poor signal from the ISP. However, the most common reason for intermittent connections is a weak signal that appears to be stronger than it actually is on the reported signal strength. Probably the best indicator of a marginal wireless signal is slow operation, but if your notebook came equipped with utility that truly shows the relative strength of signals and your connection is usually on the borderline, a weak signal is likely the problem. Relocate the laptop closer to the router or move the router to a more central location in the workspace. 

Return to Diagnostic Chart 

All 802.11g? The IEEE standard for wireless ethernet networks is supposed to be backwards compatible, but in practice, not all of the hardware produced lives up to the standard. In fact, when you get into using repeaters, it\'s best to keep to one family or brand of products for all of your wireless broadcast equipment. All newer notebooks have 802.11g wireless capability built in and they will normally work with older routers, but older notebooks and PC adapter cards of the 802.11b generation often have trouble with 802.11g routers. Some routers default to 802.11g unless you specifically choose the backwards compatibility mode.. 

Return to Diagnostic Chart 

Laptop works public network? Once you\'ve done all the troubleshooting you can at home and possibly at a friendly neighbor\'s as well, the last test is to drag the laptop out to a cafe or other location where a wireless network is offered as a draw to customers. If your laptop does connect on the public network, it indicates that the problem is either with you router hardware, your ISP, or the router settings. Even though you\'ve restored the default router settings by this point, make absolutely sure that it doesn\'t require a MAC address that\'s been typed wrong on the laptop. 

If your laptop won\'t connect to the public network, it\'s entirely possible that your wireless adapter is at fault, and you can try a USB or PC card adapter if you\'re willing to have it sticking out of the side of the notebook. But most of the time the problem will be software, either the wireless adapter is, in fact, disabled in some way you haven\'t been able to spot, the driver version isn\'t the best for the adapter model (even if Device Manager appears happy), or there\'s some corruption in the networking settings that you can\'t figure out. If you search the web, there are some free third party utilities you can run to fix the registry, stack and network settings by resting them to defaults, and which report out on the process if they find errors. 

Return to Diagnostic Chart 

Phone, Bluetooth interfere? If your wireless connection slows down or gets flaky when you or somebody else in the household is using a cellular phone, Bluetooth device or other RF emitter, the problem is interference. There is no cure other than trying to increase the distance between the laptop and the interfering device or not using the interfering device when you\'re on the Internet. However, interference is probably a much less common problem than flaky hardware, an intermittent signal from the ISP due to land-line or weather conditions (wind knocking the cables around on the poles), software timeouts or hardware problems. Overheating hardware can lead to intermittent operation, as can loose connections and power interruptions. Keep in mind that a properly functioning laptop has it\'s own built in UPS (Uninterruptible Power Source) in the form of the main battery that should provide seamless operation so you might not even notice if your power grid is suffering from brownouts or even mini-blackouts. The router, however, may be resetting every time the power glitches, and then requiring a minute or two to reestablish the Internet connection each time.',
    'status' => 'active',
    'credentials' => '',
    'add_date' => '1207141367',
    'edit_date' => '0',
    'views' => '0',
    'short_url' => 'troubleshooting_laptop_wireless_connections',
    'activity' => '0',
  ),
  6 => 
  array (
    'id' => '6',
    'cat_id' => '30',
    'user_id' => '6',
    'is_own_article' => '0',
    'author_name' => 'kingargyle',
    'title' => '2005 BMW M5 Performance and Luxury at Its best at Partstrain',
    'summary' => 'he all-new fourth generation M5 pushes that envelope even further with the first V10 engine to power a production sedan. The new V10 produces 507 horsepower and 383 lb-ft of torque by European measure. This new engine is mated to a seven-speed SMG transmission. With this new powertrain, the M5 offers the best power-to-weight ratio in its class.',
    'full_text' => 'The all-new fourth generation M5 pushes that envelope even further with the first V10 engine to power a production sedan. The new V10 produces 507 horsepower and 383 lb-ft of torque by European measure. This new engine is mated to a seven-speed SMG transmission. With this new powertrain, the M5 offers the best power-to-weight ratio in its class. 

This new engine offers 100 horsepower per liter of displacement, pure racecar territory. The 90o V10 is designed for maximum stiffness and minimum vibration. The new V10 features double-VANOS variable valve timing. Each cylinder has its own electronically controlled throttle butterfly. The new MS S65 engine management system uses the most powerful processors currently approved for use in automobiles. 

The new BMW M5 features gear changes that are 20 percent faster with a seven-speed SMG gearbox. Six of these programs can be selected in the sequential manual gearbox mode (S mode). These programs adjust shifting speed and style because, in the S mode, the driver does all the shifting. In the Drive (D mode) the transmission shifts automatically, depending on which of the five programs is selected. 

An impressive drive comfort, The Dynamic Stability Control system in the M5 has been designed to suit its performance. Of course, the DSC can be deactivated at the push of a button. The M5\'s DSC also offers the choice of two driving dynamics programs. One allows DSC to function the way it always has. At the touch of a button, the M Dynamic Mode is engaged which lets DSC facilitate more spirited driving. 

The new M5 has more aerodynamic exterior mirrors, four tailpipes and exclusive wheels. Similar to the latest M3, the M5 features exclusive gills incorporated into the front fenders. The new BMW M5 is equipped with generously sized high performance brakes with perforated compound brake discs. The aluminum twin-piston brake calipers have been designed for minimum unsprung weight and maximum stiffness. 

Parts and accessories for the BMW are available at Parts train. All you have to do is go to http://www.partstrain.com/ShopByVehicle/BMW and choose which ones are compatible for your needs. The advantage of using BMW parts and accessories is that these are especially designed to work well with all BMW cars and therefore you have ensured performance and maximized workability out of these parts and accessories. Parts train also offers car parts, which are continuously being improved upon to ensure quality service and performance. 
About the author:

Jenny McLane is a 36 year old native of Iowa and has a knack for research on cars and anything and everything about it. She works full time as a Market Analyst for one of the leading car parts suppliers in the country today.',
    'status' => 'new',
    'credentials' => '',
    'add_date' => '1207836358',
    'edit_date' => '0',
    'views' => '0',
    'short_url' => '2005_bmw_m5_performance_and_luxury_at_its_best_at_partstrain',
    'activity' => '0',
  ),
);