<?php
return '
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `active` tinyint(1) NOT NULL DEFAULT \'1\',
  `status` char(1) DEFAULT \'a\',
  `name` varchar(24) NOT NULL DEFAULT \'\',
  `pswd` varchar(32) NOT NULL DEFAULT \'\',
  `user_lastvisit` int(10) unsigned NOT NULL DEFAULT \'0\',
  `user_regdate` int(10) unsigned NOT NULL DEFAULT \'0\',
  `group` tinyint(4) DEFAULT NULL,
  `user_posts` mediumint(8) unsigned NOT NULL DEFAULT \'0\',
  `user_timezone` float NOT NULL DEFAULT \'0\',
  `user_dateformat` varchar(14) NOT NULL DEFAULT \'d M Y H:i\',
  `user_rank` int(10) unsigned DEFAULT NULL,
  `user_avatar` varchar(100) DEFAULT NULL,
  `user_email` varchar(255) DEFAULT NULL,
  `user_icq` varchar(15) DEFAULT NULL,
  `user_website` varchar(100) DEFAULT NULL,
  `user_from` varchar(100) DEFAULT NULL,
  `user_sig` text,
  `user_aim` varchar(255) DEFAULT NULL,
  `user_yim` varchar(255) DEFAULT NULL,
  `user_msnm` varchar(255) DEFAULT NULL,
  `user_occ` varchar(100) DEFAULT NULL,
  `user_interests` varchar(255) DEFAULT NULL,
  `user_birth` date NOT NULL,
  `view_sig` tinyint(1) unsigned NOT NULL DEFAULT \'1\',
  `view_images` tinyint(1) unsigned NOT NULL DEFAULT \'1\',
  `view_avatars` tinyint(1) unsigned NOT NULL DEFAULT \'1\',
  `posts_per_page` tinyint(3) unsigned NOT NULL DEFAULT \'0\',
  `topics_per_page` tinyint(3) unsigned NOT NULL DEFAULT \'0\',
  `dst_status` tinyint(1) unsigned NOT NULL DEFAULT \'0\',
  `language` varchar(12) NOT NULL DEFAULT \'0\',
  PRIMARY KEY (`id`)
';
