<?php
return '
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `parent` int(10) unsigned NOT NULL DEFAULT \'0\',
  `forum` int(10) unsigned NOT NULL DEFAULT \'0\',
  `topic` int(10) unsigned NOT NULL DEFAULT \'0\',
  `user_id` int(10) unsigned NOT NULL DEFAULT \'0\',
  `user_name` varchar(64) NOT NULL DEFAULT \'\',
  `created` int(10) unsigned NOT NULL DEFAULT \'0\',
  `status` char(1) NOT NULL DEFAULT \'a\',
  `active` tinyint(1) NOT NULL DEFAULT \'1\',
  `subject` varchar(255) NOT NULL DEFAULT \'\',
  `text` longtext NOT NULL,
  `new_topic` tinyint(1) unsigned NOT NULL DEFAULT \'0\',
  `edit_name` varchar(64) NOT NULL DEFAULT \'\',
  `edit_time` int(10) unsigned NOT NULL DEFAULT \'0\',
  `show_edit_by` tinyint(1) unsigned NOT NULL DEFAULT \'0\',
  `use_sig` tinyint(1) unsigned NOT NULL DEFAULT \'1\',
  `use_emo` tinyint(1) unsigned NOT NULL DEFAULT \'1\',
  `icon_id` smallint(5) unsigned NOT NULL DEFAULT \'0\',
  `poster_ip` varchar(16) NOT NULL DEFAULT \'\',
  `language` varchar(12) NOT NULL DEFAULT \'0\',
  `activity` int(10) unsigned NOT NULL DEFAULT \'0\',
  PRIMARY KEY (`id`),
  KEY `user_id` (`user_id`),
  KEY `status` (`status`),
  KEY `created` (`created`),
  KEY `topic` (`topic`)
';
