<?php
return '
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `forum` int(10) unsigned NOT NULL DEFAULT \'0\',
  `name` varchar(255) NOT NULL DEFAULT \'\',
  `desc` varchar(255) NOT NULL DEFAULT \'\',
  `user_id` int(10) unsigned NOT NULL DEFAULT \'0\',
  `user_name` varchar(255) NOT NULL DEFAULT \'\',
  `created` int(10) unsigned NOT NULL DEFAULT \'0\',
  `status` char(1) NOT NULL DEFAULT \'a\',
  `active` tinyint(1) NOT NULL DEFAULT \'1\',
  `num_views` int(10) unsigned NOT NULL DEFAULT \'0\',
  `num_posts` int(10) unsigned NOT NULL DEFAULT \'0\',
  `first_post_id` int(10) unsigned NOT NULL DEFAULT \'0\',
  `last_post_id` int(10) unsigned NOT NULL DEFAULT \'0\',
  `last_poster_id` int(10) unsigned NOT NULL DEFAULT \'0\',
  `last_poster_name` varchar(64) NOT NULL DEFAULT \'\',
  `last_post_date` int(10) unsigned NOT NULL DEFAULT \'0\',
  `icon_id` tinyint(2) unsigned NOT NULL DEFAULT \'0\',
  `pinned` tinyint(1) NOT NULL DEFAULT \'0\',
  `moved_to` varchar(64) NOT NULL DEFAULT \'\',
  `approved` tinyint(1) NOT NULL DEFAULT \'0\',
  `language` varchar(12) NOT NULL DEFAULT \'0\',
  PRIMARY KEY (`id`),
  KEY `forum` (`forum`,`pinned`)
';
