<?php
	/** @var System tables required data */
	$data = my_array_merge((array)$data, array(
		"admin"	=> array(
			99999 => array(
				"id"			=> 1,
				"first_name"	=> "Default",
				"last_name"		=> "site admin",
				"login"			=> "admin",
				"password"		=> "21232f297a57a5a743894a0e4a801fc3", // md5 for "admin"
				"group"			=> 1,
				"active"		=> 1,
			),
		),
		"admin_groups"	=> array(
			99999 => array(
				"id"	=> 1,
				"name"	=> "Administrator",
				"active"=> 1,
			),
		),
		"admin_modules"	=> array(
			99999 => array(
				"name"	=> "activity_viewer",
				"active"	=> 1,
			),
			array(
				"name"	=> "admin",
				"active"	=> 1,
			),
			array(
				"name"	=> "admin_groups",
				"active"	=> 1,
			),
			array(
				"name"	=> "admin_home",
				"active"	=> 1,
			),
			array(
				"name"	=> "admin_messages",
				"active"	=> 1,
			),
			array(
				"name"	=> "admin_modules",
				"active"	=> 1,
			),
			array(
				"name"	=> "backup_manager",
				"active"	=> 1,
			),
			array(
				"name"	=> "blocks",
				"active"	=> 1,
			),
			array(
				"name"	=> "category_editor",
				"active"	=> 1,
			),
			array(
				"name"	=> "check_multi_accounts",
				"active"	=> 1,
			),
			array(
				"name"	=> "conf_editor",
				"active"	=> 1,
			),
			array(
				"name"	=> "confirm_reg",
				"active"	=> 1,
			),
			array(
				"name"	=> "custom_bbcode_editor",
				"active"	=> 1,
			),
			array(
				"name"	=> "custom_replace",
				"active"	=> 1,
			),
			array(
				"name"	=> "db_manager",
				"active"	=> 1,
			),
			array(
				"name"	=> "db_parser",
				"active"	=> 1,
			),
			array(
				"name"	=> "design_manager",
				"active"	=> 1,
			),
			array(
				"name"	=> "dev",
				"active"	=> 1,
			),
			array(
				"name"	=> "file_manager",
				"active"	=> 1,
			),
			array(
				"name"	=> "forum",
				"active"	=> 1,
			),
			array(
				"name"	=> "help_tickets",
				"active"	=> 1,
			),
			array(
				"name"	=> "home_page_editor",
				"active"	=> 1,
			),
			array(
				"name"	=> "locale_editor",
				"active"	=> 1,
			),
			array(
				"name"	=> "log_auth_fails_viewer",
				"active"	=> 1,
			),
			array(
				"name"	=> "log_auth_view",
				"active"	=> 1,
			),
			array(
				"name"	=> "log_core_errors_viewer",
				"active"	=> 1,
			),
			array(
				"name"	=> "log_emails_viewer",
				"active"	=> 1,
			),
			array(
				"name"	=> "log_exec_analyser",
				"active"	=> 1,
			),
			array(
				"name"	=> "log_image_resize_viewer",
				"active"	=> 1,
			),
			array(
				"name"	=> "log_user_errors_viewer",
				"active"	=> 1,
			),
			array(
				"name"	=> "manage_articles",
				"active"	=> 1,
			),
			array(
				"name"	=> "manage_blogs",
				"active"	=> 1,
			),
			array(
				"name"	=> "manage_comments",
				"active"	=> 1,
			),
			array(
				"name"	=> "manage_faq",
				"active"	=> 1,
			),
			array(
				"name"	=> "manage_news",
				"active"	=> 1,
			),
			array(
				"name"	=> "manage_reput",
				"active"	=> 1,
			),
			array(
				"name"	=> "manage_site_links",
				"active"	=> 1,
			),
			array(
				"name"	=> "members",
				"active"	=> 1,
			),
			array(
				"name"	=> "menus_editor",
				"active"	=> 1,
			),
			array(
				"name"	=> "online_users_manager",
				"active"	=> 1,
			),
			array(
				"name"	=> "output_cache_editor",
				"active"	=> 1,
			),
			array(
				"name"	=> "polls_manager",
				"active"	=> 1,
			),
			array(
				"name"	=> "project_packer",
				"active"	=> 1,
			),
			array(
				"name"	=> "revisions_manager",
				"active"	=> 1,
			),
			array(
				"name"	=> "se_keywords_manager",
				"active"	=> 1,
			),
			array(
				"name"	=> "settings",
				"active"	=> 1,
			),
			array(
				"name"	=> "site_links",
				"active"	=> 1,
			),
			array(
				"name"	=> "site_nav_bar",
				"active"	=> 1,
			),
			array(
				"name"	=> "static_pages",
				"active"	=> 1,
			),
			array(
				"name"	=> "tasks_planner",
				"active"	=> 1,
			),
			array(
				"name"	=> "template_editor",
				"active"	=> 1,
			),
			array(
				"name"	=> "user_dynamic_info",
				"active"	=> 1,
			),
			array(
				"name"	=> "user_groups",
				"active"	=> 1,
			),
			array(
				"name"	=> "user_info",
				"active"	=> 1,
			),
			array(
				"name"	=> "user_modules",
				"active"	=> 1,
			),
			array(
				"name"	=> "widgets_editor",
				"active"	=> 1,
			),
		),
		"blocks"	=> array(
			99999 => array(
				"id"			=> 1,
				"name"			=> "center_area",
				"type"			=> "user",
				"method_name"	=> "main.tasks",
				"active"		=> 1,
			),
			array(
				"id"			=> 2,
				"name"			=> "left_area",
				"type"			=> "user",
				"method_name"	=> "",
				"active"		=> 1,
			),
			array(
				"id"			=> 3,
				"name"			=> "right_area",
				"type"			=> "user",
				"method_name"	=> "",
				"active"		=> 1,
			),
			array(
				"id"			=> 4,
				"name"			=> "center_area",
				"type"			=> "admin",
				"method_name"	=> "main.tasks",
				"active"		=> 1,
			),
		),
		"block_rules"	=> array(
			99999 => array(
				"block_id"		=> 1,
				"rule_type"		=> "ALLOW",
				"user_groups"	=> "",
				"methods"		=> "",
				"active"		=> 1,
				"order"			=> 1,
			),
			array(
				"block_id"		=> 4,
				"rule_type"		=> "ALLOW",
				"user_groups"	=> "1",
				"methods"		=> "",
				"active"		=> 1,
				"order"			=> 1,
			),
			array(
				"block_id"		=> 2,
				"rule_type"		=> "ALLOW",
				"user_groups"	=> "",
				"methods"		=> "",
				"active"		=> 1,
				"order"			=> 0,
			),
			array(
				"block_id"		=> 3,
				"rule_type"		=> "ALLOW",
				"user_groups"	=> "",
				"methods"		=> "blog.show_posts,blog.show_single_post,gallery.show_gallery,gallery.show_medium_size,gallery.view_folder,user_profile.show",
				"active"		=> 1,
				"order"			=> 1,
			),
			array(
				"block_id"		=> 3,
				"rule_type"		=> "DENY",
				"user_groups"	=> "",
				"methods"		=> "blog.show,blog.show_all_blogs,blog.add_post,blog.edit_post,gallery.show,gallery.add_photo,gallery.edit_photo",
				"active"		=> 1,
				"order"			=> 2,
			),
		),
		"custom_replace_tags"	=> array(
			99999 => array(
				"id"				=> "1",
				"name"				=> "page_title",
				"desc"				=> "<title> tag contents",
				"pattern_find"		=> "#(<title>)(.*?)(</title>)#",
				"pattern_replace"	=> "\$1%%TAG%%\$3",
				"active"			=> "0",
			),
			array(
				"id"				=> "2",
				"name"				=> "desc",
				"desc"				=> "Meta description",
				"pattern_find"		=> "#(<meta name=[\"']{0,1}description[\"']{0,1}\s+content=[\"']{0,1})([^\"']*?)([\"']{0,1}[\s\/]*?>)#",
				"pattern_replace"	=> "\$1%%TAG%%\$3",
				"active"			=> "0",
			),
			array(
				"id"				=> "3",
				"name"				=> "keywords",
				"desc"				=> "Meta keywords",
				"pattern_find"		=> "#(<meta name=[\"']{0,1}keywords[\"']{0,1}\s+content=[\"']{0,1})([^\"']*?)([\"']{0,1}[\s\/]*?>)#",
				"pattern_replace"	=> "\$1%%TAG%%\$3",
				"active"			=> "0",
			),
		),
		"locale_langs"	=> array(
			99999 => array(
				"locale"	=> "en",
				"name"		=> "English",
				"charset"	=> "utf-8",
				"active"	=> 1,
				"is_default"=> 1,
			),
		),
		"menus"	=> array(
			99999 => array(
				"id"	=> 1,
				"name"	=> "admin_left_menu",
				"type"	=> "admin",
				"active"=> 1,
			),
			array(
				"id"	=> 2,
				"name"	=> "user_main_menu",
				"type"	=> "user",
				"active"=> 1,
			),
			array(
				"id"	=> 3,
				"name"	=> "admin_top_menu",
				"type"	=> "admin",
				"active"=> 1,
			),
			array(
				"id"		=> 4,
				"name"		=> "user_side_menu",
				"type"		=> "user",
				"active"	=> 1,
				"stpl_name"	=> "system/slide_menu",
			),
			array(
				"id"	=> 5,
				"name"	=> "admin_home_menu",
				"type"	=> "admin",
				"active"=> 1,
			),
		),
		"menu_items"	=> array(
			99999 => array(
				"id"		=> 1001,
				"menu_id"	=> 1,
				"parent_id"	=> 0,
				"name"		=> "General Settings",
				"location"	=> "",
				"type_id"	=> 3,
				"active"	=> 1,
			),
			array(
				"id"		=> 1002,
				"menu_id"	=> 1,
				"parent_id"	=> 0,
				"name"		=> "Tools",
				"location"	=> "",
				"type_id"	=> 3,
				"active"	=> 1,
			),
			array(
				"id"		=> 1003,
				"menu_id"	=> 1,
				"parent_id"	=> 0,
				"name"		=> "Localization",
				"location"	=> "",
				"type_id"	=> 3,
				"active"	=> 1,
			),
			array(
				"id"		=> 1004,
				"menu_id"	=> 1,
				"parent_id"	=> 0,
				"name"		=> "Administration",
				"location"	=> "",
				"type_id"	=> 3,
				"active"	=> 1,
			),
			array(
				"id"		=> 1005,
				"menu_id"	=> 1,
				"parent_id"	=> 0,
				"name"		=> "Modules",
				"location"	=> "",
				"type_id"	=> 3,
				"active"	=> 1,
			),
			array(
				"id"		=> 1006,
				"menu_id"	=> 1,
				"parent_id"	=> 0,
				"name"		=> "Logs",
				"location"	=> "",
				"type_id"	=> 3,
				"active"	=> 1,
			),
			array(
				"id"		=> 1007,
				"menu_id"	=> 1,
				"parent_id"	=> 0,
				"name"		=> "Users",
				"location"	=> "",
				"type_id"	=> 3,
				"active"	=> 1,
			),
			array(
				"id"		=> 1008,
				"menu_id"	=> 1,
				"parent_id"	=> 0,
				"name"		=> "Manage Content",
				"location"	=> "",
				"type_id"	=> 3,
				"active"	=> 1,
			),
			array(
				"id"		=> 1009,
				"menu_id"	=> 1,
				"parent_id"	=> 1001,
				"name"		=> "Clear Core Cache",
				"location"	=> "object=admin_home&action=clear_core_cache",
				"type_id"	=> 1,
				"active"	=> 1,
			),
			array(
				"id"		=> 1010,
				"menu_id"	=> 1,
				"parent_id"	=> 1001,
				"name"		=> "Clear Output Pages Cache",
				"location"	=> "object=admin_home&action=clear_output_cache",
				"type_id"	=> 1,
				"active"	=> 1,
			),
			array(
				"id"		=> 1011,
				"menu_id"	=> 1,
				"parent_id"	=> 1001,
				"name"		=> "Change Settings",
				"location"	=> "object=settings",
				"type_id"	=> 1,
				"active"	=> 1,
			),
			array(
				"id"		=> 1012,
				"menu_id"	=> 1,
				"parent_id"	=> 1002,
				"name"		=> "File Manager",
				"location"	=> "object=file_manager",
				"type_id"	=> 1,
				"active"	=> 1,
			),
			array(
				"id"		=> 1325,
				"menu_id"	=> 1,
				"parent_id"	=> 1007,
				"name"		=> "Help Tickets",
				"location"	=> "object=help_tickets",
				"type_id"	=> 1,
				"active"	=> 1,
			),
			array(
				"id"		=> 1013,
				"menu_id"	=> 1,
				"parent_id"	=> 1007,
				"name"		=> "User dynamic info",
				"location"	=> "object=user_dynamic_info",
				"type_id"	=> 1,
				"active"	=> 1,
			),
			array(
				"id"		=> 1014,
				"menu_id"	=> 1,
				"parent_id"	=> 1002,
				"name"		=> "Database Manager",
				"location"	=> "object=db_manager",
				"type_id"	=> 1,
				"active"	=> 1,
			),
			array(
				"id"		=> 1015,
				"menu_id"	=> 1,
				"parent_id"	=> 1002,
				"name"		=> "Task Manager",
				"location"	=> "object=task_planner",
				"type_id"	=> 1,
				"active"	=> 1,
			),
			array(
				"id"		=> 1016,
				"menu_id"	=> 1,
				"parent_id"	=> 1002,
				"name"		=> "Menus Manager",
				"location"	=> "object=menus_editor",
				"type_id"	=> 1,
				"active"	=> 1,
			),
			array(
				"id"		=> 1017,
				"menu_id"	=> 1,
				"parent_id"	=> 1002,
				"name"		=> "Categories Editor",
				"location"	=> "object=category_editor",
				"type_id"	=> 1,
				"active"	=> 1,
			),
			array(
				"id"		=> 1018,
				"menu_id"	=> 1,
				"parent_id"	=> 1002,
				"name"		=> "Blocks Editor",
				"location"	=> "object=blocks",
				"type_id"	=> 1,
				"active"	=> 1,
			),
			array(
				"id"		=> 1019,
				"menu_id"	=> 1,
				"parent_id"	=> 1002,
				"name"		=> "Custom Replace Editor",
				"location"	=> "object=custom_replace",
				"type_id"	=> 1,
				"active"	=> 1,
			),
			array(
				"id"		=> 1020,
				"menu_id"	=> 1,
				"parent_id"	=> 1003,
				"name"		=> "Locale Editor",
				"location"	=> "object=locale_editor",
				"type_id"	=> 1,
				"active"	=> 1,
			),
			array(
				"id"		=> 1021,
				"menu_id"	=> 1,
				"parent_id"	=> 1003,
				"name"		=> "Tips Editor",
				"location"	=> "object=db_parser&table=tips",
				"type_id"	=> 1,
				"active"	=> 1,
			),
			array(
				"id"		=> 1022,
				"menu_id"	=> 1,
				"parent_id"	=> 1003,
				"name"		=> "Template Editor",
				"location"	=> "object=template_editor",
				"type_id"	=> 1,
				"active"	=> 1,
			),
			array(
				"id"		=> 1023,
				"menu_id"	=> 1,
				"parent_id"	=> 1004,
				"name"		=> "Admin Groups",
				"location"	=> "object=admin_groups",
				"type_id"	=> 1,
				"active"	=> 1,
			),
			array(
				"id"		=> 1024,
				"menu_id"	=> 1,
				"parent_id"	=> 1004,
				"name"		=> "Admin Management",
				"location"	=> "object=admin",
				"type_id"	=> 1,
				"active"	=> 1,
			),
			array(
				"id"		=> 1025,
				"menu_id"	=> 1,
				"parent_id"	=> 1005,
				"name"		=> "User Modules Manager",
				"location"	=> "object=user_modules",
				"type_id"	=> 1,
				"active"	=> 1,
			),
			array(
				"id"		=> 1026,
				"menu_id"	=> 1,
				"parent_id"	=> 1005,
				"name"		=> "Admin Modules Manager",
				"location"	=> "object=admin_modules",
				"type_id"	=> 1,
				"active"	=> 1,
			),
			array(
				"id"		=> 1027,
				"menu_id"	=> 1,
				"parent_id"	=> 1006,
				"name"		=> "Execution Log Analyzer",
				"location"	=> "object=log_exec_analyser",
				"type_id"	=> 1,
				"active"	=> 1,
			),
			array(
				"id"		=> 1028,
				"menu_id"	=> 1,
				"parent_id"	=> 1006,
				"name"		=> "Core Errors",
				"location"	=> "object=log_core_errors_viewer",
				"type_id"	=> 1,
				"active"	=> 1,
			),
			array(
				"id"		=> 1029,
				"menu_id"	=> 1,
				"parent_id"	=> 1006,
				"name"		=> "User Errors",
				"location"	=> "object=log_user_errors_viewer",
				"type_id"	=> 1,
				"active"	=> 1,
			),
			array(
				"id"		=> 1030,
				"menu_id"	=> 1,
				"parent_id"	=> 1006,
				"name"		=> "Emails",
				"location"	=> "object=log_emails_viewer",
				"type_id"	=> 1,
				"active"	=> 1,
			),
			array(
				"id"		=> 1031,
				"menu_id"	=> 1,
				"parent_id"	=> 1006,
				"name"		=> "Image Resize",
				"location"	=> "object=log_image_resize_viewer",
				"type_id"	=> 1,
				"active"	=> 1,
			),
			array(
				"id"		=> 1032,
				"menu_id"	=> 1,
				"parent_id"	=> 1006,
				"name"		=> "Search Engine Keywords",
				"location"	=> "object=se_keywords_manager",
				"type_id"	=> 1,
				"active"	=> 1,
			),
			array(
				"id"		=> 1033,
				"menu_id"	=> 1,
				"parent_id"	=> 1006,
				"name"		=> "Authentification fails",
				"location"	=> "object=log_auth_fails_viewer",
				"type_id"	=> 1,
				"active"	=> 1,
			),
			array(
				"id"		=> 1034,
				"menu_id"	=> 1,
				"parent_id"	=> 1006,
				"name"		=> "Webshell Actions",
				"location"	=> "object=log_webshell_actions_viewer",
				"type_id"	=> 1,
				"active"	=> 1,
			),
			array(
				"id"		=> 1035,
				"menu_id"	=> 1,
				"parent_id"	=> 1006,
				"name"		=> "SSH actions",
				"location"	=> "object=log_ssh_viewer",
				"type_id"	=> 1,
				"active"	=> 1,
			),
			array(
				"id"		=> 1036,
				"menu_id"	=> 1,
				"parent_id"	=> 1007,
				"name"		=> "User Groups",
				"location"	=> "object=user_groups",
				"type_id"	=> 1,
				"active"	=> 1,
			),
			array(
				"id"		=> 1037,
				"menu_id"	=> 1,
				"parent_id"	=> 1007,
				"name"		=> "User Management",
				"location"	=> "object=members",
				"type_id"	=> 1,
				"active"	=> 1,
			),
			array(
				"id"		=> 1038,
				"menu_id"	=> 1,
				"parent_id"	=> 1007,
				"name"		=> "Online Users",
				"location"	=> "object=online_users_manager",
				"type_id"	=> 1,
				"active"	=> 1,
			),
			array(
				"id"		=> 1039,
				"menu_id"	=> 1,
				"parent_id"	=> 1007,
				"name"		=> "Registration Confirmation",
				"location"	=> "object=confirm_reg",
				"type_id"	=> 1,
				"active"	=> 1,
			),
			array(
				"id"		=> 1040,
				"menu_id"	=> 1,
				"parent_id"	=> 1008,
				"name"		=> "Static Pages",
				"location"	=> "object=static_pages",
				"type_id"	=> 1,
				"active"	=> 1,
			),
			array(
				"id"		=> 1041,
				"menu_id"	=> 1,
				"parent_id"	=> 1008,
				"name"		=> "Forum",
				"location"	=> "object=forum",
				"type_id"	=> 1,
				"active"	=> 1,
			),
			array(
				"id"		=> 1042,
				"menu_id"	=> 1,
				"parent_id"	=> 1008,
				"name"		=> "Gallery",
				"location"	=> "object=gallery",
				"type_id"	=> 1,
				"active"	=> 1,
			),
			array(
				"id"		=> 1043,
				"menu_id"	=> 1,
				"parent_id"	=> 1008,
				"name"		=> "Blog",
				"location"	=> "object=manage_blogs",
				"type_id"	=> 1,
				"active"	=> 1,
			),
			array(
				"id"		=> 1044,
				"menu_id"	=> 1,
				"parent_id"	=> 1008,
				"name"		=> "Articles",
				"location"	=> "object=manage_articles",
				"type_id"	=> 1,
				"active"	=> 1,
			),
			array(
				"id"		=> 1045,
				"menu_id"	=> 1,
				"parent_id"	=> 1008,
				"name"		=> "News",
				"location"	=> "object=manage_news",
				"type_id"	=> 1,
				"active"	=> 1,
			),
			array(
				"id"		=> 1046,
				"menu_id"	=> 1,
				"parent_id"	=> 1008,
				"name"		=> "Comments",
				"location"	=> "object=manage_comments",
				"type_id"	=> 1,
				"active"	=> 1,
			),
 			array(
				"id"		=> 1352,
				"menu_id"	=> 1,
				"parent_id"	=> 1346,
				"name"		=> "Email alerts logs",
				"location"	=> "object=log_alert_emails",
				"type_id"	=> 1,
				"active"	=> 1,
			),
			array(
				"id"		=> 1323,
				"menu_id"	=> 1,
				"parent_id"	=> 1270,
				"name"		=> "Re-build packed code",
				"location"	=> "object=admin_home&action=rebuild_packed_code",
				"type_id"	=> 1,
				"active"	=> 1,
			),
			array(
				"id"		=> 1314,
				"menu_id"	=> 1,
				"parent_id"	=> 1312,
				"name"		=> "Forum",
				"location"	=> "object=forum",
				"type_id"	=> 1,
				"active"	=> 1,
			),
			array(
				"id"		=> 1315,
				"menu_id"	=> 1,
				"parent_id"	=> 1312,
				"name"		=> "Gallery",
				"location"	=> "object=gallery",
				"type_id"	=> 1,
				"active"	=> 1,
			),
			array(
				"id"		=> 1316,
				"menu_id"	=> 1,
				"parent_id"	=> 1312,
				"name"		=> "Blog",
				"location"	=> "object=manage_blogs",
				"type_id"	=> 1,
				"active"	=> 1,
			),
			array(
				"id"		=> 1317,
				"menu_id"	=> 1,
				"parent_id"	=> 1312,
				"name"		=> "Articles",
				"location"	=> "object=manage_articles",
				"type_id"	=> 1,
				"active"	=> 1,
			),
			array(
				"id"		=> 1318,
				"menu_id"	=> 1,
				"parent_id"	=> 1312,
				"name"		=> "News",
				"location"	=> "object=manage_news",
				"type_id"	=> 1,
				"active"	=> 1,
			),
			array(
				"id"		=> 1319,
				"menu_id"	=> 1,
				"parent_id"	=> 1312,
				"name"		=> "Comments",
				"location"	=> "object=manage_comments",
				"type_id"	=> 1,
				"active"	=> 1,
			),
			array(
				"id"		=> 1324,
				"menu_id"	=> 1,
				"parent_id"	=> 0,
				"name"		=> "My Account",
				"location"	=> "",
				"type_id"	=> 3,
				"active"	=> 1,
			),
			array(
				"id"		=> 1326,
				"menu_id"	=> 1,
				"parent_id"	=> 1324,
				"name"		=> "Edit Account Info",
				"location"	=> "object=admin_home&action=edit_account",
				"type_id"	=> 1,
				"active"	=> 1,
			),
			array(
				"id"		=> 1327,
				"menu_id"	=> 1,
				"parent_id"	=> 1324,
				"name"		=> "Logout",
				"location"	=> "task=logout",
				"type_id"	=> 1,
				"active"	=> 1,
			),
			array(
				"id"		=> 1328,
				"menu_id"	=> 1,
				"parent_id"	=> 1312,
				"name"		=> "Widgets",
				"location"	=> "object=widgets_editor",
				"type_id"	=> 1,
				"active"	=> 1,
			),
			array(
				"id"		=> 1313,
				"menu_id"	=> 1,
				"parent_id"	=> 1312,
				"name"		=> "Static Pages",
				"location"	=> "object=static_pages",
				"type_id"	=> 1,
				"active"	=> 1,
			),
			array(
				"id"		=> 1273,
				"menu_id"	=> 1,
				"parent_id"	=> 1270,
				"name"		=> "Configuration Editor",
				"location"	=> "object=conf_editor",
				"type_id"	=> 1,
				"active"	=> 1,
			),
			array(
				"id"		=> 1272,
				"menu_id"	=> 1,
				"parent_id"	=> 1270,
				"name"		=> "Clear Output Pages Cache",
				"location"	=> "object=admin_home&action=clear_output_cache",
				"type_id"	=> 1,
				"active"	=> 1,
			),
			array(
				"id"		=> 1271,
				"menu_id"	=> 1,
				"parent_id"	=> 1270,
				"name"		=> "Clear Core Cache",
				"location"	=> "object=admin_home&action=clear_core_cache",
				"type_id"	=> 1,
				"active"	=> 1,
			),
			array(
				"id"		=> 1270,
				"menu_id"	=> 1,
				"parent_id"	=> 0,
				"name"		=> "Settings",
				"location"	=> "",
				"type_id"	=> 3,
				"active"	=> 1,
			),
			array(
				"id"		=> 1405,
				"menu_id"	=> 5,
				"parent_id"	=> 0,
				"name"		=> "Settings",
				"location"	=> "",
				"type_id"	=> 3,
				"order"		=> "1",
				"active"	=> 1,
			),
			array(
				"id"		=> 1274,
				"menu_id"	=> 5,
				"parent_id"	=> 0,
				"name"		=> "Tools",
				"location"	=> "",
				"type_id"	=> 3,
				"order"		=> "2",
				"active"	=> 1,
			),
			array(
				"id"		=> 1286,
				"menu_id"	=> 5,
				"parent_id"	=> 0,
				"name"		=> "Localization",
				"location"	=> "",
				"type_id"	=> 3,
				"order"		=> "3",
				"active"	=> 1,
			),
			array(
				"id"		=> 1290,
				"menu_id"	=> 5,
				"parent_id"	=> 0,
				"name"		=> "Administration",
				"location"	=> "",
				"type_id"	=> 3,
				"order"		=> "4",
				"active"	=> 1,
			),
			array(
				"id"		=> 1293,
				"menu_id"	=> 5,
				"parent_id"	=> 0,
				"name"		=> "Modules",
				"location"	=> "",
				"type_id"	=> 3,
				"order"		=> "5",
				"active"	=> 1,
			),
			array(
				"id"		=> 1396,
				"menu_id"	=> 5,
				"parent_id"	=> 0,
				"name"		=> "My Account",
				"location"	=> "",
				"type_id"	=> 3,
				"order"		=> "6",
				"active"	=> 1,
			),
			array(
				"id"		=> 1296,
				"menu_id"	=> 5,
				"parent_id"	=> 0,
				"name"		=> "Logs",
				"location"	=> "",
				"type_id"	=> 3,
				"order"		=> "7",
				"active"	=> 1,
			),
		
			array(
				"id"		=> 1306,
				"menu_id"	=> 5,
				"parent_id"	=> 0,
				"name"		=> "Users",
				"location"	=> "",
				"type_id"	=> 3,
				"order"		=> "8",
				"active"	=> 1,
			),
			array(
				"id"		=> 1312,
				"menu_id"	=> 5,
				"parent_id"	=> 0,
				"name"		=> "Content",
				"location"	=> "",
				"type_id"	=> 3,
				"order"		=> "9",
				"active"	=> 1,
			),
			array(
				"id"		=> 1353,
				"menu_id"	=> 5,
				"parent_id"	=> 1274,
				"name"		=> "File Manager",
				"location"	=> "object=file_manager",
				"type_id"	=> 1,
				"order"		=> "",
				"active"	=> 1,
			),
			array(
				"id"		=> 1408,
				"menu_id"	=> 5,
				"parent_id"	=> 1306,
				"name"		=> "Help Tickets",
				"location"	=> "object=help_tickets",
				"type_id"	=> 1,
				"order"		=> "",
				"active"	=> 1,
			),
			array(
				"id"		=> 1354,
				"menu_id"	=> 5,
				"parent_id"	=> 1306,
				"name"		=> "User dynamic info",
				"location"	=> "object=user_dynamic_info",
				"type_id"	=> 1,
				"order"		=> "",
				"active"	=> 1,
			),
			array(
				"id"		=>1355,
				"menu_id"	=> 5,
				"parent_id"	=> 1274,
				"name"		=> "Database Manager",
				"location"	=> "object=db_manager",
				"type_id"	=> 1,
				"order"		=> "",
				"active"	=> 1,
			),
			array(
				"id"		=> 1356,
				"menu_id"	=> 5,
				"parent_id"	=> 1274,
				"name"		=> "Task Manager",
				"location"	=> "object=task_planner",
				"type_id"	=> 1,
				"order"		=> "",
				"active"	=> 1,
			),
			array(
				"id"		=> 1357,
				"menu_id"	=> 5,
				"parent_id"	=> 1274,
				"name"		=> "Menus Manager",
				"location"	=> "object=menus_editor",
				"type_id"	=> 1,
				"order"		=> "",
				"active"	=> 1,
			),
			array(
				"id"		=> 1358,
				"menu_id"	=> 5,
				"parent_id"	=> 1274,
				"name"		=> "Categories Editor",
				"location"	=> "object=category_editor",
				"type_id"	=> 1,
				"order"		=> "",
				"active"	=> 1,
			),
			array(
				"id"		=> 1359,
				"menu_id"	=> 5,
				"parent_id"	=> 1274,
				"name"		=> "Blocks Editor",
				"location"	=> "object=blocks",
				"type_id"	=> 1,
				"order"		=> "",
				"active"	=> 1,
			),
			array(
				"id"		=> 1360,
				"menu_id"	=> 5,
				"parent_id"	=> 1274,
				"name"		=> "Custom Replace Editor",
				"location"	=> "object=custom_replace",
				"type_id"	=> 1,
				"order"		=> "",
				"active"	=> 1,
			),
			array(
				"id"		=> 1361,
				"menu_id"	=> 5,
				"parent_id"	=> 1286,
				"name"		=> "Locale Editor",
				"location"	=> "object=locale_editor",
				"type_id"	=> 1,
				"order"		=> "",
				"active"	=> 1,
			),
			array(
				"id"		=> 1362,
				"menu_id"	=> 5,
				"parent_id"	=> 1286,
				"name"		=> "Tips Editor",
				"location"	=> "object=db_parser&table=tips",
				"type_id"	=> 1,
				"order"		=> "",
				"active"	=> 1,
			),
			array(
				"id"		=> 1363,
				"menu_id"	=> 5,
				"parent_id"	=> 1286,
				"name"		=> "Template Editor",
				"location"	=> "object=template_editor",
				"type_id"	=> 1,
				"order"		=> "",
				"active"	=> 1,
			),
			array(
				"id"		=> 1364,
				"menu_id"	=> 5,
				"parent_id"	=> 1290,
				"name"		=> "Admin Groups",
				"location"	=> "object=admin_groups",
				"type_id"	=> 1,
				"order"		=> "",
				"active"	=> 1,
			),
			array(
				"id"		=> 1365,
				"menu_id"	=> 5,
				"parent_id"	=> 1290,
				"name"		=> "Admin Management",
				"location"	=> "object=admin",
				"type_id"	=> 1,
				"order"		=> "",
				"active"	=> 1,
			),
			array(
				"id"		=> 1366,
				"menu_id"	=> 5,
				"parent_id"	=> 1293,
				"name"		=> "User Modules Manager",
				"location"	=> "object=user_modules",
				"type_id"	=> 1,
				"order"		=> "",
				"active"	=> 1,
			),
			array(
				"id"		=> 1367,
				"menu_id"	=> 5,
				"parent_id"	=> 1293,
				"name"		=> "Admin Modules Manager",
				"location"	=> "object=admin_modules",
				"type_id"	=> 1,
				"order"		=> "",
				"active"	=> 1,
			),
			array(
				"id"		=> 1368,
				"menu_id"	=> 5,
				"parent_id"	=> 1296,
				"name"		=> "Execution Log Analyzer",
				"location"	=> "object=log_exec_analyser",
				"type_id"	=> 1,
				"order"		=> "",
				"active"	=> 1,
			),
			array(
				"id"		=> 1369,
				"menu_id"	=> 5,
				"parent_id"	=> 1296,
				"name"		=> "Core Errors",
				"location"	=> "object=log_core_errors_viewer",
				"type_id"	=> 1,
				"order"		=> "",
				"active"	=> 1,
			),
			array(
				"id"		=> 1370,
				"menu_id"	=> 5,
				"parent_id"	=> 1296,
				"name"		=> "User Errors",
				"location"	=> "object=log_user_errors_viewer",
				"type_id"	=> 1,
				"order"		=> "",
				"active"	=> 1,
			),
			array(
				"id"		=> 1371,
				"menu_id"	=> 5,
				"parent_id"	=> 1296,
				"name"		=> "Emails",
				"location"	=> "object=log_emails_viewer",
				"type_id"	=> 1,
				"order"		=> "",
				"active"	=> 1,
			),
			array(
				"id"		=> 1372,
				"menu_id"	=> 5,
				"parent_id"	=> 1296,
				"name"		=> "Image Resize",
				"location"	=> "object=log_image_resize_viewer",
				"type_id"	=> 1,
				"order"		=> "",
				"active"	=> 1,
			),
			array(
				"id"		=> 1373,
				"menu_id"	=> 5,
				"parent_id"	=> 1296,
				"name"		=> "Search Engine Keywords",
				"location"	=> "object=se_keywords_manager",
				"type_id"	=> 1,
				"order"		=> "",
				"active"	=> 1,
			),
			array(
				"id"		=> 1374,
				"menu_id"	=> 5,
				"parent_id"	=> 1296,
				"name"		=> "Authentification fails",
				"location"	=> "object=log_auth_fails_viewer",
				"type_id"	=> 1,
				"order"		=> "",
				"active"	=> 1,
			),
			array(
				"id"		=> 1375,
				"menu_id"	=> 5,
				"parent_id"	=> 1296,
				"name"		=> "Webshell Actions",
				"location"	=> "object=log_webshell_actions_viewer",
				"type_id"	=> 1,
				"order"		=> "",
				"active"	=> 1,
			),
			array(
				"id"		=> 1376,
				"menu_id"	=> 5,
				"parent_id"	=> 1296,
				"name"		=> "SSH actions",
				"location"	=> "object=log_ssh_viewer",
				"type_id"	=> 1,
				"order"		=> "",
				"active"	=> 1,
			),
			array(
				"id"		=> 1377,
				"menu_id"	=> 5,
				"parent_id"	=> 1306,
				"name"		=> "User Groups",
				"location"	=> "object=user_groups",
				"type_id"	=> 1,
				"order"		=> "",
				"active"	=> 1,
			),
			array(
				"id"		=> 1378,
				"menu_id"	=> 5,
				"parent_id"	=> 1306,
				"name"		=> "User Management",
				"location"	=> "object=members",
				"type_id"	=> 1,
				"order"		=> "",
				"active"	=> 1,
			),
			array(
				"id"		=> 1379,
				"menu_id"	=> 5,
				"parent_id"	=> 1306,
				"name"		=> "Online Users",
				"location"	=> "object=online_users_manager",
				"type_id"	=> 1,
				"order"		=> "",
				"active"	=> 1,
			),
			array(
				"id"		=> 1380,
				"menu_id"	=> 5,
				"parent_id"	=> 1306,
				"name"		=> "Registration Confirmation",
				"location"	=> "object=confirm_reg",
				"type_id"	=> 1,
				"order"		=> "",
				"active"	=> 1,
			),
			array(
				"id"		=> 1381,
				"menu_id"	=> 5,
				"parent_id"	=> 1312,
				"name"		=> "Static Pages",
				"location"	=> "object=static_pages",
				"type_id"	=> 1,
				"order"		=> "",
				"active"	=> 1,
			),
			array(
				"id"		=> 1382,
				"menu_id"	=> 5,
				"parent_id"	=> 1312,
				"name"		=> "Forum",
				"location"	=> "object=forum",
				"type_id"	=> 1,
				"order"		=> "",
				"active"	=> 1,
			),
			array(
				"id"		=> 1383,
				"menu_id"	=> 5,
				"parent_id"	=> 1312,
				"name"		=> "Gallery",
				"location"	=> "object=gallery",
				"type_id"	=> 1,
				"order"		=> "",
				"active"	=> 1,
			),
			array(
				"id"		=> 1384,
				"menu_id"	=> 5,
				"parent_id"	=> 1312,
				"name"		=> "Blog",
				"location"	=> "object=manage_blogs",
				"type_id"	=> 1,
				"order"		=> "",
				"active"	=> 1,
			),
			array(
				"id"		=> 1385,
				"menu_id"	=> 5,
				"parent_id"	=> 1312,
				"name"		=> "Articles",
				"location"	=> "object=manage_articles",
				"type_id"	=> 1,
				"order"		=> "",
				"active"	=> 1,
			),
			array(
				"id"		=> 1386,
				"menu_id"	=> 5,
				"parent_id"	=> 1312,
				"name"		=> "News",
				"location"	=> "object=manage_news",
				"type_id"	=> 1,
				"order"		=> "",
				"active"	=> 1,
			),
			array(
				"id"		=> 1387,
				"menu_id"	=> 5,
				"parent_id"	=> 1312,
				"name"		=> "Comments",
				"location"	=> "object=manage_comments",
				"type_id"	=> 1,
				"order"		=> "",
				"active"	=> 1,
			),
			array(
				"id"		=> 1388,
				"menu_id"	=> 5,
				"parent_id"	=> 1230,
				"name"		=> "Alerts",
				"location"	=> "object=account&action=manage_alerts",
				"type_id"	=> 1,
				"order"		=> "",
				"active"	=> 1,
			),
 			array(
				"id"		=> 1389,
				"menu_id"	=> 5,
				"parent_id"	=> 1346,
				"name"		=> "Email alerts logs",
				"location"	=> "object=log_alert_emails",
				"type_id"	=> 1,
				"order"		=> "",
				"active"	=> 1,
			),
			array(
				"id"		=> 1390,
				"menu_id"	=> 5,
				"parent_id"	=> 1312,
				"name"		=> "Forum",
				"location"	=> "object=forum",
				"type_id"	=> 1,
				"order"		=> "",
				"active"	=> 1,
			),
			array(
				"id"		=> 1391,
				"menu_id"	=> 5,
				"parent_id"	=> 1312,
				"name"		=> "Gallery",
				"location"	=> "object=gallery",
				"type_id"	=> 1,
				"order"		=> "",
				"active"	=> 1,
			),
			array(
				"id"		=> 1392,
				"menu_id"	=> 5,
				"parent_id"	=> 1312,
				"name"		=> "Blog",
				"location"	=> "object=manage_blogs",
				"type_id"	=> 1,
				"order"		=> "",
				"active"	=> 1,
			),
			array(
				"id"		=> 1393,
				"menu_id"	=> 5,
				"parent_id"	=> 1312,
				"name"		=> "Articles",
				"location"	=> "object=manage_articles",
				"type_id"	=> 1,
				"order"		=> "",
				"active"	=> 1,
			),
			array(
				"id"		=> 1394,
				"menu_id"	=> 5,
				"parent_id"	=> 1312,
				"name"		=> "News",
				"location"	=> "object=manage_news",
				"type_id"	=> 1,
				"order"		=> "",
				"active"	=> 1,
			),
			array(
				"id"		=> 1395,
				"menu_id"	=> 5,
				"parent_id"	=> 1312,
				"name"		=> "Comments",
				"location"	=> "object=manage_comments",
				"type_id"	=> 1,
				"order"		=> "",
				"active"	=> 1,
			),
			array(
				"id"		=> 1397,
				"menu_id"	=> 5,
				"parent_id"	=> 1324,
				"name"		=> "Edit Account Info",
				"location"	=> "object=admin_home&action=edit_account",
				"type_id"	=> 1,
				"order"		=> "",
				"active"	=> 1,
			),
			array(
				"id"		=> 1398,
				"menu_id"	=> 5,
				"parent_id"	=> 1398,
				"name"		=> "Logout",
				"location"	=> "task=logout",
				"type_id"	=> 1,
				"order"		=> "",
				"active"	=> 1,
			),
			array(
				"id"		=> 1399,
				"menu_id"	=> 5,
				"parent_id"	=> 1395,
				"name"		=> "Widgets",
				"location"	=> "object=widgets_editor",
				"type_id"	=> 1,
				"order"		=> "",
				"active"	=> 1,
			),
			array(
				"id"		=> 1400,
				"menu_id"	=> 5,
				"parent_id"	=> 1312,
				"name"		=> "Static Pages",
				"location"	=> "object=static_pages",
				"type_id"	=> 1,
				"order"		=> "",
				"active"	=> 1,
			),
			array(
				"id"		=> 1401,
				"menu_id"	=> 5,
				"parent_id"	=> 1405,
				"name"		=> "Configuration Editor",
				"location"	=> "object=conf_editor",
				"type_id"	=> 1,
				"order"		=> "",
				"active"	=> 1,
			),
			array(
				"id"		=> 1402,
				"menu_id"	=> 5,
				"parent_id"	=> 1405,
				"name"		=> "Clear Output Pages Cache",
				"location"	=> "object=admin_home&action=clear_output_cache",
				"type_id"	=> 1,
				"order"		=> "",
				"active"	=> 1,
			),
			array(
				"id"		=> 1403,
				"menu_id"	=> 5,
				"parent_id"	=> 1405,
				"name"		=> "Clear Core Cache",
				"location"	=> "object=admin_home&action=clear_core_cache",
				"type_id"	=> 1,
				"order"		=> "",
				"active"	=> 1,
			),
			array(
				"id"		=> 1404,
				"menu_id"	=> 5,
				"parent_id"	=> 1405,
				"name"		=> "Re-build packed code",
				"location"	=> "object=admin_home&action=rebuild_packed_code",
				"type_id"	=> 1,
				"order"		=> "",
				"active"	=> 1,
			),
			array(
				"id"		=> 1406,
				"menu_id"	=> 5,
				"parent_id"	=> 1396,
				"name"		=> "Edit Account Info",
				"location"	=> "object=admin_home&action=edit_account",
				"type_id"	=> 1,
				"order"		=> "",
				"active"	=> 1,
			),
			array(
				"id"		=> 1407,
				"menu_id"	=> 5,
				"parent_id"	=> 1396,
				"name"		=> "Logout",
				"location"	=> "task=logout",
				"type_id"	=> 1,
				"order"		=> "",
				"active"	=> 1,
			),
// Reserved categories for admin menu
/*			array(
				"id"		=> 1009,
				"menu_id"	=> 1,
				"parent_id"	=> 0,
				"name"		=> "",
				"location"	=> "",
				"type_id"	=> 3,
				"active"	=> 1,
			),
			array(
				"id"		=> 1010,
				"menu_id"	=> 1,
				"parent_id"	=> 0,
				"name"		=> "",
				"location"	=> "",
				"type_id"	=> 3,
				"active"	=> 1,
			),
*/
		),
		"settings"	=> array(
			99999 => array(
				"item"		=> "constructor_mode",
				"type"		=> "enum",
				"size"		=> "'0','1'",
				"value"		=> "0",
				"category"	=> 0,
				"order"		=> 0,
			),
			array(
				"item"		=> "mail_debug",
				"type"		=> "enum",
				"size"		=> "'1','0'",
				"value"		=> "1",
				"category"	=> 1,
				"order"		=> 1,
			),
			array(
				"item"		=> "test_mail",
				"type"		=> "text",
				"size"		=> "20",
				"value"		=> "", // communet01@gmail.com
				"category"	=> 1,
				"order"		=> 1,
			),
			array(
				"item"		=> "rewrite_mode",
				"type"		=> "enum",
				"size"		=> "'1','0'",
				"value"		=> "0",
				"category"	=> 1,
				"order"		=> 1,
			),
			array(
				"item"		=> "admin_per_page",
				"type"		=> "text",
				"size"		=> "",
				"value"		=> "20",
				"category"	=> 1,
				"order"		=> 1,
			),
		),
		"settings_category"	=> array(
			99999 => array(
				"id"	=> 1,
				"name"	=> "Main",
				"order"	=> 1,
			),
		),
		"sites"	=> array(
			99999 => array(
				"name"		=> "Current site name (__CHANGE_ME!__)",
				"web_path"	=> "../",
				"real_path"	=> "INCLUDE_PATH",
				"active"	=> 1,
			),
		),
		"servers"	=> array(
			9999 => array(
				"name"		=> "Main Server",
				"active"	=> 1,
			),
		),
		"smilies"	=> array(
			99999	=> array(
				"code"		=> ":mellow:",
				"url"		=> "mellow.gif",
				"emoticon"	=> "mellow",
				"emo_set"	=> 2,
			),
			array(
				"code"		=> ":huh:",
				"url"		=> "huh.gif",
				"emoticon"	=> "huh",
				"emo_set"	=> 2,
			),
			array(
				"code"		=> "^_^",
				"url"		=> "happy.gif",
				"emoticon"	=> "happy",
				"emo_set"	=> 2,
			),
			array(
				"code"		=> ":o",
				"url"		=> "ohmy.gif",
				"emoticon"	=> "ohmy",
				"emo_set"	=> 2,
			),
			array(
				"code"		=> ";)",
				"url"		=> "wink.gif",
				"emoticon"	=> "wink",
				"emo_set"	=> 2,
			),
			array(
				"code"		=> ":P",
				"url"		=> "tongue.gif",
				"emoticon"	=> "tongue",
				"emo_set"	=> 2,
			),
			array(
				"code"		=> ":D",
				"url"		=> "biggrin.gif",
				"emoticon"	=> "biggrin",
				"emo_set"	=> 2,
			),
			array(
				"code"		=> ":lol:",
				"url"		=> "laugh.gif",
				"emoticon"	=> "laugh",
				"emo_set"	=> 2,
			),
			array(
				"code"		=> "B)",
				"url"		=> "cool.gif",
				"emoticon"	=> "cool",
				"emo_set"	=> 2,
			),
			array(
				"code"		=> ":rolleyes:",
				"url"		=> "rolleyes.gif",
				"emoticon"	=> "rolleyes",
				"emo_set"	=> 2,
			),
			array(
				"code"		=> "-_-",
				"url"		=> "sleep.gif",
				"emoticon"	=> "sleep",
				"emo_set"	=> 2,
			),
			array(
				"code"		=> "&lt;_&lt;",
				"url"		=> "dry.gif",
				"emoticon"	=> "dry",
				"emo_set"	=> 2,
			),
			array(
				"code"		=> ":)",
				"url"		=> "smile.gif",
				"emoticon"	=> "smile",
				"emo_set"	=> 2,
			),
			array(
				"code"		=> ":wub:",
				"url"		=> "wub.gif",
				"emoticon"	=> "wub",
				"emo_set"	=> 2,
			),
			array(
				"code"		=> ":angry:",
				"url"		=> "mad.gif",
				"emoticon"	=> "mad",
				"emo_set"	=> 2,
			),
			array(
				"code"		=> ":(",
				"url"		=> "sad.gif",
				"emoticon"	=> "sad",
				"emo_set"	=> 2,
			),
			array(
				"code"		=> ":unsure:",
				"url"		=> "unsure.gif",
				"emoticon"	=> "unsure",
				"emo_set"	=> 2,
			),
			array(
				"code"		=> ":wacko:",
				"url"		=> "wacko.gif",
				"emoticon"	=> "wacko",
				"emo_set"	=> 2,
			),
			array(
				"code"		=> ":blink:",
				"url"		=> "blink.gif",
				"emoticon"	=> "blink",
				"emo_set"	=> 2,
			),
			array(
				"code"		=> ":ph34r:",
				"url"		=> "ph34r.gif",
				"emoticon"	=> "ph34r",
				"emo_set"	=> 2,
			),
		),
		"user_groups"	=> array(
			99999 => array(
				"id"	=> 1,
				"name"	=> "Guest",
				"active"=> 1,
			),
			array(
				"id"	=> 2,
				"name"	=> "Member",
				"active"=> 1,
			),
		),
		"user_modules"	=> array(
			99999 => array(
				"name"	=> "home_page",
				"active"=> 1,
			),
			array(
				"name"	=> "login_form",
				"active"=> 1,
			),
			array(
				"name"	=> "static_pages",
				"active"=> 1,
			),
		),
	));
?>