<?php
	/** @var Structures for the other common used tables */
	$data = my_array_merge((array)$data, array(
		"activity_logs"	=> "
			`id` int(10) unsigned NOT NULL auto_increment,
			`task_id` tinyint(3) unsigned NOT NULL,
			`user_id` int(10) unsigned NOT NULL,
			`add_date` int(10) unsigned NOT NULL,
			`add_points` int(10) NOT NULL,
			PRIMARY KEY	(`id`),
			KEY `user_id` (`user_id`)
		",
		"activity_total"	=> "
			`user_id` int(10) unsigned NOT NULL,
			`points` int(10) unsigned NOT NULL,
			`exchanged_act_points` INT UNSIGNED NOT NULL,
			`last_update` int(10) unsigned NOT NULL,
			PRIMARY KEY	(`user_id`)
		",
		"activity_types"	=> "
			`id` int(10) unsigned NOT NULL auto_increment,
			`name` varchar(255) NOT NULL,
			`desc` varchar(255) NOT NULL,
			`points` varchar(255) NOT NULL,
			`min_value` varchar(255) NOT NULL,
			`min_time` int(10) unsigned NOT NULL,
			`active` enum('1','0') NOT NULL,
			`table_name` varchar(255) NOT NULL,
			PRIMARY KEY	(`id`)
		",
		"admin_messages"	=> "
			`id` int(10) unsigned NOT NULL auto_increment,
			`user_id` int(10) unsigned NOT NULL,
			`author_id` int(10) unsigned NOT NULL,
			`title` varchar(255) NOT NULL,
			`text` text NOT NULL,
			`read` enum('0','1') NOT NULL,
			`time` int(10) unsigned NOT NULL,
			PRIMARY KEY  (`id`)
		",
		"auto_connected"	=> "
			`user_id` int(10) unsigned NOT NULL default '0',
			`add_date` int(10) unsigned NOT NULL default '0',
			`active` enum('1','0') NOT NULL,
			PRIMARY KEY	(`user_id`)
		",
		"articles_texts"	=> "
			`id` int(10) unsigned NOT NULL auto_increment,
			`cat_id` int(10) unsigned NOT NULL,
			`user_id` int(10) unsigned NOT NULL,
			`is_own_article` enum('1','0') NOT NULL,
			`author_name` varchar(255) NOT NULL,
			`title` varchar(255) NOT NULL,
			`summary` text NOT NULL,
			`full_text` longtext NOT NULL,
			`status` enum('new','edited','suspended','active') NOT NULL,
			`credentials` text NOT NULL,
			`add_date` int(10) unsigned NOT NULL,
			`edit_date` int(10) unsigned NOT NULL,
			`views` int(10) unsigned NOT NULL,
			`short_url` varchar(255) NOT NULL,
			`activity` int(10) unsigned NOT NULL default '0',
			PRIMARY KEY	(`id`),
			KEY `user_id` (`user_id`)
		",
		"blog_posts"	=> "
			`id` int(10) unsigned NOT NULL auto_increment,
			`id2` int(10) unsigned NOT NULL,
			`user_name` varchar(255) NOT NULL default '',
			`user_id` int(10) unsigned NOT NULL default '0',
			`poster_id` int(11) unsigned NOT NULL default '0',
			`cat_id` smallint(5) unsigned NOT NULL default '0',
			`title` varchar(255) NOT NULL default '',
			`text` text NOT NULL,
			`add_date` int(10) unsigned NOT NULL default '0',
			`edit_date` int(10) unsigned NOT NULL,
			`ip` varchar(15) NOT NULL default '',
			`num_reads` int(10) unsigned NOT NULL default '0',
			`attach_image` varchar(255) NOT NULL default '',
			`disable_comments` enum('0','1') NOT NULL default '0',
			`mode_type` tinyint(3) unsigned NOT NULL default '0',
			`mode_text` varchar(255) NOT NULL default '',
			`mood` varchar(255) NOT NULL default '',
			`privacy` tinyint(3) unsigned NOT NULL default '0',
			`allow_comments` tinyint(3) unsigned NOT NULL,
			`active` tinyint(1) unsigned NOT NULL default '0',
			`custom_cat_id` smallint(5) unsigned NOT NULL,
			`activity` int(10) unsigned NOT NULL default '0',
			`old_id` int(10) unsigned NOT NULL,
			`mask` int(10) unsigned NOT NULL,
			PRIMARY KEY  (`id`),
			KEY `user_id` (`user_id`),
			KEY `id2` (`id2`)
		",
		"blog_settings"	=> "
			`user_id` int(10) unsigned NOT NULL auto_increment,
			`blog_title` varchar(255) NOT NULL,
			`blog_desc` varchar(255) NOT NULL,
			`custom_cats` text NOT NULL,
			`blog_links` text NOT NULL,
			`allow_comments` tinyint(3) unsigned NOT NULL,
			`privacy` tinyint(3) unsigned NOT NULL,
			`num_posts` int(10) unsigned NOT NULL,
			`num_comments` int(10) unsigned NOT NULL,
			`num_views` int(10) unsigned NOT NULL,
			`user_nick` varchar(255) NOT NULL,
			`allow_tagging` TINYINT UNSIGNED NOT NULL,
			PRIMARY KEY (`user_id`)
		",
		"calendar_dates"	=> "
			`id` int(10) unsigned NOT NULL auto_increment,
			`user_id` int(10) unsigned NOT NULL,
			`date` int(10) unsigned NOT NULL,
			`title` varchar(255) NOT NULL,
			`desc` text NOT NULL,
			`status` tinyint(3) unsigned NOT NULL,
			`hours` text NOT NULL,
			PRIMARY KEY	(`id`),
			UNIQUE KEY `user_id_2` (`user_id`,`date`),
			KEY `user_id` (`user_id`)
		",
		"calendar_settings"	=> "
			`user_id` int(10) unsigned NOT NULL,
			`title` varchar(255) NOT NULL,
			`desc` text NOT NULL,
			`default` text NOT NULL,
			`active` enum('1','0') NOT NULL,
			`date_format` tinyint(3) UNSIGNED NOT NULL,
			PRIMARY KEY	(`user_id`)
		",
		"check_multi_accounts"	=> "
			`user_id` int(10) unsigned NOT NULL,
			`matching_users` longtext NOT NULL,
			`matching_ips` longtext NOT NULL,
			`num_m_users` int(10) unsigned NOT NULL default '0',
			`num_m_ips` int(10) unsigned NOT NULL default '0',
			`last_update` int(10) unsigned NOT NULL default '0',
			`cookie_match` enum('0','1') NOT NULL default '0',
			`ip_match` enum('0','1') NOT NULL,
			PRIMARY KEY	(`user_id`),
			KEY `ip_match` (`ip_match`),
			KEY `cookie_match` (`cookie_match`)
		",
		"check_multi_ips"	=> "
			`ip` char(15) NOT NULL,
			`matching_users` longtext NOT NULL,
			`matching_ips` longtext NOT NULL,
			`num_m_users` int(10) unsigned NOT NULL default '0',
			`num_m_ips` int(10) unsigned NOT NULL default '0',
			`last_update` int(10) unsigned NOT NULL default '0',
			PRIMARY KEY	(`ip`)
		",
		"color_schemes"	=> "
			`id` INT UNSIGNED NOT NULL AUTO_INCREMENT ,
			`name` VARCHAR( 255 ) NOT NULL ,
			`description` TEXT NOT NULL ,
			`css` TEXT NOT NULL ,
			`active` ENUM( '1', '0' ) NOT NULL ,
			PRIMARY KEY ( `id` ) 
		",
		"comments"	=> "
			`id` int(10) unsigned NOT NULL auto_increment,
			`object_name` varchar(24) NOT NULL,
			`object_id` int(10) unsigned NOT NULL default '0',
			`parent_id` int(10) unsigned NOT NULL default '0',
			`user_id` int(10) unsigned NOT NULL default '0',
			`user_name` varchar(255) NOT NULL default '',
			`user_email` varchar(128) character set utf8 NOT NULL default '',
			`add_date` int(10) unsigned NOT NULL default '0',
			`text` text NOT NULL,
			`ip` varchar(15) NOT NULL default '',
			`active` tinyint(1) unsigned NOT NULL default '0',
			`activity` int(10) unsigned NOT NULL default '0',
			PRIMARY KEY	(`id`),
			KEY `object_name` (`object_name`),
			KEY `object_id` (`object_id`),
			KEY `user_id` (`user_id`)
		",
		"community"	=> "
			`id` int(10) unsigned NOT NULL auto_increment,
			`owner_id` int(11) NOT NULL default '0',
			`user_id` int(10) unsigned NOT NULL default '0',
			`title` text character set utf8 NOT NULL,
			`membership` enum('open','moderated','closed') NOT NULL default 'open',
			`nonmember_posting` enum('0','1') NOT NULL default '0',
			`postlevel` enum('members','select') NOT NULL default 'members',
			`moderated` enum('0','1') NOT NULL default '0',
			`adult` enum('none','concepts','explicit') NOT NULL default 'none',
			`about` text character set utf8 NOT NULL,
			`active` enum('0','1') NOT NULL default '0',
			PRIMARY KEY  (`id`)
		",
		"community_users"	=> "
			`id` int(11) NOT NULL auto_increment,
			`user_id` int(10) unsigned NOT NULL default '0',
			`community_id` int(10) unsigned NOT NULL default '0',
			`member` enum('0','1') NOT NULL default '0',
			`post` enum('0','1') NOT NULL default '0',
			`unmoderated` enum('0','1') NOT NULL default '0',
			`moderator` enum('0','1') NOT NULL default '0',
			`maintainer` enum('0','1') NOT NULL default '0',
			PRIMARY KEY  (`id`)		
		",
		"countries"	=> "
			`c` char(2) NOT NULL default '',
			 `n` varchar(64) NOT NULL default '',
			 `f` enum('0','1') NOT NULL default '0',
			`cont` char(1) NOT NULL default '',
			`call_code` char(4) NOT NULL default '',
			PRIMARY KEY  (`c`)
		",
		"custom_style"	=> "
			`id` int(11) NOT NULL,
			`item_id` int(11) NOT NULL default '0',
			`page` varchar(20) NOT NULL default '',
			`main_text_style` varchar(255) NOT NULL default '',
			`link_style` varchar(255) NOT NULL default '',
			`link_hover_style` varchar(255) NOT NULL default '',
			`back_color` varchar(16) NOT NULL default '',
			`background` varchar(10) NOT NULL default '',
			`is_scrollback` int(11) NOT NULL default '0',
			`is_tiledback` int(11) NOT NULL default '0',
			`is_transback` int(11) NOT NULL default '0',
			`image_color` varchar(16) NOT NULL default '',
			`image_hover_color` varchar(16) NOT NULL default '',
			`is_lightimg` int(11) NOT NULL default '0',
			`is_fliphorimg` int(11) NOT NULL default '0',
			`is_flipvertimg` int(11) NOT NULL default '0',
			`th_backcolor` varchar(16) NOT NULL default '',
			`th_style` varchar(255) NOT NULL default '',
			`table_backcolor` varchar(16) NOT NULL default '',
			`table_bordercolor` varchar(16) NOT NULL default '',
			PRIMARY KEY	(`id`)
		",
		"designs"	=> "
			`id` int(10) unsigned NOT NULL auto_increment,
			`name` varchar(32) NOT NULL,
			`theme_id` int(11) NOT NULL,
			`active` enum('0','1') NOT NULL,
			`tags` varchar(255) NOT NULL,
			`owner_id` int(10) unsigned NOT NULL,
			`css` text NOT NULL,
			PRIMARY KEY  (`id`)
		",
		"dynamic_fields_values"	=> "
			`category_id` int(11) NOT NULL default '0',
			`object_name` varchar(50) NOT NULL default '',
			`object_id` int(11) NOT NULL default '0',
			`field_id` int(11) NOT NULL default '0',
			`value` text NOT NULL default '',
			`add_value` text NOT NULL default ''
		",
		"dynamic_fields_categories"	=> "
			`id` int(11) NOT NULL auto_increment,
			`name` varchar(50) NOT NULL default '',
			PRIMARY KEY  (`id`)
		",
		"dynamic_fields_info"	=> "
			`id` int(10) unsigned NOT NULL auto_increment,
			`category_id` int(11) NOT NULL default '0',
			`name` varchar(64) NOT NULL default '',
			`type` varchar(64) NOT NULL default '',
			`value_list` text NOT NULL,
			`default_value` text NOT NULL,
			`order` int(10) unsigned NOT NULL default '0',
			`active` enum('1','0') NOT NULL default '1',
			PRIMARY KEY  (`id`)
		",
		"email_change"	=> "
			`id` int(10) unsigned NOT NULL auto_increment,
			`user_id` int(10) unsigned NOT NULL default '0',
			`old_mail` varchar(50) NOT NULL default '0',
			`new_mail` varchar(50) NOT NULL default '0',
			`time` int(10) unsigned NOT NULL default '0',
			PRIMARY KEY (`id`)
		",
		"faq_texts"	=> "
			`id` int(10) unsigned NOT NULL auto_increment,
			`cat_id` int(10) unsigned NOT NULL,
			`author_id` int(10) unsigned NOT NULL,
			`question_text` text NOT NULL,
			`answer_text` text NOT NULL,
			`status` enum('suspended','active') NOT NULL default 'active',
			`priority` tinyint(3) unsigned NOT NULL,
			`add_date` int(10) unsigned NOT NULL,
			`edit_date` int(10) unsigned NOT NULL,
			`views` int(10) unsigned NOT NULL,
			PRIMARY KEY	(`id`)
		",
		"favorites"	=> "
			`id` int(10) unsigned NOT NULL auto_increment,
			`user_id` int(10) unsigned NOT NULL default '0',
			`target_user_id` int(10) unsigned NOT NULL default '0',
			`add_date` int(10) unsigned NOT NULL default '0',
			`active` enum('1','0') NOT NULL default '1',
			PRIMARY KEY	(`id`),
			UNIQUE KEY `user_id` (`user_id`,`target_user_id`)
		",
		"font_size"	=> "
			`id` int(11) NOT NULL,
			`value` char(2) NOT NULL default '',
			PRIMARY KEY	(`id`)
		",
		"font_type"	=> "
			`id` int(11) NOT NULL,
			`value` varchar(50) NOT NULL default '',
			PRIMARY KEY	(`id`)
		",
		"friends"	=> "
			`user_id` int(10) unsigned NOT NULL default '0',
			`friends_list` text NOT NULL,
			UNIQUE KEY `user_id` (`user_id`)
		",
		"friends_groups"	=> "
			`id` int(11) NOT NULL auto_increment,
			`id2` tinyint(4) NOT NULL default '0',
			`user_id` int(11) NOT NULL default '0',
			`title` text character set utf8 NOT NULL,
			`order` int(11) NOT NULL default '0',
			PRIMARY KEY  (`id`),
			KEY `id2` (`id2`)
		",
		"friends_users"	=> "
			`id` int(11) NOT NULL auto_increment,
			`user_id` int(11) NOT NULL default '0',
			`friend_id` int(11) NOT NULL default '0',
			`mask` int(11) NOT NULL default '0',
			PRIMARY KEY  (`id`)
		",
		"gallery_folders"	=> "
			`id` int(10) unsigned NOT NULL auto_increment,
			`id2` int(10) unsigned NOT NULL,
			`user_id` int(10) unsigned NOT NULL,
			`title` varchar(255) NOT NULL,
			`comment` text NOT NULL,
			`allow_comments` tinyint(3) unsigned NOT NULL,
			`privacy` tinyint(3) unsigned NOT NULL,
			`content_level` tinyint(3) unsigned NOT NULL,
			`num_photos` int(10) unsigned NOT NULL,
			`num_comments` int(10) unsigned NOT NULL,
			`num_views` int(10) unsigned NOT NULL,
			`user_nick` varchar(255) NOT NULL,
			`password` varchar(32) NOT NULL,
			`is_default` enum('0','1') NOT NULL,
			`add_date` int(10) unsigned NOT NULL,
			`active` enum('1','0') NOT NULL,
			`allow_tagging` TINYINT UNSIGNED NOT NULL,
			PRIMARY KEY  (`id`),
			KEY `user_id` (`user_id`),
			KEY `id2` (`id2`)
		",
		"gallery_photos"	=> "
			`id` int(10) unsigned NOT NULL auto_increment,
			`id2` int(10) unsigned NOT NULL,
			`user_id` int(10) unsigned NOT NULL default '0',
			`cat_id` int(10) unsigned NOT NULL default '0',
			`folder_id` int(10) unsigned NOT NULL,
			`img_name` varchar(255) NOT NULL default '',
			`name` varchar(255) NOT NULL default '',
			`desc` text NOT NULL,
			`show_in_ads` enum('0','1') NOT NULL default '0',
			`diplay_order` int(10) unsigned NOT NULL default '0',
			`general_sort_id` int(10) unsigned NOT NULL default '0',
			`folder_sort_id` int(10) unsigned NOT NULL default '0',
			`add_date` int(10) unsigned NOT NULL default '0',
			`other_info` text NOT NULL,
			`active` enum('1','0') NOT NULL default '1',
			`is_public` enum('0','1') NOT NULL default '0',
			`is_featured` enum('0','1') NOT NULL default '0',
			`geo_cc` char(2) NOT NULL,
			`geo_rc` char(2) NOT NULL,
			`priority` int(11) NOT NULL default '0',
			`allow_rate` enum('1','0') NOT NULL,
			`rating` float NOT NULL,
			`num_votes` int(10) unsigned NOT NULL,
			`votes_sum` int(11) NOT NULL,
			`last_vote_date` int(10) unsigned NOT NULL,
			`allow_tagging` enum('0','1') NOT NULL,
			PRIMARY KEY  (`id`),
			KEY `user_id` (`user_id`),
			KEY `add_date` (`add_date`),
			KEY `folder_id` (`folder_id`),
			KEY `is_public` (`is_public`),
			KEY `geo_cc` (`geo_cc`),
			KEY `geo_rc` (`geo_rc`),
			KEY `rating` (`rating`),
			KEY `id2` (`id2`)
			/** ENGINE=INNODB **/ 
		",
		"gallery_rate_views"	=> "
			`sid` char(32) NOT NULL,
			`user_id` int(10) unsigned NOT NULL,
			`photo_id` int(10) unsigned NOT NULL,
			`date` int(10) unsigned NOT NULL
			/** ENGINE=MEMORY **/ 
		",
		"gallery_rate_votes"	=> "
			`id` int(10) unsigned NOT NULL auto_increment,
			`photo_id` int(10) unsigned NOT NULL,
			`user_id` int(10) unsigned NOT NULL,
			`target_user_id` int(10) unsigned NOT NULL,
			`add_date` int(10) unsigned NOT NULL,
			`voted` int(11) NOT NULL,
			`counted` int(11) NOT NULL,
			`ip` varchar(16) NOT NULL,
			`comment` varchar(255) NOT NULL,
			`active` enum('1','0') NOT NULL,
			PRIMARY KEY	(`id`)
		",
		"gallery_settings"	=> "
			`user_id` int(10) unsigned NOT NULL auto_increment,
			`title` varchar(255) NOT NULL,
			`desc` varchar(255) NOT NULL,
			`allow_comments` tinyint(3) unsigned NOT NULL,
			`allow_rate` enum('1','0') NOT NULL,
			`allow_tagging` tinyint(3) unsigned NOT NULL,
			`privacy` tinyint(3) unsigned NOT NULL,
			`thumb_type` int(10) unsigned NOT NULL,
			`medium_size` int(10) unsigned NOT NULL,
			`layout_type` int(10) unsigned NOT NULL,
			`thumbs_loc` tinyint(3) unsigned NOT NULL,
			`thumbs_in_row` tinyint(3) unsigned NOT NULL,
			`slideshow_mode` tinyint(3) unsigned NOT NULL,
			`num_photos` int(10) unsigned NOT NULL,
			`num_comments` int(10) unsigned NOT NULL,
			`num_views` int(10) unsigned NOT NULL,
			`user_nick` varchar(255) NOT NULL,
			`geo_cc` char(2) NOT NULL,
			`geo_rc` char(2) NOT NULL,
			`priority` int(11) NOT NULL,
 			PRIMARY KEY  (`user_id`)
		",
		"handshake"	=> "
			`id` int(10) unsigned NOT NULL auto_increment,
			`sender` int(11) NOT NULL default '0',
			`receiver` int(11) NOT NULL default '0',
			`text` text character set utf8 NOT NULL,
			`add_date` text NOT NULL,
			`action_date` text NOT NULL,
			`status` text NOT NULL,
			PRIMARY KEY  (`id`)
		",
		"geo_city_blocks"	=> "
			`start_ip` int(8) unsigned NOT NULL,
			`end_ip` int(8) unsigned NOT NULL,
			`loc_id` int(6) unsigned NOT NULL,
			PRIMARY KEY	(`end_ip`)
		",
		"geo_city_cutted"	=> "
			`country` char(2) NOT NULL,
			`city` varchar(32) NOT NULL,
			`region` char(3) NOT NULL,
			`population` int(8) NOT NULL default '0',
			KEY `country` (`country`)
		",
		"geo_city_location"	=> "
			`loc_id` int(10) unsigned NOT NULL,
			`country` char(2) NOT NULL,
			`region` char(3) NOT NULL,
			`city` varchar(32) NOT NULL,
			`postal_code` char(5) NOT NULL,
			`latitude` float NOT NULL,
			`longitude` float NOT NULL,
			`dma_code` int(8) unsigned NOT NULL,
			`area_code` int(8) unsigned NOT NULL,
			PRIMARY KEY	(`loc_id`),
			KEY `country` (`country`)
		",
		"geo_city_populations"	=> "
			`country` char(2) NOT NULL,
			`city` varchar(32) NOT NULL,
			`region` char(3) NOT NULL,
			`population` int(8) NOT NULL default '0',
			`latitude` float NOT NULL,
			`longitude` float NOT NULL,
			KEY `country` (`country`),
			KEY `population` (`population`)
		",
		"geo_regions"	=> "
			`country` char(2) NOT NULL,
			`code` char(2) NOT NULL,
			`name` varchar(255) NOT NULL,
			KEY `country` (`country`),
			KEY `code` (`code`)
		",
		"geo_skip_ip"	=> "
			`ip` int(10) unsigned NOT NULL,
			`hits` int(10) unsigned NOT NULL,
			PRIMARY KEY	(`ip`)
		",
		"heights"	=> "
			`id` tinyint(4) NOT NULL default '0',
			`height` varchar(50) NOT NULL default '',
			PRIMARY KEY	(`id`),
			UNIQUE KEY `id_2` (`id`),
			KEY `id` (`id`)
		",
		"help_tickets"	=> "
			`id` int(10) unsigned NOT NULL auto_increment,
			`ticket_key` varchar(32) NOT NULL,
			`user_id` int(10) unsigned NOT NULL,
			`name` varchar(255) NOT NULL,
			`email` varchar(255) NOT NULL,
			`subject` varchar(255) NOT NULL,
			`user_priority` tinyint(3) unsigned NOT NULL,
			`admin_priority` tinyint(3) unsigned NOT NULL,
			`category_id` tinyint(3) unsigned NOT NULL,
			`message` text NOT NULL,
			`urls` text NOT NULL,
			`opened_date` int(10) unsigned NOT NULL,
			`closed_date` int(10) unsigned NOT NULL,
			`admin_comments` text NOT NULL,
			`status` enum('new','read','open','closed') NOT NULL,
			`user_agent` varchar(255) NOT NULL,
			`ip` varchar(15) NOT NULL,
			`cookies_enabled` enum('0','1') NOT NULL,
			`assigned_to` int(10) unsigned NOT NULL,
			`site_id` tinyint(3) unsigned NOT NULL default '0',
			`server_id` tinyint(3) unsigned NOT NULL default '0',
			`referer` varchar(255) NOT NULL default '',
			`activity` int(10) unsigned NOT NULL default '0',
			PRIMARY KEY	(`id`),
			KEY `user_id` (`user_id`)
		",
		"ignore_list"	=> "
			`user_id` int(10) unsigned NOT NULL default '0',
			`target_user_id` int(10) unsigned NOT NULL default '0',
			`add_date` int(10) unsigned NOT NULL default '0',
			`active` enum('1','0') NOT NULL default '1',
			UNIQUE KEY `user_id` (`user_id`)
		",
		"interests"	=> "
			`user_id` int(10) unsigned NOT NULL,
			`keywords` text NOT NULL,
			PRIMARY KEY (`user_id`)
		",
		"interests_keywords"	=> "
			`keyword` varchar(32) NOT NULL,
			`users` int(10) unsigned NOT NULL,
			PRIMARY KEY	(`keyword`)
		",
		"link_request"	=> "
			`id` mediumint(7) NOT NULL auto_increment,
			`user_id` mediumint(7) NOT NULL default '0',
			`time` int(11) NOT NULL default '0',
			PRIMARY KEY	(`id`)
		",
		"links_categories"	=> "
			`id` int(5) NOT NULL auto_increment,
			`name` varchar(50) NOT NULL default '',
			`order1` smallint(3) NOT NULL default '0',
			`bottom` text NOT NULL,
			`file_name` varchar(64) NOT NULL default '',
			PRIMARY KEY	(`id`),
			UNIQUE KEY `id` (`id`)
		",
		"links_links"	=> "
			`id` int(5) NOT NULL auto_increment,
			`user_id` int(5) NOT NULL default '0',
			`cat_id` smallint(3) NOT NULL default '0',
			`status` smallint(1) NOT NULL default '0',
			`title` varchar(50) NOT NULL default '',
			`url` varchar(250) NOT NULL default '',
			`description` text NOT NULL,
			`link_url` varchar(250) NOT NULL default '',
			`banner_url` varchar(250) NOT NULL default '',
			`type` smallint(1) NOT NULL default '0',
			`priority` smallint(1) NOT NULL default '0',
			`linker` varchar(20) NOT NULL default '',
			`email1_time` int(11) NOT NULL default '0',
			`email2_time` int(11) NOT NULL default '0',
			`email3_time` int(11) NOT NULL default '0',
			`repl_url` varchar(250) NOT NULL default '',
			`linker_id` int(10) unsigned NOT NULL default '0',
			`add_date` int(10) unsigned NOT NULL default '0',
			`site1` smallint(1) NOT NULL default '0',
			`site2` smallint(1) NOT NULL default '0',
			`site3` smallint(1) NOT NULL default '0',
			`site4` smallint(1) NOT NULL default '0',
			`site5` smallint(1) NOT NULL default '0',
			`site6` smallint(1) NOT NULL default '0',
			`site7` smallint(1) NOT NULL default '0',
			`site8` smallint(1) NOT NULL default '0',
			`site9` smallint(1) NOT NULL default '0',
			`site10` smallint(1) NOT NULL default '0',
			`site11` smallint(1) NOT NULL default '0',
			`site12` smallint(1) NOT NULL default '0',
			`site13` smallint(1) NOT NULL default '0',
			`site14` smallint(1) NOT NULL default '0',
			`site15` smallint(1) NOT NULL default '0',
			`site16` smallint(1) NOT NULL default '0',
			`site17` smallint(1) NOT NULL default '0',
			`site18` smallint(1) NOT NULL default '0',
			`site19` smallint(1) NOT NULL default '0',
			`site20` smallint(1) NOT NULL default '0',
			`site21` smallint(1) NOT NULL default '0',
			`site22` smallint(1) NOT NULL default '0',
			`site23` smallint(1) NOT NULL default '0',
			`site24` smallint(1) NOT NULL default '0',
			`site25` smallint(1) NOT NULL default '0',
			`site26` smallint(1) NOT NULL default '0',
			`site27` smallint(1) NOT NULL default '0',
			`site28` smallint(1) NOT NULL default '0',
			`site29` smallint(1) NOT NULL default '0',
			`site30` smallint(1) NOT NULL default '0',
			UNIQUE KEY `id` (`id`),
			KEY `user_id` (`user_id`)
		",
		"links_mails"	=> "
			`id` int(5) NOT NULL auto_increment,
			`time` int(11) NOT NULL default '0',
			`subject` varchar(250) NOT NULL default '',
			`message` text NOT NULL,
			UNIQUE KEY `id` (`id`)
		",
		"links_sites"	=> "
			`id` int(5) NOT NULL auto_increment,
			`title` varchar(50) NOT NULL default '',
			`description` text NOT NULL,
			`url` varchar(250) NOT NULL default '',
			`links_url` varchar(250) NOT NULL default '',
			`register_url` varchar(250) NOT NULL default '',
			`login_url` varchar(250) NOT NULL default '',
			`banner_url` varchar(250) NOT NULL default '',
			`list_bottom` text NOT NULL,
			UNIQUE KEY `id` (`id`)
		",
		"links_users"	=> "
			`id` int(5) NOT NULL auto_increment,
			`name` varchar(50) NOT NULL default '',
			`password` varchar(12) NOT NULL default '',
			`email` varchar(50) NOT NULL default '',
			`linker` varchar(50) NOT NULL default '',
			`time` int(11) NOT NULL default '0',
			`linker_id` int(10) unsigned NOT NULL default '0',
			UNIQUE KEY `id` (`id`)
		",
		"log_user_action"	=> "
			`id` INT UNSIGNED NOT NULL AUTO_INCREMENT ,
			`owner_id` INT UNSIGNED NOT NULL ,
			`action_name` VARCHAR( 255 ) NOT NULL ,
			`member_id` INT UNSIGNED NOT NULL ,
			`object_name` VARCHAR( 255 ) NOT NULL ,
			`object_id` INT UNSIGNED NOT NULL ,
			`add_date` INT UNSIGNED NOT NULL ,
			PRIMARY KEY ( `id` )
		",
		"mailarchive"	=> "
			`id` mediumint(7) NOT NULL auto_increment,
			`sender` int(10) unsigned NOT NULL,
			`receiver` int(10) unsigned NOT NULL,
			`s_folder_id` tinyint(3) unsigned NOT NULL,
			`r_folder_id` tinyint(3) unsigned NOT NULL,
			`subject` varchar(255) NOT NULL default '',
			`message` text NOT NULL,
			`time` int(10) unsigned NOT NULL default '0',
			`r_read_time` int(10) unsigned NOT NULL,
			`sender_ip` varchar(16) NOT NULL,
			`activity` int(10) unsigned NOT NULL default '0',
			PRIMARY KEY  (`id`),
			KEY `receiver` (`receiver`),
			KEY `sender` (`sender`),
			KEY `r_read_time` (`r_read_time`)
		",
		"moods"	=> "
			`id` smallint(5) unsigned NOT NULL auto_increment,
			`name` varchar(255) CHARACTER SET utf8 NOT NULL default '',
			`active` enum('1','0') NOT NULL default '1',
			`locale` char(7) DEFAULT 'en' NOT NULL, 
			PRIMARY KEY	(`id`)
		",
		"news"	=> "
			`id` int(10) unsigned NOT NULL auto_increment,
			`title` varchar(255) NOT NULL default '',
			`head_text` text NOT NULL,
			`full_text` text NOT NULL,
			`meta_keywords` text NOT NULL,
			`meta_desc` text NOT NULL,
			`add_date` int(10) unsigned NOT NULL default '0',
			`active` enum('1','0') NOT NULL default '1',
			PRIMARY KEY  (`id`)
		",
		"openid_association"	=> "
			`url`		varchar(256) NOT NULL,
			`handle`	varchar(256) NOT NULL default '',
			`mac_func`	char(16) NOT NULL default '',
			`secret`	varchar(256) NOT NULL default '',
			`expires`	int(10) unsigned NOT NULL default '0',
			PRIMARY KEY  (`url`)
		",
		"openid_discovery"	=> "
			`id`		varchar(256) NOT NULL,
			`real_id`	varchar(256) NOT NULL default '',
			`server`	varchar(256) NOT NULL default '',
			`version`	float,
			`expires`	int(10) unsigned NOT NULL default '0',
			PRIMARY KEY  (`id`)
		",
		"openid_nonce"	=> "
			`nonce`		varchar(256) NOT NULL,
			`created`	int(10) unsigned NOT NULL default '0',
			PRIMARY KEY  (`nonce`)
		",
		"pm"	=> "
			`id` int(10) unsigned NOT NULL,
			`sender_id` int(10) unsigned NOT NULL default '0',
			`receiver_id` int(10) unsigned NOT NULL default '0',
			`s_section` enum('sent','trash') NOT NULL default 'sent',
			`r_section` enum('inbox','trash') NOT NULL default 'inbox',
			`s_status` enum('read','unread','replied','sent','approved','disapproved','deleted') NOT NULL default 'unread',
			`r_status` enum('read','unread','replied','approved','disapproved','deleted') NOT NULL default 'unread',
			`add_date` int(10) unsigned NOT NULL default '0',
			`subject` varchar(255) NOT NULL default '',
			`message` text NOT NULL,
			`type` varchar(20) NOT NULL default 'standard',
			`special_id` int(10) unsigned NOT NULL default '0',
			PRIMARY KEY	(`id`),
			KEY `receiver_id` (`receiver_id`),
			KEY `sender_id` (`sender_id`)
		",
		"poll_votes"	=> "
			`id` int(10) unsigned NOT NULL auto_increment,
			`poll_id` int(10) unsigned NOT NULL default '0',
			`user_id` int(10) unsigned NOT NULL default '0',
			`date` int(10) unsigned NOT NULL default '0',
			`value` tinyint(3) unsigned NOT NULL,
			PRIMARY KEY	(`id`),
			KEY `poll_id` (`poll_id`),
			KEY `user_id` (`user_id`)
		",
		"polls"	=> "
			`id` int(10) unsigned NOT NULL auto_increment,
			`object_name` varchar(255) NOT NULL,
			`object_id` int(10) unsigned NOT NULL default '0',
			`user_id` int(10) unsigned NOT NULL default '0',
			`question` varchar(255) NOT NULL,
			`add_date` int(10) unsigned NOT NULL default '0',
			`choices` text NOT NULL,
			`votes` smallint(5) unsigned NOT NULL default '0',
			`multiple` enum('0','1') NOT NULL default '0',
			`active` enum('1','0') NOT NULL default '1',
			PRIMARY KEY	(`id`),
			KEY `object_name` (`object_name`),
			KEY `object_id` (`object_id`)
		",
		"prof_interests"	=> "
			`id` int(10) unsigned NOT NULL auto_increment,
			`name` varchar(255) character set utf8 NOT NULL,
			`locale` char(7) NOT NULL default 'en',
			PRIMARY KEY  (`id`)
		",
		"prof_keywords"	=> "
			`user_id` int(10) unsigned NOT NULL,
			`keywords` text NOT NULL,
			PRIMARY KEY	(`user_id`)
		",
		"rate_votes"	=> "
			`id` int(10) unsigned NOT NULL auto_increment,
			`user_id` int(10) unsigned NOT NULL,
			`rate_id` int(10) unsigned NOT NULL,
			`add_date` int(10) unsigned NOT NULL,
			`value` int(11) NOT NULL,
			`ip` varchar(16) NOT NULL,
			`comment` varchar(255) NOT NULL,
			`active` enum('1','0') NOT NULL,
			PRIMARY KEY	(`id`),
			KEY `user_id` (`user_id`)
		",
		"rates"		=> "
			`id` int(10) unsigned NOT NULL auto_increment,
			`object_name` varchar(24) NOT NULL,
			`object_id` int(10) unsigned NOT NULL default '0',
			`owner_id` int(10) unsigned NOT NULL default '0',
			`owner_name` varchar(255) NOT NULL,
			`add_date` int(10) unsigned NOT NULL default '0',
			`last_vote_date` int(10) unsigned NOT NULL default '0',
			`num_votes` int(10) unsigned NOT NULL,
			`votes_sum` int(10) unsigned NOT NULL,
			`active` tinyint(1) unsigned NOT NULL default '0',
			`other_info` varchar(255) NOT NULL,
			PRIMARY KEY	(`id`),
			KEY `object_name` (`object_name`),
			KEY `object_id` (`object_id`)
		",
		"reput_total"	=> "
			`user_id` int(10) unsigned NOT NULL,
			`points` int(11) NOT NULL,
			`alt_power` int(11) NOT NULL,
			`num_votes` int(10) unsigned NOT NULL,
			`num_voted` int(10) unsigned NOT NULL,
			`reput_change` int(11) NOT NULL,
			PRIMARY KEY	(`user_id`)
		",
		"reput_user_votes"	=> "
			`id` int(10) unsigned NOT NULL auto_increment,
			`user_id` int(10) unsigned NOT NULL,
			`target_user_id` int(10) unsigned NOT NULL,
			`add_date` int(10) unsigned NOT NULL,
			`voted` int(11) NOT NULL,
			`ip` varchar(16) NOT NULL,
			`comment` varchar(255) NOT NULL,
			`active` enum('1','0') NOT NULL,
			`country_match` enum('0','1') NOT NULL,
			`counted` int(11) NOT NULL,
			`penalty` int(11) NOT NULL,
			`same_voter` enum('0','1') NOT NULL,
			`activity` int(10) unsigned NOT NULL default '0',
			`object_name` varchar(64) NOT NULL,
			`object_id` int(10) unsigned NOT NULL,
			PRIMARY KEY	(`id`),
			KEY `user_id` (`user_id`)
		",
		"rss_feeds"	=> "
			`id` int(10) unsigned NOT NULL auto_increment,
			`url` varchar(255) character set utf8 NOT NULL default '',
			`name` varchar(255) character set utf8 NOT NULL default '',
			`title` varchar(255) character set utf8 NOT NULL default '',
			`desc` text character set utf8 NOT NULL,
			`order` int(10) unsigned NOT NULL default '0',
			`ttl` int(10) unsigned NOT NULL default '0',
			`active` enum('1','0') NOT NULL default '1',
			`last_checked` int(10) unsigned NOT NULL default '0',
			`last_modified` int(10) unsigned NOT NULL default '0',
			`etag` text NOT NULL,
			`image` text NOT NULL,
			`aggregate_info` text NOT NULL,
			PRIMARY KEY  (`id`)		
		",
		"rss_items"	=> "
			`id` int(10) unsigned NOT NULL auto_increment,
			`feed_id` int(10) unsigned NOT NULL default '0',
			`add_date` int(10) unsigned NOT NULL default '0',
			`link` varchar(255) character set utf8 NOT NULL default '',
			`title` varchar(255) character set utf8 NOT NULL default '',
			`text` text character set utf8 NOT NULL,
			`pub_date` int(10) unsigned NOT NULL default '0',
			`author` varchar(255) character set utf8 NOT NULL default '',
			`cache_md5` varchar(32) NOT NULL default '',
			`guid` varchar(255) character set utf8 NOT NULL default '',
			`aggregate_saved` varchar(255) NOT NULL default '',
			PRIMARY KEY  (`id`),
			UNIQUE KEY `cache_md5` (`cache_md5`)
		",
		"search_engines"	=> "
			`id` int(10) unsigned NOT NULL auto_increment,
			`name` varchar(255) NOT NULL default '',
			`search_url` varchar(255) NOT NULL default '',
			`q_s_word` varchar(255) NOT NULL default '',
			`q_s_word2` varchar(255) NOT NULL default '',
			`q_s_charset` varchar(255) NOT NULL default '',
			`def_charset` varchar(255) NOT NULL default '',
			`active` enum('1','0') NOT NULL default '1',
			PRIMARY KEY	(`id`)
		",
		"search_keywords"	=> "
			`id` int(10) unsigned NOT NULL auto_increment,
			`engine` int(10) unsigned NOT NULL default '0',
			`text` varchar(64) NOT NULL,
			`ref_url` text NOT NULL,
			`site_url` varchar(255) NOT NULL default '',
			`site_id` int(10) unsigned NOT NULL default '0',
			`hits` int(10) unsigned NOT NULL default '0',
			`last_update` int(10) unsigned NOT NULL,
			`active` enum('1','0') NOT NULL default '1',
			PRIMARY KEY	(`id`),
			UNIQUE KEY `text` (`text`),
			KEY `hits` (`hits`),
			FULLTEXT KEY `text_2` (`text`)
		",
		"shop_group_options"	=> "
			`product_id` int(10) unsigned NOT NULL,
			`group_id` int(10) unsigned NOT NULL,
			`price` decimal(8,2) NOT NULL
		",
		"shop_product_related"	=> "
			`product_id` int(11) unsigned NOT NULL,
			`related_id` int(11) unsigned NOT NULL,
			PRIMARY KEY  (`product_id`,`related_id`)
	",
		"shop_product_to_category" => "
			`product_id` int(11) NOT NULL,
			`category_id` int(11) NOT NULL,
			PRIMARY KEY  (`product_id`,`category_id`)
		",
		"shop_products"	=> "
			`id` int(10) unsigned NOT NULL auto_increment,
			`name` varchar(255) collate utf8_unicode_ci NOT NULL default '',
			`url` varchar(255) collate utf8_unicode_ci NOT NULL default '',
			`image` enum('0','1') collate utf8_unicode_ci NOT NULL,
			`description` text collate utf8_unicode_ci NOT NULL,
			`meta_keywords` text collate utf8_unicode_ci NOT NULL,
			`meta_desc` text collate utf8_unicode_ci NOT NULL,
			`external_url` varchar(255) collate utf8_unicode_ci NOT NULL default '',
			`cat_id` text collate utf8_unicode_ci NOT NULL,
			`model` varchar(64) collate utf8_unicode_ci NOT NULL,
			`sku` varchar(64) collate utf8_unicode_ci NOT NULL,
			`quantity` int(4) NOT NULL default '0',
			`stock_status_id` int(11) NOT NULL,
			`manufacturer_id` int(11) NOT NULL,
			`price` decimal(8,2) NOT NULL default '0.00',
			`old_price` decimal(8,2) NOT NULL default '0.00',
			`currency` int(10) unsigned NOT NULL default '0',
			`add_date` int(10) unsigned NOT NULL default '0',
			`last_viewed_date` int(10) NOT NULL,
			`featured` enum('0','1') collate utf8_unicode_ci NOT NULL default '0',
			`active` enum('0','1') collate utf8_unicode_ci NOT NULL,
			`viewed` int(5) NOT NULL default '0',
			PRIMARY KEY  (`id`)
		",
		"shop_manufacturer" => "
			`id` int(11) NOT NULL auto_increment,
			`name` varchar(64) collate utf8_unicode_ci NOT NULL default '',
			`url` varchar(255) collate utf8_unicode_ci NOT NULL,
			`desc` varchar(255) collate utf8_unicode_ci NOT NULL,
			`meta_keywords` text collate utf8_unicode_ci NOT NULL,
			`meta_desc` text collate utf8_unicode_ci NOT NULL,
			`image` int(10) unsigned NOT NULL,
			`sort_order` int(3) NOT NULL,
			PRIMARY KEY  (`id`)
		",
		"shop_orders"	=> "
			`id` int(10) unsigned NOT NULL auto_increment,
			`user_id` int(11) unsigned NOT NULL default '0',
			`date` int(11) unsigned NOT NULL default '0',
			`ship_type` int(11) unsigned NOT NULL default '0',
			`pay_type` int(11) unsigned NOT NULL default '0',
			`total_sum` decimal(12,2) NOT NULL,
			`card_num` varchar(50) NOT NULL,
			`exp_date` varchar(4) NOT NULL,
			`name` varchar(32) NOT NULL,
			`email` varchar(50) NOT NULL,
			`phone` varchar(40) NOT NULL,
			`address` text NOT NULL,
			`comment_c` text NOT NULL,
			`comment_m` text NOT NULL,
			`hash` varchar(128) NOT NULL,
			`status` varchar(16) NOT NULL,
			PRIMARY KEY  (`id`)
		",
		"shop_order_items" => "
			`order_id` int(10) unsigned NOT NULL default '0',
			`product_id` int(10) unsigned NOT NULL default '0',
			`user_id` int(10) unsigned NOT NULL default '0',
			`quantity` int(10) unsigned NOT NULL default '0',
			`attributes` text NOT NULL default '',
			`sum` decimal(12,2) NOT NULL,
			KEY `order_id` (`order_id`)
		",
		"states"	=> "
			`id` int(11) NOT NULL auto_increment,
			`name` varchar(32) NOT NULL default '',
			`code` varchar(32) NOT NULL default '',
			`country_code` char(2) NOT NULL default '',
			PRIMARY KEY	(`id`),
			UNIQUE KEY `code` (`code`),
			KEY `state` (`name`),
			KEY `country_code` (`country_code`)
		",
		"static_pages"	=> "
			`id` int(10) unsigned NOT NULL auto_increment,
			`cat_id` int(10) unsigned NOT NULL default '0',
			`name` varchar(255) NOT NULL default '',
			`text` text NOT NULL default '',
			`page_title` varchar(255) NOT NULL default '',
			`page_heading` varchar(255) NOT NULL default '',
			`meta_keywords` text NOT NULL default '',
			`meta_desc` text NOT NULL default '',
			`locale` char(6) NOT NULL default '',
			`active` enum('1','0') NOT NULL default '1',
			PRIMARY KEY	(`id`)
		",
		"tags"	=> "
			`id` int(10) unsigned NOT NULL auto_increment,
			`object_name` varchar(24) NOT NULL,
			`object_id` int(10) unsigned NOT NULL default '0',
			`user_id` int(10) unsigned NOT NULL default '0',
			`user_name` varchar(255) NOT NULL default '',
			`add_date` int(10) unsigned NOT NULL default '0',
			`text` text NOT NULL,
			`active` tinyint(1) unsigned NOT NULL default '0',
			`activity` int(10) unsigned NOT NULL default '0',
			PRIMARY KEY  (`id`),
			KEY `object_name` (`object_name`),
			KEY `object_id` (`object_id`),
			KEY `user_id` (`user_id`)
		",
		"tags_settings"	=> "
			`user_id` INT UNSIGNED NOT NULL ,
			`allowed_group` TINYINT UNSIGNED NOT NULL ,
			PRIMARY KEY ( `user_id` ) 
		",
		"tips"	=> "
			`id` int(10) unsigned NOT NULL auto_increment,
			`name` varchar(255) NOT NULL default '',
			`text` text CHARACTER SET utf8 NOT NULL,
			`type` tinyint(1) NOT NULL default '1',
			`active` enum('1','0') NOT NULL default '1',
			`locale` char(7) DEFAULT 'en' NOT NULL, 
			PRIMARY KEY	(`id`)
		",
		// Default user table
		"user"	=> "
			`id` int(10) unsigned NOT NULL auto_increment,
			`group` tinyint(3) unsigned NOT NULL default '0',
			`name` varchar(255) NOT NULL default '',
			`nick` varchar(64) NOT NULL default '',
			`login` varchar(64) NOT NULL default '',
			`email` varchar(50) NOT NULL default '',
			`password` varchar(32) NOT NULL default '',
			`phone` varchar(40) NOT NULL default '',
			`city` varchar(40) NOT NULL default '',
			`state` varchar(20) NOT NULL default '',
			`country` varchar(30) NOT NULL default 'USA',
			`zip_code` varchar(16) NOT NULL default '',
			`address` varchar(255) NOT NULL default '',
			`sex` enum('Female','Male') NOT NULL default 'Female',
			`age` smallint(2) unsigned NOT NULL default '0',
			`birth_date` date NOT NULL default '0000-00-00',
			`visits` smallint(6) unsigned NOT NULL default '0',
			`active` tinyint(1) unsigned NOT NULL default '1',
			`add_date` int(10) unsigned NOT NULL default '0',
			`last_update` int(10) unsigned NOT NULL default '0',
			`last_login` int(10) unsigned NOT NULL default '0',
			`num_logins` smallint(6) unsigned NOT NULL default '0',
			`last_view` int(10) unsigned NOT NULL default '0',
			`num_views` int(10) unsigned NOT NULL default '0',
			`verify_code` varchar(32) NOT NULL default '',
			`profile_url` varchar(64) NOT NULL,
			`admin_comments` text NOT NULL,
			`ip` varchar(15) NOT NULL default '',
			`photo_verified` enum('0', '1') NOT NULL,
			`avatar` varchar(255) NOT NULL default '',
			`priority` int(11) NOT NULL default '0',
			`lon` decimal(8,4) NOT NULL default '0.0000',
			`lat` decimal(8,4) NOT NULL default '0.0000',
			`has_avatar` enum('0','1') NOT NULL default '0',
			`contact_by_email` enum('1','0') NOT NULL,
			`emails` smallint(6) unsigned NOT NULL default '0',
			`emailssent` smallint(6) unsigned NOT NULL default '0',
			`go_after_login` varchar(255) NOT NULL default '',

			PRIMARY KEY	(`id`),
			KEY `login` (`login`),
			KEY `nick` (`nick`),
			KEY `active` (`active`),
			KEY `group` (`group`),
			KEY `email` (`email`),
			KEY `has_avatar` (`has_avatar`),
			KEY `priority` (`priority`),
			KEY `country` (`country`)
		",
		"user_ban"	=> "
			`id` mediumint(6) unsigned NOT NULL auto_increment,
			`user_name` varchar(255) NOT NULL default '',
			`email` varchar(255) NOT NULL default '',
			`passwd` varchar(255) NOT NULL default '',
			`text` varchar(255) NOT NULL default '',
			`tel` varchar(255) NOT NULL default '',
			`fax` varchar(255) NOT NULL default '',
			`url` varchar(255) NOT NULL default '',
			`recip_url` varchar(255) NOT NULL default '',
			`ban_ads` tinyint(1) NOT NULL default '1',
			`ban_reviews` tinyint(1) NOT NULL default '1',
			`ban_images` tinyint(1) NOT NULL default '0',
			`ban_email` tinyint(1) NOT NULL default '1',
			`ban_forum` tinyint(1) NOT NULL default '1',
			PRIMARY KEY	(`id`)
		",
		"user_data_ban"	=> "
			`id` int(10) unsigned NOT NULL,
			`ban_ads` tinyint(1) unsigned NOT NULL default '0',
			`ban_reviews` tinyint(1) unsigned NOT NULL default '0',
			`ban_email` tinyint(1) unsigned NOT NULL default '0',
			`ban_images` tinyint(1) unsigned NOT NULL default '0',
			`ban_forum` tinyint(1) unsigned NOT NULL default '0',
			`ban_comments` tinyint(1) unsigned NOT NULL default '0',
			`ban_blog` tinyint(1) unsigned NOT NULL,
			`ban_bad_contact` enum('0','1') NOT NULL,
			PRIMARY KEY  (`id`)
		",
		"user_data_info_fields" => "
			`id` int(10) unsigned NOT NULL auto_increment,
			`name` varchar(64) NOT NULL,
			`type` varchar(64) NOT NULL,
			`value_list` text NOT NULL,
			`default_value` text NOT NULL,
			`comment` text NOT NULL,
			`order` int(10) unsigned NOT NULL,
			`required` enum('0','1') NOT NULL,
			`display_on` text NOT NULL,
			`active` enum('1','0') NOT NULL,
			PRIMARY KEY  (`id`)
		",
		"user_data_info_values"	=> "
			`user_id` int(10) unsigned NOT NULL,
			`field_id` int(10) unsigned NOT NULL,
			`value` text NOT NULL,
			KEY `user_id` (`user_id`)
		",
		"user_data_main"	=> "
			`id` int(10) unsigned NOT NULL auto_increment,
			`group` tinyint(3) unsigned NOT NULL default '0',
			`name` varchar(255) NOT NULL default '',
			`nick` varchar(64) NOT NULL default '',
			`login` varchar(64) NOT NULL default '',
			`email` varchar(128) NOT NULL,
			`password` varchar(12) NOT NULL default '',
			`phone` varchar(40) NOT NULL default '',
			`fax` varchar(40) NOT NULL default '',
			`address` varchar(255) NOT NULL default '',
			`city` varchar(40) NOT NULL default '',
			`zip_code` varchar(16) NOT NULL default '',
			`state` varchar(20) NOT NULL default '',
			`country` varchar(30) NOT NULL default 'USA',
			`sex` enum('Female','Male','Transsexual') NOT NULL,
			`birth_date` date NOT NULL,
			`profile_url` varchar(64) NOT NULL,
			`url` varchar(100) NOT NULL default '',
			`show_mail` enum('0','1') NOT NULL,
			`verify_code` varchar(32) NOT NULL default '',
			`admin_comments` text NOT NULL,
			`avatar` varchar(255) NOT NULL,
			`lon` decimal(8,4) NOT NULL default '0.0000',
			`lat` decimal(8,4) NOT NULL default '0.0000',
			`is_deleted` enum('0','1') NOT NULL,
			`active` tinyint(1) unsigned NOT NULL default '1',
			`level` tinyint(1) unsigned NOT NULL default '0',
			PRIMARY KEY  (`id`),
			KEY `login` (`login`),
			KEY `nick` (`nick`),
			KEY `active` (`active`),
			KEY `group` (`group`),
			KEY `email` (`email`)
		",
		"user_data_stats"	=> "
 			`id` int(10) unsigned NOT NULL,
			`views` smallint(6) unsigned NOT NULL default '0',
			`visits` smallint(6) unsigned NOT NULL default '0',
			`emails` smallint(6) unsigned NOT NULL default '0',
			`emailssent` smallint(6) unsigned NOT NULL default '0',
			`sitevisits` smallint(6) unsigned NOT NULL default '0',
 			`add_date` int(10) unsigned NOT NULL default '0',
			`last_view` int(10) unsigned NOT NULL default '0',
			`last_login` int(10) unsigned NOT NULL default '0',
 			`last_update` int(10) unsigned NOT NULL default '0',
			`num_logins` smallint(6) unsigned NOT NULL default '0',
			`num_views` int(10) unsigned NOT NULL default '0',
 			PRIMARY KEY  (`id`)
		",
/*
		"user_data_stats"	=> "
			`id` int(10) unsigned NOT NULL,
			`add_date` int(10) unsigned NOT NULL default '0',
			`last_view` int(10) unsigned NOT NULL default '0',
			`last_login` int(10) unsigned NOT NULL default '0',
			`last_update` int(10) unsigned NOT NULL default '0',
			`num_views` int(10) unsigned NOT NULL default '0',
			`num_logins` smallint(6) unsigned NOT NULL default '0',
			`num_updates` smallint(6) unsigned NOT NULL default '0',
			`num_r_mails` smallint(6) unsigned NOT NULL default '0',
			`num_s_mails` smallint(6) unsigned NOT NULL default '0',
			PRIMARY KEY  (`id`)
		",
*/
		"user_stats"	=> "
			`user_id` int(10) unsigned NOT NULL,
			`group_id` tinyint(3) unsigned NOT NULL,
			`ads` int(10) unsigned NOT NULL,
			`reviews` int(10) unsigned NOT NULL,
			`gallery_photos` int(10) unsigned NOT NULL,
			`blog_posts` int(10) unsigned NOT NULL,
			`que_answers` int(10) unsigned NOT NULL,
			`forum_posts` int(10) unsigned NOT NULL,
			`comments` int(10) unsigned NOT NULL,
			`articles` INT(10) UNSIGNED NOT NULL,
			`interests` INT(10) UNSIGNED NOT NULL,
			`favorite_users` int(10) unsigned NOT NULL,
			`ignored_users` int(10) unsigned NOT NULL,
			`paid_orders` int(10) unsigned NOT NULL,
			`friend_of` int(10) unsigned NOT NULL,
			`friends` int(10) unsigned NOT NULL,
			`nick` varchar(255) NOT NULL,
			`profile_url` varchar(255) NOT NULL,
			PRIMARY KEY	(`user_id`)
		",
		"user_themes"	=> "
			`id` int(10) unsigned NOT NULL auto_increment,
			`name` varchar(32) NOT NULL,
			`descr` text NOT NULL,
			`active` enum('0','1') NOT NULL,
			`tags` varchar(255) NOT NULL,
			PRIMARY KEY  (`id`)
		",
		"verify_photo" => "
			`id` int(10) unsigned NOT NULL auto_increment,
			`user_id` int(10) unsigned NOT NULL,
			`from_url` varchar(255) NOT NULL,
			`date` int(10) unsigned NOT NULL,
			PRIMARY KEY	(`id`),
			KEY `user_id` (`user_id`)
		",
		"verify_user" => "
			`user_id` int(10) unsigned NOT NULL auto_increment,
			`verified_url_1` varchar(255) NOT NULL,
			`verified_url_2` varchar(255) NOT NULL,
			`verified_url_3` varchar(255) NOT NULL,
			`site_url` varchar(255) NOT NULL,
			`whois` text NOT NULL,
			`status` enum('new','waiting','verified','declined') NOT NULL,
			`admin_comment` text NOT NULL,
			`submit_date` int(10) unsigned NOT NULL,
			`last_update` int(10) unsigned NOT NULL,
			PRIMARY KEY	(`user_id`),
			KEY `status` (`status`),
			KEY `last_update` (`last_update`)
		",
		"weights" => "
			`id` tinyint(4) NOT NULL default '0',
			`weight` varchar(50) NOT NULL default '',
			PRIMARY KEY	(`id`),
			UNIQUE KEY `id_2` (`id`),
			KEY `id` (`id`)
		",
		"zip_data"	=> "
			`id` int(5) unsigned zerofill NOT NULL,
			`lon` float NOT NULL default '0',
			`lat` float NOT NULL default '0'
			UNIQUE KEY `id` (`id`),
			KEY `lon` (`lon`,`lat`)
		",
		"widgets"	=> "
			`id` int(10) unsigned NOT NULL auto_increment,
			`object` text NOT NULL,
			`action` text NOT NULL,
			`theme` text NOT NULL,
			`comments` text NOT NULL,
			`columns` text NOT NULL,
			`site_ids` varchar(255) NOT NULL,
			`server_ids` varchar(255) NOT NULL,
			`active` enum('1','0') NOT NULL default '1',
			PRIMARY KEY  (`id`)
		",
		"unread"	=> "
			`module_name` varchar(30) NOT NULL default '',
			`object_id` int(11) NOT NULL default '0',
			`user_id` int(11) NOT NULL default '0'
		",
	));
	// Try to load chat tables
	$chat_tables_structs_file = YF_PATH."share/installer_chat_tables_structs.php";
	if (file_exists($chat_tables_structs_file)) {
		include_once($chat_tables_structs_file);
	}
	// Try to load forum tables
	$forum_tables_structs_file = YF_PATH."share/installer_forum_tables_structs.php";
	if (file_exists($forum_tables_structs_file)) {
		include_once($forum_tables_structs_file);
	}
?>