<?php
$data = array (
  1 => 
  array (
    'id' => '1',
    'forum' => '1',
    'name' => 'postfix',
    'desc' => 'get problem for Postfix',
    'user_id' => '1',
    'user_name' => 'test',
    'created' => '1207143466',
    'status' => 'a',
    'num_views' => '4',
    'num_posts' => '2',
    'first_post_id' => '1',
    'last_post_id' => '3',
    'last_poster_id' => '1',
    'last_poster_name' => 'test',
    'last_post_date' => '1207143721',
    'icon_id' => '0',
    'pinned' => '0',
    'moved_to' => '',
    'approved' => '1',
    'language' => '0',
  ),
  2 => 
  array (
    'id' => '2',
    'forum' => '1',
    'name' => 'linux',
    'desc' => 'Fed Up with graphics problems in Linux',
    'user_id' => '1',
    'user_name' => 'test',
    'created' => '1207143892',
    'status' => 'a',
    'num_views' => '5',
    'num_posts' => '4',
    'first_post_id' => '4',
    'last_post_id' => '8',
    'last_poster_id' => '1',
    'last_poster_name' => 'test',
    'last_post_date' => '1207144294',
    'icon_id' => '0',
    'pinned' => '0',
    'moved_to' => '',
    'approved' => '1',
    'language' => '0',
  ),
  3 => 
  array (
    'id' => '3',
    'forum' => '1',
    'name' => 'windows',
    'desc' => 'XP Windows Explorer Avi Problem',
    'user_id' => '1',
    'user_name' => 'test',
    'created' => '1207144474',
    'status' => 'a',
    'num_views' => '4',
    'num_posts' => '3',
    'first_post_id' => '9',
    'last_post_id' => '12',
    'last_poster_id' => '1',
    'last_poster_name' => 'test',
    'last_post_date' => '1207144596',
    'icon_id' => '0',
    'pinned' => '0',
    'moved_to' => '',
    'approved' => '1',
    'language' => '0',
  ),
  4 => 
  array (
    'id' => '4',
    'forum' => '2',
    'name' => 'common problems',
    'desc' => '"Problems" window stealing focus in Ecli',
    'user_id' => '4',
    'user_name' => 'ser',
    'created' => '1207832295',
    'status' => 'a',
    'num_views' => '9',
    'num_posts' => '4',
    'first_post_id' => '13',
    'last_post_id' => '17',
    'last_poster_id' => '4',
    'last_poster_name' => 'ser',
    'last_post_date' => '1207833178',
    'icon_id' => '0',
    'pinned' => '0',
    'moved_to' => '',
    'approved' => '1',
    'language' => '0',
  ),
  5 => 
  array (
    'id' => '5',
    'forum' => '2',
    'name' => 'Feature Request',
    'desc' => 'Support for ISO Schematron subject attri',
    'user_id' => '6',
    'user_name' => 'kingargyle',
    'created' => '1207833408',
    'status' => 'a',
    'num_views' => '3',
    'num_posts' => '1',
    'first_post_id' => '18',
    'last_post_id' => '19',
    'last_poster_id' => '4',
    'last_poster_name' => 'ser',
    'last_post_date' => '1207833500',
    'icon_id' => '0',
    'pinned' => '0',
    'moved_to' => '',
    'approved' => '1',
    'language' => '0',
  ),
  6 => 
  array (
    'id' => '6',
    'forum' => '2',
    'name' => 'XSL debugging in Oxygen tutorial',
    'desc' => 'XSL debugging in Oxygen tutorial',
    'user_id' => '7',
    'user_name' => 'xchaotic',
    'created' => '1207837176',
    'status' => 'a',
    'num_views' => '4',
    'num_posts' => '1',
    'first_post_id' => '20',
    'last_post_id' => '21',
    'last_poster_id' => '5',
    'last_poster_name' => 'odlman',
    'last_post_date' => '1207837409',
    'icon_id' => '0',
    'pinned' => '0',
    'moved_to' => '',
    'approved' => '1',
    'language' => '0',
  ),
);