<?php
$data = array (
  1 => 
  array (
    'id' => '1',
    'id2' => '1',
    'user_id' => '1',
    'title' => 'General',
    'comment' => '',
    'allow_comments' => '0',
    'privacy' => '0',
    'content_level' => '0',
    'num_photos' => '0',
    'num_comments' => '0',
    'num_views' => '0',
    'user_nick' => '',
    'password' => '',
    'is_default' => '1',
    'add_date' => '1207235934',
    'active' => '1',
    'allow_tagging' => '0',
  ),
  2 => 
  array (
    'id' => '2',
    'id2' => '1',
    'user_id' => '1',
    'title' => 'new',
    'comment' => 'new',
    'allow_comments' => '1',
    'privacy' => '1',
    'content_level' => '0',
    'num_photos' => '0',
    'num_comments' => '0',
    'num_views' => '0',
    'user_nick' => '',
    'password' => '',
    'is_default' => '0',
    'add_date' => '1207560946',
    'active' => '1',
    'allow_tagging' => '0',
  ),
  3 => 
  array (
    'id' => '3',
    'id2' => '1',
    'user_id' => '5',
    'title' => 'General',
    'comment' => '',
    'allow_comments' => '0',
    'privacy' => '0',
    'content_level' => '0',
    'num_photos' => '0',
    'num_comments' => '0',
    'num_views' => '0',
    'user_nick' => '',
    'password' => '',
    'is_default' => '1',
    'add_date' => '1207908744',
    'active' => '1',
    'allow_tagging' => '0',
  ),
);