<?php
$data = array (
  99999 => 
  array (
    'id' => 1001,
    'menu_id' => 1,
    'parent_id' => 0,
    'name' => 'General Settings',
    'location' => '',
    'type_id' => 3,
    'active' => 1,
  ),
  100000 => 
  array (
    'id' => 1002,
    'menu_id' => 1,
    'parent_id' => 0,
    'name' => 'Tools',
    'location' => '',
    'type_id' => 3,
    'active' => 1,
  ),
  100001 => 
  array (
    'id' => 1003,
    'menu_id' => 1,
    'parent_id' => 0,
    'name' => 'Localization',
    'location' => '',
    'type_id' => 3,
    'active' => 1,
  ),
  100002 => 
  array (
    'id' => 1004,
    'menu_id' => 1,
    'parent_id' => 0,
    'name' => 'Administration',
    'location' => '',
    'type_id' => 3,
    'active' => 1,
  ),
  100003 => 
  array (
    'id' => 1005,
    'menu_id' => 1,
    'parent_id' => 0,
    'name' => 'Modules',
    'location' => '',
    'type_id' => 3,
    'active' => 1,
  ),
  100004 => 
  array (
    'id' => 1006,
    'menu_id' => 1,
    'parent_id' => 0,
    'name' => 'Logs',
    'location' => '',
    'type_id' => 3,
    'active' => 1,
  ),
  100005 => 
  array (
    'id' => 1007,
    'menu_id' => 1,
    'parent_id' => 0,
    'name' => 'Users',
    'location' => '',
    'type_id' => 3,
    'active' => 1,
  ),
  100006 => 
  array (
    'id' => 1008,
    'menu_id' => 1,
    'parent_id' => 0,
    'name' => 'Manage Content',
    'location' => '',
    'type_id' => 3,
    'active' => 1,
  ),
  100007 => 
  array (
    'id' => 1009,
    'menu_id' => 1,
    'parent_id' => 1001,
    'name' => 'Clear Core Cache',
    'location' => 'object=admin_home&action=clear_core_cache',
    'type_id' => 1,
    'active' => 1,
  ),
  100008 => 
  array (
    'id' => 1010,
    'menu_id' => 1,
    'parent_id' => 1001,
    'name' => 'Clear Output Pages Cache',
    'location' => 'object=admin_home&action=clear_output_cache',
    'type_id' => 1,
    'active' => 1,
  ),
  100009 => 
  array (
    'id' => 1011,
    'menu_id' => 1,
    'parent_id' => 1001,
    'name' => 'Change Settings',
    'location' => 'object=settings',
    'type_id' => 1,
    'active' => 1,
  ),
  100010 => 
  array (
    'id' => 1012,
    'menu_id' => 1,
    'parent_id' => 1002,
    'name' => 'File Manager',
    'location' => 'object=file_manager',
    'type_id' => 1,
    'active' => 1,
  ),
  100011 => 
  array (
    'id' => 1325,
    'menu_id' => 1,
    'parent_id' => 1007,
    'name' => 'Help Tickets',
    'location' => 'object=help_tickets',
    'type_id' => 1,
    'active' => 1,
  ),
  100012 => 
  array (
    'id' => 1013,
    'menu_id' => 1,
    'parent_id' => 1007,
    'name' => 'User dynamic info',
    'location' => 'object=user_dynamic_info',
    'type_id' => 1,
    'active' => 1,
  ),
  100013 => 
  array (
    'id' => 1014,
    'menu_id' => 1,
    'parent_id' => 1002,
    'name' => 'Database Manager',
    'location' => 'object=db_manager',
    'type_id' => 1,
    'active' => 1,
  ),
  100014 => 
  array (
    'id' => 1015,
    'menu_id' => 1,
    'parent_id' => 1002,
    'name' => 'Task Manager',
    'location' => 'object=task_planner',
    'type_id' => 1,
    'active' => 1,
  ),
  100015 => 
  array (
    'id' => 1016,
    'menu_id' => 1,
    'parent_id' => 1002,
    'name' => 'Menus Manager',
    'location' => 'object=menus_editor',
    'type_id' => 1,
    'active' => 1,
  ),
  100016 => 
  array (
    'id' => 1017,
    'menu_id' => 1,
    'parent_id' => 1002,
    'name' => 'Categories Editor',
    'location' => 'object=category_editor',
    'type_id' => 1,
    'active' => 1,
  ),
  100017 => 
  array (
    'id' => 1018,
    'menu_id' => 1,
    'parent_id' => 1002,
    'name' => 'Blocks Editor',
    'location' => 'object=blocks',
    'type_id' => 1,
    'active' => 1,
  ),
  100018 => 
  array (
    'id' => 1019,
    'menu_id' => 1,
    'parent_id' => 1002,
    'name' => 'Custom Replace Editor',
    'location' => 'object=custom_replace',
    'type_id' => 1,
    'active' => 1,
  ),
  100019 => 
  array (
    'id' => 1020,
    'menu_id' => 1,
    'parent_id' => 1003,
    'name' => 'Locale Editor',
    'location' => 'object=locale_editor',
    'type_id' => 1,
    'active' => 1,
  ),
  100020 => 
  array (
    'id' => 1021,
    'menu_id' => 1,
    'parent_id' => 1003,
    'name' => 'Tips Editor',
    'location' => 'object=db_parser&table=tips',
    'type_id' => 1,
    'active' => 1,
  ),
  100021 => 
  array (
    'id' => 1022,
    'menu_id' => 1,
    'parent_id' => 1003,
    'name' => 'Template Editor',
    'location' => 'object=template_editor',
    'type_id' => 1,
    'active' => 1,
  ),
  100022 => 
  array (
    'id' => 1023,
    'menu_id' => 1,
    'parent_id' => 1004,
    'name' => 'Admin Groups',
    'location' => 'object=admin_groups',
    'type_id' => 1,
    'active' => 1,
  ),
  100023 => 
  array (
    'id' => 1024,
    'menu_id' => 1,
    'parent_id' => 1004,
    'name' => 'Admin Management',
    'location' => 'object=admin',
    'type_id' => 1,
    'active' => 1,
  ),
  100024 => 
  array (
    'id' => 1025,
    'menu_id' => 1,
    'parent_id' => 1005,
    'name' => 'User Modules Manager',
    'location' => 'object=user_modules',
    'type_id' => 1,
    'active' => 1,
  ),
  100025 => 
  array (
    'id' => 1026,
    'menu_id' => 1,
    'parent_id' => 1005,
    'name' => 'Admin Modules Manager',
    'location' => 'object=admin_modules',
    'type_id' => 1,
    'active' => 1,
  ),
  100026 => 
  array (
    'id' => 1027,
    'menu_id' => 1,
    'parent_id' => 1006,
    'name' => 'Execution Log Analyzer',
    'location' => 'object=log_exec_analyser',
    'type_id' => 1,
    'active' => 1,
  ),
  100027 => 
  array (
    'id' => 1028,
    'menu_id' => 1,
    'parent_id' => 1006,
    'name' => 'Core Errors',
    'location' => 'object=log_core_errors_viewer',
    'type_id' => 1,
    'active' => 1,
  ),
  100028 => 
  array (
    'id' => 1029,
    'menu_id' => 1,
    'parent_id' => 1006,
    'name' => 'User Errors',
    'location' => 'object=log_user_errors_viewer',
    'type_id' => 1,
    'active' => 1,
  ),
  100029 => 
  array (
    'id' => 1030,
    'menu_id' => 1,
    'parent_id' => 1006,
    'name' => 'Emails',
    'location' => 'object=log_emails_viewer',
    'type_id' => 1,
    'active' => 1,
  ),
  100030 => 
  array (
    'id' => 1031,
    'menu_id' => 1,
    'parent_id' => 1006,
    'name' => 'Image Resize',
    'location' => 'object=log_image_resize_viewer',
    'type_id' => 1,
    'active' => 1,
  ),
  100031 => 
  array (
    'id' => 1032,
    'menu_id' => 1,
    'parent_id' => 1006,
    'name' => 'Search Engine Keywords',
    'location' => 'object=se_keywords_manager',
    'type_id' => 1,
    'active' => 1,
  ),
  100032 => 
  array (
    'id' => 1033,
    'menu_id' => 1,
    'parent_id' => 1006,
    'name' => 'Authentification fails',
    'location' => 'object=log_auth_fails_viewer',
    'type_id' => 1,
    'active' => 1,
  ),
  100033 => 
  array (
    'id' => 1034,
    'menu_id' => 1,
    'parent_id' => 1006,
    'name' => 'Webshell Actions',
    'location' => 'object=log_webshell_actions_viewer',
    'type_id' => 1,
    'active' => 1,
  ),
  100034 => 
  array (
    'id' => 1035,
    'menu_id' => 1,
    'parent_id' => 1006,
    'name' => 'SSH actions',
    'location' => 'object=log_ssh_viewer',
    'type_id' => 1,
    'active' => 1,
  ),
  100035 => 
  array (
    'id' => 1036,
    'menu_id' => 1,
    'parent_id' => 1007,
    'name' => 'User Groups',
    'location' => 'object=user_groups',
    'type_id' => 1,
    'active' => 1,
  ),
  100036 => 
  array (
    'id' => 1037,
    'menu_id' => 1,
    'parent_id' => 1007,
    'name' => 'User Management',
    'location' => 'object=members',
    'type_id' => 1,
    'active' => 1,
  ),
  100037 => 
  array (
    'id' => 1038,
    'menu_id' => 1,
    'parent_id' => 1007,
    'name' => 'Online Users',
    'location' => 'object=online_users_manager',
    'type_id' => 1,
    'active' => 1,
  ),
  100038 => 
  array (
    'id' => 1039,
    'menu_id' => 1,
    'parent_id' => 1007,
    'name' => 'Registration Confirmation',
    'location' => 'object=confirm_reg',
    'type_id' => 1,
    'active' => 1,
  ),
  100039 => 
  array (
    'id' => 1040,
    'menu_id' => 1,
    'parent_id' => 1008,
    'name' => 'Static Pages',
    'location' => 'object=static_pages',
    'type_id' => 1,
    'active' => 1,
  ),
  100040 => 
  array (
    'id' => 1041,
    'menu_id' => 1,
    'parent_id' => 1008,
    'name' => 'Forum',
    'location' => 'object=forum',
    'type_id' => 1,
    'active' => 1,
  ),
  100041 => 
  array (
    'id' => 1042,
    'menu_id' => 1,
    'parent_id' => 1008,
    'name' => 'Gallery',
    'location' => 'object=gallery',
    'type_id' => 1,
    'active' => 1,
  ),
  100042 => 
  array (
    'id' => 1043,
    'menu_id' => 1,
    'parent_id' => 1008,
    'name' => 'Blog',
    'location' => 'object=manage_blogs',
    'type_id' => 1,
    'active' => 1,
  ),
  100043 => 
  array (
    'id' => 1044,
    'menu_id' => 1,
    'parent_id' => 1008,
    'name' => 'Articles',
    'location' => 'object=manage_articles',
    'type_id' => 1,
    'active' => 1,
  ),
  100044 => 
  array (
    'id' => 1045,
    'menu_id' => 1,
    'parent_id' => 1008,
    'name' => 'News',
    'location' => 'object=manage_news',
    'type_id' => 1,
    'active' => 1,
  ),
  100045 => 
  array (
    'id' => 1046,
    'menu_id' => 1,
    'parent_id' => 1008,
    'name' => 'Comments',
    'location' => 'object=manage_comments',
    'type_id' => 1,
    'active' => 1,
  ),
  100046 => 
  array (
    'id' => 1352,
    'menu_id' => 1,
    'parent_id' => 1346,
    'name' => 'Email alerts logs',
    'location' => 'object=log_alert_emails',
    'type_id' => 1,
    'active' => 1,
  ),
  100047 => 
  array (
    'id' => 1323,
    'menu_id' => 1,
    'parent_id' => 1270,
    'name' => 'Re-build packed code',
    'location' => 'object=admin_home&action=rebuild_packed_code',
    'type_id' => 1,
    'active' => 1,
  ),
  100048 => 
  array (
    'id' => 1314,
    'menu_id' => 1,
    'parent_id' => 1312,
    'name' => 'Forum',
    'location' => 'object=forum',
    'type_id' => 1,
    'active' => 1,
  ),
  100049 => 
  array (
    'id' => 1315,
    'menu_id' => 1,
    'parent_id' => 1312,
    'name' => 'Gallery',
    'location' => 'object=gallery',
    'type_id' => 1,
    'active' => 1,
  ),
  100050 => 
  array (
    'id' => 1316,
    'menu_id' => 1,
    'parent_id' => 1312,
    'name' => 'Blog',
    'location' => 'object=manage_blogs',
    'type_id' => 1,
    'active' => 1,
  ),
  100051 => 
  array (
    'id' => 1317,
    'menu_id' => 1,
    'parent_id' => 1312,
    'name' => 'Articles',
    'location' => 'object=manage_articles',
    'type_id' => 1,
    'active' => 1,
  ),
  100052 => 
  array (
    'id' => 1318,
    'menu_id' => 1,
    'parent_id' => 1312,
    'name' => 'News',
    'location' => 'object=manage_news',
    'type_id' => 1,
    'active' => 1,
  ),
  100053 => 
  array (
    'id' => 1319,
    'menu_id' => 1,
    'parent_id' => 1312,
    'name' => 'Comments',
    'location' => 'object=manage_comments',
    'type_id' => 1,
    'active' => 1,
  ),
  100054 => 
  array (
    'id' => 1324,
    'menu_id' => 1,
    'parent_id' => 0,
    'name' => 'My Account',
    'location' => '',
    'type_id' => 3,
    'active' => 1,
  ),
  100055 => 
  array (
    'id' => 1326,
    'menu_id' => 1,
    'parent_id' => 1324,
    'name' => 'Edit Account Info',
    'location' => 'object=admin_home&action=edit_account',
    'type_id' => 1,
    'active' => 1,
  ),
  100056 => 
  array (
    'id' => 1327,
    'menu_id' => 1,
    'parent_id' => 1324,
    'name' => 'Logout',
    'location' => 'task=logout',
    'type_id' => 1,
    'active' => 1,
  ),
  100057 => 
  array (
    'id' => 1328,
    'menu_id' => 1,
    'parent_id' => 1312,
    'name' => 'Widgets',
    'location' => 'object=widgets_editor',
    'type_id' => 1,
    'active' => 1,
  ),
  100058 => 
  array (
    'id' => 1313,
    'menu_id' => 1,
    'parent_id' => 1312,
    'name' => 'Static Pages',
    'location' => 'object=static_pages',
    'type_id' => 1,
    'active' => 1,
  ),
  100059 => 
  array (
    'id' => 1273,
    'menu_id' => 1,
    'parent_id' => 1270,
    'name' => 'Configuration Editor',
    'location' => 'object=conf_editor',
    'type_id' => 1,
    'active' => 1,
  ),
  100060 => 
  array (
    'id' => 1272,
    'menu_id' => 1,
    'parent_id' => 1270,
    'name' => 'Clear Output Pages Cache',
    'location' => 'object=admin_home&action=clear_output_cache',
    'type_id' => 1,
    'active' => 1,
  ),
  100061 => 
  array (
    'id' => 1271,
    'menu_id' => 1,
    'parent_id' => 1270,
    'name' => 'Clear Core Cache',
    'location' => 'object=admin_home&action=clear_core_cache',
    'type_id' => 1,
    'active' => 1,
  ),
  100062 => 
  array (
    'id' => 1270,
    'menu_id' => 1,
    'parent_id' => 0,
    'name' => 'Settings',
    'location' => '',
    'type_id' => 3,
    'active' => 1,
  ),
  100063 => 
  array (
    'id' => 1405,
    'menu_id' => 5,
    'parent_id' => 0,
    'name' => 'Settings',
    'location' => '',
    'type_id' => 3,
    'order' => '1',
    'active' => 1,
  ),
  100064 => 
  array (
    'id' => 1274,
    'menu_id' => 5,
    'parent_id' => 0,
    'name' => 'Tools',
    'location' => '',
    'type_id' => 3,
    'order' => '2',
    'active' => 1,
  ),
  100065 => 
  array (
    'id' => 1286,
    'menu_id' => 5,
    'parent_id' => 0,
    'name' => 'Localization',
    'location' => '',
    'type_id' => 3,
    'order' => '3',
    'active' => 1,
  ),
  100066 => 
  array (
    'id' => 1290,
    'menu_id' => 5,
    'parent_id' => 0,
    'name' => 'Administration',
    'location' => '',
    'type_id' => 3,
    'order' => '4',
    'active' => 1,
  ),
  100067 => 
  array (
    'id' => 1293,
    'menu_id' => 5,
    'parent_id' => 0,
    'name' => 'Modules',
    'location' => '',
    'type_id' => 3,
    'order' => '5',
    'active' => 1,
  ),
  100068 => 
  array (
    'id' => 1396,
    'menu_id' => 5,
    'parent_id' => 0,
    'name' => 'My Account',
    'location' => '',
    'type_id' => 3,
    'order' => '6',
    'active' => 1,
  ),
  100069 => 
  array (
    'id' => 1296,
    'menu_id' => 5,
    'parent_id' => 0,
    'name' => 'Logs',
    'location' => '',
    'type_id' => 3,
    'order' => '7',
    'active' => 1,
  ),
  100070 => 
  array (
    'id' => 1306,
    'menu_id' => 5,
    'parent_id' => 0,
    'name' => 'Users',
    'location' => '',
    'type_id' => 3,
    'order' => '8',
    'active' => 1,
  ),
  100071 => 
  array (
    'id' => 1312,
    'menu_id' => 5,
    'parent_id' => 0,
    'name' => 'Content',
    'location' => '',
    'type_id' => 3,
    'order' => '9',
    'active' => 1,
  ),
  100072 => 
  array (
    'id' => 1353,
    'menu_id' => 5,
    'parent_id' => 1274,
    'name' => 'File Manager',
    'location' => 'object=file_manager',
    'type_id' => 1,
    'order' => '',
    'active' => 1,
  ),
  100073 => 
  array (
    'id' => 1408,
    'menu_id' => 5,
    'parent_id' => 1306,
    'name' => 'Help Tickets',
    'location' => 'object=help_tickets',
    'type_id' => 1,
    'order' => '',
    'active' => 1,
  ),
  100074 => 
  array (
    'id' => 1354,
    'menu_id' => 5,
    'parent_id' => 1306,
    'name' => 'User dynamic info',
    'location' => 'object=user_dynamic_info',
    'type_id' => 1,
    'order' => '',
    'active' => 1,
  ),
  100075 => 
  array (
    'id' => 1355,
    'menu_id' => 5,
    'parent_id' => 1274,
    'name' => 'Database Manager',
    'location' => 'object=db_manager',
    'type_id' => 1,
    'order' => '',
    'active' => 1,
  ),
  100076 => 
  array (
    'id' => 1356,
    'menu_id' => 5,
    'parent_id' => 1274,
    'name' => 'Task Manager',
    'location' => 'object=task_planner',
    'type_id' => 1,
    'order' => '',
    'active' => 1,
  ),
  100077 => 
  array (
    'id' => 1357,
    'menu_id' => 5,
    'parent_id' => 1274,
    'name' => 'Menus Manager',
    'location' => 'object=menus_editor',
    'type_id' => 1,
    'order' => '',
    'active' => 1,
  ),
  100078 => 
  array (
    'id' => 1358,
    'menu_id' => 5,
    'parent_id' => 1274,
    'name' => 'Categories Editor',
    'location' => 'object=category_editor',
    'type_id' => 1,
    'order' => '',
    'active' => 1,
  ),
  100079 => 
  array (
    'id' => 1359,
    'menu_id' => 5,
    'parent_id' => 1274,
    'name' => 'Blocks Editor',
    'location' => 'object=blocks',
    'type_id' => 1,
    'order' => '',
    'active' => 1,
  ),
  100080 => 
  array (
    'id' => 1360,
    'menu_id' => 5,
    'parent_id' => 1274,
    'name' => 'Custom Replace Editor',
    'location' => 'object=custom_replace',
    'type_id' => 1,
    'order' => '',
    'active' => 1,
  ),
  100081 => 
  array (
    'id' => 1361,
    'menu_id' => 5,
    'parent_id' => 1286,
    'name' => 'Locale Editor',
    'location' => 'object=locale_editor',
    'type_id' => 1,
    'order' => '',
    'active' => 1,
  ),
  100082 => 
  array (
    'id' => 1362,
    'menu_id' => 5,
    'parent_id' => 1286,
    'name' => 'Tips Editor',
    'location' => 'object=db_parser&table=tips',
    'type_id' => 1,
    'order' => '',
    'active' => 1,
  ),
  100083 => 
  array (
    'id' => 1363,
    'menu_id' => 5,
    'parent_id' => 1286,
    'name' => 'Template Editor',
    'location' => 'object=template_editor',
    'type_id' => 1,
    'order' => '',
    'active' => 1,
  ),
  100084 => 
  array (
    'id' => 1364,
    'menu_id' => 5,
    'parent_id' => 1290,
    'name' => 'Admin Groups',
    'location' => 'object=admin_groups',
    'type_id' => 1,
    'order' => '',
    'active' => 1,
  ),
  100085 => 
  array (
    'id' => 1365,
    'menu_id' => 5,
    'parent_id' => 1290,
    'name' => 'Admin Management',
    'location' => 'object=admin',
    'type_id' => 1,
    'order' => '',
    'active' => 1,
  ),
  100086 => 
  array (
    'id' => 1366,
    'menu_id' => 5,
    'parent_id' => 1293,
    'name' => 'User Modules Manager',
    'location' => 'object=user_modules',
    'type_id' => 1,
    'order' => '',
    'active' => 1,
  ),
  100087 => 
  array (
    'id' => 1367,
    'menu_id' => 5,
    'parent_id' => 1293,
    'name' => 'Admin Modules Manager',
    'location' => 'object=admin_modules',
    'type_id' => 1,
    'order' => '',
    'active' => 1,
  ),
  100088 => 
  array (
    'id' => 1368,
    'menu_id' => 5,
    'parent_id' => 1296,
    'name' => 'Execution Log Analyzer',
    'location' => 'object=log_exec_analyser',
    'type_id' => 1,
    'order' => '',
    'active' => 1,
  ),
  100089 => 
  array (
    'id' => 1369,
    'menu_id' => 5,
    'parent_id' => 1296,
    'name' => 'Core Errors',
    'location' => 'object=log_core_errors_viewer',
    'type_id' => 1,
    'order' => '',
    'active' => 1,
  ),
  100090 => 
  array (
    'id' => 1370,
    'menu_id' => 5,
    'parent_id' => 1296,
    'name' => 'User Errors',
    'location' => 'object=log_user_errors_viewer',
    'type_id' => 1,
    'order' => '',
    'active' => 1,
  ),
  100091 => 
  array (
    'id' => 1371,
    'menu_id' => 5,
    'parent_id' => 1296,
    'name' => 'Emails',
    'location' => 'object=log_emails_viewer',
    'type_id' => 1,
    'order' => '',
    'active' => 1,
  ),
  100092 => 
  array (
    'id' => 1372,
    'menu_id' => 5,
    'parent_id' => 1296,
    'name' => 'Image Resize',
    'location' => 'object=log_image_resize_viewer',
    'type_id' => 1,
    'order' => '',
    'active' => 1,
  ),
  100093 => 
  array (
    'id' => 1373,
    'menu_id' => 5,
    'parent_id' => 1296,
    'name' => 'Search Engine Keywords',
    'location' => 'object=se_keywords_manager',
    'type_id' => 1,
    'order' => '',
    'active' => 1,
  ),
  100094 => 
  array (
    'id' => 1374,
    'menu_id' => 5,
    'parent_id' => 1296,
    'name' => 'Authentification fails',
    'location' => 'object=log_auth_fails_viewer',
    'type_id' => 1,
    'order' => '',
    'active' => 1,
  ),
  100095 => 
  array (
    'id' => 1375,
    'menu_id' => 5,
    'parent_id' => 1296,
    'name' => 'Webshell Actions',
    'location' => 'object=log_webshell_actions_viewer',
    'type_id' => 1,
    'order' => '',
    'active' => 1,
  ),
  100096 => 
  array (
    'id' => 1376,
    'menu_id' => 5,
    'parent_id' => 1296,
    'name' => 'SSH actions',
    'location' => 'object=log_ssh_viewer',
    'type_id' => 1,
    'order' => '',
    'active' => 1,
  ),
  100097 => 
  array (
    'id' => 1377,
    'menu_id' => 5,
    'parent_id' => 1306,
    'name' => 'User Groups',
    'location' => 'object=user_groups',
    'type_id' => 1,
    'order' => '',
    'active' => 1,
  ),
  100098 => 
  array (
    'id' => 1378,
    'menu_id' => 5,
    'parent_id' => 1306,
    'name' => 'User Management',
    'location' => 'object=members',
    'type_id' => 1,
    'order' => '',
    'active' => 1,
  ),
  100099 => 
  array (
    'id' => 1379,
    'menu_id' => 5,
    'parent_id' => 1306,
    'name' => 'Online Users',
    'location' => 'object=online_users_manager',
    'type_id' => 1,
    'order' => '',
    'active' => 1,
  ),
  100100 => 
  array (
    'id' => 1380,
    'menu_id' => 5,
    'parent_id' => 1306,
    'name' => 'Registration Confirmation',
    'location' => 'object=confirm_reg',
    'type_id' => 1,
    'order' => '',
    'active' => 1,
  ),
  100101 => 
  array (
    'id' => 1381,
    'menu_id' => 5,
    'parent_id' => 1312,
    'name' => 'Static Pages',
    'location' => 'object=static_pages',
    'type_id' => 1,
    'order' => '',
    'active' => 1,
  ),
  100102 => 
  array (
    'id' => 1382,
    'menu_id' => 5,
    'parent_id' => 1312,
    'name' => 'Forum',
    'location' => 'object=forum',
    'type_id' => 1,
    'order' => '',
    'active' => 1,
  ),
  100103 => 
  array (
    'id' => 1383,
    'menu_id' => 5,
    'parent_id' => 1312,
    'name' => 'Gallery',
    'location' => 'object=gallery',
    'type_id' => 1,
    'order' => '',
    'active' => 1,
  ),
  100104 => 
  array (
    'id' => 1384,
    'menu_id' => 5,
    'parent_id' => 1312,
    'name' => 'Blog',
    'location' => 'object=manage_blogs',
    'type_id' => 1,
    'order' => '',
    'active' => 1,
  ),
  100105 => 
  array (
    'id' => 1385,
    'menu_id' => 5,
    'parent_id' => 1312,
    'name' => 'Articles',
    'location' => 'object=manage_articles',
    'type_id' => 1,
    'order' => '',
    'active' => 1,
  ),
  100106 => 
  array (
    'id' => 1386,
    'menu_id' => 5,
    'parent_id' => 1312,
    'name' => 'News',
    'location' => 'object=manage_news',
    'type_id' => 1,
    'order' => '',
    'active' => 1,
  ),
  100107 => 
  array (
    'id' => 1387,
    'menu_id' => 5,
    'parent_id' => 1312,
    'name' => 'Comments',
    'location' => 'object=manage_comments',
    'type_id' => 1,
    'order' => '',
    'active' => 1,
  ),
  100108 => 
  array (
    'id' => 1388,
    'menu_id' => 5,
    'parent_id' => 1230,
    'name' => 'Alerts',
    'location' => 'object=account&action=manage_alerts',
    'type_id' => 1,
    'order' => '',
    'active' => 1,
  ),
  100109 => 
  array (
    'id' => 1389,
    'menu_id' => 5,
    'parent_id' => 1346,
    'name' => 'Email alerts logs',
    'location' => 'object=log_alert_emails',
    'type_id' => 1,
    'order' => '',
    'active' => 1,
  ),
  100110 => 
  array (
    'id' => 1390,
    'menu_id' => 5,
    'parent_id' => 1312,
    'name' => 'Forum',
    'location' => 'object=forum',
    'type_id' => 1,
    'order' => '',
    'active' => 1,
  ),
  100111 => 
  array (
    'id' => 1391,
    'menu_id' => 5,
    'parent_id' => 1312,
    'name' => 'Gallery',
    'location' => 'object=gallery',
    'type_id' => 1,
    'order' => '',
    'active' => 1,
  ),
  100112 => 
  array (
    'id' => 1392,
    'menu_id' => 5,
    'parent_id' => 1312,
    'name' => 'Blog',
    'location' => 'object=manage_blogs',
    'type_id' => 1,
    'order' => '',
    'active' => 1,
  ),
  100113 => 
  array (
    'id' => 1393,
    'menu_id' => 5,
    'parent_id' => 1312,
    'name' => 'Articles',
    'location' => 'object=manage_articles',
    'type_id' => 1,
    'order' => '',
    'active' => 1,
  ),
  100114 => 
  array (
    'id' => 1394,
    'menu_id' => 5,
    'parent_id' => 1312,
    'name' => 'News',
    'location' => 'object=manage_news',
    'type_id' => 1,
    'order' => '',
    'active' => 1,
  ),
  100115 => 
  array (
    'id' => 1395,
    'menu_id' => 5,
    'parent_id' => 1312,
    'name' => 'Comments',
    'location' => 'object=manage_comments',
    'type_id' => 1,
    'order' => '',
    'active' => 1,
  ),
  100116 => 
  array (
    'id' => 1397,
    'menu_id' => 5,
    'parent_id' => 1324,
    'name' => 'Edit Account Info',
    'location' => 'object=admin_home&action=edit_account',
    'type_id' => 1,
    'order' => '',
    'active' => 1,
  ),
  100117 => 
  array (
    'id' => 1398,
    'menu_id' => 5,
    'parent_id' => 1398,
    'name' => 'Logout',
    'location' => 'task=logout',
    'type_id' => 1,
    'order' => '',
    'active' => 1,
  ),
  100118 => 
  array (
    'id' => 1399,
    'menu_id' => 5,
    'parent_id' => 1395,
    'name' => 'Widgets',
    'location' => 'object=widgets_editor',
    'type_id' => 1,
    'order' => '',
    'active' => 1,
  ),
  100119 => 
  array (
    'id' => 1400,
    'menu_id' => 5,
    'parent_id' => 1312,
    'name' => 'Static Pages',
    'location' => 'object=static_pages',
    'type_id' => 1,
    'order' => '',
    'active' => 1,
  ),
  100120 => 
  array (
    'id' => 1401,
    'menu_id' => 5,
    'parent_id' => 1405,
    'name' => 'Configuration Editor',
    'location' => 'object=conf_editor',
    'type_id' => 1,
    'order' => '',
    'active' => 1,
  ),
  100121 => 
  array (
    'id' => 1402,
    'menu_id' => 5,
    'parent_id' => 1405,
    'name' => 'Clear Output Pages Cache',
    'location' => 'object=admin_home&action=clear_output_cache',
    'type_id' => 1,
    'order' => '',
    'active' => 1,
  ),
  100122 => 
  array (
    'id' => 1403,
    'menu_id' => 5,
    'parent_id' => 1405,
    'name' => 'Clear Core Cache',
    'location' => 'object=admin_home&action=clear_core_cache',
    'type_id' => 1,
    'order' => '',
    'active' => 1,
  ),
  100123 => 
  array (
    'id' => 1404,
    'menu_id' => 5,
    'parent_id' => 1405,
    'name' => 'Re-build packed code',
    'location' => 'object=admin_home&action=rebuild_packed_code',
    'type_id' => 1,
    'order' => '',
    'active' => 1,
  ),
  100124 => 
  array (
    'id' => 1406,
    'menu_id' => 5,
    'parent_id' => 1396,
    'name' => 'Edit Account Info',
    'location' => 'object=admin_home&action=edit_account',
    'type_id' => 1,
    'order' => '',
    'active' => 1,
  ),
  100125 => 
  array (
    'id' => 1407,
    'menu_id' => 5,
    'parent_id' => 1396,
    'name' => 'Logout',
    'location' => 'task=logout',
    'type_id' => 1,
    'order' => '',
    'active' => 1,
  ),
);