<?php
return '
	`id` mediumint(8) unsigned NOT NULL auto_increment,
	`active` tinyint(1) NOT NULL default \'1\',
	`forums_list` text NOT NULL,
	`member_name` varchar(32) NOT NULL default \'\',
	`member_id` mediumint(8) unsigned NOT NULL default \'0\',
	`view_ip` tinyint(1) unsigned NOT NULL default \'0\',
	`delete_own_topics` tinyint(1) unsigned NOT NULL default \'0\',
	`delete_other_topics` tinyint(1) unsigned NOT NULL default \'0\',
	`edit_own_topics` tinyint(1) unsigned NOT NULL default \'0\',
	`edit_other_topics` tinyint(1) unsigned NOT NULL default \'0\',
	`open_topics` tinyint(1) unsigned NOT NULL default \'0\',
	`close_topics` tinyint(1) unsigned NOT NULL default \'0\',
	`pin_topics` tinyint(1) unsigned NOT NULL default \'0\',
	`unpin_topics` tinyint(1) unsigned NOT NULL default \'0\',
	`move_topics` tinyint(1) unsigned NOT NULL default \'0\',
	`open_close_posts` tinyint(1) unsigned NOT NULL default \'0\',
	`delete_own_posts` tinyint(1) unsigned NOT NULL default \'0\',
	`delete_other_posts` tinyint(1) unsigned NOT NULL default \'0\',
	`edit_own_posts` tinyint(1) unsigned NOT NULL default \'0\',
	`edit_other_posts` tinyint(1) unsigned NOT NULL default \'0\',
	`move_posts` tinyint(1) unsigned NOT NULL default \'0\',
	`split_merge` tinyint(1) unsigned NOT NULL default \'0\',
	`edit_own_profile` tinyint(1) unsigned NOT NULL default \'0\',
	`edit_other_profile` tinyint(1) unsigned NOT NULL default \'0\',
	`make_polls` tinyint(1) unsigned NOT NULL default \'0\',
	`vote_polls` tinyint(1) unsigned NOT NULL default \'0\',
	PRIMARY KEY	(`id`)
';