INSERT INTO `cc` (n,c) VALUES ('Afghanistan','AF');
INSERT INTO `cc` (n,c) VALUES ('Aland Islands','AX');
INSERT INTO `cc` (n,c) VALUES ('Albania','AL');
INSERT INTO `cc` (n,c) VALUES ('Algeria','DZ');
INSERT INTO `cc` (n,c) VALUES ('American Samoa','AS');
INSERT INTO `cc` (n,c) VALUES ('Andorra','AD');
INSERT INTO `cc` (n,c) VALUES ('Angola','AO');
INSERT INTO `cc` (n,c) VALUES ('Anguilla','AI');
INSERT INTO `cc` (n,c) VALUES ('Antarctica','AQ');
INSERT INTO `cc` (n,c) VALUES ('Antigua and Barbuda','AG');
INSERT INTO `cc` (n,c) VALUES ('Argentina','AR');
INSERT INTO `cc` (n,c) VALUES ('Armenia','AM');
INSERT INTO `cc` (n,c) VALUES ('Aruba','AW');
INSERT INTO `cc` (n,c) VALUES ('Australia','AU');
INSERT INTO `cc` (n,c) VALUES ('Austria','AT');
INSERT INTO `cc` (n,c) VALUES ('Azerbaijan','AZ');
INSERT INTO `cc` (n,c) VALUES ('Bahamas','BS');
INSERT INTO `cc` (n,c) VALUES ('Bahrain','BH');
INSERT INTO `cc` (n,c) VALUES ('Bangladesh','BD');
INSERT INTO `cc` (n,c) VALUES ('Barbados','BB');
INSERT INTO `cc` (n,c) VALUES ('Belarus','BY');
INSERT INTO `cc` (n,c) VALUES ('Belgium','BE');
INSERT INTO `cc` (n,c) VALUES ('Belize','BZ');
INSERT INTO `cc` (n,c) VALUES ('Benin','BJ');
INSERT INTO `cc` (n,c) VALUES ('Bermuda','BM');
INSERT INTO `cc` (n,c) VALUES ('Bhutan','BT');
INSERT INTO `cc` (n,c) VALUES ('Bolivia','BO');
INSERT INTO `cc` (n,c) VALUES ('Bosnia and Herzegovina','BA');
INSERT INTO `cc` (n,c) VALUES ('Botswana','BW');
INSERT INTO `cc` (n,c) VALUES ('Bouvet Island','BV');
INSERT INTO `cc` (n,c) VALUES ('Brazil','BR');
INSERT INTO `cc` (n,c) VALUES ('British Indian Ocean Territory','IO');
INSERT INTO `cc` (n,c) VALUES ('Brunei Darussalam','BN');
INSERT INTO `cc` (n,c) VALUES ('Bulgaria','BG');
INSERT INTO `cc` (n,c) VALUES ('Burkina Faso','BF');
INSERT INTO `cc` (n,c) VALUES ('Burundi','BI');
INSERT INTO `cc` (n,c) VALUES ('Cambodia','KH');
INSERT INTO `cc` (n,c) VALUES ('Cameroon','CM');
INSERT INTO `cc` (n,c) VALUES ('Canada','CA');
INSERT INTO `cc` (n,c) VALUES ('Cape Verde','CV');
INSERT INTO `cc` (n,c) VALUES ('Cayman Islands','KY');
INSERT INTO `cc` (n,c) VALUES ('Central African Republic','CF');
INSERT INTO `cc` (n,c) VALUES ('Chad','TD');
INSERT INTO `cc` (n,c) VALUES ('Chile','CL');
INSERT INTO `cc` (n,c) VALUES ('China','CN');
INSERT INTO `cc` (n,c) VALUES ('Christmas Island','CX');
INSERT INTO `cc` (n,c) VALUES ('Cocos (Keeling) Islands','CC');
INSERT INTO `cc` (n,c) VALUES ('Colombia','CO');
INSERT INTO `cc` (n,c) VALUES ('Comoros','KM');
INSERT INTO `cc` (n,c) VALUES ('Congo','CG');
INSERT INTO `cc` (n,c) VALUES ('Congo, Democratic Republic of the','CD');
INSERT INTO `cc` (n,c) VALUES ('Cook Islands','CK');
INSERT INTO `cc` (n,c) VALUES ('Costa Rica','CR');
INSERT INTO `cc` (n,c) VALUES ('Cote d\'Ivoire','CI');
INSERT INTO `cc` (n,c) VALUES ('Croatia','HR');
INSERT INTO `cc` (n,c) VALUES ('Cuba','CU');
INSERT INTO `cc` (n,c) VALUES ('Cyprus','CY');
INSERT INTO `cc` (n,c) VALUES ('Czech Republic','CZ');
INSERT INTO `cc` (n,c) VALUES ('Denmark','DK');
INSERT INTO `cc` (n,c) VALUES ('Djibouti','DJ');
INSERT INTO `cc` (n,c) VALUES ('Dominica','DM');
INSERT INTO `cc` (n,c) VALUES ('Dominican Republic','DO');
INSERT INTO `cc` (n,c) VALUES ('Ecuador','EC');
INSERT INTO `cc` (n,c) VALUES ('Egypt','EG');
INSERT INTO `cc` (n,c) VALUES ('El Salvador','SV');
INSERT INTO `cc` (n,c) VALUES ('Equatorial Guinea','GQ');
INSERT INTO `cc` (n,c) VALUES ('Eritrea','ER');
INSERT INTO `cc` (n,c) VALUES ('Estonia','EE');
INSERT INTO `cc` (n,c) VALUES ('Ethiopia','ET');
INSERT INTO `cc` (n,c) VALUES ('Falkland Islands','FK');
INSERT INTO `cc` (n,c) VALUES ('Faroe Islands','FO');
INSERT INTO `cc` (n,c) VALUES ('Fiji','FJ');
INSERT INTO `cc` (n,c) VALUES ('Finland','FI');
INSERT INTO `cc` (n,c) VALUES ('France','FR');
INSERT INTO `cc` (n,c) VALUES ('French Guiana','GF');
INSERT INTO `cc` (n,c) VALUES ('French Polynesia','PF');
INSERT INTO `cc` (n,c) VALUES ('French Southern Territories','TF');
INSERT INTO `cc` (n,c) VALUES ('Gabon','GA');
INSERT INTO `cc` (n,c) VALUES ('Gambia','GM');
INSERT INTO `cc` (n,c) VALUES ('Georgia','GE');
INSERT INTO `cc` (n,c) VALUES ('Germany','DE');
INSERT INTO `cc` (n,c) VALUES ('Ghana','GH');
INSERT INTO `cc` (n,c) VALUES ('Gibraltar','GI');
INSERT INTO `cc` (n,c) VALUES ('Greece','GR');
INSERT INTO `cc` (n,c) VALUES ('Greenland','GL');
INSERT INTO `cc` (n,c) VALUES ('Grenada','GD');
INSERT INTO `cc` (n,c) VALUES ('Guadeloupe','GP');
INSERT INTO `cc` (n,c) VALUES ('Guam','GU');
INSERT INTO `cc` (n,c) VALUES ('Guatemala','GT');
INSERT INTO `cc` (n,c) VALUES ('Guernsey','GG');
INSERT INTO `cc` (n,c) VALUES ('Guinea','GN');
INSERT INTO `cc` (n,c) VALUES ('Guinea-Bissau','GW');
INSERT INTO `cc` (n,c) VALUES ('Guyana','GY');
INSERT INTO `cc` (n,c) VALUES ('Haiti','HT');
INSERT INTO `cc` (n,c) VALUES ('Heard Island and McDonald Islands','HM');
INSERT INTO `cc` (n,c) VALUES ('Vatican City','VA');
INSERT INTO `cc` (n,c) VALUES ('Honduras','HN');
INSERT INTO `cc` (n,c) VALUES ('Hong Kong','HK');
INSERT INTO `cc` (n,c) VALUES ('Hungary','HU');
INSERT INTO `cc` (n,c) VALUES ('Iceland','IS');
INSERT INTO `cc` (n,c) VALUES ('India','IN');
INSERT INTO `cc` (n,c) VALUES ('Indonesia','ID');
INSERT INTO `cc` (n,c) VALUES ('Iran','IR');
INSERT INTO `cc` (n,c) VALUES ('Iraq','IQ');
INSERT INTO `cc` (n,c) VALUES ('Ireland','IE');
INSERT INTO `cc` (n,c) VALUES ('Isle of Man','IM');
INSERT INTO `cc` (n,c) VALUES ('Israel','IL');
INSERT INTO `cc` (n,c) VALUES ('Italy','IT');
INSERT INTO `cc` (n,c) VALUES ('Jamaica','JM');
INSERT INTO `cc` (n,c) VALUES ('Japan','JP');
INSERT INTO `cc` (n,c) VALUES ('Jersey','JE');
INSERT INTO `cc` (n,c) VALUES ('Jordan','JO');
INSERT INTO `cc` (n,c) VALUES ('Kazakhstan','KZ');
INSERT INTO `cc` (n,c) VALUES ('Kenya','KE');
INSERT INTO `cc` (n,c) VALUES ('Kiribati','KI');
INSERT INTO `cc` (n,c) VALUES ('North Korea','KP');
INSERT INTO `cc` (n,c) VALUES ('South Korea','KR');
INSERT INTO `cc` (n,c) VALUES ('Kuwait','KW');
INSERT INTO `cc` (n,c) VALUES ('Kyrgyzstan','KG');
INSERT INTO `cc` (n,c) VALUES ('Laos','LA');
INSERT INTO `cc` (n,c) VALUES ('Latvia','LV');
INSERT INTO `cc` (n,c) VALUES ('Lebanon','LB');
INSERT INTO `cc` (n,c) VALUES ('Lesotho','LS');
INSERT INTO `cc` (n,c) VALUES ('Liberia','LR');
INSERT INTO `cc` (n,c) VALUES ('Libya','LY');
INSERT INTO `cc` (n,c) VALUES ('Liechtenstein','LI');
INSERT INTO `cc` (n,c) VALUES ('Lithuania','LT');
INSERT INTO `cc` (n,c) VALUES ('Luxembourg','LU');
INSERT INTO `cc` (n,c) VALUES ('Macao','MO');
INSERT INTO `cc` (n,c) VALUES ('Macedonia, the former Yugoslav Republic of','MK');
INSERT INTO `cc` (n,c) VALUES ('Madagascar','MG');
INSERT INTO `cc` (n,c) VALUES ('Malawi','MW');
INSERT INTO `cc` (n,c) VALUES ('Malaysia','MY');
INSERT INTO `cc` (n,c) VALUES ('Maldives','MV');
INSERT INTO `cc` (n,c) VALUES ('Mali','ML');
INSERT INTO `cc` (n,c) VALUES ('Malta','MT');
INSERT INTO `cc` (n,c) VALUES ('Marshall Islands','MH');
INSERT INTO `cc` (n,c) VALUES ('Martinique','MQ');
INSERT INTO `cc` (n,c) VALUES ('Mauritania','MR');
INSERT INTO `cc` (n,c) VALUES ('Mauritius','MU');
INSERT INTO `cc` (n,c) VALUES ('Mayotte','YT');
INSERT INTO `cc` (n,c) VALUES ('Mexico','MX');
INSERT INTO `cc` (n,c) VALUES ('Federated States of Micronesia','FM');
INSERT INTO `cc` (n,c) VALUES ('Moldova','MD');
INSERT INTO `cc` (n,c) VALUES ('Monaco','MC');
INSERT INTO `cc` (n,c) VALUES ('Mongolia','MN');
INSERT INTO `cc` (n,c) VALUES ('Montenegro','ME');
INSERT INTO `cc` (n,c) VALUES ('Montserrat','MS');
INSERT INTO `cc` (n,c) VALUES ('Morocco','MA');
INSERT INTO `cc` (n,c) VALUES ('Mozambique','MZ');
INSERT INTO `cc` (n,c) VALUES ('Myanmar','MM');
INSERT INTO `cc` (n,c) VALUES ('Namibia','NA');
INSERT INTO `cc` (n,c) VALUES ('Nauru','NR');
INSERT INTO `cc` (n,c) VALUES ('Nepal','NP');
INSERT INTO `cc` (n,c) VALUES ('Netherlands','NL');
INSERT INTO `cc` (n,c) VALUES ('Netherlands Antilles','AN');
INSERT INTO `cc` (n,c) VALUES ('New Caledonia','NC');
INSERT INTO `cc` (n,c) VALUES ('New Zealand','NZ');
INSERT INTO `cc` (n,c) VALUES ('Nicaragua','NI');
INSERT INTO `cc` (n,c) VALUES ('Niger','NE');
INSERT INTO `cc` (n,c) VALUES ('Nigeria','NG');
INSERT INTO `cc` (n,c) VALUES ('Niue','NU');
INSERT INTO `cc` (n,c) VALUES ('Norfolk Island','NF');
INSERT INTO `cc` (n,c) VALUES ('Northern Mariana Islands','MP');
INSERT INTO `cc` (n,c) VALUES ('Norway','NO');
INSERT INTO `cc` (n,c) VALUES ('Oman','OM');
INSERT INTO `cc` (n,c) VALUES ('Pakistan','PK');
INSERT INTO `cc` (n,c) VALUES ('Palau','PW');
INSERT INTO `cc` (n,c) VALUES ('Palestinian territories','PS');
INSERT INTO `cc` (n,c) VALUES ('Panama','PA');
INSERT INTO `cc` (n,c) VALUES ('Papua New Guinea','PG');
INSERT INTO `cc` (n,c) VALUES ('Paraguay','PY');
INSERT INTO `cc` (n,c) VALUES ('Peru','PE');
INSERT INTO `cc` (n,c) VALUES ('Philippines','PH');
INSERT INTO `cc` (n,c) VALUES ('Pitcairn','PN');
INSERT INTO `cc` (n,c) VALUES ('Poland','PL');
INSERT INTO `cc` (n,c) VALUES ('Portugal','PT');
INSERT INTO `cc` (n,c) VALUES ('Puerto Rico','PR');
INSERT INTO `cc` (n,c) VALUES ('Qatar','QA');
INSERT INTO `cc` (n,c) VALUES ('Reunion','RE');
INSERT INTO `cc` (n,c) VALUES ('Romania','RO');
INSERT INTO `cc` (n,c) VALUES ('Russian Federation','RU');
INSERT INTO `cc` (n,c) VALUES ('Rwanda','RW');
INSERT INTO `cc` (n,c) VALUES ('Saint Helena','SH');
INSERT INTO `cc` (n,c) VALUES ('Saint Kitts and Nevis','KN');
INSERT INTO `cc` (n,c) VALUES ('Saint Lucia','LC');
INSERT INTO `cc` (n,c) VALUES ('Saint Pierre and Miquelon','PM');
INSERT INTO `cc` (n,c) VALUES ('Saint Vincent and the Grenadines','VC');
INSERT INTO `cc` (n,c) VALUES ('Samoa','WS');
INSERT INTO `cc` (n,c) VALUES ('San Marino','SM');
INSERT INTO `cc` (n,c) VALUES ('Sao Tome and Principe','ST');
INSERT INTO `cc` (n,c) VALUES ('Saudi Arabia','SA');
INSERT INTO `cc` (n,c) VALUES ('Senegal','SN');
INSERT INTO `cc` (n,c) VALUES ('Serbia','RS');
INSERT INTO `cc` (n,c) VALUES ('Seychelles','SC');
INSERT INTO `cc` (n,c) VALUES ('Sierra Leone','SL');
INSERT INTO `cc` (n,c) VALUES ('Singapore','SG');
INSERT INTO `cc` (n,c) VALUES ('Slovakia','SK');
INSERT INTO `cc` (n,c) VALUES ('Slovenia','SI');
INSERT INTO `cc` (n,c) VALUES ('Solomon Islands','SB');
INSERT INTO `cc` (n,c) VALUES ('Somalia','SO');
INSERT INTO `cc` (n,c) VALUES ('South Africa','ZA');
INSERT INTO `cc` (n,c) VALUES ('South Georgia and the South Sandwich Islands','GS');
INSERT INTO `cc` (n,c) VALUES ('Spain','ES');
INSERT INTO `cc` (n,c) VALUES ('Sri Lanka','LK');
INSERT INTO `cc` (n,c) VALUES ('Sudan','SD');
INSERT INTO `cc` (n,c) VALUES ('Suriname','SR');
INSERT INTO `cc` (n,c) VALUES ('Svalbard and Jan Mayen','SJ');
INSERT INTO `cc` (n,c) VALUES ('Swaziland','SZ');
INSERT INTO `cc` (n,c) VALUES ('Sweden','SE');
INSERT INTO `cc` (n,c) VALUES ('Switzerland','CH');
INSERT INTO `cc` (n,c) VALUES ('Syria','SY');
INSERT INTO `cc` (n,c) VALUES ('Taiwan, Province of China','TW');
INSERT INTO `cc` (n,c) VALUES ('Tajikistan','TJ');
INSERT INTO `cc` (n,c) VALUES ('Tanzania','TZ');
INSERT INTO `cc` (n,c) VALUES ('Thailand','TH');
INSERT INTO `cc` (n,c) VALUES ('Timor-Leste','TL');
INSERT INTO `cc` (n,c) VALUES ('Togo','TG');
INSERT INTO `cc` (n,c) VALUES ('Tokelau','TK');
INSERT INTO `cc` (n,c) VALUES ('Tonga','TO');
INSERT INTO `cc` (n,c) VALUES ('Trinidad and Tobago','TT');
INSERT INTO `cc` (n,c) VALUES ('Tunisia','TN');
INSERT INTO `cc` (n,c) VALUES ('Turkey','TR');
INSERT INTO `cc` (n,c) VALUES ('Turkmenistan','TM');
INSERT INTO `cc` (n,c) VALUES ('Turks and Caicos Islands','TC');
INSERT INTO `cc` (n,c) VALUES ('Tuvalu','TV');
INSERT INTO `cc` (n,c) VALUES ('Uganda','UG');
INSERT INTO `cc` (n,c) VALUES ('Ukraine','UA');
INSERT INTO `cc` (n,c) VALUES ('United Arab Emirates','AE');
INSERT INTO `cc` (n,c) VALUES ('United Kingdom','GB');
INSERT INTO `cc` (n,c) VALUES ('United States','US');
INSERT INTO `cc` (n,c) VALUES ('United States Minor Outlying Islands','UM');
INSERT INTO `cc` (n,c) VALUES ('Uruguay','UY');
INSERT INTO `cc` (n,c) VALUES ('Uzbekistan','UZ');
INSERT INTO `cc` (n,c) VALUES ('Vanuatu','VU');
INSERT INTO `cc` (n,c) VALUES ('Venezuela','VE');
INSERT INTO `cc` (n,c) VALUES ('Viet Nam','VN');
INSERT INTO `cc` (n,c) VALUES ('British Virgin Islands','VG');
INSERT INTO `cc` (n,c) VALUES ('United States Virgin Islands','VI');
INSERT INTO `cc` (n,c) VALUES ('Wallis and Futuna','WF');
INSERT INTO `cc` (n,c) VALUES ('Western Sahara','EH');
INSERT INTO `cc` (n,c) VALUES ('Yemen','YE');
INSERT INTO `cc` (n,c) VALUES ('Zambia','ZM');
INSERT INTO `cc` (n,c) VALUES ('Zimbabwe','ZW');