<?php
$data = [
	'AU' => [
		'code' => 'AU',
		'code3' => 'AUS',
		'num' => '036',
		'name' => 'Австралия',
		'cont' => '',
		'active' => 0,
	],
	'AT' => [
		'code' => 'AT',
		'code3' => 'AUT',
		'num' => '040',
		'name' => 'Австрия',
		'cont' => '',
		'active' => 0,
	],
	'AZ' => [
		'code' => 'AZ',
		'code3' => 'AZE',
		'num' => '031',
		'name' => 'Азербайджан',
		'cont' => '',
		'active' => 0,
	],
	'AX' => [
		'code' => 'AX',
		'code3' => 'ALA',
		'num' => '248',
		'name' => 'Аландские острова',
		'cont' => '',
		'active' => 0,
	],
	'AL' => [
		'code' => 'AL',
		'code3' => 'ALB',
		'num' => '008',
		'name' => 'Албания',
		'cont' => '',
		'active' => 0,
	],
	'DZ' => [
		'code' => 'DZ',
		'code3' => 'DZA',
		'num' => '012',
		'name' => 'Алжир',
		'cont' => '',
		'active' => 0,
	],
	'VI' => [
		'code' => 'VI',
		'code3' => 'VIR',
		'num' => '850',
		'name' => 'Виргинские Острова США',
		'cont' => '',
		'active' => 0,
	],
	'AS' => [
		'code' => 'AS',
		'code3' => 'ASM',
		'num' => '016',
		'name' => 'Американское Самоа',
		'cont' => '',
		'active' => 0,
	],
	'AI' => [
		'code' => 'AI',
		'code3' => 'AIA',
		'num' => '660',
		'name' => 'Ангилья',
		'cont' => '',
		'active' => 0,
	],
	'AO' => [
		'code' => 'AO',
		'code3' => 'AGO',
		'num' => '024',
		'name' => 'Ангола',
		'cont' => '',
		'active' => 0,
	],
	'AD' => [
		'code' => 'AD',
		'code3' => 'AND',
		'num' => '020',
		'name' => 'Андорра',
		'cont' => '',
		'active' => 0,
	],
	'AQ' => [
		'code' => 'AQ',
		'code3' => 'ATA',
		'num' => '010',
		'name' => 'Антарктида',
		'cont' => '',
		'active' => 0,
	],
	'AG' => [
		'code' => 'AG',
		'code3' => 'ATG',
		'num' => '028',
		'name' => 'Антигуа и Барбуда',
		'cont' => '',
		'active' => 0,
	],
	'AR' => [
		'code' => 'AR',
		'code3' => 'ARG',
		'num' => '032',
		'name' => 'Аргентина',
		'cont' => '',
		'active' => 0,
	],
	'AM' => [
		'code' => 'AM',
		'code3' => 'ARM',
		'num' => '051',
		'name' => 'Армения',
		'cont' => '',
		'active' => 0,
	],
	'AW' => [
		'code' => 'AW',
		'code3' => 'ABW',
		'num' => '533',
		'name' => 'Аруба',
		'cont' => '',
		'active' => 0,
	],
	'AF' => [
		'code' => 'AF',
		'code3' => 'AFG',
		'num' => '004',
		'name' => 'Афганистан',
		'cont' => '',
		'active' => 0,
	],
	'BS' => [
		'code' => 'BS',
		'code3' => 'BHS',
		'num' => '044',
		'name' => 'Багамы',
		'cont' => '',
		'active' => 0,
	],
	'BD' => [
		'code' => 'BD',
		'code3' => 'BGD',
		'num' => '050',
		'name' => 'Бангладеш',
		'cont' => '',
		'active' => 0,
	],
	'BB' => [
		'code' => 'BB',
		'code3' => 'BRB',
		'num' => '052',
		'name' => 'Барбадос',
		'cont' => '',
		'active' => 0,
	],
	'BH' => [
		'code' => 'BH',
		'code3' => 'BHR',
		'num' => '048',
		'name' => 'Бахрейн',
		'cont' => '',
		'active' => 0,
	],
	'BZ' => [
		'code' => 'BZ',
		'code3' => 'BLZ',
		'num' => '084',
		'name' => 'Белиз',
		'cont' => '',
		'active' => 0,
	],
	'BY' => [
		'code' => 'BY',
		'code3' => 'BLR',
		'num' => '112',
		'name' => 'Белоруссия',
		'cont' => '',
		'active' => 0,
	],
	'BE' => [
		'code' => 'BE',
		'code3' => 'BEL',
		'num' => '056',
		'name' => 'Бельгия',
		'cont' => '',
		'active' => 0,
	],
	'BJ' => [
		'code' => 'BJ',
		'code3' => 'BEN',
		'num' => '204',
		'name' => 'Бенин',
		'cont' => '',
		'active' => 0,
	],
	'BM' => [
		'code' => 'BM',
		'code3' => 'BMU',
		'num' => '060',
		'name' => 'Бермуды',
		'cont' => '',
		'active' => 0,
	],
	'BG' => [
		'code' => 'BG',
		'code3' => 'BGR',
		'num' => '100',
		'name' => 'Болгария',
		'cont' => '',
		'active' => 0,
	],
	'BO' => [
		'code' => 'BO',
		'code3' => 'BOL',
		'num' => '068',
		'name' => 'Боливия',
		'cont' => '',
		'active' => 0,
	],
	'BQ' => [
		'code' => 'BQ',
		'code3' => 'BES',
		'num' => '535',
		'name' => 'Бонэйр, Синт-Эстатиус и Саба',
		'cont' => '',
		'active' => 0,
	],
	'BA' => [
		'code' => 'BA',
		'code3' => 'BIH',
		'num' => '070',
		'name' => 'Босния и Герцеговина',
		'cont' => '',
		'active' => 0,
	],
	'BW' => [
		'code' => 'BW',
		'code3' => 'BWA',
		'num' => '072',
		'name' => 'Ботсвана',
		'cont' => '',
		'active' => 0,
	],
	'BR' => [
		'code' => 'BR',
		'code3' => 'BRA',
		'num' => '076',
		'name' => 'Бразилия',
		'cont' => '',
		'active' => 0,
	],
	'IO' => [
		'code' => 'IO',
		'code3' => 'IOT',
		'num' => '086',
		'name' => 'Британская территория в Индийском океане',
		'cont' => '',
		'active' => 0,
	],
	'VG' => [
		'code' => 'VG',
		'code3' => 'VGB',
		'num' => '092',
		'name' => 'Виргинские Острова Великобритания',
		'cont' => '',
		'active' => 0,
	],
	'BN' => [
		'code' => 'BN',
		'code3' => 'BRN',
		'num' => '096',
		'name' => 'Бруней',
		'cont' => '',
		'active' => 0,
	],
	'BF' => [
		'code' => 'BF',
		'code3' => 'BFA',
		'num' => '854',
		'name' => 'Буркина-Фасо',
		'cont' => '',
		'active' => 0,
	],
	'BI' => [
		'code' => 'BI',
		'code3' => 'BDI',
		'num' => '108',
		'name' => 'Бурунди',
		'cont' => '',
		'active' => 0,
	],
	'BT' => [
		'code' => 'BT',
		'code3' => 'BTN',
		'num' => '064',
		'name' => 'Бутан',
		'cont' => '',
		'active' => 0,
	],
	'VU' => [
		'code' => 'VU',
		'code3' => 'VUT',
		'num' => '548',
		'name' => 'Вануату',
		'cont' => '',
		'active' => 0,
	],
	'VA' => [
		'code' => 'VA',
		'code3' => 'VAT',
		'num' => '336',
		'name' => 'Ватикан',
		'cont' => '',
		'active' => 0,
	],
	'GB' => [
		'code' => 'GB',
		'code3' => 'GBR',
		'num' => '826',
		'name' => 'Великобритания',
		'cont' => '',
		'active' => 1,
	],
	'HU' => [
		'code' => 'HU',
		'code3' => 'HUN',
		'num' => '348',
		'name' => 'Венгрия',
		'cont' => '',
		'active' => 0,
	],
	'VE' => [
		'code' => 'VE',
		'code3' => 'VEN',
		'num' => '862',
		'name' => 'Венесуэла',
		'cont' => '',
		'active' => 0,
	],
	'UM' => [
		'code' => 'UM',
		'code3' => 'UMI',
		'num' => '581',
		'name' => 'Внешние малые острова США',
		'cont' => '',
		'active' => 0,
	],
	'TL' => [
		'code' => 'TL',
		'code3' => 'TLS',
		'num' => '626',
		'name' => 'Восточный Тимор',
		'cont' => '',
		'active' => 0,
	],
	'VN' => [
		'code' => 'VN',
		'code3' => 'VNM',
		'num' => '704',
		'name' => 'Вьетнам',
		'cont' => '',
		'active' => 0,
	],
	'GA' => [
		'code' => 'GA',
		'code3' => 'GAB',
		'num' => '266',
		'name' => 'Габон',
		'cont' => '',
		'active' => 0,
	],
	'HT' => [
		'code' => 'HT',
		'code3' => 'HTI',
		'num' => '332',
		'name' => 'Гаити',
		'cont' => '',
		'active' => 0,
	],
	'GY' => [
		'code' => 'GY',
		'code3' => 'GUY',
		'num' => '328',
		'name' => 'Гайана',
		'cont' => '',
		'active' => 0,
	],
	'GM' => [
		'code' => 'GM',
		'code3' => 'GMB',
		'num' => '270',
		'name' => 'Гамбия',
		'cont' => '',
		'active' => 0,
	],
	'GH' => [
		'code' => 'GH',
		'code3' => 'GHA',
		'num' => '288',
		'name' => 'Гана',
		'cont' => '',
		'active' => 0,
	],
	'GP' => [
		'code' => 'GP',
		'code3' => 'GLP',
		'num' => '312',
		'name' => 'Гваделупа',
		'cont' => '',
		'active' => 0,
	],
	'GT' => [
		'code' => 'GT',
		'code3' => 'GTM',
		'num' => '320',
		'name' => 'Гватемала',
		'cont' => '',
		'active' => 0,
	],
	'GF' => [
		'code' => 'GF',
		'code3' => 'GUF',
		'num' => '254',
		'name' => 'Гвиана',
		'cont' => '',
		'active' => 0,
	],
	'GN' => [
		'code' => 'GN',
		'code3' => 'GIN',
		'num' => '324',
		'name' => 'Гвинея',
		'cont' => '',
		'active' => 0,
	],
	'GW' => [
		'code' => 'GW',
		'code3' => 'GNB',
		'num' => '624',
		'name' => 'Гвинея-Бисау',
		'cont' => '',
		'active' => 0,
	],
	'DE' => [
		'code' => 'DE',
		'code3' => 'DEU',
		'num' => '276',
		'name' => 'Германия',
		'cont' => '',
		'active' => 1,
	],
	'GG' => [
		'code' => 'GG',
		'code3' => 'GGY',
		'num' => '831',
		'name' => 'Гернси',
		'cont' => '',
		'active' => 0,
	],
	'GI' => [
		'code' => 'GI',
		'code3' => 'GIB',
		'num' => '292',
		'name' => 'Гибралтар',
		'cont' => '',
		'active' => 0,
	],
	'HN' => [
		'code' => 'HN',
		'code3' => 'HND',
		'num' => '340',
		'name' => 'Гондурас',
		'cont' => '',
		'active' => 0,
	],
	'HK' => [
		'code' => 'HK',
		'code3' => 'HKG',
		'num' => '344',
		'name' => 'Гонконг',
		'cont' => '',
		'active' => 0,
	],
	'GD' => [
		'code' => 'GD',
		'code3' => 'GRD',
		'num' => '308',
		'name' => 'Гренада',
		'cont' => '',
		'active' => 0,
	],
	'GL' => [
		'code' => 'GL',
		'code3' => 'GRL',
		'num' => '304',
		'name' => 'Гренландия',
		'cont' => '',
		'active' => 0,
	],
	'GR' => [
		'code' => 'GR',
		'code3' => 'GRC',
		'num' => '300',
		'name' => 'Греция',
		'cont' => '',
		'active' => 0,
	],
	'GE' => [
		'code' => 'GE',
		'code3' => 'GEO',
		'num' => '268',
		'name' => 'Грузия',
		'cont' => '',
		'active' => 0,
	],
	'GU' => [
		'code' => 'GU',
		'code3' => 'GUM',
		'num' => '316',
		'name' => 'Гуам',
		'cont' => '',
		'active' => 0,
	],
	'DK' => [
		'code' => 'DK',
		'code3' => 'DNK',
		'num' => '208',
		'name' => 'Дания',
		'cont' => '',
		'active' => 0,
	],
	'JE' => [
		'code' => 'JE',
		'code3' => 'JEY',
		'num' => '832',
		'name' => 'Джерси',
		'cont' => '',
		'active' => 0,
	],
	'DJ' => [
		'code' => 'DJ',
		'code3' => 'DJI',
		'num' => '262',
		'name' => 'Джибути',
		'cont' => '',
		'active' => 0,
	],
	'DM' => [
		'code' => 'DM',
		'code3' => 'DMA',
		'num' => '212',
		'name' => 'Доминика',
		'cont' => '',
		'active' => 0,
	],
	'DO' => [
		'code' => 'DO',
		'code3' => 'DOM',
		'num' => '214',
		'name' => 'Доминиканская Республика',
		'cont' => '',
		'active' => 0,
	],
	'CD' => [
		'code' => 'CD',
		'code3' => 'COD',
		'num' => '180',
		'name' => 'Демократическая Республика Конго',
		'cont' => '',
		'active' => 0,
	],
	'EU' => [
		'code' => 'EU',
		'code3' => '',
		'num' => '',
		'name' => 'Европейский союз',
		'cont' => '',
		'active' => 0,
	],
	'EG' => [
		'code' => 'EG',
		'code3' => 'EGY',
		'num' => '818',
		'name' => 'Египет',
		'cont' => '',
		'active' => 0,
	],
	'ZM' => [
		'code' => 'ZM',
		'code3' => 'ZMB',
		'num' => '894',
		'name' => 'Замбия',
		'cont' => '',
		'active' => 0,
	],
	'EH' => [
		'code' => 'EH',
		'code3' => 'ESH',
		'num' => '732',
		'name' => 'САДР',
		'cont' => '',
		'active' => 0,
	],
	'ZW' => [
		'code' => 'ZW',
		'code3' => 'ZWE',
		'num' => '716',
		'name' => 'Зимбабве',
		'cont' => '',
		'active' => 0,
	],
	'IL' => [
		'code' => 'IL',
		'code3' => 'ISR',
		'num' => '376',
		'name' => 'Израиль',
		'cont' => '',
		'active' => 0,
	],
	'IN' => [
		'code' => 'IN',
		'code3' => 'IND',
		'num' => '356',
		'name' => 'Индия',
		'cont' => '',
		'active' => 0,
	],
	'ID' => [
		'code' => 'ID',
		'code3' => 'IDN',
		'num' => '360',
		'name' => 'Индонезия',
		'cont' => '',
		'active' => 0,
	],
	'JO' => [
		'code' => 'JO',
		'code3' => 'JOR',
		'num' => '400',
		'name' => 'Иордания',
		'cont' => '',
		'active' => 0,
	],
	'IQ' => [
		'code' => 'IQ',
		'code3' => 'IRQ',
		'num' => '368',
		'name' => 'Ирак',
		'cont' => '',
		'active' => 0,
	],
	'IR' => [
		'code' => 'IR',
		'code3' => 'IRN',
		'num' => '364',
		'name' => 'Иран',
		'cont' => '',
		'active' => 0,
	],
	'IE' => [
		'code' => 'IE',
		'code3' => 'IRL',
		'num' => '372',
		'name' => 'Ирландия',
		'cont' => '',
		'active' => 0,
	],
	'IS' => [
		'code' => 'IS',
		'code3' => 'ISL',
		'num' => '352',
		'name' => 'Исландия',
		'cont' => '',
		'active' => 0,
	],
	'ES' => [
		'code' => 'ES',
		'code3' => 'ESP',
		'num' => '724',
		'name' => 'Испания',
		'cont' => '',
		'active' => 1,
	],
	'IT' => [
		'code' => 'IT',
		'code3' => 'ITA',
		'num' => '380',
		'name' => 'Италия',
		'cont' => '',
		'active' => 0,
	],
	'YE' => [
		'code' => 'YE',
		'code3' => 'YEM',
		'num' => '887',
		'name' => 'Йемен',
		'cont' => '',
		'active' => 0,
	],
	'CV' => [
		'code' => 'CV',
		'code3' => 'CPV',
		'num' => '132',
		'name' => 'Кабо-Верде',
		'cont' => '',
		'active' => 0,
	],
	'KZ' => [
		'code' => 'KZ',
		'code3' => 'KAZ',
		'num' => '398',
		'name' => 'Казахстан',
		'cont' => '',
		'active' => 0,
	],
	'KY' => [
		'code' => 'KY',
		'code3' => 'CYM',
		'num' => '136',
		'name' => 'Острова Кайман',
		'cont' => '',
		'active' => 0,
	],
	'KH' => [
		'code' => 'KH',
		'code3' => 'KHM',
		'num' => '116',
		'name' => 'Камбоджа',
		'cont' => '',
		'active' => 0,
	],
	'CM' => [
		'code' => 'CM',
		'code3' => 'CMR',
		'num' => '120',
		'name' => 'Камерун',
		'cont' => '',
		'active' => 0,
	],
	'CA' => [
		'code' => 'CA',
		'code3' => 'CAN',
		'num' => '124',
		'name' => 'Канада',
		'cont' => '',
		'active' => 0,
	],
	'QA' => [
		'code' => 'QA',
		'code3' => 'QAT',
		'num' => '634',
		'name' => 'Катар',
		'cont' => '',
		'active' => 0,
	],
	'KE' => [
		'code' => 'KE',
		'code3' => 'KEN',
		'num' => '404',
		'name' => 'Кения',
		'cont' => '',
		'active' => 0,
	],
	'CY' => [
		'code' => 'CY',
		'code3' => 'CYP',
		'num' => '196',
		'name' => 'Кипр',
		'cont' => '',
		'active' => 0,
	],
	'KG' => [
		'code' => 'KG',
		'code3' => 'KGZ',
		'num' => '417',
		'name' => 'Киргизия',
		'cont' => '',
		'active' => 0,
	],
	'KI' => [
		'code' => 'KI',
		'code3' => 'KIR',
		'num' => '296',
		'name' => 'Кирибати',
		'cont' => '',
		'active' => 0,
	],
	'TW' => [
		'code' => 'TW',
		'code3' => 'TWN',
		'num' => '158',
		'name' => 'Китайская Республика',
		'cont' => '',
		'active' => 0,
	],
	'KP' => [
		'code' => 'KP',
		'code3' => 'PRK',
		'num' => '408',
		'name' => 'КНДР',
		'cont' => '',
		'active' => 0,
	],
	'CN' => [
		'code' => 'CN',
		'code3' => 'CHN',
		'num' => '156',
		'name' => 'КНР',
		'cont' => '',
		'active' => 0,
	],
	'CC' => [
		'code' => 'CC',
		'code3' => 'CCK',
		'num' => '166',
		'name' => 'Кокосовые острова',
		'cont' => '',
		'active' => 0,
	],
	'CO' => [
		'code' => 'CO',
		'code3' => 'COL',
		'num' => '170',
		'name' => 'Колумбия',
		'cont' => '',
		'active' => 0,
	],
	'KM' => [
		'code' => 'KM',
		'code3' => 'COM',
		'num' => '174',
		'name' => 'Коморы',
		'cont' => '',
		'active' => 0,
	],
	'CR' => [
		'code' => 'CR',
		'code3' => 'CRI',
		'num' => '188',
		'name' => 'Коста-Рика',
		'cont' => '',
		'active' => 0,
	],
	'CI' => [
		'code' => 'CI',
		'code3' => 'CIV',
		'num' => '384',
		'name' => 'Кот-д’Ивуар',
		'cont' => '',
		'active' => 0,
	],
	'CU' => [
		'code' => 'CU',
		'code3' => 'CUB',
		'num' => '192',
		'name' => 'Куба',
		'cont' => '',
		'active' => 0,
	],
	'KW' => [
		'code' => 'KW',
		'code3' => 'KWT',
		'num' => '414',
		'name' => 'Кувейт',
		'cont' => '',
		'active' => 0,
	],
	'CW' => [
		'code' => 'CW',
		'code3' => 'CUW',
		'num' => '531',
		'name' => 'Кюрасао',
		'cont' => '',
		'active' => 0,
	],
	'LA' => [
		'code' => 'LA',
		'code3' => 'LAO',
		'num' => '418',
		'name' => 'Лаос',
		'cont' => '',
		'active' => 0,
	],
	'LV' => [
		'code' => 'LV',
		'code3' => 'LVA',
		'num' => '428',
		'name' => 'Латвия',
		'cont' => '',
		'active' => 0,
	],
	'LS' => [
		'code' => 'LS',
		'code3' => 'LSO',
		'num' => '426',
		'name' => 'Лесото',
		'cont' => '',
		'active' => 0,
	],
	'LR' => [
		'code' => 'LR',
		'code3' => 'LBR',
		'num' => '430',
		'name' => 'Либерия',
		'cont' => '',
		'active' => 0,
	],
	'LB' => [
		'code' => 'LB',
		'code3' => 'LBN',
		'num' => '422',
		'name' => 'Ливан',
		'cont' => '',
		'active' => 0,
	],
	'LY' => [
		'code' => 'LY',
		'code3' => 'LBY',
		'num' => '434',
		'name' => 'Ливия',
		'cont' => '',
		'active' => 0,
	],
	'LT' => [
		'code' => 'LT',
		'code3' => 'LTU',
		'num' => '440',
		'name' => 'Литва',
		'cont' => '',
		'active' => 0,
	],
	'LI' => [
		'code' => 'LI',
		'code3' => 'LIE',
		'num' => '438',
		'name' => 'Лихтенштейн',
		'cont' => '',
		'active' => 0,
	],
	'LU' => [
		'code' => 'LU',
		'code3' => 'LUX',
		'num' => '442',
		'name' => 'Люксембург',
		'cont' => '',
		'active' => 0,
	],
	'MU' => [
		'code' => 'MU',
		'code3' => 'MUS',
		'num' => '480',
		'name' => 'Маврикий',
		'cont' => '',
		'active' => 0,
	],
	'MR' => [
		'code' => 'MR',
		'code3' => 'MRT',
		'num' => '478',
		'name' => 'Мавритания',
		'cont' => '',
		'active' => 0,
	],
	'MG' => [
		'code' => 'MG',
		'code3' => 'MDG',
		'num' => '450',
		'name' => 'Мадагаскар',
		'cont' => '',
		'active' => 0,
	],
	'YT' => [
		'code' => 'YT',
		'code3' => 'MYT',
		'num' => '175',
		'name' => 'Майотта',
		'cont' => '',
		'active' => 0,
	],
	'MO' => [
		'code' => 'MO',
		'code3' => 'MAC',
		'num' => '446',
		'name' => 'Макао',
		'cont' => '',
		'active' => 0,
	],
	'MK' => [
		'code' => 'MK',
		'code3' => 'MKD',
		'num' => '807',
		'name' => 'Македония',
		'cont' => '',
		'active' => 0,
	],
	'MW' => [
		'code' => 'MW',
		'code3' => 'MWI',
		'num' => '454',
		'name' => 'Малави',
		'cont' => '',
		'active' => 0,
	],
	'MY' => [
		'code' => 'MY',
		'code3' => 'MYS',
		'num' => '458',
		'name' => 'Малайзия',
		'cont' => '',
		'active' => 0,
	],
	'ML' => [
		'code' => 'ML',
		'code3' => 'MLI',
		'num' => '466',
		'name' => 'Мали',
		'cont' => '',
		'active' => 0,
	],
	'MV' => [
		'code' => 'MV',
		'code3' => 'MDV',
		'num' => '462',
		'name' => 'Мальдивы',
		'cont' => '',
		'active' => 0,
	],
	'MT' => [
		'code' => 'MT',
		'code3' => 'MLT',
		'num' => '470',
		'name' => 'Мальта',
		'cont' => '',
		'active' => 0,
	],
	'MA' => [
		'code' => 'MA',
		'code3' => 'MAR',
		'num' => '504',
		'name' => 'Марокко',
		'cont' => '',
		'active' => 0,
	],
	'MQ' => [
		'code' => 'MQ',
		'code3' => 'MTQ',
		'num' => '474',
		'name' => 'Мартиника',
		'cont' => '',
		'active' => 0,
	],
	'MH' => [
		'code' => 'MH',
		'code3' => 'MHL',
		'num' => '584',
		'name' => 'Маршалловы Острова',
		'cont' => '',
		'active' => 0,
	],
	'MX' => [
		'code' => 'MX',
		'code3' => 'MEX',
		'num' => '484',
		'name' => 'Мексика',
		'cont' => '',
		'active' => 0,
	],
	'FM' => [
		'code' => 'FM',
		'code3' => 'FSM',
		'num' => '583',
		'name' => 'Микронезия',
		'cont' => '',
		'active' => 0,
	],
	'MZ' => [
		'code' => 'MZ',
		'code3' => 'MOZ',
		'num' => '508',
		'name' => 'Мозамбик',
		'cont' => '',
		'active' => 0,
	],
	'MD' => [
		'code' => 'MD',
		'code3' => 'MDA',
		'num' => '498',
		'name' => 'Молдавия',
		'cont' => '',
		'active' => 0,
	],
	'MC' => [
		'code' => 'MC',
		'code3' => 'MCO',
		'num' => '492',
		'name' => 'Монако',
		'cont' => '',
		'active' => 0,
	],
	'MN' => [
		'code' => 'MN',
		'code3' => 'MNG',
		'num' => '496',
		'name' => 'Монголия',
		'cont' => '',
		'active' => 0,
	],
	'MS' => [
		'code' => 'MS',
		'code3' => 'MSR',
		'num' => '500',
		'name' => 'Монтсеррат',
		'cont' => '',
		'active' => 0,
	],
	'MM' => [
		'code' => 'MM',
		'code3' => 'MMR',
		'num' => '104',
		'name' => 'Мьянма',
		'cont' => '',
		'active' => 0,
	],
	'NA' => [
		'code' => 'NA',
		'code3' => 'NAM',
		'num' => '516',
		'name' => 'Намибия',
		'cont' => '',
		'active' => 0,
	],
	'NR' => [
		'code' => 'NR',
		'code3' => 'NRU',
		'num' => '520',
		'name' => 'Науру',
		'cont' => '',
		'active' => 0,
	],
	'NP' => [
		'code' => 'NP',
		'code3' => 'NPL',
		'num' => '524',
		'name' => 'Непал',
		'cont' => '',
		'active' => 0,
	],
	'NE' => [
		'code' => 'NE',
		'code3' => 'NER',
		'num' => '562',
		'name' => 'Нигер',
		'cont' => '',
		'active' => 0,
	],
	'NG' => [
		'code' => 'NG',
		'code3' => 'NGA',
		'num' => '566',
		'name' => 'Нигерия',
		'cont' => '',
		'active' => 0,
	],
	'NL' => [
		'code' => 'NL',
		'code3' => 'NLD',
		'num' => '528',
		'name' => 'Нидерланды',
		'cont' => '',
		'active' => 0,
	],
	'NI' => [
		'code' => 'NI',
		'code3' => 'NIC',
		'num' => '558',
		'name' => 'Никарагуа',
		'cont' => '',
		'active' => 0,
	],
	'NU' => [
		'code' => 'NU',
		'code3' => 'NIU',
		'num' => '570',
		'name' => 'Ниуэ',
		'cont' => '',
		'active' => 0,
	],
	'NZ' => [
		'code' => 'NZ',
		'code3' => 'NZL',
		'num' => '554',
		'name' => 'Новая Зеландия',
		'cont' => '',
		'active' => 0,
	],
	'NC' => [
		'code' => 'NC',
		'code3' => 'NCL',
		'num' => '540',
		'name' => 'Новая Каледония',
		'cont' => '',
		'active' => 0,
	],
	'NO' => [
		'code' => 'NO',
		'code3' => 'NOR',
		'num' => '578',
		'name' => 'Норвегия',
		'cont' => '',
		'active' => 0,
	],
	'AE' => [
		'code' => 'AE',
		'code3' => 'ARE',
		'num' => '784',
		'name' => 'ОАЭ',
		'cont' => '',
		'active' => 0,
	],
	'OM' => [
		'code' => 'OM',
		'code3' => 'OMN',
		'num' => '512',
		'name' => 'Оман',
		'cont' => '',
		'active' => 0,
	],
	'BV' => [
		'code' => 'BV',
		'code3' => 'BVT',
		'num' => '074',
		'name' => 'Остров Буве',
		'cont' => '',
		'active' => 0,
	],
	'IM' => [
		'code' => 'IM',
		'code3' => 'IMN',
		'num' => '833',
		'name' => 'Остров Мэн',
		'cont' => '',
		'active' => 0,
	],
	'CK' => [
		'code' => 'CK',
		'code3' => 'COK',
		'num' => '184',
		'name' => 'Острова Кука',
		'cont' => '',
		'active' => 0,
	],
	'NF' => [
		'code' => 'NF',
		'code3' => 'NFK',
		'num' => '574',
		'name' => 'Остров Норфолк',
		'cont' => '',
		'active' => 0,
	],
	'CX' => [
		'code' => 'CX',
		'code3' => 'CXR',
		'num' => '162',
		'name' => 'Остров Рождества',
		'cont' => '',
		'active' => 0,
	],
	'PN' => [
		'code' => 'PN',
		'code3' => 'PCN',
		'num' => '612',
		'name' => 'Острова Питкэрн',
		'cont' => '',
		'active' => 0,
	],
	'SH' => [
		'code' => 'SH',
		'code3' => 'SHN',
		'num' => '654',
		'name' => 'Острова Святой Елены, Вознесения и Тристан-да-Кунья',
		'cont' => '',
		'active' => 0,
	],
	'PK' => [
		'code' => 'PK',
		'code3' => 'PAK',
		'num' => '586',
		'name' => 'Пакистан',
		'cont' => '',
		'active' => 0,
	],
	'PW' => [
		'code' => 'PW',
		'code3' => 'PLW',
		'num' => '585',
		'name' => 'Палау',
		'cont' => '',
		'active' => 0,
	],
	'PS' => [
		'code' => 'PS',
		'code3' => 'PSE',
		'num' => '275',
		'name' => 'Государство Палестина',
		'cont' => '',
		'active' => 0,
	],
	'PA' => [
		'code' => 'PA',
		'code3' => 'PAN',
		'num' => '591',
		'name' => 'Панама',
		'cont' => '',
		'active' => 0,
	],
	'PG' => [
		'code' => 'PG',
		'code3' => 'PNG',
		'num' => '598',
		'name' => 'Папуа — Новая Гвинея',
		'cont' => '',
		'active' => 0,
	],
	'PY' => [
		'code' => 'PY',
		'code3' => 'PRY',
		'num' => '600',
		'name' => 'Парагвай',
		'cont' => '',
		'active' => 0,
	],
	'PE' => [
		'code' => 'PE',
		'code3' => 'PER',
		'num' => '604',
		'name' => 'Перу',
		'cont' => '',
		'active' => 0,
	],
	'PL' => [
		'code' => 'PL',
		'code3' => 'POL',
		'num' => '616',
		'name' => 'Польша',
		'cont' => '',
		'active' => 0,
	],
	'PT' => [
		'code' => 'PT',
		'code3' => 'PRT',
		'num' => '620',
		'name' => 'Португалия',
		'cont' => '',
		'active' => 0,
	],
	'PR' => [
		'code' => 'PR',
		'code3' => 'PRI',
		'num' => '630',
		'name' => 'Пуэрто-Рико',
		'cont' => '',
		'active' => 0,
	],
	'CG' => [
		'code' => 'CG',
		'code3' => 'COG',
		'num' => '178',
		'name' => 'Республика Конго',
		'cont' => '',
		'active' => 0,
	],
	'KR' => [
		'code' => 'KR',
		'code3' => 'KOR',
		'num' => '410',
		'name' => 'Республика Корея',
		'cont' => '',
		'active' => 0,
	],
	'RE' => [
		'code' => 'RE',
		'code3' => 'REU',
		'num' => '638',
		'name' => 'Реюньон',
		'cont' => '',
		'active' => 0,
	],
	'RU' => [
		'code' => 'RU',
		'code3' => 'RUS',
		'num' => '643',
		'name' => 'Россия',
		'cont' => '',
		'active' => 1,
	],
	'RW' => [
		'code' => 'RW',
		'code3' => 'RWA',
		'num' => '646',
		'name' => 'Руанда',
		'cont' => '',
		'active' => 0,
	],
	'RO' => [
		'code' => 'RO',
		'code3' => 'ROU',
		'num' => '642',
		'name' => 'Румыния',
		'cont' => '',
		'active' => 0,
	],
	'SV' => [
		'code' => 'SV',
		'code3' => 'SLV',
		'num' => '222',
		'name' => 'Сальвадор',
		'cont' => '',
		'active' => 0,
	],
	'WS' => [
		'code' => 'WS',
		'code3' => 'WSM',
		'num' => '882',
		'name' => 'Самоа',
		'cont' => '',
		'active' => 0,
	],
	'SM' => [
		'code' => 'SM',
		'code3' => 'SMR',
		'num' => '674',
		'name' => 'Сан-Марино',
		'cont' => '',
		'active' => 0,
	],
	'ST' => [
		'code' => 'ST',
		'code3' => 'STP',
		'num' => '678',
		'name' => 'Сан-Томе и Принсипи',
		'cont' => '',
		'active' => 0,
	],
	'SA' => [
		'code' => 'SA',
		'code3' => 'SAU',
		'num' => '682',
		'name' => 'Саудовская Аравия',
		'cont' => '',
		'active' => 0,
	],
	'SZ' => [
		'code' => 'SZ',
		'code3' => 'SWZ',
		'num' => '748',
		'name' => 'Свазиленд',
		'cont' => '',
		'active' => 0,
	],
	'MP' => [
		'code' => 'MP',
		'code3' => 'MNP',
		'num' => '580',
		'name' => 'Северные Марианские Острова',
		'cont' => '',
		'active' => 0,
	],
	'SC' => [
		'code' => 'SC',
		'code3' => 'SYC',
		'num' => '690',
		'name' => 'Сейшельские Острова',
		'cont' => '',
		'active' => 0,
	],
	'BL' => [
		'code' => 'BL',
		'code3' => 'BLM',
		'num' => '652',
		'name' => 'Сен-Бартелеми',
		'cont' => '',
		'active' => 0,
	],
	'MF' => [
		'code' => 'MF',
		'code3' => 'MAF',
		'num' => '663',
		'name' => 'Сен-Мартен',
		'cont' => '',
		'active' => 0,
	],
	'PM' => [
		'code' => 'PM',
		'code3' => 'SPM',
		'num' => '666',
		'name' => 'Сен-Пьер и Микелон',
		'cont' => '',
		'active' => 0,
	],
	'SN' => [
		'code' => 'SN',
		'code3' => 'SEN',
		'num' => '686',
		'name' => 'Сенегал',
		'cont' => '',
		'active' => 0,
	],
	'VC' => [
		'code' => 'VC',
		'code3' => 'VCT',
		'num' => '670',
		'name' => 'Сент-Винсент и Гренадины',
		'cont' => '',
		'active' => 0,
	],
	'KN' => [
		'code' => 'KN',
		'code3' => 'KNA',
		'num' => '659',
		'name' => 'Сент-Китс и Невис',
		'cont' => '',
		'active' => 0,
	],
	'LC' => [
		'code' => 'LC',
		'code3' => 'LCA',
		'num' => '662',
		'name' => 'Сент-Люсия',
		'cont' => '',
		'active' => 0,
	],
	'RS' => [
		'code' => 'RS',
		'code3' => 'SRB',
		'num' => '688',
		'name' => 'Сербия',
		'cont' => '',
		'active' => 0,
	],
	'SG' => [
		'code' => 'SG',
		'code3' => 'SGP',
		'num' => '702',
		'name' => 'Сингапур',
		'cont' => '',
		'active' => 0,
	],
	'SX' => [
		'code' => 'SX',
		'code3' => 'SXM',
		'num' => '534',
		'name' => 'Синт-Мартен',
		'cont' => '',
		'active' => 0,
	],
	'SY' => [
		'code' => 'SY',
		'code3' => 'SYR',
		'num' => '760',
		'name' => 'Сирия',
		'cont' => '',
		'active' => 0,
	],
	'SK' => [
		'code' => 'SK',
		'code3' => 'SVK',
		'num' => '703',
		'name' => 'Словакия',
		'cont' => '',
		'active' => 0,
	],
	'SI' => [
		'code' => 'SI',
		'code3' => 'SVN',
		'num' => '705',
		'name' => 'Словения',
		'cont' => '',
		'active' => 0,
	],
	'SB' => [
		'code' => 'SB',
		'code3' => 'SLB',
		'num' => '090',
		'name' => 'Соломоновы Острова',
		'cont' => '',
		'active' => 0,
	],
	'SO' => [
		'code' => 'SO',
		'code3' => 'SOM',
		'num' => '706',
		'name' => 'Сомали',
		'cont' => '',
		'active' => 0,
	],
	'SD' => [
		'code' => 'SD',
		'code3' => 'SDN',
		'num' => '729',
		'name' => 'Судан',
		'cont' => '',
		'active' => 0,
	],
	'SU' => [
		'code' => 'SU',
		'code3' => 'SUN',
		'num' => '810',
		'name' => 'СССР',
		'cont' => '',
		'active' => 0,
	],
	'SR' => [
		'code' => 'SR',
		'code3' => 'SUR',
		'num' => '740',
		'name' => 'Суринам',
		'cont' => '',
		'active' => 0,
	],
	'US' => [
		'code' => 'US',
		'code3' => 'USA',
		'num' => '840',
		'name' => 'США',
		'cont' => '',
		'active' => 1,
	],
	'SL' => [
		'code' => 'SL',
		'code3' => 'SLE',
		'num' => '694',
		'name' => 'Сьерра-Леоне',
		'cont' => '',
		'active' => 0,
	],
	'TJ' => [
		'code' => 'TJ',
		'code3' => 'TJK',
		'num' => '762',
		'name' => 'Таджикистан',
		'cont' => '',
		'active' => 0,
	],
	'TH' => [
		'code' => 'TH',
		'code3' => 'THA',
		'num' => '764',
		'name' => 'Таиланд',
		'cont' => '',
		'active' => 0,
	],
	'TZ' => [
		'code' => 'TZ',
		'code3' => 'TZA',
		'num' => '834',
		'name' => 'Танзания',
		'cont' => '',
		'active' => 0,
	],
	'TC' => [
		'code' => 'TC',
		'code3' => 'TCA',
		'num' => '796',
		'name' => 'Тёркс и Кайкос',
		'cont' => '',
		'active' => 0,
	],
	'TG' => [
		'code' => 'TG',
		'code3' => 'TGO',
		'num' => '768',
		'name' => 'Того',
		'cont' => '',
		'active' => 0,
	],
	'TK' => [
		'code' => 'TK',
		'code3' => 'TKL',
		'num' => '772',
		'name' => 'Токелау',
		'cont' => '',
		'active' => 0,
	],
	'TO' => [
		'code' => 'TO',
		'code3' => 'TON',
		'num' => '776',
		'name' => 'Тонга',
		'cont' => '',
		'active' => 0,
	],
	'TT' => [
		'code' => 'TT',
		'code3' => 'TTO',
		'num' => '780',
		'name' => 'Тринидад и Тобаго',
		'cont' => '',
		'active' => 0,
	],
	'TV' => [
		'code' => 'TV',
		'code3' => 'TUV',
		'num' => '798',
		'name' => 'Тувалу',
		'cont' => '',
		'active' => 0,
	],
	'TN' => [
		'code' => 'TN',
		'code3' => 'TUN',
		'num' => '788',
		'name' => 'Тунис',
		'cont' => '',
		'active' => 0,
	],
	'TM' => [
		'code' => 'TM',
		'code3' => 'TKM',
		'num' => '795',
		'name' => 'Туркмения',
		'cont' => '',
		'active' => 0,
	],
	'TR' => [
		'code' => 'TR',
		'code3' => 'TUR',
		'num' => '792',
		'name' => 'Турция',
		'cont' => '',
		'active' => 0,
	],
	'UG' => [
		'code' => 'UG',
		'code3' => 'UGA',
		'num' => '800',
		'name' => 'Уганда',
		'cont' => '',
		'active' => 0,
	],
	'UZ' => [
		'code' => 'UZ',
		'code3' => 'UZB',
		'num' => '860',
		'name' => 'Узбекистан',
		'cont' => '',
		'active' => 0,
	],
	'UA' => [
		'code' => 'UA',
		'code3' => 'UKR',
		'num' => '804',
		'name' => 'Украина',
		'cont' => '',
		'active' => 1,
	],
	'WF' => [
		'code' => 'WF',
		'code3' => 'WLF',
		'num' => '876',
		'name' => 'Уоллис и Футуна',
		'cont' => '',
		'active' => 0,
	],
	'UY' => [
		'code' => 'UY',
		'code3' => 'URY',
		'num' => '858',
		'name' => 'Уругвай',
		'cont' => '',
		'active' => 0,
	],
	'FO' => [
		'code' => 'FO',
		'code3' => 'FRO',
		'num' => '234',
		'name' => 'Фареры',
		'cont' => '',
		'active' => 0,
	],
	'FJ' => [
		'code' => 'FJ',
		'code3' => 'FJI',
		'num' => '242',
		'name' => 'Фиджи',
		'cont' => '',
		'active' => 0,
	],
	'PH' => [
		'code' => 'PH',
		'code3' => 'PHL',
		'num' => '608',
		'name' => 'Филиппины',
		'cont' => '',
		'active' => 0,
	],
	'FI' => [
		'code' => 'FI',
		'code3' => 'FIN',
		'num' => '246',
		'name' => 'Финляндия',
		'cont' => '',
		'active' => 0,
	],
	'FK' => [
		'code' => 'FK',
		'code3' => 'FLK',
		'num' => '238',
		'name' => 'Фолклендские острова',
		'cont' => '',
		'active' => 0,
	],
	'FR' => [
		'code' => 'FR',
		'code3' => 'FRA',
		'num' => '250',
		'name' => 'Франция',
		'cont' => '',
		'active' => 1,
	],
	'PF' => [
		'code' => 'PF',
		'code3' => 'PYF',
		'num' => '258',
		'name' => 'Французская Полинезия',
		'cont' => '',
		'active' => 0,
	],
	'TF' => [
		'code' => 'TF',
		'code3' => 'ATF',
		'num' => '260',
		'name' => 'Французские Южные и Антарктические Территории',
		'cont' => '',
		'active' => 0,
	],
	'HM' => [
		'code' => 'HM',
		'code3' => 'HMD',
		'num' => '334',
		'name' => 'Херд и Макдональд',
		'cont' => '',
		'active' => 0,
	],
	'HR' => [
		'code' => 'HR',
		'code3' => 'HRV',
		'num' => '191',
		'name' => 'Хорватия',
		'cont' => '',
		'active' => 0,
	],
	'CF' => [
		'code' => 'CF',
		'code3' => 'CAF',
		'num' => '140',
		'name' => 'ЦАР',
		'cont' => '',
		'active' => 0,
	],
	'TD' => [
		'code' => 'TD',
		'code3' => 'TCD',
		'num' => '148',
		'name' => 'Чад',
		'cont' => '',
		'active' => 0,
	],
	'ME' => [
		'code' => 'ME',
		'code3' => 'MNE',
		'num' => '499',
		'name' => 'Черногория',
		'cont' => '',
		'active' => 0,
	],
	'CZ' => [
		'code' => 'CZ',
		'code3' => 'CZE',
		'num' => '203',
		'name' => 'Чехия',
		'cont' => '',
		'active' => 0,
	],
	'CL' => [
		'code' => 'CL',
		'code3' => 'CHL',
		'num' => '152',
		'name' => 'Чили',
		'cont' => '',
		'active' => 0,
	],
	'CH' => [
		'code' => 'CH',
		'code3' => 'CHE',
		'num' => '756',
		'name' => 'Швейцария',
		'cont' => '',
		'active' => 0,
	],
	'SE' => [
		'code' => 'SE',
		'code3' => 'SWE',
		'num' => '752',
		'name' => 'Швеция',
		'cont' => '',
		'active' => 0,
	],
	'SJ' => [
		'code' => 'SJ',
		'code3' => 'SJM',
		'num' => '744',
		'name' => 'Шпицберген и Ян-Майен',
		'cont' => '',
		'active' => 0,
	],
	'LK' => [
		'code' => 'LK',
		'code3' => 'LKA',
		'num' => '144',
		'name' => 'Шри-Ланка',
		'cont' => '',
		'active' => 0,
	],
	'EC' => [
		'code' => 'EC',
		'code3' => 'ECU',
		'num' => '218',
		'name' => 'Эквадор',
		'cont' => '',
		'active' => 0,
	],
	'GQ' => [
		'code' => 'GQ',
		'code3' => 'GNQ',
		'num' => '226',
		'name' => 'Экваториальная Гвинея',
		'cont' => '',
		'active' => 0,
	],
	'ER' => [
		'code' => 'ER',
		'code3' => 'ERI',
		'num' => '232',
		'name' => 'Эритрея',
		'cont' => '',
		'active' => 0,
	],
	'EE' => [
		'code' => 'EE',
		'code3' => 'EST',
		'num' => '233',
		'name' => 'Эстония',
		'cont' => '',
		'active' => 0,
	],
	'ET' => [
		'code' => 'ET',
		'code3' => 'ETH',
		'num' => '231',
		'name' => 'Эфиопия',
		'cont' => '',
		'active' => 0,
	],
	'ZA' => [
		'code' => 'ZA',
		'code3' => 'ZAF',
		'num' => '710',
		'name' => 'ЮАР',
		'cont' => '',
		'active' => 0,
	],
	'GS' => [
		'code' => 'GS',
		'code3' => 'SGS',
		'num' => '239',
		'name' => 'Южная Георгия и Южные Сандвичевы Острова',
		'cont' => '',
		'active' => 0,
	],
	'SS' => [
		'code' => 'SS',
		'code3' => 'SSD',
		'num' => '728',
		'name' => 'Южный Судан',
		'cont' => '',
		'active' => 0,
	],
	'JM' => [
		'code' => 'JM',
		'code3' => 'JAM',
		'num' => '388',
		'name' => 'Ямайка',
		'cont' => '',
		'active' => 0,
	],
	'JP' => [
		'code' => 'JP',
		'code3' => 'JPN',
		'num' => '392',
		'name' => 'Япония',
		'cont' => '',
		'active' => 0,
	],
];