<?php

return [
    'fields' => [
        'id' => [
            'name' => 'id',
            'type' => 'int',
            'length' => 11,
            'decimals' => null,
            'unsigned' => false,
            'nullable' => false,
            'default' => null,
            'charset' => null,
            'collate' => null,
            'auto_inc' => true,
            'primary' => true,
            'unique' => false,
            'values' => null,
        ],
        'city_raw' => [
            'name' => 'city_raw',
            'type' => 'varchar',
            'length' => 255,
            'decimals' => null,
            'unsigned' => null,
            'nullable' => true,
            'default' => 'NULL',
            'charset' => null,
            'collate' => null,
            'auto_inc' => false,
            'primary' => false,
            'unique' => true,
            'values' => null,
        ],
        'address_raw' => [
            'name' => 'address_raw',
            'type' => 'varchar',
            'length' => 255,
            'decimals' => null,
            'unsigned' => null,
            'nullable' => true,
            'default' => 'NULL',
            'charset' => null,
            'collate' => null,
            'auto_inc' => false,
            'primary' => false,
            'unique' => true,
            'values' => null,
        ],
        'tel_raw' => [
            'name' => 'tel_raw',
            'type' => 'varchar',
            'length' => 255,
            'decimals' => null,
            'unsigned' => null,
            'nullable' => true,
            'default' => 'NULL',
            'charset' => null,
            'collate' => null,
            'auto_inc' => false,
            'primary' => false,
            'unique' => false,
            'values' => null,
        ],
        'city' => [
            'name' => 'city',
            'type' => 'varchar',
            'length' => 255,
            'decimals' => null,
            'unsigned' => null,
            'nullable' => true,
            'default' => 'NULL',
            'charset' => null,
            'collate' => null,
            'auto_inc' => false,
            'primary' => false,
            'unique' => false,
            'values' => null,
        ],
        'branch_no' => [
            'name' => 'branch_no',
            'type' => 'int',
            'length' => 11,
            'decimals' => null,
            'unsigned' => false,
            'nullable' => true,
            'default' => 'NULL',
            'charset' => null,
            'collate' => null,
            'auto_inc' => false,
            'primary' => false,
            'unique' => false,
            'values' => null,
        ],
        'address' => [
            'name' => 'address',
            'type' => 'varchar',
            'length' => 255,
            'decimals' => null,
            'unsigned' => null,
            'nullable' => true,
            'default' => 'NULL',
            'charset' => null,
            'collate' => null,
            'auto_inc' => false,
            'primary' => false,
            'unique' => false,
            'values' => null,
        ],
        'info' => [
            'name' => 'info',
            'type' => 'varchar',
            'length' => 255,
            'decimals' => null,
            'unsigned' => null,
            'nullable' => true,
            'default' => 'NULL',
            'charset' => null,
            'collate' => null,
            'auto_inc' => false,
            'primary' => false,
            'unique' => false,
            'values' => null,
        ],
        'location' => [
            'name' => 'location',
            'type' => 'varchar',
            'length' => 255,
            'decimals' => null,
            'unsigned' => null,
            'nullable' => true,
            'default' => 'NULL',
            'charset' => null,
            'collate' => null,
            'auto_inc' => false,
            'primary' => false,
            'unique' => false,
            'values' => null,
        ],
        'tel' => [
            'name' => 'tel',
            'type' => 'varchar',
            'length' => 255,
            'decimals' => null,
            'unsigned' => null,
            'nullable' => true,
            'default' => 'NULL',
            'charset' => null,
            'collate' => null,
            'auto_inc' => false,
            'primary' => false,
            'unique' => false,
            'values' => null,
        ],
        'options' => [
            'name' => 'options',
            'type' => 'text',
            'length' => null,
            'decimals' => null,
            'unsigned' => null,
            'nullable' => true,
            'default' => 'NULL',
            'charset' => null,
            'collate' => null,
            'auto_inc' => false,
            'primary' => false,
            'unique' => false,
            'values' => null,
        ],
    ],
    'indexes' => [
        'PRIMARY' => [
            'name' => 'PRIMARY',
            'type' => 'primary',
            'columns' => [
                'id' => 'id',
            ],
        ],
        'city_raw__address_raw' => [
            'name' => 'city_raw__address_raw',
            'type' => 'unique',
            'columns' => [
                'city_raw' => 'city_raw',
                'address_raw' => 'address_raw',
            ],
        ],
        'city' => [
            'name' => 'city',
            'type' => 'index',
            'columns' => [
                'city' => 'city',
            ],
        ],
        'branch_no' => [
            'name' => 'branch_no',
            'type' => 'index',
            'columns' => [
                'branch_no' => 'branch_no',
            ],
        ],
        'address' => [
            'name' => 'address',
            'type' => 'index',
            'columns' => [
                'address' => 'address',
            ],
        ],
    ],
    'foreign_keys' => [
    ],
    'options' => [
    ],
];
