<?php

return [
    'fields' => [
        'id' => [
            'name' => 'id',
            'type' => 'int',
            'length' => 10,
            'decimals' => null,
            'unsigned' => true,
            'nullable' => false,
            'default' => null,
            'charset' => null,
            'collate' => null,
            'auto_inc' => true,
            'primary' => true,
            'unique' => false,
            'values' => null,
        ],
        'name' => [
            'name' => 'name',
            'type' => 'varchar',
            'length' => 255,
            'decimals' => null,
            'unsigned' => null,
            'nullable' => false,
            'default' => '',
            'charset' => 'utf8',
            'collate' => 'utf8_unicode_ci',
            'auto_inc' => false,
            'primary' => false,
            'unique' => false,
            'values' => null,
        ],
        'url' => [
            'name' => 'url',
            'type' => 'varchar',
            'length' => 255,
            'decimals' => null,
            'unsigned' => null,
            'nullable' => false,
            'default' => '',
            'charset' => 'utf8',
            'collate' => 'utf8_unicode_ci',
            'auto_inc' => false,
            'primary' => false,
            'unique' => false,
            'values' => null,
        ],
        'image' => [
            'name' => 'image',
            'type' => 'tinyint',
            'length' => 1,
            'decimals' => null,
            'unsigned' => false,
            'nullable' => false,
            'default' => '0',
            'charset' => null,
            'collate' => null,
            'auto_inc' => false,
            'primary' => false,
            'unique' => false,
            'values' => null,
        ],
        'description' => [
            'name' => 'description',
            'type' => 'text',
            'length' => null,
            'decimals' => null,
            'unsigned' => null,
            'nullable' => false,
            'default' => null,
            'charset' => 'utf8',
            'collate' => 'utf8_unicode_ci',
            'auto_inc' => false,
            'primary' => false,
            'unique' => false,
            'values' => null,
        ],
        'features' => [
            'name' => 'features',
            'type' => 'text',
            'length' => null,
            'decimals' => null,
            'unsigned' => null,
            'nullable' => false,
            'default' => null,
            'charset' => 'utf8',
            'collate' => 'utf8_unicode_ci',
            'auto_inc' => false,
            'primary' => false,
            'unique' => false,
            'values' => null,
        ],
        'meta_keywords' => [
            'name' => 'meta_keywords',
            'type' => 'text',
            'length' => null,
            'decimals' => null,
            'unsigned' => null,
            'nullable' => false,
            'default' => null,
            'charset' => 'utf8',
            'collate' => 'utf8_unicode_ci',
            'auto_inc' => false,
            'primary' => false,
            'unique' => false,
            'values' => null,
        ],
        'meta_desc' => [
            'name' => 'meta_desc',
            'type' => 'text',
            'length' => null,
            'decimals' => null,
            'unsigned' => null,
            'nullable' => false,
            'default' => null,
            'charset' => 'utf8',
            'collate' => 'utf8_unicode_ci',
            'auto_inc' => false,
            'primary' => false,
            'unique' => false,
            'values' => null,
        ],
        'external_url' => [
            'name' => 'external_url',
            'type' => 'varchar',
            'length' => 255,
            'decimals' => null,
            'unsigned' => null,
            'nullable' => false,
            'default' => '',
            'charset' => 'utf8',
            'collate' => 'utf8_unicode_ci',
            'auto_inc' => false,
            'primary' => false,
            'unique' => false,
            'values' => null,
        ],
        'cat_id' => [
            'name' => 'cat_id',
            'type' => 'int',
            'length' => 11,
            'decimals' => null,
            'unsigned' => false,
            'nullable' => false,
            'default' => null,
            'charset' => null,
            'collate' => null,
            'auto_inc' => false,
            'primary' => false,
            'unique' => false,
            'values' => null,
        ],
        'model' => [
            'name' => 'model',
            'type' => 'varchar',
            'length' => 64,
            'decimals' => null,
            'unsigned' => null,
            'nullable' => false,
            'default' => null,
            'charset' => 'utf8',
            'collate' => 'utf8_unicode_ci',
            'auto_inc' => false,
            'primary' => false,
            'unique' => false,
            'values' => null,
        ],
        'sku' => [
            'name' => 'sku',
            'type' => 'varchar',
            'length' => 64,
            'decimals' => null,
            'unsigned' => null,
            'nullable' => false,
            'default' => null,
            'charset' => 'utf8',
            'collate' => 'utf8_unicode_ci',
            'auto_inc' => false,
            'primary' => false,
            'unique' => false,
            'values' => null,
        ],
        'quantity' => [
            'name' => 'quantity',
            'type' => 'int',
            'length' => 10,
            'decimals' => null,
            'unsigned' => false,
            'nullable' => false,
            'default' => '100',
            'charset' => null,
            'collate' => null,
            'auto_inc' => false,
            'primary' => false,
            'unique' => false,
            'values' => null,
        ],
        'stock_status_id' => [
            'name' => 'stock_status_id',
            'type' => 'int',
            'length' => 10,
            'decimals' => null,
            'unsigned' => false,
            'nullable' => false,
            'default' => '0',
            'charset' => null,
            'collate' => null,
            'auto_inc' => false,
            'primary' => false,
            'unique' => false,
            'values' => null,
        ],
        'manufacturer_id' => [
            'name' => 'manufacturer_id',
            'type' => 'int',
            'length' => 10,
            'decimals' => null,
            'unsigned' => false,
            'nullable' => false,
            'default' => '0',
            'charset' => null,
            'collate' => null,
            'auto_inc' => false,
            'primary' => false,
            'unique' => false,
            'values' => null,
        ],
        'supplier_id' => [
            'name' => 'supplier_id',
            'type' => 'int',
            'length' => 10,
            'decimals' => null,
            'unsigned' => false,
            'nullable' => false,
            'default' => '0',
            'charset' => null,
            'collate' => null,
            'auto_inc' => false,
            'primary' => false,
            'unique' => false,
            'values' => null,
        ],
        'price' => [
            'name' => 'price',
            'type' => 'decimal',
            'length' => 8,
            'decimals' => '2',
            'unsigned' => false,
            'nullable' => false,
            'default' => '0.00',
            'charset' => null,
            'collate' => null,
            'auto_inc' => false,
            'primary' => false,
            'unique' => false,
            'values' => null,
        ],
        'price_promo' => [
            'name' => 'price_promo',
            'type' => 'decimal',
            'length' => 8,
            'decimals' => '2',
            'unsigned' => false,
            'nullable' => false,
            'default' => '0.00',
            'charset' => null,
            'collate' => null,
            'auto_inc' => false,
            'primary' => false,
            'unique' => false,
            'values' => null,
        ],
        'price_partner' => [
            'name' => 'price_partner',
            'type' => 'decimal',
            'length' => 8,
            'decimals' => '2',
            'unsigned' => false,
            'nullable' => false,
            'default' => '0.00',
            'charset' => null,
            'collate' => null,
            'auto_inc' => false,
            'primary' => false,
            'unique' => false,
            'values' => null,
        ],
        'price_raw' => [
            'name' => 'price_raw',
            'type' => 'decimal',
            'length' => 8,
            'decimals' => '2',
            'unsigned' => false,
            'nullable' => false,
            'default' => '0.00',
            'charset' => null,
            'collate' => null,
            'auto_inc' => false,
            'primary' => false,
            'unique' => false,
            'values' => null,
        ],
        'old_price' => [
            'name' => 'old_price',
            'type' => 'decimal',
            'length' => 8,
            'decimals' => '2',
            'unsigned' => false,
            'nullable' => false,
            'default' => '0.00',
            'charset' => null,
            'collate' => null,
            'auto_inc' => false,
            'primary' => false,
            'unique' => false,
            'values' => null,
        ],
        'currency' => [
            'name' => 'currency',
            'type' => 'tinyint',
            'length' => 3,
            'decimals' => null,
            'unsigned' => true,
            'nullable' => false,
            'default' => '0',
            'charset' => null,
            'collate' => null,
            'auto_inc' => false,
            'primary' => false,
            'unique' => false,
            'values' => null,
        ],
        'add_date' => [
            'name' => 'add_date',
            'type' => 'int',
            'length' => 10,
            'decimals' => null,
            'unsigned' => true,
            'nullable' => false,
            'default' => '0',
            'charset' => null,
            'collate' => null,
            'auto_inc' => false,
            'primary' => false,
            'unique' => false,
            'values' => null,
        ],
        'update_date' => [
            'name' => 'update_date',
            'type' => 'int',
            'length' => 10,
            'decimals' => null,
            'unsigned' => true,
            'nullable' => false,
            'default' => '0',
            'charset' => null,
            'collate' => null,
            'auto_inc' => false,
            'primary' => false,
            'unique' => false,
            'values' => null,
        ],
        'last_viewed_date' => [
            'name' => 'last_viewed_date',
            'type' => 'int',
            'length' => 10,
            'decimals' => null,
            'unsigned' => false,
            'nullable' => false,
            'default' => '0',
            'charset' => null,
            'collate' => null,
            'auto_inc' => false,
            'primary' => false,
            'unique' => false,
            'values' => null,
        ],
        'featured' => [
            'name' => 'featured',
            'type' => 'tinyint',
            'length' => 1,
            'decimals' => null,
            'unsigned' => false,
            'nullable' => false,
            'default' => '0',
            'charset' => null,
            'collate' => null,
            'auto_inc' => false,
            'primary' => false,
            'unique' => false,
            'values' => null,
        ],
        'active' => [
            'name' => 'active',
            'type' => 'tinyint',
            'length' => 1,
            'decimals' => null,
            'unsigned' => false,
            'nullable' => false,
            'default' => '0',
            'charset' => null,
            'collate' => null,
            'auto_inc' => false,
            'primary' => false,
            'unique' => false,
            'values' => null,
        ],
        'viewed' => [
            'name' => 'viewed',
            'type' => 'int',
            'length' => 10,
            'decimals' => null,
            'unsigned' => false,
            'nullable' => false,
            'default' => '0',
            'charset' => null,
            'collate' => null,
            'auto_inc' => false,
            'primary' => false,
            'unique' => false,
            'values' => null,
        ],
        'sold' => [
            'name' => 'sold',
            'type' => 'int',
            'length' => 10,
            'decimals' => null,
            'unsigned' => false,
            'nullable' => false,
            'default' => '0',
            'charset' => null,
            'collate' => null,
            'auto_inc' => false,
            'primary' => false,
            'unique' => false,
            'values' => null,
        ],
        'status' => [
            'name' => 'status',
            'type' => 'int',
            'length' => 10,
            'decimals' => null,
            'unsigned' => false,
            'nullable' => false,
            'default' => '0',
            'charset' => null,
            'collate' => null,
            'auto_inc' => false,
            'primary' => false,
            'unique' => false,
            'values' => null,
        ],
        'articul' => [
            'name' => 'articul',
            'type' => 'varchar',
            'length' => 32,
            'decimals' => null,
            'unsigned' => null,
            'nullable' => false,
            'default' => '',
            'charset' => null,
            'collate' => null,
            'auto_inc' => false,
            'primary' => false,
            'unique' => false,
            'values' => null,
        ],
        'origin_url' => [
            'name' => 'origin_url',
            'type' => 'varchar',
            'length' => 255,
            'decimals' => null,
            'unsigned' => null,
            'nullable' => false,
            'default' => null,
            'charset' => null,
            'collate' => null,
            'auto_inc' => false,
            'primary' => false,
            'unique' => false,
            'values' => null,
        ],
        'source' => [
            'name' => 'source',
            'type' => 'varchar',
            'length' => 255,
            'decimals' => null,
            'unsigned' => null,
            'nullable' => false,
            'default' => null,
            'charset' => null,
            'collate' => null,
            'auto_inc' => false,
            'primary' => false,
            'unique' => false,
            'values' => null,
        ],
    ],
    'indexes' => [
        'PRIMARY' => [
            'name' => 'PRIMARY',
            'type' => 'primary',
            'columns' => [
                'id' => 'id',
            ],
        ],
        'cat_id' => [
            'name' => 'cat_id',
            'type' => 'index',
            'columns' => [
                'cat_id' => 'cat_id',
            ],
        ],
        'active' => [
            'name' => 'active',
            'type' => 'index',
            'columns' => [
                'active' => 'active',
            ],
        ],
        'viewed' => [
            'name' => 'viewed',
            'type' => 'index',
            'columns' => [
                'viewed' => 'viewed',
            ],
        ],
        'sold' => [
            'name' => 'sold',
            'type' => 'index',
            'columns' => [
                'sold' => 'sold',
            ],
        ],
        'active_cat_id' => [
            'name' => 'active_cat_id',
            'type' => 'index',
            'columns' => [
                'active' => 'active',
                'cat_id' => 'cat_id',
            ],
        ],
        'add_date' => [
            'name' => 'add_date',
            'type' => 'index',
            'columns' => [
                'add_date' => 'add_date',
            ],
        ],
        'update_date' => [
            'name' => 'update_date',
            'type' => 'index',
            'columns' => [
                'update_date' => 'update_date',
            ],
        ],
        'manufacturer_id' => [
            'name' => 'manufacturer_id',
            'type' => 'index',
            'columns' => [
                'manufacturer_id' => 'manufacturer_id',
            ],
        ],
        'supplier_id' => [
            'name' => 'supplier_id',
            'type' => 'index',
            'columns' => [
                'supplier_id' => 'supplier_id',
            ],
        ],
    ],
    'foreign_keys' => [
    ],
    'options' => [
    ],
];
