<?php

return [
    'fields' => [
        'id' => [
            'name' => 'id',
            'type' => 'int',
            'length' => 11,
            'decimals' => null,
            'unsigned' => false,
            'nullable' => false,
            'default' => null,
            'charset' => null,
            'collate' => null,
            'auto_inc' => true,
            'primary' => true,
            'unique' => false,
            'values' => null,
        ],
        'active' => [
            'name' => 'active',
            'type' => 'tinyint',
            'length' => 4,
            'decimals' => null,
            'unsigned' => false,
            'nullable' => false,
            'default' => '0',
            'charset' => null,
            'collate' => null,
            'auto_inc' => false,
            'primary' => false,
            'unique' => false,
            'values' => null,
        ],
        'type' => [
            'name' => 'type',
            'type' => 'tinyint',
            'length' => 4,
            'decimals' => null,
            'unsigned' => false,
            'nullable' => false,
            'default' => '0',
            'charset' => null,
            'collate' => null,
            'auto_inc' => false,
            'primary' => false,
            'unique' => false,
            'values' => null,
        ],
        'value' => [
            'name' => 'value',
            'type' => 'decimal',
            'length' => 10,
            'decimals' => '2',
            'unsigned' => false,
            'nullable' => true,
            'default' => 'NULL',
            'charset' => null,
            'collate' => null,
            'auto_inc' => false,
            'primary' => false,
            'unique' => false,
            'values' => null,
        ],
        'description' => [
            'name' => 'description',
            'type' => 'varchar',
            'length' => 255,
            'decimals' => null,
            'unsigned' => null,
            'nullable' => true,
            'default' => 'NULL',
            'charset' => null,
            'collate' => null,
            'auto_inc' => false,
            'primary' => false,
            'unique' => false,
            'values' => null,
        ],
        'time_from' => [
            'name' => 'time_from',
            'type' => 'datetime',
            'length' => null,
            'decimals' => null,
            'unsigned' => null,
            'nullable' => true,
            'default' => 'NULL',
            'charset' => null,
            'collate' => null,
            'auto_inc' => false,
            'primary' => false,
            'unique' => false,
            'values' => null,
        ],
        'time_to' => [
            'name' => 'time_to',
            'type' => 'datetime',
            'length' => null,
            'decimals' => null,
            'unsigned' => null,
            'nullable' => true,
            'default' => 'NULL',
            'charset' => null,
            'collate' => null,
            'auto_inc' => false,
            'primary' => false,
            'unique' => false,
            'values' => null,
        ],
        'conditions' => [
            'name' => 'conditions',
            'type' => 'text',
            'length' => null,
            'decimals' => null,
            'unsigned' => null,
            'nullable' => true,
            'default' => null,
            'charset' => null,
            'collate' => null,
            'auto_inc' => false,
            'primary' => false,
            'unique' => false,
            'values' => null,
        ],
    ],
    'indexes' => [
        'PRIMARY' => [
            'name' => 'PRIMARY',
            'type' => 'primary',
            'columns' => [
                'id' => 'id',
            ],
        ],
        'active' => [
            'name' => 'active',
            'type' => 'index',
            'columns' => [
                'active' => 'active',
            ],
        ],
    ],
    'foreign_keys' => [
    ],
    'options' => [
    ],
];
