<?php
return [
	'fields' => [
		'id' => [
			'name' => 'id',
			'type' => 'int',
			'length' => 10,
			'decimals' => NULL,
			'unsigned' => true,
			'nullable' => false,
			'default' => NULL,
			'charset' => NULL,
			'collate' => NULL,
			'auto_inc' => true,
			'primary' => true,
			'unique' => false,
			'values' => NULL,
		],
		'name' => [
			'name' => 'name',
			'type' => 'varchar',
			'length' => 255,
			'decimals' => NULL,
			'unsigned' => NULL,
			'nullable' => false,
			'default' => '',
			'charset' => 'utf8',
			'collate' => 'utf8_unicode_ci',
			'auto_inc' => false,
			'primary' => false,
			'unique' => false,
			'values' => NULL,
		],
		'url' => [
			'name' => 'url',
			'type' => 'varchar',
			'length' => 255,
			'decimals' => NULL,
			'unsigned' => NULL,
			'nullable' => false,
			'default' => '',
			'charset' => 'utf8',
			'collate' => 'utf8_unicode_ci',
			'auto_inc' => false,
			'primary' => false,
			'unique' => false,
			'values' => NULL,
		],
		'image' => [
			'name' => 'image',
			'type' => 'tinyint',
			'length' => 1,
			'decimals' => NULL,
			'unsigned' => false,
			'nullable' => false,
			'default' => '0',
			'charset' => NULL,
			'collate' => NULL,
			'auto_inc' => false,
			'primary' => false,
			'unique' => false,
			'values' => NULL,
		],
		'description' => [
			'name' => 'description',
			'type' => 'text',
			'length' => NULL,
			'decimals' => NULL,
			'unsigned' => NULL,
			'nullable' => false,
			'default' => NULL,
			'charset' => 'utf8',
			'collate' => 'utf8_unicode_ci',
			'auto_inc' => false,
			'primary' => false,
			'unique' => false,
			'values' => NULL,
		],
		'features' => [
			'name' => 'features',
			'type' => 'text',
			'length' => NULL,
			'decimals' => NULL,
			'unsigned' => NULL,
			'nullable' => false,
			'default' => NULL,
			'charset' => 'utf8',
			'collate' => 'utf8_unicode_ci',
			'auto_inc' => false,
			'primary' => false,
			'unique' => false,
			'values' => NULL,
		],
		'meta_keywords' => [
			'name' => 'meta_keywords',
			'type' => 'text',
			'length' => NULL,
			'decimals' => NULL,
			'unsigned' => NULL,
			'nullable' => false,
			'default' => NULL,
			'charset' => 'utf8',
			'collate' => 'utf8_unicode_ci',
			'auto_inc' => false,
			'primary' => false,
			'unique' => false,
			'values' => NULL,
		],
		'meta_desc' => [
			'name' => 'meta_desc',
			'type' => 'text',
			'length' => NULL,
			'decimals' => NULL,
			'unsigned' => NULL,
			'nullable' => false,
			'default' => NULL,
			'charset' => 'utf8',
			'collate' => 'utf8_unicode_ci',
			'auto_inc' => false,
			'primary' => false,
			'unique' => false,
			'values' => NULL,
		],
		'external_url' => [
			'name' => 'external_url',
			'type' => 'varchar',
			'length' => 255,
			'decimals' => NULL,
			'unsigned' => NULL,
			'nullable' => false,
			'default' => '',
			'charset' => 'utf8',
			'collate' => 'utf8_unicode_ci',
			'auto_inc' => false,
			'primary' => false,
			'unique' => false,
			'values' => NULL,
		],
		'cat_id' => [
			'name' => 'cat_id',
			'type' => 'int',
			'length' => 11,
			'decimals' => NULL,
			'unsigned' => false,
			'nullable' => false,
			'default' => NULL,
			'charset' => NULL,
			'collate' => NULL,
			'auto_inc' => false,
			'primary' => false,
			'unique' => false,
			'values' => NULL,
		],
		'model' => [
			'name' => 'model',
			'type' => 'varchar',
			'length' => 64,
			'decimals' => NULL,
			'unsigned' => NULL,
			'nullable' => false,
			'default' => NULL,
			'charset' => 'utf8',
			'collate' => 'utf8_unicode_ci',
			'auto_inc' => false,
			'primary' => false,
			'unique' => false,
			'values' => NULL,
		],
		'sku' => [
			'name' => 'sku',
			'type' => 'varchar',
			'length' => 64,
			'decimals' => NULL,
			'unsigned' => NULL,
			'nullable' => false,
			'default' => NULL,
			'charset' => 'utf8',
			'collate' => 'utf8_unicode_ci',
			'auto_inc' => false,
			'primary' => false,
			'unique' => false,
			'values' => NULL,
		],
		'quantity' => [
			'name' => 'quantity',
			'type' => 'int',
			'length' => 10,
			'decimals' => NULL,
			'unsigned' => false,
			'nullable' => false,
			'default' => '100',
			'charset' => NULL,
			'collate' => NULL,
			'auto_inc' => false,
			'primary' => false,
			'unique' => false,
			'values' => NULL,
		],
		'stock_status_id' => [
			'name' => 'stock_status_id',
			'type' => 'int',
			'length' => 10,
			'decimals' => NULL,
			'unsigned' => false,
			'nullable' => false,
			'default' => '0',
			'charset' => NULL,
			'collate' => NULL,
			'auto_inc' => false,
			'primary' => false,
			'unique' => false,
			'values' => NULL,
		],
		'manufacturer_id' => [
			'name' => 'manufacturer_id',
			'type' => 'int',
			'length' => 10,
			'decimals' => NULL,
			'unsigned' => false,
			'nullable' => false,
			'default' => '0',
			'charset' => NULL,
			'collate' => NULL,
			'auto_inc' => false,
			'primary' => false,
			'unique' => false,
			'values' => NULL,
		],
		'supplier_id' => [
			'name' => 'supplier_id',
			'type' => 'int',
			'length' => 10,
			'decimals' => NULL,
			'unsigned' => false,
			'nullable' => false,
			'default' => '0',
			'charset' => NULL,
			'collate' => NULL,
			'auto_inc' => false,
			'primary' => false,
			'unique' => false,
			'values' => NULL,
		],
		'price' => [
			'name' => 'price',
			'type' => 'decimal',
			'length' => 8,
			'decimals' => '2',
			'unsigned' => false,
			'nullable' => false,
			'default' => '0.00',
			'charset' => NULL,
			'collate' => NULL,
			'auto_inc' => false,
			'primary' => false,
			'unique' => false,
			'values' => NULL,
		],
		'price_promo' => [
			'name' => 'price_promo',
			'type' => 'decimal',
			'length' => 8,
			'decimals' => '2',
			'unsigned' => false,
			'nullable' => false,
			'default' => '0.00',
			'charset' => NULL,
			'collate' => NULL,
			'auto_inc' => false,
			'primary' => false,
			'unique' => false,
			'values' => NULL,
		],
		'price_partner' => [
			'name' => 'price_partner',
			'type' => 'decimal',
			'length' => 8,
			'decimals' => '2',
			'unsigned' => false,
			'nullable' => false,
			'default' => '0.00',
			'charset' => NULL,
			'collate' => NULL,
			'auto_inc' => false,
			'primary' => false,
			'unique' => false,
			'values' => NULL,
		],
		'price_raw' => [
			'name' => 'price_raw',
			'type' => 'decimal',
			'length' => 8,
			'decimals' => '2',
			'unsigned' => false,
			'nullable' => false,
			'default' => '0.00',
			'charset' => NULL,
			'collate' => NULL,
			'auto_inc' => false,
			'primary' => false,
			'unique' => false,
			'values' => NULL,
		],
		'old_price' => [
			'name' => 'old_price',
			'type' => 'decimal',
			'length' => 8,
			'decimals' => '2',
			'unsigned' => false,
			'nullable' => false,
			'default' => '0.00',
			'charset' => NULL,
			'collate' => NULL,
			'auto_inc' => false,
			'primary' => false,
			'unique' => false,
			'values' => NULL,
		],
		'currency' => [
			'name' => 'currency',
			'type' => 'tinyint',
			'length' => 3,
			'decimals' => NULL,
			'unsigned' => true,
			'nullable' => false,
			'default' => '0',
			'charset' => NULL,
			'collate' => NULL,
			'auto_inc' => false,
			'primary' => false,
			'unique' => false,
			'values' => NULL,
		],
		'add_date' => [
			'name' => 'add_date',
			'type' => 'int',
			'length' => 10,
			'decimals' => NULL,
			'unsigned' => true,
			'nullable' => false,
			'default' => '0',
			'charset' => NULL,
			'collate' => NULL,
			'auto_inc' => false,
			'primary' => false,
			'unique' => false,
			'values' => NULL,
		],
		'update_date' => [
			'name' => 'update_date',
			'type' => 'int',
			'length' => 10,
			'decimals' => NULL,
			'unsigned' => true,
			'nullable' => false,
			'default' => '0',
			'charset' => NULL,
			'collate' => NULL,
			'auto_inc' => false,
			'primary' => false,
			'unique' => false,
			'values' => NULL,
		],
		'last_viewed_date' => [
			'name' => 'last_viewed_date',
			'type' => 'int',
			'length' => 10,
			'decimals' => NULL,
			'unsigned' => false,
			'nullable' => false,
			'default' => '0',
			'charset' => NULL,
			'collate' => NULL,
			'auto_inc' => false,
			'primary' => false,
			'unique' => false,
			'values' => NULL,
		],
		'featured' => [
			'name' => 'featured',
			'type' => 'tinyint',
			'length' => 1,
			'decimals' => NULL,
			'unsigned' => false,
			'nullable' => false,
			'default' => '0',
			'charset' => NULL,
			'collate' => NULL,
			'auto_inc' => false,
			'primary' => false,
			'unique' => false,
			'values' => NULL,
		],
		'active' => [
			'name' => 'active',
			'type' => 'tinyint',
			'length' => 1,
			'decimals' => NULL,
			'unsigned' => false,
			'nullable' => false,
			'default' => '0',
			'charset' => NULL,
			'collate' => NULL,
			'auto_inc' => false,
			'primary' => false,
			'unique' => false,
			'values' => NULL,
		],
		'viewed' => [
			'name' => 'viewed',
			'type' => 'int',
			'length' => 10,
			'decimals' => NULL,
			'unsigned' => false,
			'nullable' => false,
			'default' => '0',
			'charset' => NULL,
			'collate' => NULL,
			'auto_inc' => false,
			'primary' => false,
			'unique' => false,
			'values' => NULL,
		],
		'sold' => [
			'name' => 'sold',
			'type' => 'int',
			'length' => 10,
			'decimals' => NULL,
			'unsigned' => false,
			'nullable' => false,
			'default' => '0',
			'charset' => NULL,
			'collate' => NULL,
			'auto_inc' => false,
			'primary' => false,
			'unique' => false,
			'values' => NULL,
		],
		'status' => [
			'name' => 'status',
			'type' => 'int',
			'length' => 10,
			'decimals' => NULL,
			'unsigned' => false,
			'nullable' => false,
			'default' => '0',
			'charset' => NULL,
			'collate' => NULL,
			'auto_inc' => false,
			'primary' => false,
			'unique' => false,
			'values' => NULL,
		],
		'articul' => [
			'name' => 'articul',
			'type' => 'varchar',
			'length' => 32,
			'decimals' => NULL,
			'unsigned' => NULL,
			'nullable' => false,
			'default' => '',
			'charset' => NULL,
			'collate' => NULL,
			'auto_inc' => false,
			'primary' => false,
			'unique' => false,
			'values' => NULL,
		],
		'origin_url' => [
			'name' => 'origin_url',
			'type' => 'varchar',
			'length' => 255,
			'decimals' => NULL,
			'unsigned' => NULL,
			'nullable' => false,
			'default' => NULL,
			'charset' => NULL,
			'collate' => NULL,
			'auto_inc' => false,
			'primary' => false,
			'unique' => false,
			'values' => NULL,
		],
		'source' => [
			'name' => 'source',
			'type' => 'varchar',
			'length' => 255,
			'decimals' => NULL,
			'unsigned' => NULL,
			'nullable' => false,
			'default' => NULL,
			'charset' => NULL,
			'collate' => NULL,
			'auto_inc' => false,
			'primary' => false,
			'unique' => false,
			'values' => NULL,
		],
	],
	'indexes' => [
		'PRIMARY' => [
			'name' => 'PRIMARY',
			'type' => 'primary',
			'columns' => [
				'id' => 'id',
			],
		],
		'cat_id' => [
			'name' => 'cat_id',
			'type' => 'index',
			'columns' => [
				'cat_id' => 'cat_id',
			],
		],
		'active' => [
			'name' => 'active',
			'type' => 'index',
			'columns' => [
				'active' => 'active',
			],
		],
		'viewed' => [
			'name' => 'viewed',
			'type' => 'index',
			'columns' => [
				'viewed' => 'viewed',
			],
		],
		'sold' => [
			'name' => 'sold',
			'type' => 'index',
			'columns' => [
				'sold' => 'sold',
			],
		],
		'active_cat_id' => [
			'name' => 'active_cat_id',
			'type' => 'index',
			'columns' => [
				'active' => 'active',
				'cat_id' => 'cat_id',
			],
		],
		'add_date' => [
			'name' => 'add_date',
			'type' => 'index',
			'columns' => [
				'add_date' => 'add_date',
			],
		],
		'update_date' => [
			'name' => 'update_date',
			'type' => 'index',
			'columns' => [
				'update_date' => 'update_date',
			],
		],
		'manufacturer_id' => [
			'name' => 'manufacturer_id',
			'type' => 'index',
			'columns' => [
				'manufacturer_id' => 'manufacturer_id',
			],
		],
		'supplier_id' => [
			'name' => 'supplier_id',
			'type' => 'index',
			'columns' => [
				'supplier_id' => 'supplier_id',
			],
		],
	],
	'foreign_keys' => [
	],
	'options' => [
	],
];
