<?php

return [
    'fields' => [
        'id' => [
            'name' => 'id',
            'type' => 'int',
            'length' => 10,
            'decimals' => null,
            'unsigned' => true,
            'nullable' => false,
            'default' => null,
            'charset' => null,
            'collate' => null,
            'auto_inc' => true,
            'primary' => true,
            'unique' => false,
            'values' => null,
        ],
        'event_id' => [
            'name' => 'event_id',
            'type' => 'int',
            'length' => 10,
            'decimals' => null,
            'unsigned' => true,
            'nullable' => false,
            'default' => null,
            'charset' => null,
            'collate' => null,
            'auto_inc' => false,
            'primary' => false,
            'unique' => false,
            'values' => null,
        ],
        'from_email' => [
            'name' => 'from_email',
            'type' => 'varchar',
            'length' => 254,
            'decimals' => null,
            'unsigned' => null,
            'nullable' => true,
            'default' => 'NULL',
            'charset' => null,
            'collate' => null,
            'auto_inc' => false,
            'primary' => false,
            'unique' => false,
            'values' => null,
        ],
        'from_name' => [
            'name' => 'from_name',
            'type' => 'varchar',
            'length' => 100,
            'decimals' => null,
            'unsigned' => null,
            'nullable' => true,
            'default' => 'NULL',
            'charset' => null,
            'collate' => null,
            'auto_inc' => false,
            'primary' => false,
            'unique' => false,
            'values' => null,
        ],
        'subject' => [
            'name' => 'subject',
            'type' => 'varchar',
            'length' => 78,
            'decimals' => null,
            'unsigned' => null,
            'nullable' => true,
            'default' => 'NULL',
            'charset' => null,
            'collate' => null,
            'auto_inc' => false,
            'primary' => false,
            'unique' => false,
            'values' => null,
        ],
        'html' => [
            'name' => 'html',
            'type' => 'text',
            'length' => null,
            'decimals' => null,
            'unsigned' => null,
            'nullable' => true,
            'default' => null,
            'charset' => null,
            'collate' => null,
            'auto_inc' => false,
            'primary' => false,
            'unique' => false,
            'values' => null,
        ],
        'active' => [
            'name' => 'active',
            'type' => 'tinyint',
            'length' => 4,
            'decimals' => null,
            'unsigned' => false,
            'nullable' => false,
            'default' => '0',
            'charset' => null,
            'collate' => null,
            'auto_inc' => false,
            'primary' => false,
            'unique' => false,
            'values' => null,
        ],
    ],
    'indexes' => [
        'PRIMARY' => [
            'name' => 'PRIMARY',
            'type' => 'primary',
            'columns' => [
                'id' => 'id',
            ],
        ],
        'event_id' => [
            'name' => 'event_id',
            'type' => 'index',
            'columns' => [
                'event_id' => 'event_id',
            ],
        ],
        'event_id_active' => [
            'name' => 'event_id_active',
            'type' => 'index',
            'columns' => [
                'event_id' => 'event_id',
                'active' => 'active',
            ],
        ],
    ],
    'foreign_keys' => [
    ],
    'options' => [
    ],
];
