name: PHP Unit Tests

on:
  push:
    branches:
      - 31
  pull_request:
    branches:
      - 31

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    env:
      WORKDIR: /var/www/vendor/yf31
      TESTS_DIR: ./.dev/tests/
      MYSQL_HOST: mysql-tmp
      MYSQL_PORT: 3306
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_DATABASE: tests
      REDIS_HOST: redis
      REDIS_PORT: 6379

    strategy:
      matrix:
        php-image: ['7.4', '8.0', '8.1', '8.2', '8.3']

    container:
      image: yfix/php:${{ matrix.php-image }}
      volumes:
        - ${{ github.workspace }}:${{ env.WORKDIR }}
      options: --workdir ${{ env.WORKDIR }}

    services:
      mysql-tmp:
        image: yfix/mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: ${{ env.MYSQL_PASSWORD }}
          MYSQL_DATABASE: ${{ env.MYSQL_DATABASE }}
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

      redis:
        image: redis:latest
        ports:
          - 6379:6379
        options: >-
          --health-cmd="redis-cli ping"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    steps:
    - uses: actions/checkout@v4

    - name: Wait for MySQL to be ready
      run: |
        while ! mysqladmin ping -h ${{ env.MYSQL_HOST }} -u ${{ env.MYSQL_USER }} -p${{ env.MYSQL_PASSWORD }} --silent; do
          sleep 1
        done

    - name: Wait for Redis to be ready
      run: |
        redis-cli -h ${{ env.REDIS_HOST }} ping || exit 1

    - name: Run PHPUnit tests
      env: ${{ env }}
      working-directory: ${{ env.TESTS_DIR }}
      run: make phpunit-all
