name: PHP Unit Tests

on:
  push:
    branches:
      - 31
  pull_request:
    branches:
      - 31

jobs:
  unit-tests:
    runs-on: ubuntu-latest

    services:
      mysql-tmp:
        # image: mysql:8.0
        image: yfix/mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: 123456
          MYSQL_DATABASE: tests
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

      redis:
        image: redis:latest
        ports:
          - 6379:6379
        options: >-
          --health-cmd="redis-cli ping"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    strategy:
      matrix:
        php-image: ['7.4', '8.0', '8.1', '8.2', '8.3']
        # mysql-image: ['5.7', '8.0', '8.4']
      fail-fast: false

    container:
      image: yfix/php:${{ matrix.php-image }}
      volumes:
        - ${{ github.workspace }}:${{ env.WORKDIR }}
      options: --workdir ${{ env.WORKDIR }}

    steps:
    - uses: actions/checkout@v4

    - name: Install system dependencies
      run: |
        apt-get update && apt-get install -y \
        git \
        make \
        redis-tools \
        default-mysql-client

    - name: Wait for MySQL to be ready
      run: |
        while ! mysqladmin ping -h mysql-tmp -u root -proot --silent; do
          sleep 1
        done

    - name: Wait for Redis to be ready
      run: |
        redis-cli -h redis ping || exit 1

    - name: Run PHPUnit tests
      env:
        MYSQL_HOST: mysql-tmp
        MYSQL_PORT: 3306
        MYSQL_USER: root
        MYSQL_PASSWORD: root
        MYSQL_DATABASE: tests
        REDIS_HOST: redis
        REDIS_PORT: 6379
      working-directory: ./.dev/tests/
      run: make phpunit-all
