<?php
return '
	`id` int(10) unsigned NOT NULL auto_increment,
	`ticket_key` varchar(32) NOT NULL,
	`user_id` int(10) unsigned NOT NULL,
	`name` varchar(255) NOT NULL,
	`email` varchar(255) NOT NULL,
	`subject` varchar(255) NOT NULL,
	`user_priority` tinyint(3) unsigned NOT NULL,
	`admin_priority` tinyint(3) unsigned NOT NULL,
	`category_id` tinyint(3) unsigned NOT NULL,
	`message` text NOT NULL,
	`urls` text NOT NULL,
	`opened_date` int(10) unsigned NOT NULL,
	`closed_date` int(10) unsigned NOT NULL,
	`admin_comments` text NOT NULL,
	`status` enum(\'new\',\'read\',\'open\',\'closed\') NOT NULL,
	`user_agent` varchar(255) NOT NULL,
	`ip` varchar(15) NOT NULL,
	`cookies_enabled` enum(\'0\',\'1\') NOT NULL,
	`assigned_to` int(10) unsigned NOT NULL,
	`site_id` tinyint(3) unsigned NOT NULL default \'0\',
	`server_id` tinyint(3) unsigned NOT NULL default \'0\',
	`referer` varchar(255) NOT NULL default \'\',
	`activity` int(10) unsigned NOT NULL default \'0\',
	PRIMARY KEY	(`id`),
	KEY `user_id` (`user_id`)
';