<?php
return '
	`id` int(10) unsigned NOT NULL auto_increment,
	`group` tinyint(3) unsigned NOT NULL default \'0\',
	`name` varchar(255) NOT NULL default \'\',
	`nick` varchar(64) NOT NULL default \'\',
	`login` varchar(64) NOT NULL default \'\',
	`email` varchar(50) NOT NULL default \'\',
	`password` varchar(32) NOT NULL default \'\',
	`phone` varchar(40) NOT NULL default \'\',
	`city` varchar(40) NOT NULL default \'\',
	`state` varchar(20) NOT NULL default \'\',
	`country` varchar(30) NOT NULL default \'USA\',
	`zip_code` varchar(16) NOT NULL default \'\',
	`address` varchar(255) NOT NULL default \'\',
	`sex` enum(\'Female\',\'Male\') NOT NULL default \'Female\',
	`age` smallint(2) unsigned NOT NULL default \'0\',
	`birth_date` date NOT NULL default \'0000-00-00\',
	`visits` smallint(6) unsigned NOT NULL default \'0\',
	`active` tinyint(1) unsigned NOT NULL default \'1\',
	`add_date` int(10) unsigned NOT NULL default \'0\',
	`last_update` int(10) unsigned NOT NULL default \'0\',
	`last_login` int(10) unsigned NOT NULL default \'0\',
	`num_logins` smallint(6) unsigned NOT NULL default \'0\',
	`last_view` int(10) unsigned NOT NULL default \'0\',
	`num_views` int(10) unsigned NOT NULL default \'0\',
	`verify_code` varchar(32) NOT NULL default \'\',
	`profile_url` varchar(64) NOT NULL,
	`admin_comments` text NOT NULL,
	`ip` varchar(15) NOT NULL default \'\',
	`photo_verified` enum(\'0\', \'1\') NOT NULL,
	`avatar` varchar(255) NOT NULL default \'\',
	`priority` int(11) NOT NULL default \'0\',
	`lon` decimal(8,4) NOT NULL default \'0.0000\',
	`lat` decimal(8,4) NOT NULL default \'0.0000\',
	`has_avatar` enum(\'0\',\'1\') NOT NULL default \'0\',
	`contact_by_email` enum(\'1\',\'0\') NOT NULL,
	`emails` smallint(6) unsigned NOT NULL default \'0\',
	`emailssent` smallint(6) unsigned NOT NULL default \'0\',
	`go_after_login` varchar(255) NOT NULL default \'\',

	PRIMARY KEY	(`id`),
	KEY `login` (`login`),
	KEY `nick` (`nick`),
	KEY `active` (`active`),
	KEY `group` (`group`),
	KEY `email` (`email`),
	KEY `has_avatar` (`has_avatar`),
	KEY `priority` (`priority`),
	KEY `country` (`country`)
	/** ENGINE=InnoDB DEFAULT CHARSET=utf8 **/
';