REPLACE INTO `%%prefix%%states` (`id`, `name`, `code`, `country_code`) VALUES (1, 'Alabama', 'AL', 'US'),
(2, 'Alaska', 'AK', 'US'),
(3, 'Arizona', 'AZ', 'US'),
(4, 'Arkansas', 'AR', 'US'),
(5, 'California', 'CA', 'US'),
(6, 'Colorado', 'CO', 'US'),
(7, 'Connecticut', 'CT', 'US'),
(8, 'Delaware', 'DE', 'US'),
(9, 'District of Columbia', 'DC', 'US'),
(10, 'Florida', 'FL', 'US'),
(11, 'Georgia', 'GA', 'US'),
(12, 'Guam', 'GU', 'US'),
(13, 'Hawaii', 'HI', 'US'),
(14, 'Idaho', 'ID', 'US'),
(15, 'Illinois', 'IL', 'US'),
(16, 'Indiana', 'IN', 'US'),
(17, 'Iowa', 'IA', 'US'),
(18, 'Kansas', 'KS', 'US'),
(19, 'Kentucky', 'KY', 'US'),
(20, 'Louisiana', 'LA', 'US'),
(21, 'Maine', 'ME', 'US'),
(22, 'Maryland', 'MD', 'US'),
(23, 'Massachusetts', 'MA', 'US'),
(24, 'Michigan', 'MI', 'US'),
(25, 'Minnesota', 'MN', 'US'),
(26, 'Mississippi', 'MS', 'US'),
(27, 'Missouri', 'MO', 'US'),
(28, 'Montana', 'MT', 'US'),
(29, 'Nebraska', 'NE', 'US'),
(30, 'Nevada', 'NV', 'US'),
(31, 'New Hampshire', 'NH', 'US'),
(32, 'New Jersey', 'NJ', 'US'),
(33, 'New Mexico', 'NM', 'US'),
(34, 'New York', 'NY', 'US'),
(35, 'North Carolina', 'NC', 'US'),
(36, 'North Dakota', 'ND', 'US'),
(37, 'Ohio', 'OH', 'US'),
(38, 'Oklahoma', 'OK', 'US'),
(39, 'Oregon', 'OR', 'US'),
(40, 'Pennsylvania', 'PA', 'US'),
(41, 'Puerto Rico', 'PR', 'US'),
(42, 'Rhode Island', 'RI', 'US'),
(43, 'South Carolina', 'SC', 'US'),
(44, 'South Dakota', 'SD', 'US'),
(45, 'Tennessee', 'TN', 'US'),
(46, 'Texas', 'TX', 'US'),
(47, 'Utah', 'UT', 'US'),
(48, 'Vermont', 'VT', 'US'),
(49, 'Virgin Islands', 'VI', 'US'),
(50, 'Virginia', 'VA', 'US'),
(51, 'Washington', 'WA', 'US'),
(52, 'West Virginia', 'WV', 'US'),
(53, 'Wisconsin', 'WI', 'US'),
(54, 'Wyoming', 'WY', 'US');
        