REPLACE INTO `%%prefix%%tips` (`id`, `name`, `text`, `type`, `active`, `locale`) VALUES 
('', 'register.nick', 'Please enter your name or nickname, how you want to be called by other users of our site. It should be unique among the site members. Please keep in mind that this info will be available to other site members, so if you want to keep your name private don''t use it as a nickname.', 1, '1', 'en'),
('', 'register.login', 'Please enter your login, a unique name that will be used in our system to identify you. You will need to remember and enter it every time you want to log in to your account on our site. Only english letters and digits are allowed, no symbols.', 1, '1', 'en'),
('', 'register.email', 'Enter your primary email address here, it will be used to send you your password, account information, site news and messages from other members. It must be real working email address. We automatically remove accounts with invalid email addresses. We respect your privacy, your email will not be sold to third parties.', 1, '1', 'en'),
('', 'category.form', 'You can use this form to select the ads according to your own criteria. You can either click on the links for simple queries (e.g. Black for black escorts in this area) or check the form boxes for more complex terms (e.g. check Female+Black+Independants to find the black female independent escorts). The search is limited to the country, state or city of the current page.', 1, '1', 'en'),
('', 'register.status', 'Choose ''Independent'', if you work on your own, and ''Agency'', if you''re an agency employee.', 1, '1', 'en'),
('', 'register.agency', 'Choose an agency you employed with. If you''re an independent escort you should leave this field blank. The agency you select will have access to your account and will be able to edit it.', 1, '1', 'en'),
('', 'register.measurements', 'Your measurements, such as bust, cup fitting, waist, and hips in inches. Example, 36C-24-35. This field is for females only.', 1, '1', 'en'),
('', 'general.captcha', 'CAPTCHA is a technology that helps to determine whether or not the user is human and to prevent system abuse by robots. You should be able to read the code on the image and to enter it into the appropriate field.', 1, '1', 'en'),
('', 'register.password', 'Password should be between 6 and 12 characters, only latin letters and digits allowed. No spaces, special characters or symbols.', 1, '1', 'en'),
('', 'register.english', 'English language fluency level.', 1, '1', 'en'),
('', 'gallery.password', 'Here you can set a password that will make this folder private. If you have some photos, \r\nthat you don''t want to be public accessible, you can set a password here and give it out to those users, \r\nwho should have access to this folder. ', 1, '1', 'en'),
('', 'gallery.privacy', 'You can restrict access to this folder and all photos inside it to certain groups of users or even only yourself (completely private content).', 1, '1', 'en'),
('', 'gallery.content', 'Please set it to appropriate value according to the most explicit image inside this folder. So even one nude image makes content level ''Softcore'', and even one image showing some hardcore action makes content level ''Hardcore''. It will help us to restrict access to some areas of the site in the future.', 1, '1', 'en'),
('', 'user_info.reciprocal', 'Please, enter the address(es) of page(s), where the link(s) to our site will be placed. We require a link back, if you want to place your website URL in your ads. If you don''t, you may leave this field blank. One URL per line.', 1, '1', 'en'),
('', 'user_info.avatar', 'Avatar is a small image that will be placed next to your posts on our sites.', 1, '1', 'en'),
('', 'blog.def_privacy', 'Blog default privacy defines who will be able to read your blog entries by default. You can set privacy level also individually on per entry basis. We suggest you to leave default privacy level as public.', 1, '1', 'en'),
('', 'blog.def_comments', 'This field determines who will be able to post comments to your blog entries by default. This value can also be changed individually on per entry basis.', 1, '1', 'en'),
('', 'blog.privacy', 'Privacy level determines who will be able to read this blog entry.', 1, '1', 'en'),
('', 'blog.comments', 'This field determines who will be allowed to submit commnets to this blog entry.', 1, '1', 'en'),
('', 'blog.custom_categories', 'You can organize your blog in custom categories. This will add more logical structure and help both you and your readers to navigate through your blog easier.', 1, '1', 'en'),
('', 'blog.general_categories', 'You can set  the general subject category of your blog entry and it will appear under this category in the site blog list.', 1, '1', 'en'),
('', 'articles.associate', 'If you are not the author, but have the right to disctribute this article check this field. This article will have name of the author from Author field and will not have link to your account.', 1, '1', 'en'),
('', 'articles.credentials', 'Write about the author  in brief here. You can place a link to author''s website.', 1, '1', 'en'),
('', 'articles.summary', 'Give a short outline of your article here. It will be placed in the list of articles.', 1, '1', 'en'),
('', 'gallery.show_in_ads', 'Checking this box will make this photo to appear on your ads. Folder permissions should allow the public access to this photo. Otherwise, the photo won''t show up on your ads.', 1, '1', 'en'),
('', 'gallery.folder', 'Folders help to organize your gallery in a more structured way.  You can place different sets of images into different folders to make user navigation easier.', 1, '1', 'en'),


('', 'register.nick', 'Пожалуйста, введите ваше имя или ник, что бы пользователи сайта могли как-то вас называть. Он должен быть уникальный среди посетителей сайта. Пожалуйста, заметьте, что эта информация будет доступна другим пользователям сайта, поэтому если вы хотите сохранить свое имя в тайне, не используйте его как ник', 1, '1', 'ru'),
('', 'register.login', 'Пожалуйста, введите свой логин, уникальное имя, с помощью которого мы сможем распознавать вас в нашей системе. Вам нужно запомнить и вводить его каждый раз при входе в свой аккаунт на нашем сайте. Для логина разрешены только английские буквы и цифры,  никаких символов или кирилицы.', 1, '1', 'ru'),
('', 'register.email', 'Введите здесь ваш емейл адрес, он будет использоваться для отсылки вам пароля, информации аккаунта, новостей сайта и сообщений от других пользователей. Это должен быть рабочий емейл адрес. Система автоматически удалит аккаунт  с недействительным емейл адресом. Мы уважаем вашу приватность, ваш емейл не будет разглашен третьим лицам ', 1, '1', 'ru'),
('', 'register.password', 'Пароль должен быть от 6 до 12 символов, разрешены только латинские буквы и цифры. Без пробелов, специальных знаков и символов', 1, '1', 'ru'),
('', 'general.captcha', 'CAPTCHA – технология, которая помогает определить, является ли пользователь человеком, и не допустить использования системы роботами и спам-ботами. Вы должны будете прочесть код на изображении и ввести его в нужное поле для подтверждения ваших действий', 1, '1', 'ru'),
('', 'gallery.password', 'Здесь вы можете установить пароль, который сделает эту папку личной. Если у вас есть какие то изображения, которые вы хотите показать только определенным людям, вы можете поставить пароль здесь, и дать его тем пользователям, которым открываете доступ к этой папке', 1, '1', 'ru'),
('', 'gallery.privacy', ' Вы можете разрешить доступ в эту папку и на все изображения внутри для определенных групп пользователей или даже только для себя (абсолютно личный  контент)', 1, '1', 'ru'),
('', 'gallery.folder', 'Папки помогают структурировать Вашу галерею. Вы можете размещать разные сеты изображений в разные папки для более удобной и логичной навигации.', 1, '1', 'ru'),
('', 'user_info.avatar', 'Аватар – маленькое изображение, которое будет расположено возле ваших постов на нашем сайте.', 1, '1', 'ru'),
('', 'blog.def_privacy', 'Установка приватности блога определяет, кто будет иметь возможность читать записи вашего блога по умолчанию. Вы так же можете установить уровень приватности индивидуально на входе. Но мы советуем вам оставить его как публичный(Public).', 1, '1', 'ru'),
('', 'blog.def_comments', 'Это поле определяет, кто сможет писать комментарии в ваш блог по умолчанию. Это значение также может быть определена для каждого вхождения в блоге.', 1, '1', 'ru'),
('', 'blog.privacy', 'Уровень приватности определяет, кто будет иметь доступ читать содержимое этого блога.', 1, '1', 'ru'),
('', 'blog.comments', 'Это поле определяет, кому будет разрешено оставлять комментарии к постам этого блога.', 1, '1', 'ru'),
('', 'blog.custom_categories', 'Пользовательские категории помогают организовать Ваш блог для более удобной и логической навигации.', 1, '1', 'ru'),
('', 'blog.general_categories', 'Вы можете установить общую категорию вашего блога, и он появится под этой категорией на сайте в списке блогов.', 1, '1', 'ru'),
('', 'articles.associate', 'Если Вы не автор, но имеете право разместить эту статью, выберите это поле. Эта статья получит имя автора из поля Автор и не будет ссылаться на Ваш аккаунт', 1, '1', 'ru'),
('', 'articles.credentials', 'Укажите источник информации здесь. Вы можете добавить ссылку на вэбсайт автора.', 1, '1', 'ru'),
('', 'articles.summary', 'Здесь вы можете дать краткое описание статьи, которое будет помещено в список статей.', 1, '1', 'ru'),


('', 'register.nick', 'Будь ласка, введіть Ваше ім&#39я чи нік, щоб користувачі сайта мали можливість якось Вас називати. Він має бути унікальним серед відвідувачив сайта. Будь ласка, врахуйте, що ця інформація буде доступна іншим користувачам сайта,  отож якщо Ви бажаєте зберегти своє ім&#39я  в таємниці, не ивикористовуйте його як нік', 1, '1', 'uk'),
('', 'register.login', 'Будь ласка, введіть свій логін, уникальне им&#39я, за допомогою якого ми зможемо розпізнавать Вас в нашей системі. Вам треба запам&#39ятати і вводити його кожен раз при вході у  свій аккаунт на нашеому сайті. Для логина рдозволені тільки англійські буквыи та цифри,  ніяких символів ии кирилиці.', 1, '1', 'uk'),
('', 'register.email', 'Введіть тут Ваш ємейл адрес, він буде використовуватися для відсилки Вам пароля, информації аккаунта, новин сайта та повідомлень інших користувачей. Це має бути працююча ємейл адреса. Система автоматично видалить аккаунт  з недійсною ємейл адресою. Ми поважаємо Вашу приватність, Ваш ємейл не буде розголошено іншим людям', 1, '1', 'uk'),
('', 'register.password', 'Пароль повинен бути від 6 до 12 символів, дозволені тільки латинські букви та цифри. Без пробілів, спеціальних знаків та символів', 1, '1', 'uk'),
('', 'general.captcha', 'CAPTCHA – технологія, яка допомогає визначити, чи користувач людина, і не допустить використання системи роботами і спам-ботами. Ви повинні будете прочитати код на зображенні і ввести його у потрібне поле для підтвердження ваших дій', 1,'1', 'uk'),
('', 'gallery.password', 'Тут Ви можете встановити пароль, який зробить цю папку особистою. Якщо у Вас є  якесь зображення, яке ви бажаєте показувати тільки визначенним  людям, вы можете встановити пароль, і надати  його тим  користувачам,  яким  відкриєте доступ  до  цієї папки', 1, '1', 'uk'),
('', 'gallery.privacy', ' Ви можете дозволити доступ у цю папку і на всі зображення всередині для визначенних груп користувачив або навіть тільки для себе (цілком особистий  контент)', 1, '1', 'uk'),
('', 'gallery.folder', 'Папки допомогають структурувати Вашу галерею. Ви можете розміщати різні зображення у різні папки для більш зручної і логічної навігації.', 1, '1', 'uk'),
('', 'user_info.avatar', 'Аватар – маленьке зображення, яке буде розташовано поряд Ваших постів на нашем сайті.', 1, '1', 'uk'),
('', 'blog.def_privacy', 'Встановлення приватності блога визначає, хто буде мати можливість читати записи вашого блога по вмовчанню. Ви також маєте можливість встановити рівень приватності індивідуально на вході. Але ми радимо Вам залишити його як публічний(Public).', 1, '1', 'uk'),
('', 'blog.def_comments', 'Це поле визначає, хто зможе писати комментарі у Ваш блог по вмовчанню. Це значення також може бути визначено для кожного входженни у блозі.', 1, '1', 'uk'),
('', 'blog.privacy', 'Рівень приватності визначає, хто буде мати доступ читати уміст цього блога.', 1, '1', 'uk'),
('', 'blog.comments', 'Це поле визначає, кому буде дозволено залишати коментарі до постів цього блога.', 1, '1', 'uk'),
('', 'blog.custom_categories', 'Категорії, які визначив користувач допомогають організувати Ваш блог для більш зручної та логічної навігації.', 1, '1', 'uk'),
('', 'blog.general_categories', 'Ви маєте можливість встановити загальні категорію Вашого блогу, і він з&#39явиться під цією категорією на сайті у списку блогів.', 1, '1', 'uk'),
('', 'articles.associate', 'Якщо Ви не автор, але маєте право розмістити цю статтю, виберіть це поле. Ця стаття отримає ім&#39я автора з поля Автор і не будет посилатися  на Ваш аккаунт', 1, '1', 'uk'),
('', 'articles.credentials', 'Вкажіть джерело інформації тут. Ви можете додати ссилку на вебсайт автора.', 1, '1', 'uk'),
('', 'articles.summary', 'Тут Ви маєте можливість надати стисле описання статті, яке буде розташоване у списку статтей.', 1, '1', 'uk');
